/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=16 (degree 2); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes C(f)=log2(1+f)/f by unsigned v (WFRAC+1 bits) and returns log2(m')=f*C(f) as
/// the unsigned magnitude l_mag = |f|*C(f) plus the sign l_neg (set when m>=sqrt(2)), at scale 2**-F2,
/// F2 = WFRAC+1+CF. The final f*C(f) multiply is fully unsigned (|f|*C(f)); the caller folds l_neg into its
/// reconstruction add/subtract. Register stages: two-stage ROM read + Horner + final multiply.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_log2_m16 #(
    parameter D                   = 2,
    parameter WSB                 = 1,
    parameter WMULTIPLIER         = 0,
    parameter STAGE_PRODUCT       = 0,
    parameter STAGE_PRODUCT_FINAL = STAGE_PRODUCT
) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire     [ 16-1:0] v,  // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire        [44:0] l_mag,  // |log2(m')| = |f|*C(f) magnitude at scale 2**-F2, F2 = WFRAC+1+CF
    output wire               l_neg   // sign of log2(m') (= sign of reduced f); 1 when m >= sqrt(2)
);
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 16;
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 7;
    localparam integer SEG_BASE = 26;
    localparam integer RW   = 9;
    localparam integer CW   = 31;
    localparam integer ACCW = 31;
    localparam integer NSEG = 92;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [K-1:0]    idx_raw = v[WMAN-1 -: K];
    wire [K-1:0]    idx_ofs = idx_raw - SEG_BASE[K-1:0];
    wire [WIDX-1:0] idx     = idx_ofs[WIDX-1:0];
    wire [RW-1:0]   w       = v[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[ 0] = {31'h000042b3, 31'h7fdb5557, 31'h1b62edf4};
        rom[ 1] = {31'h00004119, 31'h7fdbdabb, 31'h1b3e85f6};
        rom[ 2] = {31'h00003f8d, 31'h7fdc5ceb, 31'h1b1aa1c2};
        rom[ 3] = {31'h00003e0e, 31'h7fdcdc03, 31'h1af73e32};
        rom[ 4] = {31'h00003c9c, 31'h7fdd581d, 31'h1ad4583b};
        rom[ 5] = {31'h00003b36, 31'h7fddd153, 31'h1ab1eced};
        rom[ 6] = {31'h000039db, 31'h7fde47bd, 31'h1a8ff96e};
        rom[ 7] = {31'h0000388c, 31'h7fdebb72, 31'h1a6e7aff};
        rom[ 8] = {31'h00003748, 31'h7fdf2c8a, 31'h1a4d6ef7};
        rom[ 9] = {31'h0000360e, 31'h7fdf9b18, 31'h1a2cd2c2};
        rom[10] = {31'h000034de, 31'h7fe00733, 31'h1a0ca3e2};
        rom[11] = {31'h000033b7, 31'h7fe070ed, 31'h19ecdfec};
        rom[12] = {31'h00003299, 31'h7fe0d85a, 31'h19cd848a};
        rom[13] = {31'h00003184, 31'h7fe13d8b, 31'h19ae8f78};
        rom[14] = {31'h00003078, 31'h7fe1a093, 31'h198ffe82};
        rom[15] = {31'h00002f73, 31'h7fe20182, 31'h1971cf87};
        rom[16] = {31'h00002e76, 31'h7fe26067, 31'h19540077};
        rom[17] = {31'h00002d81, 31'h7fe2bd53, 31'h19368f4f};
        rom[18] = {31'h00002c93, 31'h7fe31854, 31'h19197a1e};
        rom[19] = {31'h00002bac, 31'h7fe37179, 31'h18fcbf01};
        rom[20] = {31'h00002acb, 31'h7fe3c8d0, 31'h18e05c21};
        rom[21] = {31'h000029f1, 31'h7fe41e65, 31'h18c44fb7};
        rom[22] = {31'h0000291d, 31'h7fe47245, 31'h18a89809};
        rom[23] = {31'h0000284e, 31'h7fe4c47e, 31'h188d3366};
        rom[24] = {31'h00002786, 31'h7fe51519, 31'h1872202e};
        rom[25] = {31'h000026c3, 31'h7fe56424, 31'h18575cc9};
        rom[26] = {31'h00002605, 31'h7fe5b1a9, 31'h183ce7ac};
        rom[27] = {31'h0000254d, 31'h7fe5fdb3, 31'h1822bf57};
        rom[28] = {31'h00002499, 31'h7fe6484b, 31'h1808e252};
        rom[29] = {31'h000023ea, 31'h7fe6917c, 31'h17ef4f32};
        rom[30] = {31'h00002340, 31'h7fe6d950, 31'h17d60495};
        rom[31] = {31'h0000229a, 31'h7fe71fcf, 31'h17bd0121};
        rom[32] = {31'h000021f9, 31'h7fe76502, 31'h17a44386};
        rom[33] = {31'h0000215b, 31'h7fe7a8f3, 31'h178bca7e};
        rom[34] = {31'h000020c2, 31'h7fe7eba8, 31'h177394c8};
        rom[35] = {31'h0000202c, 31'h7fe82d2c, 31'h175ba12f};
        rom[36] = {31'h00001f9b, 31'h7fe86d84, 31'h1743ee85};
        rom[37] = {31'h00001f0d, 31'h7fe8acb9, 31'h172c7ba1};
        rom[38] = {31'h00001e82, 31'h7fe8ead2, 31'h17154764};
        rom[39] = {31'h00001dfb, 31'h7fe927d6, 31'h16fe50b6};
        rom[40] = {31'h00001d77, 31'h7fe963cc, 31'h16e79684};
        rom[41] = {31'h00001cf7, 31'h7fe99ebb, 31'h16d117c5};
        rom[42] = {31'h00001c79, 31'h7fe9d8a8, 31'h16bad374};
        rom[43] = {31'h00001bff, 31'h7fea119a, 31'h16a4c893};
        rom[44] = {31'h00001b87, 31'h7fea4997, 31'h168ef629};
        rom[45] = {31'h00001b12, 31'h7fea80a5, 31'h16795b45};
        rom[46] = {31'h00001aa0, 31'h7feab6c9, 31'h1663f6fa};
        rom[47] = {31'h00001a31, 31'h7feaec0a, 31'h164ec861};
        rom[48] = {31'h000019c4, 31'h7feb206b, 31'h1639ce99};
        rom[49] = {31'h0000195a, 31'h7feb53f3, 31'h162508c6};
        rom[50] = {31'h000018f2, 31'h7feb86a6, 31'h16107610};
        rom[51] = {31'h0000188c, 31'h7febb889, 31'h15fc15a6};
        rom[52] = {31'h00001829, 31'h7febe9a1, 31'h15e7e6b9};
        rom[53] = {31'h000017c8, 31'h7fec19f3, 31'h15d3e881};
        rom[54] = {31'h00001769, 31'h7fec4982, 31'h15c01a39};
        rom[55] = {31'h0000170c, 31'h7fec7853, 31'h15ac7b22};
        rom[56] = {31'h000016b1, 31'h7feca66b, 31'h15990a7f};
        rom[57] = {31'h00001658, 31'h7fecd3cd, 31'h1585c79a};
        rom[58] = {31'h00001601, 31'h7fed007e, 31'h1572b1bd};
        rom[59] = {31'h000015ac, 31'h7fed2c80, 31'h155fc83a};
        rom[60] = {31'h00001559, 31'h7fed57d8, 31'h154d0a65};
        rom[61] = {31'h00001508, 31'h7fed828a, 31'h153a7795};
        rom[62] = {31'h000014b8, 31'h7fedac99, 31'h15280f25};
        rom[63] = {31'h0000146a, 31'h7fedd609, 31'h1515d075};
        rom[64] = {31'h0000141d, 31'h7fedfedc, 31'h1503bae5};
        rom[65] = {31'h000013d2, 31'h7fee2716, 31'h14f1cddc};
        rom[66] = {31'h00001389, 31'h7fee4eba, 31'h14e008c3};
        rom[67] = {31'h00001341, 31'h7fee75cb, 31'h14ce6b04};
        rom[68] = {31'h000012fb, 31'h7fee9c4d, 31'h14bcf40f};
        rom[69] = {31'h000012b5, 31'h7feec242, 31'h14aba355};
        rom[70] = {31'h00001272, 31'h7feee7ad, 31'h149a784b};
        rom[71] = {31'h00001230, 31'h7fef0c90, 31'h14897268};
        rom[72] = {31'h000011ef, 31'h7fef30ef, 31'h14789127};
        rom[73] = {31'h000011af, 31'h7fef54cc, 31'h1467d403};
        rom[74] = {31'h00001170, 31'h7fef782a, 31'h14573a7d};
        rom[75] = {31'h00001133, 31'h7fef9b0b, 31'h1446c416};
        rom[76] = {31'h000010f7, 31'h7fefbd71, 31'h14367053};
        rom[77] = {31'h000010bc, 31'h7fefdf5f, 31'h14263eba};
        rom[78] = {31'h00001082, 31'h7ff000d7, 31'h14162ed3};
        rom[79] = {31'h0000104a, 31'h7ff021dc, 31'h1406402c};
        rom[80] = {31'h00001012, 31'h7ff0426f, 31'h13f67251};
        rom[81] = {31'h00000fdc, 31'h7ff06293, 31'h13e6c4d1};
        rom[82] = {31'h00000fa6, 31'h7ff0824b, 31'h13d7373f};
        rom[83] = {31'h00000f71, 31'h7ff0a196, 31'h13c7c92e};
        rom[84] = {31'h00000f3e, 31'h7ff0c079, 31'h13b87a35};
        rom[85] = {31'h00000f0b, 31'h7ff0def5, 31'h13a949eb};
        rom[86] = {31'h00000eda, 31'h7ff0fd0b, 31'h139a37ea};
        rom[87] = {31'h00000ea9, 31'h7ff11abe, 31'h138b43ce};
        rom[88] = {31'h00000e79, 31'h7ff1380f, 31'h137c6d34};
        rom[89] = {31'h00000e4a, 31'h7ff15501, 31'h136db3bb};
        rom[90] = {31'h00000e1b, 31'h7ff17194, 31'h135f1705};
        rom[91] = {31'h00000dee, 31'h7ff18dcb, 31'h135096b4};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [(K + WSB)-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= {sb_in, idx_raw};
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [(K + WSB)-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB((K + WSB)), .ACC_SIGNED(1),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire        [K-1:0]    idx_p = esb[K-1:0];
    wire        [WSB-1:0]  sb_p  = esb[K +: WSB];
    wire        [WMAN-1:0] v_p   = {idx_p, ew};
    wire signed [WF-1:0]   f_p   = $signed({~v_p[WMAN-1], v_p[WMAN-2:0]});
    wire                   f_neg = f_p[WF-1];
    wire        [WF-1:0]   mag_f = f_neg ? (-f_p) : f_p;   // |f|, fits WF-1 bits (top bit structurally 0)

    wire [WF+ACCM-1:0] umag_p;   // unsigned |f| * C(f)
    wire [WSB:0]       fsb;      // {delayed f sign, external sideband} riding the pmul
    _zkf_pmul #(
        .WA(WF), .WB(ACCM), .A_SIGNED(0), .B_SIGNED(0),
        .WSB(WSB + 1), .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT_FINAL)
    ) u_final_pmul (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in({f_neg, sb_p}),
        .a(mag_f), .b(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(fsb), .p(umag_p)
    );
    assign sb_out = fsb[WSB-1:0];
    // Emit the magnitude and the sign SEPARATELY rather than a signed product: the caller folds the sign into
    // its e + log2(m') reconstruction as a single add/subtract, so the post-product cone carries one fewer wide
    // negate carry chain (a standalone two's-complement negate here would otherwise sit in series with that
    // adder and the magnitude abs, the critical path on wide formats). umag_p is the exact |f|*C(f): C(f) < 2
    // and |f| < 2**(WF-1) bound it below 2**(F2-1), so the F2+1-bit slice is lossless. The sign rode the pmul
    // sideband (fsb[WSB]) and so is aligned with out_valid.
    assign l_mag = umag_p[F2:0];
    assign l_neg = fsb[WSB];
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
