/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=32 (degree 3); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes C(f)=log2(1+f)/f by unsigned v (WFRAC+1 bits) and returns log2(m')=f*C(f) as
/// the unsigned magnitude l_mag = |f|*C(f) plus the sign l_neg (set when m>=sqrt(2)), at scale 2**-F2,
/// F2 = WFRAC+1+CF. The final f*C(f) multiply is fully unsigned (|f|*C(f)); the caller folds l_neg into its
/// reconstruction add/subtract. Register stages: two-stage ROM read + Horner + final multiply.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_log2_m32 #(
    parameter D                   = 3,
    parameter WSB                 = 1,
    parameter WMULTIPLIER         = 0,
    parameter STAGE_PRODUCT       = 0,
    parameter STAGE_PRODUCT_FINAL = STAGE_PRODUCT
) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire     [ 32-1:0] v,  // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire        [76:0] l_mag,  // |log2(m')| = |f|*C(f) magnitude at scale 2**-F2, F2 = WFRAC+1+CF
    output wire               l_neg   // sign of log2(m') (= sign of reduced f); 1 when m >= sqrt(2)
);
    generate if (D != 3) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 32;
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 9;
    localparam integer SEG_BASE = 106;
    localparam integer RW   = 23;
    localparam integer CW   = 47;
    localparam integer ACCW = 47;
    localparam integer NSEG = 363;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [K-1:0]    idx_raw = v[WMAN-1 -: K];
    wire [K-1:0]    idx_ofs = idx_raw - SEG_BASE[K-1:0];
    wire [WIDX-1:0] idx     = idx_ofs[WIDX-1:0];
    wire [RW-1:0]   w       = v[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[  0] = {47'h7ffffffdd5e7, 47'h0000042b2ecc, 47'h7ff6e608fead, 47'h1b50a94c5c27};
        rom[  1] = {47'h7ffffffddab6, 47'h00000424b084, 47'h7ff6ee58de94, 47'h1b47937e5f87};
        rom[  2] = {47'h7ffffffddf78, 47'h0000041e40a9, 47'h7ff6f69bd056, 47'h1b3e85f9c955};
        rom[  3] = {47'h7ffffffde42b, 47'h00000417df13, 47'h7ff6fed1f0a6, 47'h1b3580b1b9cc};
        rom[  4] = {47'h7ffffffde8d2, 47'h000004118b99, 47'h7ff706fb5be3, 47'h1b2c83996db0};
        rom[  5] = {47'h7ffffffded6b, 47'h0000040b4611, 47'h7ff70f182e1d, 47'h1b238ea43dfe};
        rom[  6] = {47'h7ffffffdf1f6, 47'h000004050e53, 47'h7ff71728830f, 47'h1b1aa1c59f95};
        rom[  7] = {47'h7ffffffdf675, 47'h000003fee439, 47'h7ff71f2c7627, 47'h1b11bcf122ee};
        rom[  8] = {47'h7ffffffdfae7, 47'h000003f8c79a, 47'h7ff727242286, 47'h1b08e01a73c2};
        rom[  9] = {47'h7ffffffdff4c, 47'h000003f2b852, 47'h7ff72f0fa2fb, 47'h1b000b3558c9};
        rom[ 10] = {47'h7ffffffe03a5, 47'h000003ecb639, 47'h7ff736ef120e, 47'h1af73e35b362};
        rom[ 11] = {47'h7ffffffe07f1, 47'h000003e6c12a, 47'h7ff73ec289f7, 47'h1aee790f7f4d};
        rom[ 12] = {47'h7ffffffe0c32, 47'h000003e0d901, 47'h7ff7468a24a7, 47'h1ae5bbb6d25f};
        rom[ 13] = {47'h7ffffffe1066, 47'h000003dafd99, 47'h7ff74e45fbc5, 47'h1add061fdc39};
        rom[ 14] = {47'h7ffffffe148f, 47'h000003d52ece, 47'h7ff755f628af, 47'h1ad4583ee5fe};
        rom[ 15] = {47'h7ffffffe18ac, 47'h000003cf6c7e, 47'h7ff75d9ac47c, 47'h1acbb208520a};
        rom[ 16] = {47'h7ffffffe1cbd, 47'h000003c9b684, 47'h7ff76533e7fd, 47'h1ac313709baf};
        rom[ 17] = {47'h7ffffffe20c4, 47'h000003c40cbf, 47'h7ff76cc1abbd, 47'h1aba7c6c56ed};
        rom[ 18] = {47'h7ffffffe24bf, 47'h000003be6f0c, 47'h7ff774442805, 47'h1ab1ecf0302d};
        rom[ 19] = {47'h7ffffffe28af, 47'h000003b8dd4a, 47'h7ff77bbb74d6, 47'h1aa964f0ebfc};
        rom[ 20] = {47'h7ffffffe2c94, 47'h000003b35758, 47'h7ff78327a9f3, 47'h1aa0e46366cb};
        rom[ 21] = {47'h7ffffffe306e, 47'h000003addd16, 47'h7ff78a88deda, 47'h1a986b3c94aa};
        rom[ 22] = {47'h7ffffffe343e, 47'h000003a86e63, 47'h7ff791df2acb, 47'h1a8ff9718108};
        rom[ 23] = {47'h7ffffffe3803, 47'h000003a30b1f, 47'h7ff7992aa4c3, 47'h1a878ef74e74};
        rom[ 24] = {47'h7ffffffe3bbe, 47'h0000039db32b, 47'h7ff7a06b6382, 47'h1a7f2bc33659};
        rom[ 25] = {47'h7ffffffe3f6f, 47'h000003986668, 47'h7ff7a7a17d8a, 47'h1a76cfca88c5};
        rom[ 26] = {47'h7ffffffe4316, 47'h0000039324b8, 47'h7ff7aecd091d, 47'h1a6e7b02ac26};
        rom[ 27] = {47'h7ffffffe46b3, 47'h0000038dedfd, 47'h7ff7b5ee1c43, 47'h1a662d611d11};
        rom[ 28] = {47'h7ffffffe4a46, 47'h00000388c217, 47'h7ff7bd04ccc7, 47'h1a5de6db6e04};
        rom[ 29] = {47'h7ffffffe4dd0, 47'h00000383a0ec, 47'h7ff7c411303a, 47'h1a55a7674728};
        rom[ 30] = {47'h7ffffffe514f, 47'h0000037e8a5d, 47'h7ff7cb135bf0, 47'h1a4d6efa661d};
        rom[ 31] = {47'h7ffffffe54c6, 47'h000003797e4d, 47'h7ff7d20b6506, 47'h1a453d8a9db9};
        rom[ 32] = {47'h7ffffffe5833, 47'h000003747ca1, 47'h7ff7d8f96060, 47'h1a3d130dd5d3};
        rom[ 33] = {47'h7ffffffe5b97, 47'h0000036f853d, 47'h7ff7dfdd62a9, 47'h1a34ef7a0b08};
        rom[ 34] = {47'h7ffffffe5ef2, 47'h0000036a9806, 47'h7ff7e6b78056, 47'h1a2cd2c54e86};
        rom[ 35] = {47'h7ffffffe6245, 47'h00000365b4df, 47'h7ff7ed87cda2, 47'h1a24bce5c5d3};
        rom[ 36] = {47'h7ffffffe658e, 47'h00000360dbaf, 47'h7ff7f44e5e97, 47'h1a1cadd1aa99};
        rom[ 37] = {47'h7ffffffe68cf, 47'h0000035c0c5a, 47'h7ff7fb0b4706, 47'h1a14a57f4a6c};
        rom[ 38] = {47'h7ffffffe6c07, 47'h0000035746c8, 47'h7ff801be9a8d, 47'h1a0ca3e5069b};
        rom[ 39] = {47'h7ffffffe6f36, 47'h000003528add, 47'h7ff808686c96, 47'h1a04a8f953f6};
        rom[ 40] = {47'h7ffffffe725d, 47'h0000034dd881, 47'h7ff80f08d058, 47'h19fcb4b2baa0};
        rom[ 41] = {47'h7ffffffe757c, 47'h000003492f9b, 47'h7ff8159fd8d6, 47'h19f4c707d5d6};
        rom[ 42] = {47'h7ffffffe7893, 47'h000003449011, 47'h7ff81c2d98e3, 47'h19ecdfef53c3};
        rom[ 43] = {47'h7ffffffe7ba2, 47'h0000033ff9cc, 47'h7ff822b22321, 47'h19e4ff5ff54b};
        rom[ 44] = {47'h7ffffffe7ea8, 47'h0000033b6cb2, 47'h7ff8292d89fe, 47'h19dd25508dd9};
        rom[ 45] = {47'h7ffffffe81a7, 47'h00000336e8ad, 47'h7ff82f9fdfbb, 47'h19d551b80331};
        rom[ 46] = {47'h7ffffffe849e, 47'h000003326da4, 47'h7ff836093669, 47'h19cd848d4d40};
        rom[ 47] = {47'h7ffffffe878e, 47'h0000032dfb81, 47'h7ff83c699fea, 47'h19c5bdc775ec};
        rom[ 48] = {47'h7ffffffe8a76, 47'h00000329922b, 47'h7ff842c12df2, 47'h19bdfd5d98e5};
        rom[ 49] = {47'h7ffffffe8d56, 47'h00000325318e, 47'h7ff8490ff205, 47'h19b64346e378};
        rom[ 50] = {47'h7ffffffe902f, 47'h00000320d991, 47'h7ff84f55fd7e, 47'h19ae8f7a9461};
        rom[ 51] = {47'h7ffffffe9301, 47'h0000031c8a20, 47'h7ff855936188, 47'h19a6e1effb9f};
        rom[ 52] = {47'h7ffffffe95cb, 47'h000003184324, 47'h7ff85bc82f23, 47'h199f3a9e7a47};
        rom[ 53] = {47'h7ffffffe988f, 47'h000003140487, 47'h7ff861f47724, 47'h1997997d8259};
        rom[ 54] = {47'h7ffffffe9b4b, 47'h0000030fce34, 47'h7ff868184a35, 47'h198ffe849692};
        rom[ 55] = {47'h7ffffffe9e00, 47'h0000030ba017, 47'h7ff86e33b8d5, 47'h198869ab4a46};
        rom[ 56] = {47'h7ffffffea0af, 47'h000003077a1a, 47'h7ff87446d35a, 47'h1980dae94132};
        rom[ 57] = {47'h7ffffffea357, 47'h000003035c28, 47'h7ff87a51a9ef, 47'h197952362f55};
        rom[ 58] = {47'h7ffffffea5f8, 47'h000002ff462e, 47'h7ff880544c99, 47'h1971cf89d8c3};
        rom[ 59] = {47'h7ffffffea893, 47'h000002fb3818, 47'h7ff8864ecb31, 47'h196a52dc1183};
        rom[ 60] = {47'h7ffffffeab27, 47'h000002f731d1, 47'h7ff88c41356b, 47'h1962dc24bd5e};
        rom[ 61] = {47'h7ffffffeadb4, 47'h000002f33346, 47'h7ff8922b9ad2, 47'h195b6b5bcfc0};
        rom[ 62] = {47'h7ffffffeb03b, 47'h000002ef3c64, 47'h7ff8980e0acb, 47'h195400794b8c};
        rom[ 63] = {47'h7ffffffeb2bc, 47'h000002eb4d17, 47'h7ff89de89494, 47'h194c9b7542f6};
        rom[ 64] = {47'h7ffffffeb537, 47'h000002e7654d, 47'h7ff8a3bb4745, 47'h19453c47d75d};
        rom[ 65] = {47'h7ffffffeb7ab, 47'h000002e384f2, 47'h7ff8a98631d1, 47'h193de2e93926};
        rom[ 66] = {47'h7ffffffeba1a, 47'h000002dfabf6, 47'h7ff8af496306, 47'h19368f51a794};
        rom[ 67] = {47'h7ffffffebc82, 47'h000002dbda44, 47'h7ff8b504e98b, 47'h192f417970aa};
        rom[ 68] = {47'h7ffffffebee5, 47'h000002d80fcc, 47'h7ff8bab8d3e7, 47'h1927f958f0fb};
        rom[ 69] = {47'h7ffffffec141, 47'h000002d44c7c, 47'h7ff8c0653079, 47'h1920b6e89393};
        rom[ 70] = {47'h7ffffffec398, 47'h000002d09041, 47'h7ff8c60a0d80, 47'h19197a20d1ca};
        rom[ 71] = {47'h7ffffffec5e9, 47'h000002ccdb0c, 47'h7ff8cba77916, 47'h191242fa3324};
        rom[ 72] = {47'h7ffffffec835, 47'h000002c92cc9, 47'h7ff8d13d8133, 47'h190b116d4d30};
        rom[ 73] = {47'h7ffffffeca7b, 47'h000002c58569, 47'h7ff8d6cc33ad, 47'h1903e572c361};
        rom[ 74] = {47'h7ffffffeccbb, 47'h000002c1e4db, 47'h7ff8dc539e39, 47'h18fcbf0346f3};
        rom[ 75] = {47'h7ffffffecef6, 47'h000002be4b0e, 47'h7ff8e1d3ce69, 47'h18f59e1796c3};
        rom[ 76] = {47'h7ffffffed12c, 47'h000002bab7f2, 47'h7ff8e74cd1af, 47'h18ee82a87f30};
        rom[ 77] = {47'h7ffffffed35c, 47'h000002b72b77, 47'h7ff8ecbeb55d, 47'h18e76caed9fe};
        rom[ 78] = {47'h7ffffffed587, 47'h000002b3a58c, 47'h7ff8f22986a5, 47'h18e05c238e2e};
        rom[ 79] = {47'h7ffffffed7ad, 47'h000002b02622, 47'h7ff8f78d5297, 47'h18d950ff8fe6};
        rom[ 80] = {47'h7ffffffed9cd, 47'h000002acad2a, 47'h7ff8fcea2625, 47'h18d24b3be04b};
        rom[ 81] = {47'h7ffffffedbe9, 47'h000002a93a93, 47'h7ff902400e24, 47'h18cb4ad18d67};
        rom[ 82] = {47'h7ffffffeddff, 47'h000002a5ce4e, 47'h7ff9078f1747, 47'h18c44fb9b207};
        rom[ 83] = {47'h7ffffffee011, 47'h000002a2684d, 47'h7ff90cd74e24, 47'h18bd59ed759b};
        rom[ 84] = {47'h7ffffffee21d, 47'h0000029f0881, 47'h7ff91218bf33, 47'h18b669660c1d};
        rom[ 85] = {47'h7ffffffee425, 47'h0000029baedb, 47'h7ff9175376ce, 47'h18af7e1cb5ee};
        rom[ 86] = {47'h7ffffffee628, 47'h000002985b4b, 47'h7ff91c878134, 47'h18a8980abfbc};
        rom[ 87] = {47'h7ffffffee826, 47'h000002950dc5, 47'h7ff921b4ea82, 47'h18a1b7298263};
        rom[ 88] = {47'h7ffffffeea20, 47'h00000291c639, 47'h7ff926dbbebe, 47'h189adb7262d1};
        rom[ 89] = {47'h7ffffffeec15, 47'h0000028e849a, 47'h7ff92bfc09cf, 47'h189404ded1e8};
        rom[ 90] = {47'h7ffffffeee05, 47'h0000028b48d9, 47'h7ff93115d77e, 47'h188d33684c65};
        rom[ 91] = {47'h7ffffffeeff1, 47'h0000028812e9, 47'h7ff93629337c, 47'h188667085ac1};
        rom[ 92] = {47'h7ffffffef1d8, 47'h00000284e2bc, 47'h7ff93b36295d, 47'h187f9fb89116};
        rom[ 93] = {47'h7ffffffef3bb, 47'h00000281b845, 47'h7ff9403cc499, 47'h1878dd728f07};
        rom[ 94] = {47'h7ffffffef599, 47'h0000027e9377, 47'h7ff9453d1090, 47'h1872202fffa0};
        rom[ 95] = {47'h7ffffffef773, 47'h0000027b7443, 47'h7ff94a371884, 47'h186b67ea993f};
        rom[ 96] = {47'h7ffffffef949, 47'h000002785a9e, 47'h7ff94f2ae79f, 47'h1864b49c1d79};
        rom[ 97] = {47'h7ffffffefb1b, 47'h00000275467b, 47'h7ff9541888f1, 47'h185e063e5900};
        rom[ 98] = {47'h7ffffffefce8, 47'h0000027237cc, 47'h7ff959000771, 47'h18575ccb2387};
        rom[ 99] = {47'h7ffffffefeb1, 47'h0000026f2e85, 47'h7ff95de16dfb, 47'h1850b83c5fac};
        rom[100] = {47'h7fffffff0077, 47'h0000026c2a9a, 47'h7ff962bcc752, 47'h184a188bfade};
        rom[101] = {47'h7fffffff0238, 47'h000002692bff, 47'h7ff967921e23, 47'h18437db3ed41};
        rom[102] = {47'h7fffffff03f5, 47'h0000026632a7, 47'h7ff96c617cff, 47'h183ce7ae399b};
        rom[103] = {47'h7fffffff05ae, 47'h000002633e86, 47'h7ff9712aee62, 47'h18365674ed35};
        rom[104] = {47'h7fffffff0763, 47'h000002604f90, 47'h7ff975ee7cad, 47'h182fca021fcb};
        rom[105] = {47'h7fffffff0914, 47'h0000025d65ba, 47'h7ff97aac322c, 47'h1829424ff36b};
        rom[106] = {47'h7fffffff0ac2, 47'h0000025a80f7, 47'h7ff97f641912, 47'h1822bf589465};
        rom[107] = {47'h7fffffff0c6b, 47'h00000257a13e, 47'h7ff984163b7c, 47'h181c41163931};
        rom[108] = {47'h7fffffff0e11, 47'h00000254c681, 47'h7ff988c2a36e, 47'h1815c7832256};
        rom[109] = {47'h7fffffff0fb4, 47'h00000251f0b6, 47'h7ff98d695ad8, 47'h180f52999a56};
        rom[110] = {47'h7fffffff1152, 47'h0000024f1fd1, 47'h7ff9920a6b92, 47'h1808e253f597};
        rom[111] = {47'h7fffffff12ed, 47'h0000024c53c8, 47'h7ff996a5df5e, 47'h180276ac924c};
        rom[112] = {47'h7fffffff1484, 47'h000002498c90, 47'h7ff99b3bbfe9, 47'h17fc0f9dd85f};
        rom[113] = {47'h7fffffff1618, 47'h00000246ca1e, 47'h7ff99fcc16c9, 47'h17f5ad22395c};
        rom[114] = {47'h7fffffff17a8, 47'h000002440c67, 47'h7ff9a456ed7f, 47'h17ef4f34305b};
        rom[115] = {47'h7fffffff1935, 47'h000002415361, 47'h7ff9a8dc4d78, 47'h17e8f5ce41ea};
        rom[116] = {47'h7fffffff1abe, 47'h0000023e9f01, 47'h7ff9ad5c400a, 47'h17e2a0eafbf8};
        rom[117] = {47'h7fffffff1c44, 47'h0000023bef3d, 47'h7ff9b1d6ce78, 47'h17dc5084f5c1};
        rom[118] = {47'h7fffffff1dc7, 47'h00000239440b, 47'h7ff9b64c01ef, 47'h17d60496cfbb};
        rom[119] = {47'h7fffffff1f46, 47'h000002369d60, 47'h7ff9babbe389, 47'h17cfbd1b337c};
        rom[120] = {47'h7fffffff20c2, 47'h00000233fb33, 47'h7ff9bf267c4c, 47'h17c97a0cd3ab};
        rom[121] = {47'h7fffffff223b, 47'h000002315d7a, 47'h7ff9c38bd527, 47'h17c33b666bec};
        rom[122] = {47'h7fffffff23b0, 47'h0000022ec42b, 47'h7ff9c7ebf6fa, 47'h17bd0122c0c8};
        rom[123] = {47'h7fffffff2522, 47'h0000022c2f3c, 47'h7ff9cc46ea8e, 47'h17b6cb3c9f9c};
        rom[124] = {47'h7fffffff2691, 47'h000002299ea3, 47'h7ff9d09cb89a, 47'h17b099aede88};
        rom[125] = {47'h7fffffff27fd, 47'h000002271258, 47'h7ff9d4ed69c3, 47'h17aa6c745c57};
        rom[126] = {47'h7fffffff2966, 47'h000002248a51, 47'h7ff9d9390699, 47'h17a443880070};
        rom[127] = {47'h7fffffff2acc, 47'h000002220685, 47'h7ff9dd7f979b, 47'h179e1ee4bac1};
        rom[128] = {47'h7fffffff2c2f, 47'h0000021f86e9, 47'h7ff9e1c12534, 47'h1797fe8583ac};
        rom[129] = {47'h7fffffff2d8f, 47'h0000021d0b76, 47'h7ff9e5fdb7bf, 47'h1791e2655bf8};
        rom[130] = {47'h7fffffff2eeb, 47'h0000021a9423, 47'h7ff9ea355783, 47'h178bca7f4cbc};
        rom[131] = {47'h7fffffff3045, 47'h0000021820e5, 47'h7ff9ee680cb5, 47'h1785b6ce674d};
        rom[132] = {47'h7fffffff319c, 47'h00000215b1b6, 47'h7ff9f295df7a, 47'h177fa74dc52d};
        rom[133] = {47'h7fffffff32f0, 47'h00000213468b, 47'h7ff9f6bed7e4, 47'h17799bf887f9};
        rom[134] = {47'h7fffffff3441, 47'h00000210df5c, 47'h7ff9fae2fdf5, 47'h177394c9d958};
        rom[135] = {47'h7fffffff3590, 47'h0000020e7c21, 47'h7ff9ff02599b, 47'h176d91bceaea};
        rom[136] = {47'h7fffffff36dc, 47'h0000020c1cd2, 47'h7ffa031cf2b7, 47'h176792ccf637};
        rom[137] = {47'h7fffffff3824, 47'h00000209c165, 47'h7ffa0732d115, 47'h176197f53c9a};
        rom[138] = {47'h7fffffff396b, 47'h0000020769d3, 47'h7ffa0b43fc75, 47'h175ba1310739};
        rom[139] = {47'h7fffffff3aae, 47'h000002051613, 47'h7ffa0f507c82, 47'h1755ae7ba6eb};
        rom[140] = {47'h7fffffff3bef, 47'h00000202c61e, 47'h7ffa135858da, 47'h174fbfd0742e};
        rom[141] = {47'h7fffffff3d2d, 47'h0000020079ea, 47'h7ffa175b9909, 47'h1749d52acf14};
        rom[142] = {47'h7fffffff3e68, 47'h000001fe3172, 47'h7ffa1b5a448c, 47'h1743ee861f35};
        rom[143] = {47'h7fffffff3fa1, 47'h000001fbecab, 47'h7ffa1f5462d0, 47'h173e0bddd39b};
        rom[144] = {47'h7fffffff40d8, 47'h000001f9ab90, 47'h7ffa2349fb32, 47'h17382d2d62b8};
        rom[145] = {47'h7fffffff420b, 47'h000001f76e17, 47'h7ffa273b14ff, 47'h173252704a51};
        rom[146] = {47'h7fffffff433d, 47'h000001f5343a, 47'h7ffa2b27b776, 47'h172c7ba20f73};
        rom[147] = {47'h7fffffff446c, 47'h000001f2fdf1, 47'h7ffa2f0fe9c7, 47'h1726a8be3e60};
        rom[148] = {47'h7fffffff4598, 47'h000001f0cb34, 47'h7ffa32f3b311, 47'h1720d9c06a83};
        rom[149] = {47'h7fffffff46c2, 47'h000001ee9bfc, 47'h7ffa36d31a65, 47'h171b0ea42e5f};
        rom[150] = {47'h7fffffff47e9, 47'h000001ec7042, 47'h7ffa3aae26c8, 47'h171547652b82};
        rom[151] = {47'h7fffffff490e, 47'h000001ea47fe, 47'h7ffa3e84df2b, 47'h170f83ff0a75};
        rom[152] = {47'h7fffffff4a31, 47'h000001e82329, 47'h7ffa42574a76, 47'h1709c46d7aac};
        rom[153] = {47'h7fffffff4b51, 47'h000001e601bc, 47'h7ffa46256f7f, 47'h170408ac327c};
        rom[154] = {47'h7fffffff4c6f, 47'h000001e3e3b1, 47'h7ffa49ef550f, 47'h16fe50b6ef08};
        rom[155] = {47'h7fffffff4d8b, 47'h000001e1c8ff, 47'h7ffa4db501e2, 47'h16f89c897437};
        rom[156] = {47'h7fffffff4ea5, 47'h000001dfb1a1, 47'h7ffa51767ca5, 47'h16f2ec1f8ca4};
        rom[157] = {47'h7fffffff4fbc, 47'h000001dd9d8f, 47'h7ffa5533cbf8, 47'h16ed3f75098e};
        rom[158] = {47'h7fffffff50d1, 47'h000001db8cc3, 47'h7ffa58ecf66d, 47'h16e79685c2d2};
        rom[159] = {47'h7fffffff51e4, 47'h000001d97f36, 47'h7ffa5ca20287, 47'h16e1f14d96d2};
        rom[160] = {47'h7fffffff52f4, 47'h000001d774e1, 47'h7ffa6052f6bf, 47'h16dc4fc86a72};
        rom[161] = {47'h7fffffff5402, 47'h000001d56dbd, 47'h7ffa63ffd97f, 47'h16d6b1f22906};
        rom[162] = {47'h7fffffff550f, 47'h000001d369c5, 47'h7ffa67a8b123, 47'h16d117c6c445};
        rom[163] = {47'h7fffffff5619, 47'h000001d168f2, 47'h7ffa6b4d83fb, 47'h16cb8142343c};
        rom[164] = {47'h7fffffff5721, 47'h000001cf6b3d, 47'h7ffa6eee584b, 47'h16c5ee607742};
        rom[165] = {47'h7fffffff5827, 47'h000001cd70a1, 47'h7ffa728b344a, 47'h16c05f1d91ec};
        rom[166] = {47'h7fffffff592b, 47'h000001cb7916, 47'h7ffa76241e21, 47'h16bad3758efd};
        rom[167] = {47'h7fffffff5a2d, 47'h000001c98497, 47'h7ffa79b91bed, 47'h16b54b647f5e};
        rom[168] = {47'h7fffffff5b2d, 47'h000001c7931d, 47'h7ffa7d4a33c1, 47'h16afc6e67a0f};
        rom[169] = {47'h7fffffff5c2a, 47'h000001c5a4a3, 47'h7ffa80d76ba1, 47'h16aa45f79c1a};
        rom[170] = {47'h7fffffff5d26, 47'h000001c3b923, 47'h7ffa8460c986, 47'h16a4c8940889};
        rom[171] = {47'h7fffffff5e20, 47'h000001c1d096, 47'h7ffa87e6535d, 47'h169f4eb7e858};
        rom[172] = {47'h7fffffff5f18, 47'h000001bfeaf6, 47'h7ffa8b680f08, 47'h1699d85f6a6b};
        rom[173] = {47'h7fffffff600e, 47'h000001be083f, 47'h7ffa8ee6025c, 47'h16946586c381};
        rom[174] = {47'h7fffffff6102, 47'h000001bc2869, 47'h7ffa92603322, 47'h168ef62a2e2a};
        rom[175] = {47'h7fffffff61f4, 47'h000001ba4b70, 47'h7ffa95d6a719, 47'h16898a45eab7};
        rom[176] = {47'h7fffffff62e5, 47'h000001b8714d, 47'h7ffa994963f3, 47'h168421d63f34};
        rom[177] = {47'h7fffffff63d3, 47'h000001b699fc, 47'h7ffa9cb86f5a, 47'h167ebcd77759};
        rom[178] = {47'h7fffffff64c0, 47'h000001b4c575, 47'h7ffaa023cee8, 47'h16795b45e482};
        rom[179] = {47'h7fffffff65ab, 47'h000001b2f3b5, 47'h7ffaa38b8830, 47'h1673fd1ddd9f};
        rom[180] = {47'h7fffffff6694, 47'h000001b124b5, 47'h7ffaa6efa0b7, 47'h166ea25bbf2e};
        rom[181] = {47'h7fffffff677b, 47'h000001af5871, 47'h7ffaaa501df9, 47'h16694afbeb2e};
        rom[182] = {47'h7fffffff6860, 47'h000001ad8ee2, 47'h7ffaadad0568, 47'h1663f6fac913};
        rom[183] = {47'h7fffffff6944, 47'h000001abc803, 47'h7ffab1065c68, 47'h165ea654c5bc};
        rom[184] = {47'h7fffffff6a26, 47'h000001aa03cf, 47'h7ffab45c2856, 47'h16595906536b};
        rom[185] = {47'h7fffffff6b06, 47'h000001a84242, 47'h7ffab7ae6e83, 47'h16540f0be9b7};
        rom[186] = {47'h7fffffff6be5, 47'h000001a68355, 47'h7ffabafd3436, 47'h164ec8620583};
        rom[187] = {47'h7fffffff6cc2, 47'h000001a4c704, 47'h7ffabe487eaa, 47'h1649850528f2};
        rom[188] = {47'h7fffffff6d9d, 47'h000001a30d49, 47'h7ffac1905312, 47'h164444f1db62};
        rom[189] = {47'h7fffffff6e76, 47'h000001a15621, 47'h7ffac4d4b697, 47'h163f0824a95b};
        rom[190] = {47'h7fffffff6f4e, 47'h0000019fa184, 47'h7ffac815ae57, 47'h1639ce9a2489};
        rom[191] = {47'h7fffffff7025, 47'h0000019def70, 47'h7ffacb533f65, 47'h1634984ee3b3};
        rom[192] = {47'h7fffffff70f9, 47'h0000019c3fde, 47'h7fface8d6ece, 47'h162f653f82ac};
        rom[193] = {47'h7fffffff71cc, 47'h0000019a92ca, 47'h7ffad1c44190, 47'h162a3568a251};
        rom[194] = {47'h7fffffff729e, 47'h00000198e830, 47'h7ffad4f7bca4, 47'h162508c6e878};
        rom[195] = {47'h7fffffff736e, 47'h00000197400a, 47'h7ffad827e4f7, 47'h161fdf56ffea};
        rom[196] = {47'h7fffffff743c, 47'h000001959a54, 47'h7ffadb54bf6e, 47'h161ab9159859};
        rom[197] = {47'h7fffffff7509, 47'h00000193f709, 47'h7ffade7e50e4, 47'h161595ff6657};
        rom[198] = {47'h7fffffff75d4, 47'h000001925624, 47'h7ffae1a49e29, 47'h16107611234d};
        rom[199] = {47'h7fffffff769e, 47'h00000190b7a1, 47'h7ffae4c7ac08, 47'h160b59478d6f};
        rom[200] = {47'h7fffffff7766, 47'h0000018f1b7c, 47'h7ffae7e77f3e, 47'h16063f9f67b6};
        rom[201] = {47'h7fffffff782d, 47'h0000018d81b0, 47'h7ffaeb041c82, 47'h1601291579d6};
        rom[202] = {47'h7fffffff78f3, 47'h0000018bea38, 47'h7ffaee1d8882, 47'h15fc15a69035};
        rom[203] = {47'h7fffffff79b7, 47'h0000018a5510, 47'h7ffaf133c7e3, 47'h15f7054f7be2};
        rom[204] = {47'h7fffffff7a79, 47'h00000188c234, 47'h7ffaf446df3f, 47'h15f1f80d128c};
        rom[205] = {47'h7fffffff7b3a, 47'h0000018731a0, 47'h7ffaf756d32b, 47'h15eceddc2e78};
        rom[206] = {47'h7fffffff7bfa, 47'h00000185a34e, 47'h7ffafa63a831, 47'h15e7e6b9ae7d};
        rom[207] = {47'h7fffffff7cb8, 47'h00000184173c, 47'h7ffafd6d62d2, 47'h15e2e2a275f6};
        rom[208] = {47'h7fffffff7d75, 47'h000001828d64, 47'h7ffb00740789, 47'h15dde1936cbc};
        rom[209] = {47'h7fffffff7e30, 47'h0000018105c2, 47'h7ffb03779ac5, 47'h15d8e3897f1d};
        rom[210] = {47'h7fffffff7eea, 47'h0000017f8053, 47'h7ffb067820f1, 47'h15d3e8819dd4};
        rom[211] = {47'h7fffffff7fa3, 47'h0000017dfd12, 47'h7ffb09759e6d, 47'h15cef078be03};
        rom[212] = {47'h7fffffff805a, 47'h0000017c7bfb, 47'h7ffb0c701791, 47'h15c9fb6bd925};
        rom[213] = {47'h7fffffff8110, 47'h0000017afd0b, 47'h7ffb0f6790ae, 47'h15c50957ed0d};
        rom[214] = {47'h7fffffff81c5, 47'h00000179803d, 47'h7ffb125c0e0c, 47'h15c01a39fbd6};
        rom[215] = {47'h7fffffff8279, 47'h00000178058c, 47'h7ffb154d93eb, 47'h15bb2e0f0be4};
        rom[216] = {47'h7fffffff832b, 47'h000001768cf7, 47'h7ffb183c2684, 47'h15b644d427d4};
        rom[217] = {47'h7fffffff83dc, 47'h000001751677, 47'h7ffb1b27ca08, 47'h15b15e865e7a};
        rom[218] = {47'h7fffffff848b, 47'h00000173a20b, 47'h7ffb1e1082a0, 47'h15ac7b22c2d5};
        rom[219] = {47'h7fffffff853a, 47'h000001722fad, 47'h7ffb20f6546c, 47'h15a79aa66c0a};
        rom[220] = {47'h7fffffff85e7, 47'h00000170bf5a, 47'h7ffb23d94388, 47'h15a2bd0e755d};
        rom[221] = {47'h7fffffff8693, 47'h0000016f510e, 47'h7ffb26b95405, 47'h159de257fe25};
        rom[222] = {47'h7fffffff873d, 47'h0000016de4c6, 47'h7ffb299689ed, 47'h15990a8029ca};
        rom[223] = {47'h7fffffff87e7, 47'h0000016c7a7d, 47'h7ffb2c70e945, 47'h159435841fba};
        rom[224] = {47'h7fffffff888f, 47'h0000016b1231, 47'h7ffb2f487609, 47'h158f63610b63};
        rom[225] = {47'h7fffffff8936, 47'h00000169abde, 47'h7ffb321d342c, 47'h158a94141c2c};
        rom[226] = {47'h7fffffff89dc, 47'h00000168477f, 47'h7ffb34ef279e, 47'h1585c79a856c};
        rom[227] = {47'h7fffffff8a80, 47'h00000166e512, 47'h7ffb37be5444, 47'h1580fdf17e65};
        rom[228] = {47'h7fffffff8b24, 47'h000001658493, 47'h7ffb3a8abdfd, 47'h157c3716423b};
        rom[229] = {47'h7fffffff8bc6, 47'h0000016425fe, 47'h7ffb3d5468a3, 47'h157773060fef};
        rom[230] = {47'h7fffffff8c67, 47'h00000162c951, 47'h7ffb401b5806, 47'h1572b1be2a57};
        rom[231] = {47'h7fffffff8d07, 47'h000001616e87, 47'h7ffb42df8ff1, 47'h156df33bd815};
        rom[232] = {47'h7fffffff8da6, 47'h00000160159d, 47'h7ffb45a11428, 47'h1569377c6394};
        rom[233] = {47'h7fffffff8e44, 47'h0000015ebe90, 47'h7ffb485fe868, 47'h15647e7d1aff};
        rom[234] = {47'h7fffffff8ee1, 47'h0000015d695c, 47'h7ffb4b1c1067, 47'h155fc83b503b};
        rom[235] = {47'h7fffffff8f7c, 47'h0000015c15fe, 47'h7ffb4dd58fd4, 47'h155b14b458df};
        rom[236] = {47'h7fffffff9017, 47'h0000015ac474, 47'h7ffb508c6a59, 47'h155663e58e2e};
        rom[237] = {47'h7fffffff90b0, 47'h0000015974b8, 47'h7ffb5340a398, 47'h1551b5cc4d11};
        rom[238] = {47'h7fffffff9149, 47'h0000015826ca, 47'h7ffb55f23f2d, 47'h154d0a65f612};
        rom[239] = {47'h7fffffff91e0, 47'h00000156daa4, 47'h7ffb58a140ad, 47'h154861afed51};
        rom[240] = {47'h7fffffff9276, 47'h000001559044, 47'h7ffb5b4daba8, 47'h1543bba79a83};
        rom[241] = {47'h7fffffff930c, 47'h0000015447a8, 47'h7ffb5df783a6, 47'h153f184a68e5};
        rom[242] = {47'h7fffffff93a0, 47'h0000015300ca, 47'h7ffb609ecc2a, 47'h153a7795c73f};
        rom[243] = {47'h7fffffff9433, 47'h00000151bbaa, 47'h7ffb634388b1, 47'h1535d98727d3};
        rom[244] = {47'h7fffffff94c5, 47'h000001507843, 47'h7ffb65e5bcb0, 47'h15313e1c0061};
        rom[245] = {47'h7fffffff9556, 47'h0000014f3693, 47'h7ffb68856b98, 47'h152ca551ca1a};
        rom[246] = {47'h7fffffff95e6, 47'h0000014df696, 47'h7ffb6b2298d2, 47'h15280f26019a};
        rom[247] = {47'h7fffffff9676, 47'h0000014cb849, 47'h7ffb6dbd47c3, 47'h15237b9626e9};
        rom[248] = {47'h7fffffff9704, 47'h0000014b7bab, 47'h7ffb70557bc9, 47'h151eea9fbd6b};
        rom[249] = {47'h7fffffff9791, 47'h0000014a40b7, 47'h7ffb72eb383c, 47'h151a5c404be3};
        rom[250] = {47'h7fffffff981d, 47'h00000149076a, 47'h7ffb757e806e, 47'h1515d0755c66};
        rom[251] = {47'h7fffffff98a9, 47'h00000147cfc2, 47'h7ffb780f57ab, 47'h1511473c7c5b};
        rom[252] = {47'h7fffffff9933, 47'h0000014699bd, 47'h7ffb7a9dc13b, 47'h150cc0933c71};
        rom[253] = {47'h7fffffff99bc, 47'h000001456556, 47'h7ffb7d29c05f, 47'h15083c77309c};
        rom[254] = {47'h7fffffff9a45, 47'h00000144328c, 47'h7ffb7fb35852, 47'h1503bae5f00e};
        rom[255] = {47'h7fffffff9acd, 47'h00000143015b, 47'h7ffb823a8c49, 47'h14ff3bdd1530};
        rom[256] = {47'h7fffffff9b53, 47'h00000141d1c1, 47'h7ffb84bf5f75, 47'h14fabf5a3da0};
        rom[257] = {47'h7fffffff9bd9, 47'h00000140a3bb, 47'h7ffb8741d501, 47'h14f6455b0a29};
        rom[258] = {47'h7fffffff9c5e, 47'h0000013f7746, 47'h7ffb89c1f012, 47'h14f1cddd1ebe};
        rom[259] = {47'h7fffffff9ce2, 47'h0000013e4c5f, 47'h7ffb8c3fb3c7, 47'h14ed58de2273};
        rom[260] = {47'h7fffffff9d65, 47'h0000013d2305, 47'h7ffb8ebb233b, 47'h14e8e65bbf7b};
        rom[261] = {47'h7fffffff9de7, 47'h0000013bfb34, 47'h7ffb91344184, 47'h14e47653a320};
        rom[262] = {47'h7fffffff9e68, 47'h0000013ad4e9, 47'h7ffb93ab11b0, 47'h14e008c37dbf};
        rom[263] = {47'h7fffffff9ee9, 47'h00000139b022, 47'h7ffb961f96cb, 47'h14db9da902c1};
        rom[264] = {47'h7fffffff9f68, 47'h000001388cdd, 47'h7ffb9891d3da, 47'h14d73501e897};
        rom[265] = {47'h7fffffff9fe7, 47'h000001376b16, 47'h7ffb9b01cbdd, 47'h14d2cecbe8b6};
        rom[266] = {47'h7fffffffa065, 47'h000001364acc, 47'h7ffb9d6f81ce, 47'h14ce6b04bf90};
        rom[267] = {47'h7fffffffa0e2, 47'h000001352bfb, 47'h7ffb9fdaf8a5, 47'h14ca09aa2c8f};
        rom[268] = {47'h7fffffffa15e, 47'h000001340ea2, 47'h7ffba2443351, 47'h14c5aab9f211};
        rom[269] = {47'h7fffffffa1da, 47'h00000132f2bd, 47'h7ffba4ab34c0, 47'h14c14e31d563};
        rom[270] = {47'h7fffffffa254, 47'h00000131d84b, 47'h7ffba70fffd7, 47'h14bcf40f9eb9};
        rom[271] = {47'h7fffffffa2ce, 47'h00000130bf48, 47'h7ffba9729778, 47'h14b89c51192f};
        rom[272] = {47'h7fffffffa347, 47'h0000012fa7b3, 47'h7ffbabd2fe82, 47'h14b446f412be};
        rom[273] = {47'h7fffffffa3bf, 47'h0000012e9189, 47'h7ffbae3137cd, 47'h14aff3f65c3a};
        rom[274] = {47'h7fffffffa437, 47'h0000012d7cc7, 47'h7ffbb08d462b, 47'h14aba355c94f};
        rom[275] = {47'h7fffffffa4ad, 47'h0000012c696b, 47'h7ffbb2e72c6c, 47'h14a755103077};
        rom[276] = {47'h7fffffffa523, 47'h0000012b5774, 47'h7ffbb53eed59, 47'h14a309236afb};
        rom[277] = {47'h7fffffffa598, 47'h0000012a46de, 47'h7ffbb7948bb9, 47'h149ebf8d54ec};
        rom[278] = {47'h7fffffffa60d, 47'h0000012937a7, 47'h7ffbb9e80a4c, 47'h149a784bcd1b};
        rom[279] = {47'h7fffffffa680, 47'h0000012829cd, 47'h7ffbbc396bce, 47'h1496335cb51b};
        rom[280] = {47'h7fffffffa6f3, 47'h000001271d4e, 47'h7ffbbe88b2f7, 47'h1491f0bdf136};
        rom[281] = {47'h7fffffffa765, 47'h000001261227, 47'h7ffbc0d5e279, 47'h148db06d686e};
        rom[282] = {47'h7fffffffa7d6, 47'h000001250856, 47'h7ffbc320fd04, 47'h148972690473};
        rom[283] = {47'h7fffffffa847, 47'h00000123ffd9, 47'h7ffbc56a0541, 47'h148536aeb1a3};
        rom[284] = {47'h7fffffffa8b7, 47'h00000122f8ae, 47'h7ffbc7b0fdd6, 47'h1480fd3c5f04};
        rom[285] = {47'h7fffffffa926, 47'h00000121f2d3, 47'h7ffbc9f5e965, 47'h147cc60ffe3f};
        rom[286] = {47'h7fffffffa994, 47'h00000120ee44, 47'h7ffbcc38ca89, 47'h14789127839d};
        rom[287] = {47'h7fffffffaa02, 47'h0000011feb02, 47'h7ffbce79a3dd, 47'h14745e80e5ff};
        rom[288] = {47'h7fffffffaa6f, 47'h0000011ee908, 47'h7ffbd0b877f4, 47'h14702e1a1edf};
        rom[289] = {47'h7fffffffaadb, 47'h0000011de855, 47'h7ffbd2f5495e, 47'h146bfff12a49};
        rom[290] = {47'h7fffffffab47, 47'h0000011ce8e7, 47'h7ffbd5301aa7, 47'h1467d40406d7};
        rom[291] = {47'h7fffffffabb2, 47'h0000011beabc, 47'h7ffbd768ee57, 47'h1463aa50b5ac};
        rom[292] = {47'h7fffffffac1c, 47'h0000011aedd1, 47'h7ffbd99fc6f1, 47'h145f82d53a70};
        rom[293] = {47'h7fffffffac86, 47'h00000119f226, 47'h7ffbdbd4a6f5, 47'h145b5d8f9b4f};
        rom[294] = {47'h7fffffffacee, 47'h00000118f7b6, 47'h7ffbde0790de, 47'h14573a7de0ef};
        rom[295] = {47'h7fffffffad57, 47'h00000117fe82, 47'h7ffbe0388723, 47'h1453199e1672};
        rom[296] = {47'h7fffffffadbe, 47'h000001170686, 47'h7ffbe2678c38, 47'h144efaee496e};
        rom[297] = {47'h7fffffffae25, 47'h000001160fc1, 47'h7ffbe494a28c, 47'h144ade6c89ea};
        rom[298] = {47'h7fffffffae8b, 47'h000001151a30, 47'h7ffbe6bfcc8a, 47'h1446c416ea5d};
        rom[299] = {47'h7fffffffaef1, 47'h0000011425d2, 47'h7ffbe8e90c99, 47'h1442abeb7fa2};
        rom[300] = {47'h7fffffffaf56, 47'h0000011332a5, 47'h7ffbeb10651e, 47'h143e95e860ff};
        rom[301] = {47'h7fffffffafba, 47'h0000011240a7, 47'h7ffbed35d876, 47'h143a820ba818};
        rom[302] = {47'h7fffffffb01e, 47'h000001114fd6, 47'h7ffbef596900, 47'h1436705370ef};
        rom[303] = {47'h7fffffffb081, 47'h00000110602f, 47'h7ffbf17b1911, 47'h143260bdd9e2};
        rom[304] = {47'h7fffffffb0e3, 47'h0000010f71b2, 47'h7ffbf39aeaff, 47'h142e534903a4};
        rom[305] = {47'h7fffffffb145, 47'h0000010e845c, 47'h7ffbf5b8e11a, 47'h142a47f31139};
        rom[306] = {47'h7fffffffb1a6, 47'h0000010d982c, 47'h7ffbf7d4fdaf, 47'h14263eba27f4};
        rom[307] = {47'h7fffffffb207, 47'h0000010cad1f, 47'h7ffbf9ef4306, 47'h1422379c6f75};
        rom[308] = {47'h7fffffffb267, 47'h0000010bc334, 47'h7ffbfc07b365, 47'h141e329811a1};
        rom[309] = {47'h7fffffffb2c6, 47'h0000010ada69, 47'h7ffbfe1e510e, 47'h141a2fab3aa2};
        rom[310] = {47'h7fffffffb325, 47'h00000109f2bc, 47'h7ffc00331e3f, 47'h14162ed418df};
        rom[311] = {47'h7fffffffb383, 47'h000001090c2c, 47'h7ffc02461d32, 47'h14123010dcff};
        rom[312] = {47'h7fffffffb3e1, 47'h0000010826b6, 47'h7ffc0457501f, 47'h140e335fb9e1};
        rom[313] = {47'h7fffffffb43e, 47'h000001074259, 47'h7ffc0666b939, 47'h140a38bee497};
        rom[314] = {47'h7fffffffb49a, 47'h000001065f13, 47'h7ffc08745ab0, 47'h1406402c9466};
        rom[315] = {47'h7fffffffb4f6, 47'h000001057ce2, 47'h7ffc0a8036b0, 47'h140249a702c3};
        rom[316] = {47'h7fffffffb552, 47'h000001049bc5, 47'h7ffc0c8a4f62, 47'h13fe552c6b4b};
        rom[317] = {47'h7fffffffb5ac, 47'h00000103bbba, 47'h7ffc0e92a6ed, 47'h13fa62bb0bc5};
        rom[318] = {47'h7fffffffb607, 47'h00000102dcc0, 47'h7ffc10993f72, 47'h13f672512418};
        rom[319] = {47'h7fffffffb660, 47'h00000101fed4, 47'h7ffc129e1b11, 47'h13f283ecf651};
        rom[320] = {47'h7fffffffb6b9, 47'h0000010121f5, 47'h7ffc14a13be4, 47'h13ee978cc696};
        rom[321] = {47'h7fffffffb712, 47'h000001004621, 47'h7ffc16a2a404, 47'h13eaad2edb28};
        rom[322] = {47'h7fffffffb76a, 47'h000000ff6b57, 47'h7ffc18a25587, 47'h13e6c4d17c5f};
        rom[323] = {47'h7fffffffb7c1, 47'h000000fe9195, 47'h7ffc1aa0527d, 47'h13e2de72f4a6};
        rom[324] = {47'h7fffffffb818, 47'h000000fdb8d9, 47'h7ffc1c9c9cf5, 47'h13defa119079};
        rom[325] = {47'h7fffffffb86f, 47'h000000fce122, 47'h7ffc1e9736fb, 47'h13db17ab9e5f};
        rom[326] = {47'h7fffffffb8c5, 47'h000000fc0a6e, 47'h7ffc20902296, 47'h13d7373f6eea};
        rom[327] = {47'h7fffffffb91a, 47'h000000fb34bc, 47'h7ffc228761cb, 47'h13d358cb54b3};
        rom[328] = {47'h7fffffffb96f, 47'h000000fa600b, 47'h7ffc247cf69d, 47'h13cf7c4da455};
        rom[329] = {47'h7fffffffb9c3, 47'h000000f98c57, 47'h7ffc2670e309, 47'h13cba1c4b46b};
        rom[330] = {47'h7fffffffba17, 47'h000000f8b9a1, 47'h7ffc2863290b, 47'h13c7c92edd8e};
        rom[331] = {47'h7fffffffba6a, 47'h000000f7e7e6, 47'h7ffc2a53ca9c, 47'h13c3f28a7a51};
        rom[332] = {47'h7fffffffbabd, 47'h000000f71725, 47'h7ffc2c42c9b1, 47'h13c01dd5e73d};
        rom[333] = {47'h7fffffffbb0f, 47'h000000f6475c, 47'h7ffc2e30283c, 47'h13bc4b0f82d0};
        rom[334] = {47'h7fffffffbb61, 47'h000000f5788b, 47'h7ffc301be82d, 47'h13b87a35ad77};
        rom[335] = {47'h7fffffffbbb3, 47'h000000f4aaae, 47'h7ffc32060b70, 47'h13b4ab46c990};
        rom[336] = {47'h7fffffffbc03, 47'h000000f3ddc6, 47'h7ffc33ee93ee, 47'h13b0de413b60};
        rom[337] = {47'h7fffffffbc54, 47'h000000f311d0, 47'h7ffc35d5838e, 47'h13ad13236917};
        rom[338] = {47'h7fffffffbca4, 47'h000000f246cc, 47'h7ffc37badc34, 47'h13a949ebbaca};
        rom[339] = {47'h7fffffffbcf3, 47'h000000f17cb6, 47'h7ffc399e9fc0, 47'h13a582989a6d};
        rom[340] = {47'h7fffffffbd42, 47'h000000f0b390, 47'h7ffc3b80d010, 47'h13a1bd2873d6};
        rom[341] = {47'h7fffffffbd90, 47'h000000efeb55, 47'h7ffc3d616efe, 47'h139df999b4b8};
        rom[342] = {47'h7fffffffbdde, 47'h000000ef2407, 47'h7ffc3f407e64, 47'h139a37eacc9c};
        rom[343] = {47'h7fffffffbe2c, 47'h000000ee5da2, 47'h7ffc411e0016, 47'h1396781a2ce5};
        rom[344] = {47'h7fffffffbe79, 47'h000000ed9825, 47'h7ffc42f9f5e6, 47'h1392ba2648c8};
        rom[345] = {47'h7fffffffbec6, 47'h000000ecd390, 47'h7ffc44d461a5, 47'h138efe0d954d};
        rom[346] = {47'h7fffffffbf12, 47'h000000ec0fe1, 47'h7ffc46ad4520, 47'h138b43ce8948};
        rom[347] = {47'h7fffffffbf5d, 47'h000000eb4d16, 47'h7ffc4884a220, 47'h13878b679d5a};
        rom[348] = {47'h7fffffffbfa9, 47'h000000ea8b2e, 47'h7ffc4a5a7a6d, 47'h1383d4d74bed};
        rom[349] = {47'h7fffffffbff3, 47'h000000e9ca28, 47'h7ffc4c2ecfcc, 47'h1380201c1130};
        rom[350] = {47'h7fffffffc03e, 47'h000000e90a02, 47'h7ffc4e01a3ff, 47'h137c6d346b17};
        rom[351] = {47'h7fffffffc088, 47'h000000e84abc, 47'h7ffc4fd2f8c6, 47'h1378bc1ed957};
        rom[352] = {47'h7fffffffc0d1, 47'h000000e78c53, 47'h7ffc51a2cfde, 47'h13750cd9dd60};
        rom[353] = {47'h7fffffffc11a, 47'h000000e6cec6, 47'h7ffc53712b00, 47'h13715f63fa62};
        rom[354] = {47'h7fffffffc163, 47'h000000e61215, 47'h7ffc553e0be5, 47'h136db3bbb542};
        rom[355] = {47'h7fffffffc1ab, 47'h000000e5563e, 47'h7ffc57097441, 47'h136a09df94a0};
        rom[356] = {47'h7fffffffc1f3, 47'h000000e49b40, 47'h7ffc58d365c8, 47'h136661ce20ca};
        rom[357] = {47'h7fffffffc23a, 47'h000000e3e118, 47'h7ffc5a9be228, 47'h1362bb85e3c4};
        rom[358] = {47'h7fffffffc281, 47'h000000e327c7, 47'h7ffc5c62eb11, 47'h135f1705693f};
        rom[359] = {47'h7fffffffc2c8, 47'h000000e26f4b, 47'h7ffc5e28822c, 47'h135b744b3e98};
        rom[360] = {47'h7fffffffc30e, 47'h000000e1b7a2, 47'h7ffc5feca921, 47'h1357d355f2d6};
        rom[361] = {47'h7fffffffc354, 47'h000000e100cc, 47'h7ffc61af6198, 47'h1354342416a8};
        rom[362] = {47'h7fffffffc399, 47'h000000e04ac7, 47'h7ffc6370ad34, 47'h135096b43c60};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [(K + WSB)-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= {sb_in, idx_raw};
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [(K + WSB)-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB((K + WSB)), .ACC_SIGNED(1),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire        [K-1:0]    idx_p = esb[K-1:0];
    wire        [WSB-1:0]  sb_p  = esb[K +: WSB];
    wire        [WMAN-1:0] v_p   = {idx_p, ew};
    wire signed [WF-1:0]   f_p   = $signed({~v_p[WMAN-1], v_p[WMAN-2:0]});
    wire                   f_neg = f_p[WF-1];
    wire        [WF-1:0]   mag_f = f_neg ? (-f_p) : f_p;   // |f|, fits WF-1 bits (top bit structurally 0)

    wire [WF+ACCM-1:0] umag_p;   // unsigned |f| * C(f)
    wire [WSB:0]       fsb;      // {delayed f sign, external sideband} riding the pmul
    _zkf_pmul #(
        .WA(WF), .WB(ACCM), .A_SIGNED(0), .B_SIGNED(0),
        .WSB(WSB + 1), .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT_FINAL)
    ) u_final_pmul (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in({f_neg, sb_p}),
        .a(mag_f), .b(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(fsb), .p(umag_p)
    );
    assign sb_out = fsb[WSB-1:0];
    // Emit the magnitude and the sign SEPARATELY rather than a signed product: the caller folds the sign into
    // its e + log2(m') reconstruction as a single add/subtract, so the post-product cone carries one fewer wide
    // negate carry chain (a standalone two's-complement negate here would otherwise sit in series with that
    // adder and the magnitude abs, the critical path on wide formats). umag_p is the exact |f|*C(f): C(f) < 2
    // and |f| < 2**(WF-1) bound it below 2**(F2-1), so the F2+1-bit slice is lossless. The sign rode the pmul
    // sideband (fsb[WSB]) and so is aligned with out_valid.
    assign l_mag = umag_p[F2:0];
    assign l_neg = fsb[WSB];
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
