/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=27 (degree 3); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes C(f)=log2(1+f)/f by unsigned v (WFRAC+1 bits) and returns log2(m')=f*C(f) as
/// the unsigned magnitude l_mag = |f|*C(f) plus the sign l_neg (set when m>=sqrt(2)), at scale 2**-F2,
/// F2 = WFRAC+1+CF. The final f*C(f) multiply is fully unsigned (|f|*C(f)); the caller folds l_neg into its
/// reconstruction add/subtract. Register stages: two-stage ROM read + Horner + final multiply.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_log2_m27 #(
    parameter D                   = 3,
    parameter WSB                 = 1,
    parameter WMULTIPLIER         = 0,
    parameter STAGE_PRODUCT       = 0,
    parameter STAGE_PRODUCT_FINAL = STAGE_PRODUCT
) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire     [ 27-1:0] v,  // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire        [66:0] l_mag,  // |log2(m')| = |f|*C(f) magnitude at scale 2**-F2, F2 = WFRAC+1+CF
    output wire               l_neg   // sign of log2(m') (= sign of reduced f); 1 when m >= sqrt(2)
);
    generate if (D != 3) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 27;
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 7;
    localparam integer SEG_BASE = 26;
    localparam integer RW   = 20;
    localparam integer CW   = 42;
    localparam integer ACCW = 42;
    localparam integer NSEG = 92;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [K-1:0]    idx_raw = v[WMAN-1 -: K];
    wire [K-1:0]    idx_ofs = idx_raw - SEG_BASE[K-1:0];
    wire [WIDX-1:0] idx     = idx_ofs[WIDX-1:0];
    wire [RW-1:0]   w       = v[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[ 0] = {42'h3fffffba6ee, 42'h000021c2031, 42'h3fedaa84268, 42'h0db176fc4b0};
        rom[ 1] = {42'h3fffffbccfb, 42'h000020f1560, 42'h3feded37c57, 42'h0d9f42fce38};
        rom[ 2] = {42'h3fffffbf15a, 42'h00002027cb0, 42'h3fee2e51294, 42'h0d8d50e2ceb};
        rom[ 3] = {42'h3fffffc1422, 42'h00001f65117, 42'h3fee6dde45c, 42'h0d7b9f1ad8a};
        rom[ 4] = {42'h3fffffc3568, 42'h00001ea8dd1, 42'h3feeabec719, 42'h0d6a2c1f720};
        rom[ 5] = {42'h3fffffc5541, 42'h00001df2e58, 42'h3feee8886ee, 42'h0d58f678172};
        rom[ 6] = {42'h3fffffc73c0, 42'h00001d42e67, 42'h3fef23be731, 42'h0d47fcb8bf9};
        rom[ 7] = {42'h3fffffc90f8, 42'h00001c989f0, 42'h3fef5d9a2e8, 42'h0d373d81553};
        rom[ 8] = {42'h3fffffcacf8, 42'h00001bf3d1c, 42'h3fef9626d30, 42'h0d26b77d323};
        rom[ 9] = {42'h3fffffcc7d1, 42'h00001b54445, 42'h3fefcd6f1ab, 42'h0d166962a67};
        rom[10] = {42'h3fffffce192, 42'h00001ab9bf6, 42'h3ff0037d4e1, 42'h0d0651f2828};
        rom[11] = {42'h3fffffcfa49, 42'h00001a240e8, 42'h3ff0385b49b, 42'h0cf66ff7a92};
        rom[12] = {42'h3fffffd1202, 42'h00001992ffa, 42'h3ff06c1283d, 42'h0ce6c246a5e};
        rom[13] = {42'h3fffffd28cb, 42'h00001906636, 42'h3ff09eac111, 42'h0cd747bd498};
        rom[14] = {42'h3fffffd3eaf, 42'h0000187e0c9, 42'h3ff0d030a9a, 42'h0cc7ff424aa};
        rom[15] = {42'h3fffffd53b8, 42'h000017f9d05, 42'h3ff100a8ad9, 42'h0cb8e7c4ebc};
        rom[16] = {42'h3fffffd67f2, 42'h0000177985b, 42'h3ff1301c293, 42'h0caa003ca52};
        rom[17] = {42'h3fffffd7b66, 42'h000016fd05d, 42'h3ff15e92d8e, 42'h0c9b47a8d33};
        rom[18] = {42'h3fffffd8e1e, 42'h000016842b9, 42'h3ff18c142d2, 42'h0c8cbd10685};
        rom[19] = {42'h3fffffda021, 42'h0000160ed3a, 42'h3ff1b8a74df, 42'h0c7e5f81a2f};
        rom[20] = {42'h3fffffdb179, 42'h0000159cdc4, 42'h3ff1e4531e2, 42'h0c702e11c69};
        rom[21] = {42'h3fffffdc22e, 42'h0000152e254, 42'h3ff20f1e3ec, 42'h0c6227dcd88};
        rom[22] = {42'h3fffffdd246, 42'h000014c2900, 42'h3ff2390f120, 42'h0c544c055f6};
        rom[23] = {42'h3fffffde1c8, 42'h00001459ff1, 42'h3ff2622bbe0, 42'h0c4699b425c};
        rom[24] = {42'h3fffffdf0bc, 42'h000013f4569, 42'h3ff28a7a2fa, 42'h0c391017ff6};
        rom[25] = {42'h3fffffdff27, 42'h000013917bb, 42'h3ff2b2001ce, 42'h0c2bae65915};
        rom[26] = {42'h3fffffe0d10, 42'h0000133154e, 42'h3ff2d8c3078, 42'h0c1e73d71c6};
        rom[27] = {42'h3fffffe1a7c, 42'h000012d3c9b, 42'h3ff2fec83f3, 42'h0c115fac49d};
        rom[28] = {42'h3fffffe2771, 42'h00001278c2a, 42'h3ff32414e3b, 42'h0c047129fa6};
        rom[29] = {42'h3fffffe33f3, 42'h00001220296, 42'h3ff348ade72, 42'h0bf7a79a17d};
        rom[30] = {42'h3fffffe4008, 42'h000011c9e87, 42'h3ff36c980fa, 42'h0beb024b678};
        rom[31] = {42'h3fffffe4bb3, 42'h00001175eb5, 42'h3ff38fd7f95, 42'h0bde8091601};
        rom[32] = {42'h3fffffe56fa, 42'h000011241e6, 42'h3ff3b272182, 42'h0bd221c3ffe};
        rom[33] = {42'h3fffffe61e1, 42'h000010d46ea, 42'h3ff3d46ab9a, 42'h0bc5e53fa61};
        rom[34] = {42'h3fffffe6c6b, 42'h00001086ca2, 42'h3ff3f5c6062, 42'h0bb9ca64ec6};
        rom[35] = {42'h3fffffe769c, 42'h0000103b1f6, 42'h3ff4168802d, 42'h0badd098835};
        rom[36] = {42'h3fffffe8079, 42'h00000ff15df, 42'h3ff436b492b, 42'h0ba1f7430f5};
        rom[37] = {42'h3fffffe8a03, 42'h00000fa975a, 42'h3ff4564f783, 42'h0b963dd1077};
        rom[38] = {42'h3fffffe933f, 42'h00000f63575, 42'h3ff4755c568, 42'h0b8aa3b2958};
        rom[39] = {42'h3fffffe9c2f, 42'h00000f1ef42, 42'h3ff493deb2d, 42'h0b7f285b774};
        rom[40] = {42'h3fffffea4d7, 42'h00000edc3e0, 42'h3ff4b1d9f54, 42'h0b73cb42e12};
        rom[41] = {42'h3fffffead3a, 42'h00000e9b275, 42'h3ff4cf516a7, 42'h0b688be361e};
        rom[42] = {42'h3fffffeb559, 42'h00000e5ba31, 42'h3ff4ec48442, 42'h0b5d69bac74};
        rom[43] = {42'h3fffffebd38, 42'h00000e1da4a, 42'h3ff508c19ab, 42'h0b52644a040};
        rom[44] = {42'h3fffffec4d9, 42'h00000de11ff, 42'h3ff524c06db, 42'h0b477b1516e};
        rom[45] = {42'h3fffffecc3e, 42'h00000da6097, 42'h3ff54047a50, 42'h0b3cada2f20};
        rom[46] = {42'h3fffffed36a, 42'h00000d6c55d, 42'h3ff55b5a11d, 42'h0b31fb7d645};
        rom[47] = {42'h3fffffeda5e, 42'h00000d33fa7, 42'h3ff575fa6f3, 42'h0b276431029};
        rom[48] = {42'h3fffffee11e, 42'h00000cfcece, 42'h3ff5902b634, 42'h0b1ce74d121};
        rom[49] = {42'h3fffffee7aa, 42'h00000cc7232, 42'h3ff5a9ef7fa, 42'h0b128463741};
        rom[50] = {42'h3fffffeee04, 42'h00000c9293b, 42'h3ff5c349428, 42'h0b083b08917};
        rom[51] = {42'h3fffffef42f, 42'h00000c5f353, 42'h3ff5dc3b170, 42'h0afe0ad347f};
        rom[52] = {42'h3fffffefa2c, 42'h00000c2cfeb, 42'h3ff5f4c7563, 42'h0af3f35cd71};
        rom[53] = {42'h3fffffefffd, 42'h00000bfbe7a, 42'h3ff60cf0479, 42'h0ae9f440cec};
        rom[54] = {42'h3ffffff05a3, 42'h00000bcbe7b, 42'h3ff624b8219, 42'h0ae00d1cfdc};
        rom[55] = {42'h3ffffff0b20, 42'h00000b9cf6e, 42'h3ff63c210a9, 42'h0ad63d91614};
        rom[56] = {42'h3ffffff1075, 42'h00000b6f0d7, 42'h3ff6532d191, 42'h0acc854014c};
        rom[57] = {42'h3ffffff15a4, 42'h00000b4223f, 42'h3ff669de544, 42'h0ac2e3cd429};
        rom[58] = {42'h3ffffff1aad, 42'h00000b16333, 42'h3ff68036b4f, 42'h0ab958df150};
        rom[59] = {42'h3ffffff1f93, 42'h00000aeb343, 42'h3ff69638259, 42'h0aafe41da7f};
        rom[60] = {42'h3ffffff2456, 42'h00000ac1203, 42'h3ff6abe4830, 42'h0aa68532fae};
        rom[61] = {42'h3ffffff28f8, 42'h00000a97f0d, 42'h3ff6c13d9cd, 42'h0a9d3bcae38};
        rom[62] = {42'h3ffffff2d79, 42'h00000a6f9fd, 42'h3ff6d645360, 42'h0a94079300b};
        rom[63] = {42'h3ffffff31dc, 42'h00000a48270, 42'h3ff6eafd052, 42'h0a8ae83aae1};
        rom[64] = {42'h3ffffff3620, 42'h00000a21809, 42'h3ff6ff66b4d, 42'h0a81dd72f7e};
        rom[65] = {42'h3ffffff3a47, 42'h000009fba6f, 42'h3ff71383e43, 42'h0a78e6ee8f4};
        rom[66] = {42'h3ffffff3e51, 42'h000009d6948, 42'h3ff72756275, 42'h0a700461bec};
        rom[67] = {42'h3ffffff4240, 42'h000009b2442, 42'h3ff73adf077, 42'h0a6735825fb};
        rom[68] = {42'h3ffffff4615, 42'h0000098eb09, 42'h3ff74e20037, 42'h0a5e7a07cf4};
        rom[69] = {42'h3ffffff49d1, 42'h0000096bd4e, 42'h3ff7611a900, 42'h0a55d1aae49};
        rom[70] = {42'h3ffffff4d73, 42'h00000949ac5, 42'h3ff773d0182, 42'h0a4d3c25e67};
        rom[71] = {42'h3ffffff50fe, 42'h00000928324, 42'h3ff78641fd8, 42'h0a44b934822};
        rom[72] = {42'h3ffffff5471, 42'h00000907622, 42'h3ff79871987, 42'h0a3c4893c1b};
        rom[73] = {42'h3ffffff57ce, 42'h000008e737a, 42'h3ff7aa60389, 42'h0a33ea02035};
        rom[74] = {42'h3ffffff5b15, 42'h000008c7ae8, 42'h3ff7bc0f24f, 42'h0a2b9d3ef06};
        rom[75] = {42'h3ffffff5e47, 42'h000008a8c2b, 42'h3ff7cd7f9c3, 42'h0a23620b751};
        rom[76] = {42'h3ffffff6164, 42'h0000088a703, 42'h3ff7deb2d51, 42'h0a1b3829b86};
        rom[77] = {42'h3ffffff646e, 42'h0000086cb34, 42'h3ff7efa9fe5, 42'h0a131f5d13e};
        rom[78] = {42'h3ffffff6764, 42'h0000084f882, 42'h3ff800663f6, 42'h0a0b176a0c6};
        rom[79] = {42'h3ffffff6a48, 42'h00000832eb3, 42'h3ff810e8b83, 42'h0a0320164a2};
        rom[80] = {42'h3ffffff6d1a, 42'h00000816d8e, 42'h3ff8213281a, 42'h09fb392891f};
        rom[81] = {42'h3ffffff6fda, 42'h000007fb4df, 42'h3ff83144adc, 42'h09f36268be2};
        rom[82] = {42'h3ffffff7289, 42'h000007e0470, 42'h3ff8412047d, 42'h09eb9b9fb76};
        rom[83] = {42'h3ffffff7527, 42'h000007c5c0e, 42'h3ff850c654a, 42'h09e3e4976eb};
        rom[84] = {42'h3ffffff77b6, 42'h000007abb87, 42'h3ff86037d2d, 42'h09dc3d1ad6a};
        rom[85] = {42'h3ffffff7a35, 42'h000007922ac, 42'h3ff86f75bad, 42'h09d4a4f5dd5};
        rom[86] = {42'h3ffffff7ca5, 42'h0000077914e, 42'h3ff87e80ff3, 42'h09cd1bf5664};
        rom[87] = {42'h3ffffff7f06, 42'h00000760740, 42'h3ff88d5a8c9, 42'h09c5a1e7449};
        rom[88] = {42'h3ffffff8159, 42'h00000748454, 42'h3ff89c034a4, 42'h09be369a358};
        rom[89] = {42'h3ffffff839e, 42'h00000730862, 42'h3ff8aa7c1a0, 42'h09b6d9ddda9};
        rom[90] = {42'h3ffffff85d6, 42'h0000071933f, 42'h3ff8b8c5d85, 42'h09af8b82b49};
        rom[91] = {42'h3ffffff8800, 42'h000007024c2, 42'h3ff8c6e15c8, 42'h09a84b5a1e2};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [(K + WSB)-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= {sb_in, idx_raw};
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [(K + WSB)-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB((K + WSB)), .ACC_SIGNED(1),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire        [K-1:0]    idx_p = esb[K-1:0];
    wire        [WSB-1:0]  sb_p  = esb[K +: WSB];
    wire        [WMAN-1:0] v_p   = {idx_p, ew};
    wire signed [WF-1:0]   f_p   = $signed({~v_p[WMAN-1], v_p[WMAN-2:0]});
    wire                   f_neg = f_p[WF-1];
    wire        [WF-1:0]   mag_f = f_neg ? (-f_p) : f_p;   // |f|, fits WF-1 bits (top bit structurally 0)

    wire [WF+ACCM-1:0] umag_p;   // unsigned |f| * C(f)
    wire [WSB:0]       fsb;      // {delayed f sign, external sideband} riding the pmul
    _zkf_pmul #(
        .WA(WF), .WB(ACCM), .A_SIGNED(0), .B_SIGNED(0),
        .WSB(WSB + 1), .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT_FINAL)
    ) u_final_pmul (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in({f_neg, sb_p}),
        .a(mag_f), .b(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(fsb), .p(umag_p)
    );
    assign sb_out = fsb[WSB-1:0];
    // Emit the magnitude and the sign SEPARATELY rather than a signed product: the caller folds the sign into
    // its e + log2(m') reconstruction as a single add/subtract, so the post-product cone carries one fewer wide
    // negate carry chain (a standalone two's-complement negate here would otherwise sit in series with that
    // adder and the magnitude abs, the critical path on wide formats). umag_p is the exact |f|*C(f): C(f) < 2
    // and |f| < 2**(WF-1) bound it below 2**(F2-1), so the F2+1-bit slice is lossless. The sign rode the pmul
    // sideband (fsb[WSB]) and so is aligned with out_valid.
    assign l_mag = umag_p[F2:0];
    assign l_neg = fsb[WSB];
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
