/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=24 (degree 2); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes C(f)=log2(1+f)/f by unsigned v (WFRAC+1 bits) and returns log2(m')=f*C(f) as
/// the unsigned magnitude l_mag = |f|*C(f) plus the sign l_neg (set when m>=sqrt(2)), at scale 2**-F2,
/// F2 = WFRAC+1+CF. The final f*C(f) multiply is fully unsigned (|f|*C(f)); the caller folds l_neg into its
/// reconstruction add/subtract. Register stages: two-stage ROM read + Horner + final multiply.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_log2_m24 #(
    parameter D                   = 2,
    parameter WSB                 = 1,
    parameter WMULTIPLIER         = 0,
    parameter STAGE_PRODUCT       = 0,
    parameter STAGE_PRODUCT_FINAL = STAGE_PRODUCT
) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire     [ 24-1:0] v,  // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire        [60:0] l_mag,  // |log2(m')| = |f|*C(f) magnitude at scale 2**-F2, F2 = WFRAC+1+CF
    output wire               l_neg   // sign of log2(m') (= sign of reduced f); 1 when m >= sqrt(2)
);
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 24;
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 9;
    localparam integer SEG_BASE = 106;
    localparam integer RW   = 15;
    localparam integer CW   = 39;
    localparam integer ACCW = 39;
    localparam integer NSEG = 363;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [K-1:0]    idx_raw = v[WMAN-1 -: K];
    wire [K-1:0]    idx_ofs = idx_raw - SEG_BASE[K-1:0];
    wire [WIDX-1:0] idx     = idx_ofs[WIDX-1:0];
    wire [RW-1:0]   w       = v[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[  0] = {39'h00000427f0, 39'h7ff6e60a36, 39'h1b50a94c4b};
        rom[  1] = {39'h0000042179, 39'h7ff6ee5a14, 39'h1b47937e4e};
        rom[  2] = {39'h0000041b10, 39'h7ff6f69d03, 39'h1b3e85f9b8};
        rom[  3] = {39'h00000414b5, 39'h7ff6fed320, 39'h1b3580b1a9};
        rom[  4] = {39'h0000040e69, 39'h7ff706fc89, 39'h1b2c83995d};
        rom[  5] = {39'h000004082a, 39'h7ff70f1959, 39'h1b238ea42d};
        rom[  6] = {39'h00000401f9, 39'h7ff71729ab, 39'h1b1aa1c58f};
        rom[  7] = {39'h000003fbd6, 39'h7ff71f2d9c, 39'h1b11bcf113};
        rom[  8] = {39'h000003f5c0, 39'h7ff7272545, 39'h1b08e01a64};
        rom[  9] = {39'h000003efb7, 39'h7ff72f10c3, 39'h1b000b3549};
        rom[ 10] = {39'h000003e9bc, 39'h7ff736f030, 39'h1af73e35a3};
        rom[ 11] = {39'h000003e3cd, 39'h7ff73ec3a6, 39'h1aee790f70};
        rom[ 12] = {39'h000003ddeb, 39'h7ff7468b3e, 39'h1ae5bbb6c3};
        rom[ 13] = {39'h000003d816, 39'h7ff74e4713, 39'h1add061fcd};
        rom[ 14] = {39'h000003d24e, 39'h7ff755f73d, 39'h1ad4583ed7};
        rom[ 15] = {39'h000003cc91, 39'h7ff75d9bd7, 39'h1acbb20843};
        rom[ 16] = {39'h000003c6e2, 39'h7ff76534f8, 39'h1ac313708d};
        rom[ 17] = {39'h000003c13e, 39'h7ff76cc2b9, 39'h1aba7c6c48};
        rom[ 18] = {39'h000003bba6, 39'h7ff7744533, 39'h1ab1ecf021};
        rom[ 19] = {39'h000003b61a, 39'h7ff77bbc7e, 39'h1aa964f0dd};
        rom[ 20] = {39'h000003b09a, 39'h7ff78328b1, 39'h1aa0e46358};
        rom[ 21] = {39'h000003ab26, 39'h7ff78a89e4, 39'h1a986b3c86};
        rom[ 22] = {39'h000003a5bd, 39'h7ff791e02d, 39'h1a8ff97173};
        rom[ 23] = {39'h000003a05f, 39'h7ff7992ba5, 39'h1a878ef740};
        rom[ 24] = {39'h0000039b0d, 39'h7ff7a06c62, 39'h1a7f2bc328};
        rom[ 25] = {39'h00000395c6, 39'h7ff7a7a27a, 39'h1a76cfca7b};
        rom[ 26] = {39'h0000039089, 39'h7ff7aece03, 39'h1a6e7b029e};
        rom[ 27] = {39'h0000038b58, 39'h7ff7b5ef15, 39'h1a662d610f};
        rom[ 28] = {39'h0000038631, 39'h7ff7bd05c3, 39'h1a5de6db60};
        rom[ 29] = {39'h0000038116, 39'h7ff7c41225, 39'h1a55a7673a};
        rom[ 30] = {39'h0000037c04, 39'h7ff7cb144e, 39'h1a4d6efa59};
        rom[ 31] = {39'h00000376fd, 39'h7ff7d20c55, 39'h1a453d8a90};
        rom[ 32] = {39'h0000037201, 39'h7ff7d8fa4f, 39'h1a3d130dc9};
        rom[ 33] = {39'h0000036d0f, 39'h7ff7dfde4f, 39'h1a34ef79fe};
        rom[ 34] = {39'h0000036826, 39'h7ff7e6b86b, 39'h1a2cd2c541};
        rom[ 35] = {39'h0000036348, 39'h7ff7ed88b6, 39'h1a24bce5b9};
        rom[ 36] = {39'h0000035e74, 39'h7ff7f44f46, 39'h1a1cadd19e};
        rom[ 37] = {39'h00000359aa, 39'h7ff7fb0c2c, 39'h1a14a57f3e};
        rom[ 38] = {39'h00000354e9, 39'h7ff801bf7e, 39'h1a0ca3e4fa};
        rom[ 39] = {39'h0000035032, 39'h7ff808694e, 39'h1a04a8f947};
        rom[ 40] = {39'h0000034b84, 39'h7ff80f09b0, 39'h19fcb4b2ae};
        rom[ 41] = {39'h00000346e0, 39'h7ff815a0b7, 39'h19f4c707ca};
        rom[ 42] = {39'h0000034245, 39'h7ff81c2e75, 39'h19ecdfef48};
        rom[ 43] = {39'h0000033db3, 39'h7ff822b2fe, 39'h19e4ff5fe9};
        rom[ 44] = {39'h000003392b, 39'h7ff8292e63, 39'h19dd255082};
        rom[ 45] = {39'h00000334ab, 39'h7ff82fa0b7, 39'h19d551b7f7};
        rom[ 46] = {39'h0000033035, 39'h7ff8360a0c, 39'h19cd848d41};
        rom[ 47] = {39'h0000032bc7, 39'h7ff83c6a74, 39'h19c5bdc76a};
        rom[ 48] = {39'h0000032762, 39'h7ff842c200, 39'h19bdfd5d8d};
        rom[ 49] = {39'h0000032306, 39'h7ff84910c3, 39'h19b64346d8};
        rom[ 50] = {39'h0000031eb2, 39'h7ff84f56cc, 39'h19ae8f7a89};
        rom[ 51] = {39'h0000031a67, 39'h7ff855942f, 39'h19a6e1eff0};
        rom[ 52] = {39'h0000031624, 39'h7ff85bc8fb, 39'h199f3a9e6f};
        rom[ 53] = {39'h00000311e9, 39'h7ff861f541, 39'h1997997d77};
        rom[ 54] = {39'h0000030db7, 39'h7ff8681913, 39'h198ffe848b};
        rom[ 55] = {39'h000003098d, 39'h7ff86e3480, 39'h198869ab3f};
        rom[ 56] = {39'h000003056b, 39'h7ff8744799, 39'h1980dae936};
        rom[ 57] = {39'h0000030151, 39'h7ff87a526e, 39'h1979523624};
        rom[ 58] = {39'h000002fd3f, 39'h7ff880550f, 39'h1971cf89ce};
        rom[ 59] = {39'h000002f935, 39'h7ff8864f8c, 39'h196a52dc07};
        rom[ 60] = {39'h000002f533, 39'h7ff88c41f5, 39'h1962dc24b3};
        rom[ 61] = {39'h000002f138, 39'h7ff8922c59, 39'h195b6b5bc5};
        rom[ 62] = {39'h000002ed45, 39'h7ff8980ec8, 39'h1954007941};
        rom[ 63] = {39'h000002e959, 39'h7ff89de950, 39'h194c9b7539};
        rom[ 64] = {39'h000002e575, 39'h7ff8a3bc01, 39'h19453c47cd};
        rom[ 65] = {39'h000002e198, 39'h7ff8a986eb, 39'h193de2e92f};
        rom[ 66] = {39'h000002ddc3, 39'h7ff8af4a1a, 39'h19368f519d};
        rom[ 67] = {39'h000002d9f5, 39'h7ff8b505a0, 39'h192f417967};
        rom[ 68] = {39'h000002d62e, 39'h7ff8bab989, 39'h1927f958e7};
        rom[ 69] = {39'h000002d26e, 39'h7ff8c065e4, 39'h1920b6e88a};
        rom[ 70] = {39'h000002ceb6, 39'h7ff8c60ac0, 39'h19197a20c8};
        rom[ 71] = {39'h000002cb04, 39'h7ff8cba82a, 39'h191242fa29};
        rom[ 72] = {39'h000002c759, 39'h7ff8d13e31, 39'h190b116d43};
        rom[ 73] = {39'h000002c3b5, 39'h7ff8d6cce2, 39'h1903e572ba};
        rom[ 74] = {39'h000002c018, 39'h7ff8dc544b, 39'h18fcbf033d};
        rom[ 75] = {39'h000002bc81, 39'h7ff8e1d47a, 39'h18f59e178d};
        rom[ 76] = {39'h000002b8f2, 39'h7ff8e74d7c, 39'h18ee82a876};
        rom[ 77] = {39'h000002b568, 39'h7ff8ecbf5f, 39'h18e76caed1};
        rom[ 78] = {39'h000002b1e6, 39'h7ff8f22a2f, 39'h18e05c2385};
        rom[ 79] = {39'h000002ae6a, 39'h7ff8f78df9, 39'h18d950ff87};
        rom[ 80] = {39'h000002aaf4, 39'h7ff8fceacc, 39'h18d24b3bd7};
        rom[ 81] = {39'h000002a784, 39'h7ff90240b2, 39'h18cb4ad184};
        rom[ 82] = {39'h000002a41b, 39'h7ff9078fba, 39'h18c44fb9a9};
        rom[ 83] = {39'h000002a0b8, 39'h7ff90cd7f0, 39'h18bd59ed6d};
        rom[ 84] = {39'h0000029d5c, 39'h7ff9121960, 39'h18b6696603};
        rom[ 85] = {39'h0000029a05, 39'h7ff9175417, 39'h18af7e1cad};
        rom[ 86] = {39'h00000296b4, 39'h7ff91c8820, 39'h18a8980ab7};
        rom[ 87] = {39'h000002936a, 39'h7ff921b588, 39'h18a1b7297a};
        rom[ 88] = {39'h0000029025, 39'h7ff926dc5b, 39'h189adb725a};
        rom[ 89] = {39'h0000028ce7, 39'h7ff92bfca5, 39'h189404dec9};
        rom[ 90] = {39'h00000289ae, 39'h7ff9311672, 39'h188d336844};
        rom[ 91] = {39'h000002867b, 39'h7ff93629cd, 39'h1886670852};
        rom[ 92] = {39'h000002834d, 39'h7ff93b36c1, 39'h187f9fb889};
        rom[ 93] = {39'h0000028026, 39'h7ff9403d5c, 39'h1878dd7287};
        rom[ 94] = {39'h0000027d04, 39'h7ff9453da6, 39'h1872202ff7};
        rom[ 95] = {39'h00000279e7, 39'h7ff94a37ad, 39'h186b67ea91};
        rom[ 96] = {39'h00000276d1, 39'h7ff94f2b7b, 39'h1864b49c15};
        rom[ 97] = {39'h00000273bf, 39'h7ff954191c, 39'h185e063e51};
        rom[ 98] = {39'h00000270b3, 39'h7ff9590099, 39'h18575ccb1b};
        rom[ 99] = {39'h0000026dad, 39'h7ff95de1ff, 39'h1850b83c58};
        rom[100] = {39'h0000026aab, 39'h7ff962bd57, 39'h184a188bf3};
        rom[101] = {39'h00000267af, 39'h7ff96792ad, 39'h18437db3e5};
        rom[102] = {39'h00000264b9, 39'h7ff96c620b, 39'h183ce7ae32};
        rom[103] = {39'h00000261c7, 39'h7ff9712b7b, 39'h18365674e5};
        rom[104] = {39'h0000025edb, 39'h7ff975ef09, 39'h182fca0218};
        rom[105] = {39'h0000025bf3, 39'h7ff97aacbd, 39'h1829424fec};
        rom[106] = {39'h0000025911, 39'h7ff97f64a3, 39'h1822bf588d};
        rom[107] = {39'h0000025634, 39'h7ff98416c5, 39'h181c411632};
        rom[108] = {39'h000002535c, 39'h7ff988c32c, 39'h1815c7831b};
        rom[109] = {39'h0000025088, 39'h7ff98d69e2, 39'h180f529993};
        rom[110] = {39'h0000024dba, 39'h7ff9920af2, 39'h1808e253ee};
        rom[111] = {39'h0000024af0, 39'h7ff996a665, 39'h180276ac8b};
        rom[112] = {39'h000002482b, 39'h7ff99b3c44, 39'h17fc0f9dd1};
        rom[113] = {39'h000002456b, 39'h7ff99fcc9a, 39'h17f5ad2232};
        rom[114] = {39'h00000242b0, 39'h7ff9a45770, 39'h17ef4f3429};
        rom[115] = {39'h0000023ff9, 39'h7ff9a8dccf, 39'h17e8f5ce3b};
        rom[116] = {39'h0000023d47, 39'h7ff9ad5cc1, 39'h17e2a0eaf5};
        rom[117] = {39'h0000023a9a, 39'h7ff9b1d74f, 39'h17dc5084ef};
        rom[118] = {39'h00000237f1, 39'h7ff9b64c81, 39'h17d60496c9};
        rom[119] = {39'h000002354c, 39'h7ff9babc62, 39'h17cfbd1b2c};
        rom[120] = {39'h00000232ac, 39'h7ff9bf26fa, 39'h17c97a0ccd};
        rom[121] = {39'h0000023011, 39'h7ff9c38c52, 39'h17c33b6665};
        rom[122] = {39'h0000022d7a, 39'h7ff9c7ec73, 39'h17bd0122ba};
        rom[123] = {39'h0000022ae7, 39'h7ff9cc4766, 39'h17b6cb3c99};
        rom[124] = {39'h0000022858, 39'h7ff9d09d33, 39'h17b099aed8};
        rom[125] = {39'h00000225ce, 39'h7ff9d4ede3, 39'h17aa6c7456};
        rom[126] = {39'h0000022348, 39'h7ff9d9397f, 39'h17a44387fa};
        rom[127] = {39'h00000220c7, 39'h7ff9dd8010, 39'h179e1ee4b4};
        rom[128] = {39'h0000021e49, 39'h7ff9e1c19c, 39'h1797fe857d};
        rom[129] = {39'h0000021bd0, 39'h7ff9e5fe2e, 39'h1791e26555};
        rom[130] = {39'h000002195a, 39'h7ff9ea35cd, 39'h178bca7f46};
        rom[131] = {39'h00000216e9, 39'h7ff9ee6882, 39'h1785b6ce61};
        rom[132] = {39'h000002147c, 39'h7ff9f29654, 39'h177fa74dbf};
        rom[133] = {39'h0000021213, 39'h7ff9f6bf4b, 39'h17799bf882};
        rom[134] = {39'h0000020fae, 39'h7ff9fae371, 39'h177394c9d3};
        rom[135] = {39'h0000020d4c, 39'h7ff9ff02cb, 39'h176d91bce5};
        rom[136] = {39'h0000020aef, 39'h7ffa031d64, 39'h176792ccf0};
        rom[137] = {39'h0000020896, 39'h7ffa073342, 39'h176197f536};
        rom[138] = {39'h0000020640, 39'h7ffa0b446c, 39'h175ba13101};
        rom[139] = {39'h00000203ee, 39'h7ffa0f50ec, 39'h1755ae7ba1};
        rom[140] = {39'h00000201a0, 39'h7ffa1358c7, 39'h174fbfd06e};
        rom[141] = {39'h000001ff56, 39'h7ffa175c07, 39'h1749d52ac9};
        rom[142] = {39'h000001fd0f, 39'h7ffa1b5ab1, 39'h1743ee8619};
        rom[143] = {39'h000001facc, 39'h7ffa1f54cf, 39'h173e0bddce};
        rom[144] = {39'h000001f88d, 39'h7ffa234a67, 39'h17382d2d5d};
        rom[145] = {39'h000001f651, 39'h7ffa273b80, 39'h1732527044};
        rom[146] = {39'h000001f419, 39'h7ffa2b2822, 39'h172c7ba20a};
        rom[147] = {39'h000001f1e5, 39'h7ffa2f1053, 39'h1726a8be39};
        rom[148] = {39'h000001efb4, 39'h7ffa32f41c, 39'h1720d9c065};
        rom[149] = {39'h000001ed86, 39'h7ffa36d383, 39'h171b0ea429};
        rom[150] = {39'h000001eb5c, 39'h7ffa3aae8e, 39'h1715476526};
        rom[151] = {39'h000001e936, 39'h7ffa3e8546, 39'h170f83ff05};
        rom[152] = {39'h000001e712, 39'h7ffa4257b1, 39'h1709c46d75};
        rom[153] = {39'h000001e4f3, 39'h7ffa4625d5, 39'h170408ac2d};
        rom[154] = {39'h000001e2d6, 39'h7ffa49efba, 39'h16fe50b6e9};
        rom[155] = {39'h000001e0bd, 39'h7ffa4db566, 39'h16f89c896f};
        rom[156] = {39'h000001dea8, 39'h7ffa5176e0, 39'h16f2ec1f87};
        rom[157] = {39'h000001dc95, 39'h7ffa55342f, 39'h16ed3f7504};
        rom[158] = {39'h000001da86, 39'h7ffa58ed59, 39'h16e79685bd};
        rom[159] = {39'h000001d87a, 39'h7ffa5ca264, 39'h16e1f14d91};
        rom[160] = {39'h000001d671, 39'h7ffa605358, 39'h16dc4fc865};
        rom[161] = {39'h000001d46c, 39'h7ffa64003a, 39'h16d6b1f224};
        rom[162] = {39'h000001d269, 39'h7ffa67a911, 39'h16d117c6bf};
        rom[163] = {39'h000001d06a, 39'h7ffa6b4de4, 39'h16cb81422f};
        rom[164] = {39'h000001ce6e, 39'h7ffa6eeeb7, 39'h16c5ee6072};
        rom[165] = {39'h000001cc75, 39'h7ffa728b93, 39'h16c05f1d8d};
        rom[166] = {39'h000001ca7f, 39'h7ffa76247c, 39'h16bad3758a};
        rom[167] = {39'h000001c88c, 39'h7ffa79b979, 39'h16b54b647a};
        rom[168] = {39'h000001c69c, 39'h7ffa7d4a90, 39'h16afc6e675};
        rom[169] = {39'h000001c4af, 39'h7ffa80d7c8, 39'h16aa45f797};
        rom[170] = {39'h000001c2c5, 39'h7ffa846125, 39'h16a4c89403};
        rom[171] = {39'h000001c0de, 39'h7ffa87e6ae, 39'h169f4eb7e3};
        rom[172] = {39'h000001befa, 39'h7ffa8b686a, 39'h1699d85f65};
        rom[173] = {39'h000001bd18, 39'h7ffa8ee65c, 39'h16946586bf};
        rom[174] = {39'h000001bb3a, 39'h7ffa92608d, 39'h168ef62a29};
        rom[175] = {39'h000001b95e, 39'h7ffa95d700, 39'h16898a45e6};
        rom[176] = {39'h000001b786, 39'h7ffa9949bc, 39'h168421d63a};
        rom[177] = {39'h000001b5b0, 39'h7ffa9cb8c7, 39'h167ebcd772};
        rom[178] = {39'h000001b3dd, 39'h7ffaa02426, 39'h16795b45e0};
        rom[179] = {39'h000001b20c, 39'h7ffaa38bdf, 39'h1673fd1dd9};
        rom[180] = {39'h000001b03f, 39'h7ffaa6eff7, 39'h166ea25bba};
        rom[181] = {39'h000001ae74, 39'h7ffaaa5074, 39'h16694afbe6};
        rom[182] = {39'h000001acab, 39'h7ffaadad5b, 39'h1663f6fac4};
        rom[183] = {39'h000001aae6, 39'h7ffab106b1, 39'h165ea654c1};
        rom[184] = {39'h000001a923, 39'h7ffab45c7d, 39'h165959064f};
        rom[185] = {39'h000001a763, 39'h7ffab7aec2, 39'h16540f0be5};
        rom[186] = {39'h000001a5a5, 39'h7ffabafd88, 39'h164ec86201};
        rom[187] = {39'h000001a3ea, 39'h7ffabe48d2, 39'h1649850524};
        rom[188] = {39'h000001a232, 39'h7ffac190a5, 39'h164444f1d7};
        rom[189] = {39'h000001a07c, 39'h7ffac4d508, 39'h163f0824a5};
        rom[190] = {39'h0000019ec8, 39'h7ffac81600, 39'h1639ce9a20};
        rom[191] = {39'h0000019d18, 39'h7ffacb5390, 39'h1634984edf};
        rom[192] = {39'h0000019b69, 39'h7fface8dbf, 39'h162f653f7e};
        rom[193] = {39'h00000199bd, 39'h7ffad1c492, 39'h162a35689e};
        rom[194] = {39'h0000019814, 39'h7ffad4f80c, 39'h162508c6e4};
        rom[195] = {39'h000001966d, 39'h7ffad82834, 39'h161fdf56fc};
        rom[196] = {39'h00000194c9, 39'h7ffadb550e, 39'h161ab91594};
        rom[197] = {39'h0000019327, 39'h7ffade7e9f, 39'h161595ff62};
        rom[198] = {39'h0000019187, 39'h7ffae1a4ec, 39'h161076111f};
        rom[199] = {39'h0000018fea, 39'h7ffae4c7f9, 39'h160b594789};
        rom[200] = {39'h0000018e4f, 39'h7ffae7e7cc, 39'h16063f9f63};
        rom[201] = {39'h0000018cb6, 39'h7ffaeb0469, 39'h1601291576};
        rom[202] = {39'h0000018b20, 39'h7ffaee1dd4, 39'h15fc15a68c};
        rom[203] = {39'h000001898c, 39'h7ffaf13413, 39'h15f7054f78};
        rom[204] = {39'h00000187fa, 39'h7ffaf4472a, 39'h15f1f80d0e};
        rom[205] = {39'h000001866a, 39'h7ffaf7571e, 39'h15eceddc2a};
        rom[206] = {39'h00000184dd, 39'h7ffafa63f2, 39'h15e7e6b9aa};
        rom[207] = {39'h0000018352, 39'h7ffafd6dad, 39'h15e2e2a272};
        rom[208] = {39'h00000181ca, 39'h7ffb007451, 39'h15dde19369};
        rom[209] = {39'h0000018043, 39'h7ffb0377e4, 39'h15d8e3897b};
        rom[210] = {39'h0000017ebf, 39'h7ffb06786a, 39'h15d3e8819a};
        rom[211] = {39'h0000017d3d, 39'h7ffb0975e7, 39'h15cef078ba};
        rom[212] = {39'h0000017bbd, 39'h7ffb0c705f, 39'h15c9fb6bd5};
        rom[213] = {39'h0000017a3f, 39'h7ffb0f67d8, 39'h15c50957e9};
        rom[214] = {39'h00000178c3, 39'h7ffb125c55, 39'h15c01a39f8};
        rom[215] = {39'h0000017749, 39'h7ffb154ddb, 39'h15bb2e0f08};
        rom[216] = {39'h00000175d2, 39'h7ffb183c6d, 39'h15b644d424};
        rom[217] = {39'h000001745c, 39'h7ffb1b2810, 39'h15b15e865b};
        rom[218] = {39'h00000172e9, 39'h7ffb1e10c8, 39'h15ac7b22bf};
        rom[219] = {39'h0000017178, 39'h7ffb20f699, 39'h15a79aa668};
        rom[220] = {39'h0000017008, 39'h7ffb23d988, 39'h15a2bd0e72};
        rom[221] = {39'h0000016e9b, 39'h7ffb26b998, 39'h159de257fa};
        rom[222] = {39'h0000016d30, 39'h7ffb2996ce, 39'h15990a8026};
        rom[223] = {39'h0000016bc6, 39'h7ffb2c712d, 39'h159435841c};
        rom[224] = {39'h0000016a5f, 39'h7ffb2f48b9, 39'h158f636108};
        rom[225] = {39'h00000168fa, 39'h7ffb321d77, 39'h158a941418};
        rom[226] = {39'h0000016796, 39'h7ffb34ef6a, 39'h1585c79a82};
        rom[227] = {39'h0000016635, 39'h7ffb37be96, 39'h1580fdf17b};
        rom[228] = {39'h00000164d5, 39'h7ffb3a8b00, 39'h157c37163f};
        rom[229] = {39'h0000016378, 39'h7ffb3d54aa, 39'h157773060c};
        rom[230] = {39'h000001621c, 39'h7ffb401b99, 39'h1572b1be27};
        rom[231] = {39'h00000160c2, 39'h7ffb42dfd1, 39'h156df33bd4};
        rom[232] = {39'h0000015f6a, 39'h7ffb45a154, 39'h1569377c60};
        rom[233] = {39'h0000015e14, 39'h7ffb486028, 39'h15647e7d17};
        rom[234] = {39'h0000015cc0, 39'h7ffb4b1c50, 39'h155fc83b4d};
        rom[235] = {39'h0000015b6d, 39'h7ffb4dd5cf, 39'h155b14b455};
        rom[236] = {39'h0000015a1d, 39'h7ffb508ca9, 39'h155663e58b};
        rom[237] = {39'h00000158ce, 39'h7ffb5340e2, 39'h1551b5cc4a};
        rom[238] = {39'h0000015781, 39'h7ffb55f27d, 39'h154d0a65f3};
        rom[239] = {39'h0000015635, 39'h7ffb58a17f, 39'h154861afea};
        rom[240] = {39'h00000154ec, 39'h7ffb5b4de9, 39'h1543bba797};
        rom[241] = {39'h00000153a4, 39'h7ffb5df7c1, 39'h153f184a65};
        rom[242] = {39'h000001525e, 39'h7ffb609f09, 39'h153a7795c4};
        rom[243] = {39'h000001511a, 39'h7ffb6343c5, 39'h1535d98724};
        rom[244] = {39'h0000014fd7, 39'h7ffb65e5f9, 39'h15313e1bfd};
        rom[245] = {39'h0000014e97, 39'h7ffb6885a8, 39'h152ca551c7};
        rom[246] = {39'h0000014d57, 39'h7ffb6b22d5, 39'h15280f25fe};
        rom[247] = {39'h0000014c1a, 39'h7ffb6dbd83, 39'h15237b9624};
        rom[248] = {39'h0000014ade, 39'h7ffb7055b7, 39'h151eea9fba};
        rom[249] = {39'h00000149a4, 39'h7ffb72eb73, 39'h151a5c4049};
        rom[250] = {39'h000001486c, 39'h7ffb757ebb, 39'h1515d07559};
        rom[251] = {39'h0000014735, 39'h7ffb780f92, 39'h1511473c79};
        rom[252] = {39'h0000014600, 39'h7ffb7a9dfb, 39'h150cc09339};
        rom[253] = {39'h00000144cc, 39'h7ffb7d29fa, 39'h15083c772d};
        rom[254] = {39'h000001439a, 39'h7ffb7fb392, 39'h1503bae5ed};
        rom[255] = {39'h000001426a, 39'h7ffb823ac5, 39'h14ff3bdd12};
        rom[256] = {39'h000001413b, 39'h7ffb84bf98, 39'h14fabf5a3a};
        rom[257] = {39'h000001400d, 39'h7ffb87420d, 39'h14f6455b07};
        rom[258] = {39'h0000013ee2, 39'h7ffb89c228, 39'h14f1cddd1c};
        rom[259] = {39'h0000013db8, 39'h7ffb8c3fec, 39'h14ed58de1f};
        rom[260] = {39'h0000013c8f, 39'h7ffb8ebb5b, 39'h14e8e65bbc};
        rom[261] = {39'h0000013b68, 39'h7ffb913479, 39'h14e47653a0};
        rom[262] = {39'h0000013a43, 39'h7ffb93ab49, 39'h14e008c37b};
        rom[263] = {39'h000001391e, 39'h7ffb961fcd, 39'h14db9da900};
        rom[264] = {39'h00000137fc, 39'h7ffb98920a, 39'h14d73501e6};
        rom[265] = {39'h00000136db, 39'h7ffb9b0202, 39'h14d2cecbe6};
        rom[266] = {39'h00000135bb, 39'h7ffb9d6fb8, 39'h14ce6b04bd};
        rom[267] = {39'h000001349d, 39'h7ffb9fdb2e, 39'h14ca09aa2a};
        rom[268] = {39'h0000013381, 39'h7ffba24469, 39'h14c5aab9ef};
        rom[269] = {39'h0000013266, 39'h7ffba4ab6a, 39'h14c14e31d2};
        rom[270] = {39'h000001314c, 39'h7ffba71035, 39'h14bcf40f9c};
        rom[271] = {39'h0000013033, 39'h7ffba972cc, 39'h14b89c5116};
        rom[272] = {39'h0000012f1d, 39'h7ffbabd333, 39'h14b446f410};
        rom[273] = {39'h0000012e07, 39'h7ffbae316c, 39'h14aff3f659};
        rom[274] = {39'h0000012cf3, 39'h7ffbb08d7a, 39'h14aba355c6};
        rom[275] = {39'h0000012be0, 39'h7ffbb2e760, 39'h14a755102e};
        rom[276] = {39'h0000012acf, 39'h7ffbb53f20, 39'h14a3092368};
        rom[277] = {39'h00000129bf, 39'h7ffbb794bf, 39'h149ebf8d52};
        rom[278] = {39'h00000128b1, 39'h7ffbb9e83d, 39'h149a784bca};
        rom[279] = {39'h00000127a4, 39'h7ffbbc399e, 39'h1496335cb2};
        rom[280] = {39'h0000012698, 39'h7ffbbe88e5, 39'h1491f0bdee};
        rom[281] = {39'h000001258d, 39'h7ffbc0d614, 39'h148db06d66};
        rom[282] = {39'h0000012484, 39'h7ffbc3212f, 39'h1489726902};
        rom[283] = {39'h000001237c, 39'h7ffbc56a37, 39'h148536aeaf};
        rom[284] = {39'h0000012276, 39'h7ffbc7b12f, 39'h1480fd3c5c};
        rom[285] = {39'h0000012171, 39'h7ffbc9f61a, 39'h147cc60ffc};
        rom[286] = {39'h000001206d, 39'h7ffbcc38fb, 39'h1478912781};
        rom[287] = {39'h0000011f6a, 39'h7ffbce79d4, 39'h14745e80e3};
        rom[288] = {39'h0000011e69, 39'h7ffbd0b8a8, 39'h14702e1a1c};
        rom[289] = {39'h0000011d69, 39'h7ffbd2f579, 39'h146bfff128};
        rom[290] = {39'h0000011c6a, 39'h7ffbd5304a, 39'h1467d40404};
        rom[291] = {39'h0000011b6c, 39'h7ffbd7691e, 39'h1463aa50b3};
        rom[292] = {39'h0000011a70, 39'h7ffbd99ff6, 39'h145f82d538};
        rom[293] = {39'h0000011975, 39'h7ffbdbd4d6, 39'h145b5d8f99};
        rom[294] = {39'h000001187b, 39'h7ffbde07c0, 39'h14573a7dde};
        rom[295] = {39'h0000011783, 39'h7ffbe038b6, 39'h1453199e14};
        rom[296] = {39'h000001168b, 39'h7ffbe267ba, 39'h144efaee47};
        rom[297] = {39'h0000011595, 39'h7ffbe494d1, 39'h144ade6c87};
        rom[298] = {39'h00000114a0, 39'h7ffbe6bffa, 39'h1446c416e8};
        rom[299] = {39'h00000113ac, 39'h7ffbe8e93a, 39'h1442abeb7d};
        rom[300] = {39'h00000112ba, 39'h7ffbeb1092, 39'h143e95e85e};
        rom[301] = {39'h00000111c8, 39'h7ffbed3606, 39'h143a820ba6};
        rom[302] = {39'h00000110d8, 39'h7ffbef5996, 39'h143670536e};
        rom[303] = {39'h0000010fe9, 39'h7ffbf17b46, 39'h143260bdd7};
        rom[304] = {39'h0000010efb, 39'h7ffbf39b18, 39'h142e534901};
        rom[305] = {39'h0000010e0e, 39'h7ffbf5b90d, 39'h142a47f30f};
        rom[306] = {39'h0000010d23, 39'h7ffbf7d52a, 39'h14263eba26};
        rom[307] = {39'h0000010c38, 39'h7ffbf9ef6f, 39'h1422379c6d};
        rom[308] = {39'h0000010b4f, 39'h7ffbfc07df, 39'h141e32980f};
        rom[309] = {39'h0000010a67, 39'h7ffbfe1e7d, 39'h141a2fab38};
        rom[310] = {39'h000001097f, 39'h7ffc003349, 39'h14162ed416};
        rom[311] = {39'h0000010899, 39'h7ffc024648, 39'h14123010db};
        rom[312] = {39'h00000107b5, 39'h7ffc04577b, 39'h140e335fb7};
        rom[313] = {39'h00000106d1, 39'h7ffc0666e4, 39'h140a38bee2};
        rom[314] = {39'h00000105ee, 39'h7ffc087485, 39'h1406402c92};
        rom[315] = {39'h000001050c, 39'h7ffc0a8061, 39'h140249a700};
        rom[316] = {39'h000001042c, 39'h7ffc0c8a79, 39'h13fe552c69};
        rom[317] = {39'h000001034c, 39'h7ffc0e92d1, 39'h13fa62bb09};
        rom[318] = {39'h000001026e, 39'h7ffc109969, 39'h13f6725122};
        rom[319] = {39'h0000010190, 39'h7ffc129e44, 39'h13f283ecf4};
        rom[320] = {39'h00000100b4, 39'h7ffc14a165, 39'h13ee978cc4};
        rom[321] = {39'h000000ffd9, 39'h7ffc16a2cd, 39'h13eaad2ed9};
        rom[322] = {39'h000000fefe, 39'h7ffc18a27e, 39'h13e6c4d17a};
        rom[323] = {39'h000000fe25, 39'h7ffc1aa07b, 39'h13e2de72f2};
        rom[324] = {39'h000000fd4d, 39'h7ffc1c9cc5, 39'h13defa118e};
        rom[325] = {39'h000000fc76, 39'h7ffc1e975f, 39'h13db17ab9c};
        rom[326] = {39'h000000fba0, 39'h7ffc20904b, 39'h13d7373f6d};
        rom[327] = {39'h000000faca, 39'h7ffc22878a, 39'h13d358cb52};
        rom[328] = {39'h000000f9f6, 39'h7ffc247d1e, 39'h13cf7c4da2};
        rom[329] = {39'h000000f923, 39'h7ffc26710b, 39'h13cba1c4b2};
        rom[330] = {39'h000000f851, 39'h7ffc286350, 39'h13c7c92edb};
        rom[331] = {39'h000000f780, 39'h7ffc2a53f2, 39'h13c3f28a78};
        rom[332] = {39'h000000f6af, 39'h7ffc2c42f1, 39'h13c01dd5e5};
        rom[333] = {39'h000000f5e0, 39'h7ffc2e304f, 39'h13bc4b0f81};
        rom[334] = {39'h000000f512, 39'h7ffc301c0f, 39'h13b87a35ab};
        rom[335] = {39'h000000f444, 39'h7ffc320632, 39'h13b4ab46c7};
        rom[336] = {39'h000000f378, 39'h7ffc33eeba, 39'h13b0de4139};
        rom[337] = {39'h000000f2ac, 39'h7ffc35d5aa, 39'h13ad132367};
        rom[338] = {39'h000000f1e2, 39'h7ffc37bb02, 39'h13a949ebb9};
        rom[339] = {39'h000000f118, 39'h7ffc399ec5, 39'h13a5829898};
        rom[340] = {39'h000000f04f, 39'h7ffc3b80f6, 39'h13a1bd2872};
        rom[341] = {39'h000000ef88, 39'h7ffc3d6194, 39'h139df999b3};
        rom[342] = {39'h000000eec1, 39'h7ffc3f40a4, 39'h139a37eacb};
        rom[343] = {39'h000000edfb, 39'h7ffc411e25, 39'h1396781a2b};
        rom[344] = {39'h000000ed36, 39'h7ffc42fa1b, 39'h1392ba2647};
        rom[345] = {39'h000000ec72, 39'h7ffc44d486, 39'h138efe0d93};
        rom[346] = {39'h000000ebae, 39'h7ffc46ad6a, 39'h138b43ce87};
        rom[347] = {39'h000000eaec, 39'h7ffc4884c6, 39'h13878b679b};
        rom[348] = {39'h000000ea2b, 39'h7ffc4a5a9f, 39'h1383d4d74a};
        rom[349] = {39'h000000e96a, 39'h7ffc4c2ef4, 39'h1380201c0f};
        rom[350] = {39'h000000e8aa, 39'h7ffc4e01c8, 39'h137c6d3469};
        rom[351] = {39'h000000e7ec, 39'h7ffc4fd31c, 39'h1378bc1ed7};
        rom[352] = {39'h000000e72e, 39'h7ffc51a2f3, 39'h13750cd9db};
        rom[353] = {39'h000000e670, 39'h7ffc53714e, 39'h13715f63f8};
        rom[354] = {39'h000000e5b4, 39'h7ffc553e2f, 39'h136db3bbb3};
        rom[355] = {39'h000000e4f9, 39'h7ffc570997, 39'h136a09df93};
        rom[356] = {39'h000000e43e, 39'h7ffc58d389, 39'h136661ce1f};
        rom[357] = {39'h000000e384, 39'h7ffc5a9c05, 39'h1362bb85e2};
        rom[358] = {39'h000000e2cc, 39'h7ffc5c630e, 39'h135f170567};
        rom[359] = {39'h000000e213, 39'h7ffc5e28a5, 39'h135b744b3d};
        rom[360] = {39'h000000e15c, 39'h7ffc5feccb, 39'h1357d355f1};
        rom[361] = {39'h000000e0a6, 39'h7ffc61af84, 39'h1354342415};
        rom[362] = {39'h000000dff0, 39'h7ffc6370cf, 39'h135096b43a};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [(K + WSB)-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= {sb_in, idx_raw};
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [(K + WSB)-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB((K + WSB)), .ACC_SIGNED(1),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire        [K-1:0]    idx_p = esb[K-1:0];
    wire        [WSB-1:0]  sb_p  = esb[K +: WSB];
    wire        [WMAN-1:0] v_p   = {idx_p, ew};
    wire signed [WF-1:0]   f_p   = $signed({~v_p[WMAN-1], v_p[WMAN-2:0]});
    wire                   f_neg = f_p[WF-1];
    wire        [WF-1:0]   mag_f = f_neg ? (-f_p) : f_p;   // |f|, fits WF-1 bits (top bit structurally 0)

    wire [WF+ACCM-1:0] umag_p;   // unsigned |f| * C(f)
    wire [WSB:0]       fsb;      // {delayed f sign, external sideband} riding the pmul
    _zkf_pmul #(
        .WA(WF), .WB(ACCM), .A_SIGNED(0), .B_SIGNED(0),
        .WSB(WSB + 1), .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT_FINAL)
    ) u_final_pmul (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in({f_neg, sb_p}),
        .a(mag_f), .b(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(fsb), .p(umag_p)
    );
    assign sb_out = fsb[WSB-1:0];
    // Emit the magnitude and the sign SEPARATELY rather than a signed product: the caller folds the sign into
    // its e + log2(m') reconstruction as a single add/subtract, so the post-product cone carries one fewer wide
    // negate carry chain (a standalone two's-complement negate here would otherwise sit in series with that
    // adder and the magnitude abs, the critical path on wide formats). umag_p is the exact |f|*C(f): C(f) < 2
    // and |f| < 2**(WF-1) bound it below 2**(F2-1), so the F2+1-bit slice is lossless. The sign rode the pmul
    // sideband (fsb[WSB]) and so is aligned with out_valid.
    assign l_mag = umag_p[F2:0];
    assign l_neg = fsb[WSB];
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
