/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=24): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds the generic engine _zkf_cordic; MODE selects rotation (sin/cos) vs vectoring (atan2). Also exposes the
/// pre-narrowed multiplier constants (each at its own native fixed-point scale): the 2*pi constant for the
/// sin/cos small-angle/linear-rotation path, and 1/(2*pi) + 1/gain for the atan2 turns-scaling and magnitude
/// descale. Unused outputs are simply left unconnected per mode.

`default_nettype none

module _zkf_cordic_m24 #(
    parameter integer MODE      = 0,
    parameter integer UNROLL100 = 100,
    parameter integer PARALLEL  = (UNROLL100 < 100) ? 1 : 0,
    parameter integer WSB       = 1,
    parameter integer EXPECT_WMAN       = 24,
    parameter integer EXPECT_N          = 13,
    parameter integer EXPECT_XF         = 42,
    parameter integer EXPECT_WX         = 44,
    parameter integer EXPECT_WT         = 36,
    parameter integer EXPECT_ZF         = 44,
    parameter integer EXPECT_WZ         = 47,
    parameter integer EXPECT_CONST2PI_W = 29,
    parameter integer EXPECT_CONST2PI_S = 26,
    parameter integer EXPECT_INVTAU_W   = 29,
    parameter integer EXPECT_INVTAU_S   = 31,
    parameter integer EXPECT_KINV_MAG_W = 29,
    parameter integer EXPECT_KINV_S     = 29
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire      [WSB-1:0] sb_in,
    input  wire signed [ 43:0] x0,
    input  wire signed [ 43:0] y0,
    input  wire signed [ 46:0] z0,
    output wire                busy,
    output wire                done,
    output wire                z_done,
    output wire      [WSB-1:0] sb_out,
    output wire signed [ 43:0] xn,
    output wire signed [ 43:0] yn,
    output wire signed [ 46:0] zn,
    output wire        [ 28:0] const2pi,   // round(2*pi * 2**CONST2PI_S), WMAN+5 bits (sin/cos small angle)
    output wire        [ 28:0] inv_tau,    // round(2**INVTAU_S / (2*pi)), WMAN+5 bits (atan2 turns scale)
    output wire        [ 28:0] kinv_mag,   // round(2**KINV_S / gain), WMAN+5 bits (atan2 magnitude descale)
    output wire        [ 43:0] kinv        // round(2**XF / gain), full inverse CORDIC-gain (sin/cos seed)
);
    localparam integer N    = 13;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 44;
    localparam integer WZ   = 47;
    localparam integer XF   = 42;   // x/y fractional scale
    localparam integer WT   = 36;   // quadrant-local coordinate width used to derive ZF
    localparam integer ZF   = 44;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer CWB  = 29;   // narrowed const2pi width (== WMAN+5)
    localparam integer ITWB = 29;   // narrowed inv_tau width (== WMAN+5)
    localparam integer KMW  = 29;   // narrowed kinv_mag width (== WMAN+5)
    localparam integer CONST2PI_S = 26;   // scale of const2pi (== WMAN+2)
    localparam integer INVTAU_S   = 31;   // scale of inv_tau  (== WMAN+7)
    localparam integer KINV_S     = 29;   // scale of kinv_mag (== WMAN+5)
    localparam signed [WX-1:0] KINV = 44'sd2670726678705;   // round(1/gain * 2**XF), the sin/cos seed

    // Geometry contract: the consuming RTL passes its locally-computed dimensions and constant scales here. If a
    // formula drifts away from zkf_trig.py, elaboration fails before any port truncation/extension can hide it.
    generate
        if ((EXPECT_WMAN       != 24) || (EXPECT_N          != N)    || (EXPECT_XF       != XF) ||
            (EXPECT_WX         != WX) || (EXPECT_WT         != WT)   || (EXPECT_ZF       != ZF) ||
            (EXPECT_WZ         != WZ) || (EXPECT_CONST2PI_W != CWB)  || (EXPECT_CONST2PI_S != CONST2PI_S) ||
            (EXPECT_INVTAU_W   != ITWB) || (EXPECT_INVTAU_S != INVTAU_S) ||
            (EXPECT_KINV_MAG_W != KMW)  || (EXPECT_KINV_S   != KINV_S)) begin : g_invalid_geometry_contract
            _zkf_invalid_cordic_geometry_contract u_invalid();
        end
    endgenerate

    assign const2pi = 29'd421657428;
    assign inv_tau  = 29'd341782638;
    assign kinv_mag = 29'd326016440;
    assign kinv     = KINV[WX-1:0];

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        47'd683565262,   // atan(2^-12)/2pi
        47'd1367130443,   // atan(2^-11)/2pi
        47'd2734260233,   // atan(2^-10)/2pi
        47'd5468515251,   // atan(2^-9)/2pi
        47'd10936988781,   // atan(2^-8)/2pi
        47'd21873643805,   // atan(2^-7)/2pi
        47'd43744617923,   // atan(2^-6)/2pi
        47'd87467890064,   // atan(2^-5)/2pi
        47'd174765388006,   // atan(2^-4)/2pi
        47'd348179481054,   // atan(2^-3)/2pi
        47'd685911684590,   // atan(2^-2)/2pi
        47'd1298159229407,   // atan(2^-1)/2pi
        47'd2199023255552   // atan(2^-0)/2pi
    };

    // Rotation mode (sin/cos) seeds the vector with the gain-compensated (1/gain, 0) so (xn, yn) = (cos z0, sin z0);
    // the x0/y0 inputs are then ignored. Vectoring mode (atan2) uses the x0/y0 vector inputs as given.
    wire signed [WX-1:0] seed_x = (MODE == 0) ? KINV       : x0;
    wire signed [WX-1:0] seed_y = (MODE == 0) ? {WX{1'b0}} : y0;
    _zkf_cordic #(
        .N(N), .UNROLL100(UNROLL100), .PARALLEL(PARALLEL), .WX(WX), .WZ(WZ), .MODE(MODE), .WSB(WSB)
    ) u_cordic (
        .clk(clk), .rst(rst), .start(start), .sb_in(sb_in),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .z_done(z_done), .sb_out(sb_out), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
