/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=18 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: two-stage ROM read + D*(2+STAGE_PRODUCT) (Horner).

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_exp2_m18 #(
    parameter D             = 2,
    parameter WSB           = 1,
    parameter WMULTIPLIER   = 0,
    parameter STAGE_PRODUCT = 0
) (
    input  wire           clk,
    input  wire           rst,
    input  wire           in_valid,
    input  wire [WSB-1:0] sb_in,
    input  wire [ 30-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire           out_valid,
    output wire [WSB-1:0] sb_out,
    output wire [ 18-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire           guard,
    output wire           round,
    output wire           sticky
);
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 18;
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 6;
    localparam integer CF   = 30;
    localparam integer RW   = 24;
    localparam integer CW   = 33;
    localparam integer ACCW = 33;
    localparam integer NSEG = 64;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [WIDX-1:0] idx = f[FF-1 -: WIDX];
    wire [RW-1:0]   w   = f[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[ 0] = {33'h00000f754, 33'h000b17198, 33'h040000007};
        rom[ 1] = {33'h00000fa05, 33'h000b3603f, 33'h040b26901};
        rom[ 2] = {33'h00000fcbe, 33'h000b55448, 33'h04166c354};
        rom[ 3] = {33'h00000ff7f, 33'h000b74dc4, 33'h0421d1469};
        rom[ 4] = {33'h000010247, 33'h000b94cc1, 33'h042d561bb};
        rom[ 5] = {33'h000010517, 33'h000bb514f, 33'h0438fb0d3};
        rom[ 6] = {33'h0000107ef, 33'h000bd5b7c, 33'h0444c0748};
        rom[ 7] = {33'h000010acf, 33'h000bf6b59, 33'h0450a6ac2};
        rom[ 8] = {33'h000010db7, 33'h000c180f6, 33'h045cae0fa};
        rom[ 9] = {33'h0000110a6, 33'h000c39c62, 33'h0468d6fb6};
        rom[10] = {33'h00001139f, 33'h000c5bdad, 33'h047521cce};
        rom[11] = {33'h00001169f, 33'h000c7e4e9, 33'h04818ee2a};
        rom[12] = {33'h0000119a8, 33'h000ca1226, 33'h048e1e9c2};
        rom[13] = {33'h000011cb9, 33'h000cc4574, 33'h049ad15a0};
        rom[14] = {33'h000011fd2, 33'h000ce7ee4, 33'h04a7a77dd};
        rom[15] = {33'h0000122f5, 33'h000d0be88, 33'h04b4a16a4};
        rom[16] = {33'h000012620, 33'h000d30470, 33'h04c1bf831};
        rom[17] = {33'h000012954, 33'h000d550ae, 33'h04cf022d2};
        rom[18] = {33'h000012c91, 33'h000d7a355, 33'h04dc69ce6};
        rom[19] = {33'h000012fd6, 33'h000d9fc75, 33'h04e9f6cdc};
        rom[20] = {33'h000013325, 33'h000dc5c20, 33'h04f7a9939};
        rom[21] = {33'h00001367e, 33'h000dec26a, 33'h050582891};
        rom[22] = {33'h0000139df, 33'h000e12f64, 33'h05138218b};
        rom[23] = {33'h000013d4a, 33'h000e3a321, 33'h0521a8ae0};
        rom[24] = {33'h0000140bf, 33'h000e61db4, 33'h052ff6b5e};
        rom[25] = {33'h00001443d, 33'h000e89f30, 33'h053e6c9e4};
        rom[26] = {33'h0000147c5, 33'h000eb27a9, 33'h054d0ad64};
        rom[27] = {33'h000014b56, 33'h000edb731, 33'h055bd1ce4};
        rom[28] = {33'h000014ef2, 33'h000f04ddc, 33'h056ac1f7f};
        rom[29] = {33'h000015298, 33'h000f2ebbf, 33'h0579dbc60};
        rom[30] = {33'h000015648, 33'h000f590ed, 33'h05891facb};
        rom[31] = {33'h000015a02, 33'h000f83d7b, 33'h05988e213};
        rom[32] = {33'h000015dc6, 33'h000faf17d, 33'h05a8279a4};
        rom[33] = {33'h000016195, 33'h000fdad08, 33'h05b7ec8fc};
        rom[34] = {33'h00001656f, 33'h001007032, 33'h05c7dd7ae};
        rom[35] = {33'h000016953, 33'h001033b0e, 33'h05d7fad63};
        rom[36] = {33'h000016d43, 33'h001060db4, 33'h05e8451da};
        rom[37] = {33'h00001713d, 33'h00108e838, 33'h05f8bcce6};
        rom[38] = {33'h000017542, 33'h0010bcab0, 33'h060962670};
        rom[39] = {33'h000017953, 33'h0010eb533, 33'h061a36678};
        rom[40] = {33'h000017d6f, 33'h00111a7d7, 33'h062b39514};
        rom[41] = {33'h000018196, 33'h00114a2b3, 33'h063c6ba6f};
        rom[42] = {33'h0000185c9, 33'h00117a5dd, 33'h064dcdece};
        rom[43] = {33'h000018a07, 33'h0011ab16d, 33'h065f60a8b};
        rom[44] = {33'h000018e52, 33'h0011dc57a, 33'h067124616};
        rom[45] = {33'h0000192a8, 33'h00120e21c, 33'h0683199f9};
        rom[46] = {33'h00001970b, 33'h00124076b, 33'h069540ed5};
        rom[47] = {33'h000019b79, 33'h00127357e, 33'h06a79ad62};
        rom[48] = {33'h000019ff4, 33'h0012a6c6f, 33'h06ba27e71};
        rom[49] = {33'h00001a47c, 33'h0012dac56, 33'h06cce8aed};
        rom[50] = {33'h00001a910, 33'h00130f54d, 33'h06dfddbd8};
        rom[51] = {33'h00001adb1, 33'h00134476b, 33'h06f307a4e};
        rom[52] = {33'h00001b25f, 33'h00137a2cb, 33'h070666f83};
        rom[53] = {33'h00001b71a, 33'h0013b0787, 33'h0719fc4c6};
        rom[54] = {33'h00001bbe2, 33'h0013e75b9, 33'h072dc8381};
        rom[55] = {33'h00001c0b7, 33'h00141ed7b, 33'h0741cb535};
        rom[56] = {33'h00001c59a, 33'h001456ee7, 33'h075606381};
        rom[57] = {33'h00001ca8b, 33'h00148fa19, 33'h076a7981d};
        rom[58] = {33'h00001cf89, 33'h0014c8f2d, 33'h077f25cdb};
        rom[59] = {33'h00001d495, 33'h001502e3c, 33'h07940bbac};
        rom[60] = {33'h00001d9af, 33'h00153d764, 33'h07a92be98};
        rom[61] = {33'h00001ded8, 33'h001578ac1, 33'h07be86fc7};
        rom[62] = {33'h00001e40f, 33'h0015b486e, 33'h07d41d97c};
        rom[63] = {33'h00001e954, 33'h0015f1089, 33'h07e9f0615};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [WSB-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= sb_in;
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [WSB-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(WSB), .ACC_SIGNED(0),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire _unused_horner = &{1'b0, ew, 1'b0};
    assign sb_out      = esb;
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
