/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=16 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: two-stage ROM read + D*(2+STAGE_PRODUCT) (Horner).

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_exp2_m16 #(
    parameter D             = 2,
    parameter WSB           = 1,
    parameter WMULTIPLIER   = 0,
    parameter STAGE_PRODUCT = 0
) (
    input  wire           clk,
    input  wire           rst,
    input  wire           in_valid,
    input  wire [WSB-1:0] sb_in,
    input  wire [ 28-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire           out_valid,
    output wire [WSB-1:0] sb_out,
    output wire [ 16-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire           guard,
    output wire           round,
    output wire           sticky
);
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 16;
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 6;
    localparam integer CF   = 28;
    localparam integer RW   = 22;
    localparam integer CW   = 31;
    localparam integer ACCW = 31;
    localparam integer NSEG = 64;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [WIDX-1:0] idx = f[FF-1 -: WIDX];
    wire [RW-1:0]   w   = f[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[ 0] = {31'h00003dd5, 31'h002c5c66, 31'h10000002};
        rom[ 1] = {31'h00003e81, 31'h002cd810, 31'h102c9a40};
        rom[ 2] = {31'h00003f30, 31'h002d5512, 31'h1059b0d5};
        rom[ 3] = {31'h00003fe0, 31'h002dd371, 31'h1087451a};
        rom[ 4] = {31'h00004092, 31'h002e5330, 31'h10b5586f};
        rom[ 5] = {31'h00004146, 31'h002ed454, 31'h10e3ec35};
        rom[ 6] = {31'h000041fc, 31'h002f56df, 31'h111301d2};
        rom[ 7] = {31'h000042b4, 31'h002fdad6, 31'h11429ab1};
        rom[ 8] = {31'h0000436e, 31'h0030603d, 31'h1172b83e};
        rom[ 9] = {31'h0000442a, 31'h0030e718, 31'h11a35bed};
        rom[10] = {31'h000044e8, 31'h00316f6b, 31'h11d48733};
        rom[11] = {31'h000045a8, 31'h0031f93a, 31'h12063b8a};
        rom[12] = {31'h0000466a, 31'h00328489, 31'h12387a70};
        rom[13] = {31'h0000472e, 31'h0033115d, 31'h126b4568};
        rom[14] = {31'h000047f5, 31'h00339fb9, 31'h129e9df7};
        rom[15] = {31'h000048bd, 31'h00342fa2, 31'h12d285a9};
        rom[16] = {31'h00004988, 31'h0034c11c, 31'h1306fe0c};
        rom[17] = {31'h00004a55, 31'h0035542c, 31'h133c08b5};
        rom[18] = {31'h00004b24, 31'h0035e8d5, 31'h1371a739};
        rom[19] = {31'h00004bf6, 31'h00367f1d, 31'h13a7db37};
        rom[20] = {31'h00004cc9, 31'h00371708, 31'h13dea64e};
        rom[21] = {31'h00004d9f, 31'h0037b09b, 31'h14160a24};
        rom[22] = {31'h00004e78, 31'h00384bd9, 31'h144e0863};
        rom[23] = {31'h00004f53, 31'h0038e8c8, 31'h1486a2b8};
        rom[24] = {31'h00005030, 31'h0039876d, 31'h14bfdad8};
        rom[25] = {31'h0000510f, 31'h003a27cc, 31'h14f9b279};
        rom[26] = {31'h000051f1, 31'h003ac9ea, 31'h15342b59};
        rom[27] = {31'h000052d6, 31'h003b6dcc, 31'h156f4739};
        rom[28] = {31'h000053bd, 31'h003c1377, 31'h15ab07e0};
        rom[29] = {31'h000054a6, 31'h003cbaf0, 31'h15e76f18};
        rom[30] = {31'h00005592, 31'h003d643b, 31'h16247eb3};
        rom[31] = {31'h00005680, 31'h003e0f5f, 31'h16623885};
        rom[32] = {31'h00005772, 31'h003ebc5f, 31'h16a09e69};
        rom[33] = {31'h00005865, 31'h003f6b42, 31'h16dfb23f};
        rom[34] = {31'h0000595c, 31'h00401c0c, 31'h171f75ec};
        rom[35] = {31'h00005a55, 31'h0040cec4, 31'h175feb59};
        rom[36] = {31'h00005b51, 31'h0041836d, 31'h17a11477};
        rom[37] = {31'h00005c4f, 31'h00423a0e, 31'h17e2f339};
        rom[38] = {31'h00005d51, 31'h0042f2ac, 31'h1825899c};
        rom[39] = {31'h00005e55, 31'h0043ad4d, 31'h1868d99e};
        rom[40] = {31'h00005f5c, 31'h004469f6, 31'h18ace545};
        rom[41] = {31'h00006065, 31'h004528ad, 31'h18f1ae9c};
        rom[42] = {31'h00006172, 31'h0045e977, 31'h193737b4};
        rom[43] = {31'h00006282, 31'h0046ac5b, 31'h197d82a3};
        rom[44] = {31'h00006394, 31'h0047715f, 31'h19c49186};
        rom[45] = {31'h000064aa, 31'h00483887, 31'h1a0c667e};
        rom[46] = {31'h000065c3, 31'h004901db, 31'h1a5503b5};
        rom[47] = {31'h000066de, 31'h0049cd60, 31'h1a9e6b58};
        rom[48] = {31'h000067fd, 31'h004a9b1c, 31'h1ae89f9c};
        rom[49] = {31'h0000691f, 31'h004b6b16, 31'h1b33a2bb};
        rom[50] = {31'h00006a44, 31'h004c3d53, 31'h1b7f76f6};
        rom[51] = {31'h00006b6c, 31'h004d11db, 31'h1bcc1e93};
        rom[52] = {31'h00006c98, 31'h004de8b3, 31'h1c199be1};
        rom[53] = {31'h00006dc6, 31'h004ec1e2, 31'h1c67f132};
        rom[54] = {31'h00006ef8, 31'h004f9d6e, 31'h1cb720e0};
        rom[55] = {31'h0000702e, 31'h00507b5f, 31'h1d072d4d};
        rom[56] = {31'h00007167, 31'h00515bba, 31'h1d5818e0};
        rom[57] = {31'h000072a3, 31'h00523e86, 31'h1da9e607};
        rom[58] = {31'h000073e2, 31'h005323cb, 31'h1dfc9737};
        rom[59] = {31'h00007525, 31'h00540b8f, 31'h1e502eeb};
        rom[60] = {31'h0000766c, 31'h0054f5d9, 31'h1ea4afa6};
        rom[61] = {31'h000077b6, 31'h0055e2b0, 31'h1efa1bf2};
        rom[62] = {31'h00007904, 31'h0056d21c, 31'h1f50765f};
        rom[63] = {31'h00007a55, 31'h0057c422, 31'h1fa7c185};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [WSB-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= sb_in;
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [WSB-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(WSB), .ACC_SIGNED(0),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire _unused_horner = &{1'b0, ew, 1'b0};
    assign sb_out      = esb;
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
