/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=48): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds the generic engine _zkf_cordic; MODE selects rotation (sin/cos) vs vectoring (atan2). Also exposes the
/// pre-narrowed multiplier constants (each at its own native fixed-point scale): the 2*pi constant for the
/// sin/cos small-angle/linear-rotation path, and 1/(2*pi) + 1/gain for the atan2 turns-scaling and magnitude
/// descale. Unused outputs are simply left unconnected per mode.

`default_nettype none

module _zkf_cordic_m48 #(
    parameter integer MODE      = 0,
    parameter integer UNROLL100 = 100,
    parameter integer PARALLEL  = (UNROLL100 < 100) ? 1 : 0,
    parameter integer WSB       = 1,
    parameter integer EXPECT_WMAN       = 48,
    parameter integer EXPECT_N          = 25,
    parameter integer EXPECT_XF         = 78,
    parameter integer EXPECT_WX         = 80,
    parameter integer EXPECT_WT         = 72,
    parameter integer EXPECT_ZF         = 80,
    parameter integer EXPECT_WZ         = 83,
    parameter integer EXPECT_CONST2PI_W = 53,
    parameter integer EXPECT_CONST2PI_S = 50,
    parameter integer EXPECT_INVTAU_W   = 53,
    parameter integer EXPECT_INVTAU_S   = 55,
    parameter integer EXPECT_KINV_MAG_W = 53,
    parameter integer EXPECT_KINV_S     = 53
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire      [WSB-1:0] sb_in,
    input  wire signed [ 79:0] x0,
    input  wire signed [ 79:0] y0,
    input  wire signed [ 82:0] z0,
    output wire                busy,
    output wire                done,
    output wire                z_done,
    output wire      [WSB-1:0] sb_out,
    output wire signed [ 79:0] xn,
    output wire signed [ 79:0] yn,
    output wire signed [ 82:0] zn,
    output wire        [ 52:0] const2pi,   // round(2*pi * 2**CONST2PI_S), WMAN+5 bits (sin/cos small angle)
    output wire        [ 52:0] inv_tau,    // round(2**INVTAU_S / (2*pi)), WMAN+5 bits (atan2 turns scale)
    output wire        [ 52:0] kinv_mag,   // round(2**KINV_S / gain), WMAN+5 bits (atan2 magnitude descale)
    output wire        [ 79:0] kinv        // round(2**XF / gain), full inverse CORDIC-gain (sin/cos seed)
);
    localparam integer N    = 25;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 80;
    localparam integer WZ   = 83;
    localparam integer XF   = 78;   // x/y fractional scale
    localparam integer WT   = 72;   // quadrant-local coordinate width used to derive ZF
    localparam integer ZF   = 80;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer CWB  = 53;   // narrowed const2pi width (== WMAN+5)
    localparam integer ITWB = 53;   // narrowed inv_tau width (== WMAN+5)
    localparam integer KMW  = 53;   // narrowed kinv_mag width (== WMAN+5)
    localparam integer CONST2PI_S = 50;   // scale of const2pi (== WMAN+2)
    localparam integer INVTAU_S   = 55;   // scale of inv_tau  (== WMAN+7)
    localparam integer KINV_S     = 53;   // scale of kinv_mag (== WMAN+5)
    localparam signed [WX-1:0] KINV = 80'sd183530938042250337464848;   // round(1/gain * 2**XF), the sin/cos seed

    // Geometry contract: the consuming RTL passes its locally-computed dimensions and constant scales here. If a
    // formula drifts away from zkf_trig.py, elaboration fails before any port truncation/extension can hide it.
    generate
        if ((EXPECT_WMAN       != 48) || (EXPECT_N          != N)    || (EXPECT_XF       != XF) ||
            (EXPECT_WX         != WX) || (EXPECT_WT         != WT)   || (EXPECT_ZF       != ZF) ||
            (EXPECT_WZ         != WZ) || (EXPECT_CONST2PI_W != CWB)  || (EXPECT_CONST2PI_S != CONST2PI_S) ||
            (EXPECT_INVTAU_W   != ITWB) || (EXPECT_INVTAU_S != INVTAU_S) ||
            (EXPECT_KINV_MAG_W != KMW)  || (EXPECT_KINV_S   != KINV_S)) begin : g_invalid_geometry_contract
            _zkf_invalid_cordic_geometry_contract u_invalid();
        end
    endgenerate

    assign const2pi = 53'd7074237752028440;
    assign inv_tau  = 53'd5734161139222659;
    assign kinv_mag = 53'd5469648183651279;
    assign kinv     = KINV[WX-1:0];

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        83'd11468322278445304,   // atan(2^-24)/2pi
        83'd22936644556890526,   // atan(2^-23)/2pi
        83'd45873289113780400,   // atan(2^-22)/2pi
        83'd91746578227555585,   // atan(2^-21)/2pi
        83'd183493156455069448,   // atan(2^-20)/2pi
        83'd366986312909805124,   // atan(2^-19)/2pi
        83'd733972625816940071,   // atan(2^-18)/2pi
        83'd1467945251612518727,   // atan(2^-17)/2pi
        83'd2935890503054146135,   // atan(2^-16)/2pi
        83'd5871781004741161719,   // atan(2^-15)/2pi
        83'd11743561998545279060,   // atan(2^-14)/2pi
        83'd23487123909594203823,   // atan(2^-13)/2pi
        83'd46974247119217596747,   // atan(2^-12)/2pi
        83'd93948488638669457289,   // atan(2^-11)/2pi
        83'd187896932479237056500,   // atan(2^-10)/2pi
        83'd375793506574428256564,   // atan(2^-9)/2pi
        83'd751584146101097659537,   // atan(2^-8)/2pi
        83'd1503145356607546630851,   // atan(2^-7)/2pi
        83'd3006107253651087656151,   // atan(2^-6)/2pi
        83'd6010747636418885473949,   // atan(2^-5)/2pi
        83'd12009786015304569897164,   // atan(2^-4)/2pi
        83'd23926711748232606351250,   // atan(2^-3)/2pi
        83'd47135492052148619697988,   // atan(2^-2)/2pi
        83'd89208822964871049401993,   // atan(2^-1)/2pi
        83'd151115727451828646838272   // atan(2^-0)/2pi
    };

    // Rotation mode (sin/cos) seeds the vector with the gain-compensated (1/gain, 0) so (xn, yn) = (cos z0, sin z0);
    // the x0/y0 inputs are then ignored. Vectoring mode (atan2) uses the x0/y0 vector inputs as given.
    wire signed [WX-1:0] seed_x = (MODE == 0) ? KINV       : x0;
    wire signed [WX-1:0] seed_y = (MODE == 0) ? {WX{1'b0}} : y0;
    _zkf_cordic #(
        .N(N), .UNROLL100(UNROLL100), .PARALLEL(PARALLEL), .WX(WX), .WZ(WZ), .MODE(MODE), .WSB(WSB)
    ) u_cordic (
        .clk(clk), .rst(rst), .start(start), .sb_in(sb_in),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .z_done(z_done), .sb_out(sb_out), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
