/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=53): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds the generic engine _zkf_cordic; MODE selects rotation (sin/cos) vs vectoring (atan2). Also exposes the
/// pre-narrowed multiplier constants (each at its own native fixed-point scale): the 2*pi constant for the
/// sin/cos small-angle/linear-rotation path, and 1/(2*pi) + 1/gain for the atan2 turns-scaling and magnitude
/// descale. Unused outputs are simply left unconnected per mode.

`default_nettype none

module _zkf_cordic_m53 #(
    parameter integer MODE      = 0,
    parameter integer UNROLL100 = 100,
    parameter integer PARALLEL  = (UNROLL100 < 100) ? 1 : 0,
    parameter integer WSB       = 1,
    parameter integer EXPECT_WMAN       = 53,
    parameter integer EXPECT_N          = 28,
    parameter integer EXPECT_XF         = 86,
    parameter integer EXPECT_WX         = 88,
    parameter integer EXPECT_WT         = 79,
    parameter integer EXPECT_ZF         = 87,
    parameter integer EXPECT_WZ         = 90,
    parameter integer EXPECT_CONST2PI_W = 58,
    parameter integer EXPECT_CONST2PI_S = 55,
    parameter integer EXPECT_INVTAU_W   = 58,
    parameter integer EXPECT_INVTAU_S   = 60,
    parameter integer EXPECT_KINV_MAG_W = 58,
    parameter integer EXPECT_KINV_S     = 58
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire      [WSB-1:0] sb_in,
    input  wire signed [ 87:0] x0,
    input  wire signed [ 87:0] y0,
    input  wire signed [ 89:0] z0,
    output wire                busy,
    output wire                done,
    output wire                z_done,
    output wire      [WSB-1:0] sb_out,
    output wire signed [ 87:0] xn,
    output wire signed [ 87:0] yn,
    output wire signed [ 89:0] zn,
    output wire        [ 57:0] const2pi,   // round(2*pi * 2**CONST2PI_S), WMAN+5 bits (sin/cos small angle)
    output wire        [ 57:0] inv_tau,    // round(2**INVTAU_S / (2*pi)), WMAN+5 bits (atan2 turns scale)
    output wire        [ 57:0] kinv_mag,   // round(2**KINV_S / gain), WMAN+5 bits (atan2 magnitude descale)
    output wire        [ 87:0] kinv        // round(2**XF / gain), full inverse CORDIC-gain (sin/cos seed)
);
    localparam integer N    = 28;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 88;
    localparam integer WZ   = 90;
    localparam integer XF   = 86;   // x/y fractional scale
    localparam integer WT   = 79;   // quadrant-local coordinate width used to derive ZF
    localparam integer ZF   = 87;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer CWB  = 58;   // narrowed const2pi width (== WMAN+5)
    localparam integer ITWB = 58;   // narrowed inv_tau width (== WMAN+5)
    localparam integer KMW  = 58;   // narrowed kinv_mag width (== WMAN+5)
    localparam integer CONST2PI_S = 55;   // scale of const2pi (== WMAN+2)
    localparam integer INVTAU_S   = 60;   // scale of inv_tau  (== WMAN+7)
    localparam integer KINV_S     = 58;   // scale of kinv_mag (== WMAN+5)
    localparam signed [WX-1:0] KINV = 88'sd46983920138816059005620361;   // round(1/gain * 2**XF), the sin/cos seed

    // Geometry contract: the consuming RTL passes its locally-computed dimensions and constant scales here. If a
    // formula drifts away from zkf_trig.py, elaboration fails before any port truncation/extension can hide it.
    generate
        if ((EXPECT_WMAN       != 53) || (EXPECT_N          != N)    || (EXPECT_XF       != XF) ||
            (EXPECT_WX         != WX) || (EXPECT_WT         != WT)   || (EXPECT_ZF       != ZF) ||
            (EXPECT_WZ         != WZ) || (EXPECT_CONST2PI_W != CWB)  || (EXPECT_CONST2PI_S != CONST2PI_S) ||
            (EXPECT_INVTAU_W   != ITWB) || (EXPECT_INVTAU_S != INVTAU_S) ||
            (EXPECT_KINV_MAG_W != KMW)  || (EXPECT_KINV_S   != KINV_S)) begin : g_invalid_geometry_contract
            _zkf_invalid_cordic_geometry_contract u_invalid();
        end
    endgenerate

    assign const2pi = 58'd226375608064910089;
    assign inv_tau  = 58'd183493156455125077;
    assign kinv_mag = 58'd175028741876840811;
    assign kinv     = KINV[WX-1:0];

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        90'd183493156455125073,   // atan(2^-27)/2pi
        90'd366986312910250126,   // atan(2^-26)/2pi
        90'd733972625820500089,   // atan(2^-25)/2pi
        90'd1467945251640998875,   // atan(2^-24)/2pi
        90'd2935890503281987319,   // atan(2^-23)/2pi
        90'd5871781006563891196,   // atan(2^-22)/2pi
        90'd11743562013127114847,   // atan(2^-21)/2pi
        90'd23487124026248889340,   // atan(2^-20)/2pi
        90'd46974248052455055851,   // atan(2^-19)/2pi
        90'd93948496104568329064,   // atan(2^-18)/2pi
        90'd187896992206402397026,   // atan(2^-17)/2pi
        90'd375793984390930705238,   // atan(2^-16)/2pi
        90'd751587968606868700050,   // atan(2^-15)/2pi
        90'd1503175935813795719631,   // atan(2^-14)/2pi
        90'd3006351860428058089382,   // atan(2^-13)/2pi
        90'd6012703631259852383675,   // atan(2^-12)/2pi
        90'd12025406545749690532984,   // atan(2^-11)/2pi
        90'd24050807357342343232029,   // atan(2^-10)/2pi
        90'd48101568841526816840208,   // atan(2^-9)/2pi
        90'd96202770700940500420797,   // atan(2^-8)/2pi
        90'd192402605645765968748931,   // atan(2^-7)/2pi
        90'd384781728467339219987296,   // atan(2^-6)/2pi
        90'd769375697461617340665418,   // atan(2^-5)/2pi
        90'd1537252609958984946836992,   // atan(2^-4)/2pi
        90'd3062619103773773612960043,   // atan(2^-3)/2pi
        90'd6033342982675023321342458,   // atan(2^-2)/2pi
        90'd11418729339503494323455099,   // atan(2^-1)/2pi
        90'd19342813113834066795298816   // atan(2^-0)/2pi
    };

    // Rotation mode (sin/cos) seeds the vector with the gain-compensated (1/gain, 0) so (xn, yn) = (cos z0, sin z0);
    // the x0/y0 inputs are then ignored. Vectoring mode (atan2) uses the x0/y0 vector inputs as given.
    wire signed [WX-1:0] seed_x = (MODE == 0) ? KINV       : x0;
    wire signed [WX-1:0] seed_y = (MODE == 0) ? {WX{1'b0}} : y0;
    _zkf_cordic #(
        .N(N), .UNROLL100(UNROLL100), .PARALLEL(PARALLEL), .WX(WX), .WZ(WZ), .MODE(MODE), .WSB(WSB)
    ) u_cordic (
        .clk(clk), .rst(rst), .start(start), .sb_in(sb_in),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .z_done(z_done), .sb_out(sb_out), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
