/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=18 (degree 2); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes C(f)=log2(1+f)/f by unsigned v (WFRAC+1 bits) and returns log2(m')=f*C(f) as
/// the unsigned magnitude l_mag = |f|*C(f) plus the sign l_neg (set when m>=sqrt(2)), at scale 2**-F2,
/// F2 = WFRAC+1+CF. The final f*C(f) multiply is fully unsigned (|f|*C(f)); the caller folds l_neg into its
/// reconstruction add/subtract. Register stages: two-stage ROM read + Horner + final multiply.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_log2_m18 #(
    parameter D                   = 2,
    parameter WSB                 = 1,
    parameter WMULTIPLIER         = 0,
    parameter STAGE_PRODUCT       = 0,
    parameter STAGE_PRODUCT_FINAL = STAGE_PRODUCT
) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire     [ 18-1:0] v,  // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire        [48:0] l_mag,  // |log2(m')| = |f|*C(f) magnitude at scale 2**-F2, F2 = WFRAC+1+CF
    output wire               l_neg   // sign of log2(m') (= sign of reduced f); 1 when m >= sqrt(2)
);
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 18;
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 7;
    localparam integer SEG_BASE = 26;
    localparam integer RW   = 11;
    localparam integer CW   = 33;
    localparam integer ACCW = 33;
    localparam integer NSEG = 92;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [K-1:0]    idx_raw = v[WMAN-1 -: K];
    wire [K-1:0]    idx_ofs = idx_raw - SEG_BASE[K-1:0];
    wire [WIDX-1:0] idx     = idx_ofs[WIDX-1:0];
    wire [RW-1:0]   w       = v[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[ 0] = {33'h000010acd, 33'h1ff6d555b, 33'h06d8bb7d1};
        rom[ 1] = {33'h000010464, 33'h1ff6f6aed, 33'h06cfa17d6};
        rom[ 2] = {33'h00000fe33, 33'h1ff7173ae, 33'h06c6a8706};
        rom[ 3] = {33'h00000f837, 33'h1ff73700d, 33'h06bdcf8c7};
        rom[ 4] = {33'h00000f26f, 33'h1ff756075, 33'h06b5160ec};
        rom[ 5] = {33'h00000ecd7, 33'h1ff77454c, 33'h06ac7b3b2};
        rom[ 6] = {33'h00000e76e, 33'h1ff791ef3, 33'h06a3fe5b8};
        rom[ 7] = {33'h00000e231, 33'h1ff7aedc9, 33'h069b9ebfd};
        rom[ 8] = {33'h00000dd20, 33'h1ff7cb226, 33'h06935bbdc};
        rom[ 9] = {33'h00000d838, 33'h1ff7e6c61, 33'h068b34b08};
        rom[10] = {33'h00000d377, 33'h1ff801ccb, 33'h068328f88};
        rom[11] = {33'h00000cedc, 33'h1ff81c3b4, 33'h067b37fb1};
        rom[12] = {33'h00000ca65, 33'h1ff836167, 33'h067361229};
        rom[13] = {33'h00000c612, 33'h1ff84f62d, 33'h066ba3ddf};
        rom[14] = {33'h00000c1df, 33'h1ff86824c, 33'h0663ffa07};
        rom[15] = {33'h00000bdcd, 33'h1ff880606, 33'h065c73e1d};
        rom[16] = {33'h00000b9da, 33'h1ff89819c, 33'h0655001db};
        rom[17] = {33'h00000b605, 33'h1ff8af54c, 33'h064da3d3d};
        rom[18] = {33'h00000b24c, 33'h1ff8c6152, 33'h06465e879};
        rom[19] = {33'h00000aeaf, 33'h1ff8dc5e6, 33'h063f2fc04};
        rom[20] = {33'h00000ab2c, 33'h1ff8f233f, 33'h063817085};
        rom[21] = {33'h00000a7c3, 33'h1ff907993, 33'h063113ede};
        rom[22] = {33'h00000a472, 33'h1ff91c916, 33'h062a26022};
        rom[23] = {33'h00000a139, 33'h1ff9311f7, 33'h06234cd99};
        rom[24] = {33'h000009e17, 33'h1ff945466, 33'h061c880b8};
        rom[25] = {33'h000009b0b, 33'h1ff959091, 33'h0615d7325};
        rom[26] = {33'h000009814, 33'h1ff96c6a5, 33'h060f39eb1};
        rom[27] = {33'h000009532, 33'h1ff97f6cb, 33'h0608afd5b};
        rom[28] = {33'h000009264, 33'h1ff99212c, 33'h060238948};
        rom[29] = {33'h000008fa8, 33'h1ff9a45f1, 33'h05fbd3cca};
        rom[30] = {33'h000008cff, 33'h1ff9b653f, 33'h05f581254};
        rom[31] = {33'h000008a68, 33'h1ff9c7f3b, 33'h05ef40484};
        rom[32] = {33'h0000087e2, 33'h1ff9d9408, 33'h05e910e19};
        rom[33] = {33'h00000856d, 33'h1ff9ea3ca, 33'h05e2f29f7};
        rom[34] = {33'h000008308, 33'h1ff9faea2, 33'h05dce5321};
        rom[35] = {33'h0000080b2, 33'h1ffa0b4af, 33'h05d6e84be};
        rom[36] = {33'h000007e6b, 33'h1ffa1b611, 33'h05d0fba12};
        rom[37] = {33'h000007c33, 33'h1ffa2b2e5, 33'h05cb1ee82};
        rom[38] = {33'h000007a09, 33'h1ffa3ab49, 33'h05c551d8f};
        rom[39] = {33'h0000077ed, 33'h1ffa49f5a, 33'h05bf942d6};
        rom[40] = {33'h0000075de, 33'h1ffa58f31, 33'h05b9e5a12};
        rom[41] = {33'h0000073db, 33'h1ffa67aeb, 33'h05b445f16};
        rom[42] = {33'h0000071e5, 33'h1ffa7629f, 33'h05aeb4dd1};
        rom[43] = {33'h000006ffb, 33'h1ffa84668, 33'h05a93224b};
        rom[44] = {33'h000006e1d, 33'h1ffa9265c, 33'h05a3bd8a4};
        rom[45] = {33'h000006c49, 33'h1ffaa0294, 33'h059e56d13};
        rom[46] = {33'h000006a81, 33'h1ffaadb25, 33'h0598fdbe6};
        rom[47] = {33'h0000068c4, 33'h1ffabb026, 33'h0593b2183};
        rom[48] = {33'h000006710, 33'h1ffac81ac, 33'h058e73a64};
        rom[49] = {33'h000006567, 33'h1ffad4fcb, 33'h058942317};
        rom[50] = {33'h0000063c7, 33'h1ffae1a97, 33'h05841d840};
        rom[51] = {33'h000006231, 33'h1ffaee224, 33'h057f05696};
        rom[52] = {33'h0000060a4, 33'h1ffafa684, 33'h0579f9ae3};
        rom[53] = {33'h000005f1f, 33'h1ffb067ca, 33'h0574fa202};
        rom[54] = {33'h000005da3, 33'h1ffb12608, 33'h0570068e4};
        rom[55] = {33'h000005c30, 33'h1ffb1e14d, 33'h056b1ec87};
        rom[56] = {33'h000005ac5, 33'h1ffb299ac, 33'h0566429fd};
        rom[57] = {33'h000005961, 33'h1ffb34f35, 33'h056171e66};
        rom[58] = {33'h000005806, 33'h1ffb401f6, 33'h055cac6f5};
        rom[59] = {33'h0000056b1, 33'h1ffb4b200, 33'h0557f20ea};
        rom[60] = {33'h000005564, 33'h1ffb55f62, 33'h055342994};
        rom[61] = {33'h00000541e, 33'h1ffb60a29, 33'h054e9de54};
        rom[62] = {33'h0000052df, 33'h1ffb6b265, 33'h054a03c95};
        rom[63] = {33'h0000051a7, 33'h1ffb75822, 33'h0545741d2};
        rom[64] = {33'h000005075, 33'h1ffb7fb6e, 33'h0540eeb95};
        rom[65] = {33'h000004f49, 33'h1ffb89c57, 33'h053c73771};
        rom[66] = {33'h000004e23, 33'h1ffb93ae8, 33'h05380230b};
        rom[67] = {33'h000004d04, 33'h1ffb9d72e, 33'h05339ac10};
        rom[68] = {33'h000004bea, 33'h1ffba7134, 33'h052f3d03c};
        rom[69] = {33'h000004ad6, 33'h1ffbb0908, 33'h052ae8d54};
        rom[70] = {33'h0000049c7, 33'h1ffbb9eb3, 33'h05269e12c};
        rom[71] = {33'h0000048be, 33'h1ffbc3241, 33'h05225c9a1};
        rom[72] = {33'h0000047ba, 33'h1ffbcc3bd, 33'h051e2449b};
        rom[73] = {33'h0000046bc, 33'h1ffbd5331, 33'h0519f500d};
        rom[74] = {33'h0000045c2, 33'h1ffbde0a8, 33'h0515ce9f5};
        rom[75] = {33'h0000044cd, 33'h1ffbe6c2a, 33'h0511b1059};
        rom[76] = {33'h0000043dd, 33'h1ffbef5c3, 33'h050d9c14b};
        rom[77] = {33'h0000042f1, 33'h1ffbf7d7c, 33'h05098fae6};
        rom[78] = {33'h00000420a, 33'h1ffc0035d, 33'h05058bb4e};
        rom[79] = {33'h000004127, 33'h1ffc08770, 33'h0501900b0};
        rom[80] = {33'h000004049, 33'h1ffc109bd, 33'h04fd9c942};
        rom[81] = {33'h000003f6e, 33'h1ffc18a4e, 33'h04f9b1344};
        rom[82] = {33'h000003e98, 33'h1ffc2092a, 33'h04f5cdcfc};
        rom[83] = {33'h000003dc6, 33'h1ffc2865a, 33'h04f1f24b9};
        rom[84] = {33'h000003cf8, 33'h1ffc301e5, 33'h04ee1e8d5};
        rom[85] = {33'h000003c2d, 33'h1ffc37bd3, 33'h04ea527ad};
        rom[86] = {33'h000003b66, 33'h1ffc3f42d, 33'h04e68dfa9};
        rom[87] = {33'h000003aa3, 33'h1ffc46af9, 33'h04e2d0f38};
        rom[88] = {33'h0000039e3, 33'h1ffc4e03e, 33'h04df1b4d0};
        rom[89] = {33'h000003927, 33'h1ffc55404, 33'h04db6ceed};
        rom[90] = {33'h00000386e, 33'h1ffc5c651, 33'h04d7c5c14};
        rom[91] = {33'h0000037b8, 33'h1ffc6372d, 33'h04d425acf};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [(K + WSB)-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= {sb_in, idx_raw};
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [(K + WSB)-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB((K + WSB)), .ACC_SIGNED(1),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire        [K-1:0]    idx_p = esb[K-1:0];
    wire        [WSB-1:0]  sb_p  = esb[K +: WSB];
    wire        [WMAN-1:0] v_p   = {idx_p, ew};
    wire signed [WF-1:0]   f_p   = $signed({~v_p[WMAN-1], v_p[WMAN-2:0]});
    wire                   f_neg = f_p[WF-1];
    wire        [WF-1:0]   mag_f = f_neg ? (-f_p) : f_p;   // |f|, fits WF-1 bits (top bit structurally 0)

    wire [WF+ACCM-1:0] umag_p;   // unsigned |f| * C(f)
    wire [WSB:0]       fsb;      // {delayed f sign, external sideband} riding the pmul
    _zkf_pmul #(
        .WA(WF), .WB(ACCM), .A_SIGNED(0), .B_SIGNED(0),
        .WSB(WSB + 1), .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT_FINAL)
    ) u_final_pmul (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in({f_neg, sb_p}),
        .a(mag_f), .b(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(fsb), .p(umag_p)
    );
    assign sb_out = fsb[WSB-1:0];
    // Emit the magnitude and the sign SEPARATELY rather than a signed product: the caller folds the sign into
    // its e + log2(m') reconstruction as a single add/subtract, so the post-product cone carries one fewer wide
    // negate carry chain (a standalone two's-complement negate here would otherwise sit in series with that
    // adder and the magnitude abs, the critical path on wide formats). umag_p is the exact |f|*C(f): C(f) < 2
    // and |f| < 2**(WF-1) bound it below 2**(F2-1), so the F2+1-bit slice is lossless. The sign rode the pmul
    // sideband (fsb[WSB]) and so is aligned with out_valid.
    assign l_mag = umag_p[F2:0];
    assign l_neg = fsb[WSB];
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
