/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=48 (degree 5); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes C(f)=log2(1+f)/f by unsigned v (WFRAC+1 bits) and returns log2(m')=f*C(f) as
/// the unsigned magnitude l_mag = |f|*C(f) plus the sign l_neg (set when m>=sqrt(2)), at scale 2**-F2,
/// F2 = WFRAC+1+CF. The final f*C(f) multiply is fully unsigned (|f|*C(f)); the caller folds l_neg into its
/// reconstruction add/subtract. Register stages: two-stage ROM read + Horner + final multiply.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_log2_m48 #(
    parameter D                   = 5,
    parameter WSB                 = 1,
    parameter WMULTIPLIER         = 0,
    parameter STAGE_PRODUCT       = 0,
    parameter STAGE_PRODUCT_FINAL = STAGE_PRODUCT
) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire     [ 48-1:0] v,  // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire        [108:0] l_mag,  // |log2(m')| = |f|*C(f) magnitude at scale 2**-F2, F2 = WFRAC+1+CF
    output wire               l_neg   // sign of log2(m') (= sign of reduced f); 1 when m >= sqrt(2)
);
    generate if (D != 5) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 48;
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 8;
    localparam integer SEG_BASE = 53;
    localparam integer RW   = 40;
    localparam integer CW   = 63;
    localparam integer ACCW = 63;
    localparam integer NSEG = 182;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [K-1:0]    idx_raw = v[WMAN-1 -: K];
    wire [K-1:0]    idx_ofs = idx_raw - SEG_BASE[K-1:0];
    wire [WIDX-1:0] idx     = idx_ofs[WIDX-1:0];
    wire [RW-1:0]   w       = v[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[  0] = {63'h7fffffffffe98efc, 63'h000000001375cb6a, 63'h7fffffee9bcfa735, 63'h000010acc13f1b4a, 63'h7fedcc11fcbff242, 63'h1b50a94c5c294c2b};
        rom[  1] = {63'h7fffffffffea2e28, 63'h0000000013059875, 63'h7fffffeee8c6c78d, 63'h0000107908906b86, 63'h7feded37a01418e3, 63'h1b3e85f9c9575b50};
        rom[  2] = {63'h7fffffffffeac819, 63'h000000001298814a, 63'h7fffffef340350c1, 63'h00001046342c22c9, 63'h7fee0df6b7329101, 63'h1b2c83996db26de4};
        rom[  3] = {63'h7fffffffffeb5d02, 63'h00000000122e6bbf, 63'h7fffffef7d917dc2, 63'h000010143ef4ee09, 63'h7fee2e51058cb839, 63'h1b1aa1c59f97bbd1};
        rom[  4] = {63'h7fffffffffebed13, 63'h0000000011c73eae, 63'h7fffffefc57d22df, 63'h00000fe323f19024, 63'h7fee4e48447d8f47, 63'h1b08e01a73c4a896};
        rom[  5] = {63'h7fffffffffec787b, 63'h000000001162e1e1, 63'h7ffffff00bd1b1ab, 63'h00000fb2de4bb3d8, 63'h7fee6dde2390b5e6, 63'h1af73e35b36416a2};
        rom[  6] = {63'h7fffffffffecff67, 63'h0000000011013e0b, 63'h7ffffff0509a3cb5, 63'h00000f83694ec930, 63'h7fee8d1448c71619, 63'h1ae5bbb6d2618c67};
        rom[  7] = {63'h7fffffffffed8201, 63'h0000000010a23cbf, 63'h7ffffff093e17b18, 63'h00000f54c066edd6, 63'h7feeabec50d95551, 63'h1ad4583ee5ffe5d8};
        rom[  8] = {63'h7fffffffffee0072, 63'h000000001045c865, 63'h7ffffff0d5b1cbe1, 63'h00000f26df1fdfdd, 63'h7feeca67cf7820c0, 63'h1ac313709bb162d7};
        rom[  9] = {63'h7fffffffffee7ae2, 63'h000000000febcc32, 63'h7ffffff116153958, 63'h00000ef9c123fa8d, 63'h7feee8884f8a695b, 63'h1ab1ecf0302ef82c};
        rom[ 10] = {63'h7fffffffffeef176, 63'h000000000f94341f, 63'h7ffffff155157c20, 63'h00000ecd623b3ccd, 63'h7fef064f5369a314, 63'h1aa0e46366ccdc81};
        rom[ 11] = {63'h7fffffffffef6451, 63'h000000000f3eecdf, 63'h7ffffff192bbfe33, 63'h00000ea1be4a58b1, 63'h7fef23be551c1a2d, 63'h1a8ff971810a5e16};
        rom[ 12] = {63'h7fffffffffefd397, 63'h000000000eebe3dc, 63'h7ffffff1cf11ddc5, 63'h00000e76d151cbe5, 63'h7fef40d6c68d7088, 63'h1a7f2bc3365b2057};
        rom[ 13] = {63'h7ffffffffff03f69, 63'h000000000e9b072b, 63'h7ffffff20a1ff006, 63'h00000e4c976d007a, 63'h7fef5d9a11c5544c, 63'h1a6e7b02ac27f1fd};
        rom[ 14] = {63'h7ffffffffff0a7e6, 63'h000000000e4c4586, 63'h7ffffff243eec3c2, 63'h00000e230cd175db, 63'h7fef7a09991c8048, 63'h1a5de6db6e057d5e};
        rom[ 15] = {63'h7ffffffffff10d2d, 63'h000000000dff8e47, 63'h7ffffff27c86a3ed, 63'h00000dfa2dcdf173, 63'h7fef9626b770160d, 63'h1a4d6efa661f24af};
        rom[ 16] = {63'h7ffffffffff16f5b, 63'h000000000db4d15e, 63'h7ffffff2b3ef9a0e, 63'h00000dd1f6c9b6cf, 63'h7fefb1f2c05360db, 63'h1a3d130dd5d46b90};
        rom[ 17] = {63'h7ffffffffff1ce8c, 63'h000000000d6bff4f, 63'h7ffffff2ea317098, 63'h00000daa6443c6e2, 63'h7fefcd6f00400ffd, 63'h1a2cd2c54e875e00};
        rom[ 18] = {63'h7ffffffffff22ada, 63'h000000000d25092a, 63'h7ffffff31f53b520, 63'h00000d8372d2261f, 63'h7fefe89cbcc4f692, 63'h1a1cadd1aa9a7352};
        rom[ 19] = {63'h7ffffffffff28461, 63'h000000000cdfe085, 63'h7ffffff3535dba89, 63'h00000d5d1f212929, 63'h7ff0037d34b35e27, 63'h1a0ca3e5069c7927};
        rom[ 20] = {63'h7ffffffffff2db38, 63'h000000000c9c7777, 63'h7ffffff386569b0f, 63'h00000d3765f2c7d2, 63'h7ff01e11a04af911, 63'h19fcb4b2baa11fe6};
        rom[ 21] = {63'h7ffffffffff32f78, 63'h000000000c5ac095, 63'h7ffffff3b8453a45, 63'h00000d12441df624, 63'h7ff0385b316480d6, 63'h19ecdfef53c4ce88};
        rom[ 22] = {63'h7ffffffffff38137, 63'h000000000c1aaee8, 63'h7ffffff3e93046f8, 63'h00000cedb68e0343, 63'h7ff0525b139b0c8d, 63'h19dd25508dda6fd4};
        rom[ 23] = {63'h7ffffffffff3d08b, 63'h000000000bdc35ed, 63'h7ffffff4191e3d04, 63'h00000cc9ba41fde3, 63'h7ff06c126c742a9b, 63'h19cd848d4d41f6bb};
        rom[ 24] = {63'h7ffffffffff41d8a, 63'h000000000b9f4991, 63'h7ffffff448156717, 63'h00000ca64c4c1e14, 63'h7ff085825b86c8c3, 63'h19bdfd5d98e662b6};
        rom[ 25] = {63'h7ffffffffff46848, 63'h000000000b63de27, 63'h7ffffff4761be05b, 63'h00000c8369d13444, 63'h7ff09eabfaa0f506, 63'h19ae8f7a946217bf};
        rom[ 26] = {63'h7ffffffffff4b0d8, 63'h000000000b29e86a, 63'h7ffffff4a337961b, 63'h00000c6110081d2e, 63'h7ff0b7905dec817d, 63'h199f3a9e7a4867d4};
        rom[ 27] = {63'h7ffffffffff4f74d, 63'h000000000af15d76, 63'h7ffffff4cf6e494d, 63'h00000c3f3c393a88, 63'h7ff0d030941294dc, 63'h198ffe84969335db};
        rom[ 28] = {63'h7ffffffffff53bba, 63'h000000000aba32c5, 63'h7ffffff4fac59014, 63'h00000c1debbdf054, 63'h7ff0e88da65e30fb, 63'h1980dae94133a350};
        rom[ 29] = {63'h7ffffffffff57e2f, 63'h000000000a845e2b, 63'h7ffffff52542d72e, 63'h00000bfd1c00268b, 63'h7ff100a898ddb85b, 63'h1971cf89d8c4c332};
        rom[ 30] = {63'h7ffffffffff5bebd, 63'h000000000a4fd5d5, 63'h7ffffff54eeb6359, 63'h00000bdcca79cf0a, 63'h7ff118826a837b55, 63'h1962dc24bd5f55a1};
        rom[ 31] = {63'h7ffffffffff5fd75, 63'h000000000a1c9040, 63'h7ffffff577c452a8, 63'h00000bbcf4b46f93, 63'h7ff1301c15455537, 63'h195400794b8d97eb};
        rom[ 32] = {63'h7ffffffffff63a66, 63'h0000000009ea843c, 63'h7ffffff59fd29dc9, 63'h00000b9d9848afb9, 63'h7ff147768e3b6155, 63'h19453c47d75e3d11};
        rom[ 33] = {63'h7ffffffffff6759f, 63'h0000000009b9a8e7, 63'h7ffffff5c71b1942, 63'h00000b7eb2ddea93, 63'h7ff15e92c5bdcfc4, 63'h19368f51a795aa8b};
        rom[ 34] = {63'h7ffffffffff6af2d, 63'h000000000989f5a7, 63'h7ffffff5eda276a3, 63'h00000b604229c40d, 63'h7ff17571a781e112, 63'h1927f958f0fc9caa};
        rom[ 35] = {63'h7ffffffffff6e720, 63'h00000000095b622b, 63'h7ffffff6136d45a7, 63'h00000b4243efc1ba, 63'h7ff18c141ab61039, 63'h19197a20d1cb5d3f};
        rom[ 36] = {63'h7ffffffffff71d84, 63'h00000000092de669, 63'h7ffffff6387ff550, 63'h00000b24b600e70a, 63'h7ff1a27b021d7192, 63'h190b116d4d30be25};
        rom[ 37] = {63'h7ffffffffff75267, 63'h0000000009017a96, 63'h7ffffff65cded4f8, 63'h00000b07963b54af, 63'h7ff1b8a73c2a4d6d, 63'h18fcbf0346f40ffd};
        rom[ 38] = {63'h7ffffffffff785d4, 63'h0000000008d6172a, 63'h7ffffff6808e1554, 63'h00000aeae289eb35, 63'h7ff1ce99a317fca9, 63'h18ee82a87f31540f};
        rom[ 39] = {63'h7ffffffffff7b7d7, 63'h0000000008abb4db, 63'h7ffffff6a391c96f, 63'h00000ace98e3f087, 63'h7ff1e4530d040d6f, 63'h18e05c238e2eee3e};
        rom[ 40] = {63'h7ffffffffff7e87c, 63'h0000000008824c97, 63'h7ffffff6c5ede79f, 63'h00000ab2b74cb86b, 63'h7ff1f9d44c06b5f7, 63'h18d24b3be04c2254};
        rom[ 41] = {63'h7ffffffffff817cf, 63'h000000000859d789, 63'h7ffffff6e7a64a71, 63'h00000a973bd34fc1, 63'h7ff20f1e2e4a9b03, 63'h18c44fb9b207ad69};
        rom[ 42] = {63'h7ffffffffff845d9, 63'h0000000008324f13, 63'h7ffffff708beb184, 63'h00000a7c24922a71, 63'h7ff224317e23ef90, 63'h18b669660c1dd1f5};
        rom[ 43] = {63'h7ffffffffff872a4, 63'h00000000080baccb, 63'h7ffffff7293ac268, 63'h00000a616faed3f8, 63'h7ff2390f0226f30c, 63'h18a8980abfbd3265};
        rom[ 44] = {63'h7ffffffffff89e3c, 63'h0000000007e5ea7a, 63'h7ffffff7491e096e, 63'h00000a471b59a26f, 63'h7ff24db77d3dd318, 63'h189adb7262d1db40};
        rom[ 45] = {63'h7ffffffffff8c8aa, 63'h0000000007c1021d, 63'h7ffffff7686bfa71, 63'h00000a2d25cd6c01, 63'h7ff2622baebdf5d5, 63'h188d33684c65e2ec};
        rom[ 46] = {63'h7ffffffffff8f1f5, 63'h00000000079cedde, 63'h7ffffff78727f199, 63'h00000a138d4f3eae, 63'h7ff2766c527cb167, 63'h187f9fb8911709f9};
        rom[ 47] = {63'h7ffffffffff91a29, 63'h000000000779a817, 63'h7ffffff7a555341b, 63'h000009fa502e1a53, 63'h7ff28a7a20e3754a, 63'h1872202fffa0cb7b};
        rom[ 48] = {63'h7ffffffffff9414d, 63'h0000000007572b4f, 63'h7ffffff7c2f6f0e8, 63'h000009e16cc2acd9, 63'h7ff29e55cf0369e1, 63'h1864b49c1d7a5174};
        rom[ 49] = {63'h7ffffffffff96769, 63'h0000000007357237, 63'h7ffffff7e0104160, 63'h000009c8e16f107a, 63'h7ff2b2000ea88a7a, 63'h18575ccb2387c5b2};
        rom[ 50] = {63'h7ffffffffff98c86, 63'h00000000071477a9, 63'h7ffffff7fca429fd, 63'h000009b0ac9e8c0c, 63'h7ff2c5798e6c3de6, 63'h184a188bfade7ba6};
        rom[ 51] = {63'h7ffffffffff9b0ab, 63'h0000000006f436a7, 63'h7ffffff818b59af0, 63'h00000998ccc5553e, 63'h7ff2d8c2f9c771a0, 63'h183ce7ae399b73c3};
        rom[ 52] = {63'h7ffffffffff9d3e0, 63'h0000000006d4aa5c, 63'h7ffffff8344770c4, 63'h00000981406054b4, 63'h7ff2ebdcf9243b4a, 63'h182fca021fcbbce4};
        rom[ 53] = {63'h7ffffffffff9f62b, 63'h0000000006b5ce17, 63'h7ffffff84f5c74f5, 63'h0000096a05f4ebf5, 63'h7ff2fec831ef0436, 63'h1822bf5894663be2};
        rom[ 54] = {63'h7ffffffffffa1795, 63'h0000000006979d49, 63'h7ffffff869f75e7f, 63'h000009531c10bd1a, 63'h7ff3118546a74296, 63'h1815c78322566543};
        rom[ 55] = {63'h7ffffffffffa3823, 63'h00000000067a1388, 63'h7ffffff8841ad272, 63'h0000093c8149742a, 63'h7ff32414d6efc3b4, 63'h1808e253f5977850};
        rom[ 56] = {63'h7ffffffffffa57dd, 63'h00000000065d2c8c, 63'h7ffffff89dc96475, 63'h00000926343c921d, 63'h7ff336777f9e8a8e, 63'h17fc0f9dd85fce4b};
        rom[ 57] = {63'h7ffffffffffa76c8, 63'h000000000640e42d, 63'h7ffffff8b7059750, 63'h00000910338f3973, 63'h7ff348addacc4607, 63'h17ef4f34305bd3d5};
        rom[ 58] = {63'h7ffffffffffa94ea, 63'h0000000006253662, 63'h7ffffff8cfd1dd66, 63'h000008fa7dedfc4c, 63'h7ff35ab87fe361d4, 63'h17e2a0eafbf84594};
        rom[ 59] = {63'h7ffffffffffab24a, 63'h00000000060a1f41, 63'h7ffffff8e8309937, 63'h000008e5120cabfc, 63'h7ff36c9803aeb513, 63'h17d60496cfbb4c67};
        rom[ 60] = {63'h7ffffffffffaceed, 63'h0000000005ef9afc, 63'h7ffffff900241dd1, 63'h000008cfeea62a13, 63'h7ff37e4cf867d17a, 63'h17c97a0cd3ac1837};
        rom[ 61] = {63'h7ffffffffffaead8, 63'h0000000005d5a5e3, 63'h7ffffff917aeaf48, 63'h000008bb127c3ab5, 63'h7ff38fd7edc4f5f4, 63'h17bd0122c0c89b7d};
        rom[ 62] = {63'h7ffffffffffb0611, 63'h0000000005bc3c61, 63'h7ffffff92ed28326, 63'h000008a67c575859, 63'h7ff3a1397106a74c, 63'h17b099aede890c29};
        rom[ 63] = {63'h7ffffffffffb209d, 63'h0000000005a35afb, 63'h7ffffff94591c0d2, 63'h000008922b0688c6, 63'h7ff3b2720d04f199, 63'h17a443880070d166};
        rom[ 64] = {63'h7ffffffffffb3a82, 63'h00000000058afe50, 63'h7ffffff95bee81ff, 63'h0000087e1d5f334e, 63'h7ff3c3824a3c54e8, 63'h1797fe8583ac882f};
        rom[ 65] = {63'h7ffffffffffb53c3, 63'h0000000005732319, 63'h7ffffff971ead30d, 63'h0000086a523cf848, 63'h7ff3d46aaeda5f98, 63'h178bca7f4cbccb36};
        rom[ 66] = {63'h7ffffffffffb6c65, 63'h00000000055bc624, 63'h7ffffff98788b369, 63'h00000856c88189a6, 63'h7ff3e52bbec9f8c8, 63'h177fa74dc52d6cfe};
        rom[ 67] = {63'h7ffffffffffb846d, 63'h000000000544e45a, 63'h7ffffff99cca15f1, 63'h000008437f1484b4, 63'h7ff3f5c5fbbf5d1f, 63'h177394c9d958d55d};
        rom[ 68] = {63'h7ffffffffffb9be0, 63'h00000000052e7ab7, 63'h7ffffff9b1b0e14b, 63'h0000083074e34cee, 63'h7ff40639e543d029, 63'h176792ccf63735e8};
        rom[ 69] = {63'h7ffffffffffbb2c1, 63'h0000000005188650, 63'h7ffffff9c63ef040, 63'h0000081da8e0e7e2, 63'h7ff41687f8c10468, 63'h175ba13107394ae1};
        rom[ 70] = {63'h7ffffffffffbc915, 63'h000000000503044c, 63'h7ffffff9da761210, 63'h0000080b1a05da14, 63'h7ff426b0b18c3c34, 63'h174fbfd0742e607c};
        rom[ 71] = {63'h7ffffffffffbdedf, 63'h0000000004edf1e9, 63'h7ffffff9ee580ac6, 63'h000007f8c75004e5, 63'h7ff436b488f12567, 63'h1743ee861f355636};
        rom[ 72] = {63'h7ffffffffffbf423, 63'h0000000004d94c78, 63'h7ffffffa01e69387, 63'h000007e6afc28569, 63'h7ff44693f63c71c0, 63'h17382d2d62b85c0f};
        rom[ 73] = {63'h7ffffffffffc08e6, 63'h0000000004c5115b, 63'h7ffffffa15235ae2, 63'h000007d4d2659434, 63'h7ff4564f6ec62df5, 63'h172c7ba20f73275b};
        rom[ 74] = {63'h7ffffffffffc1d2a, 63'h0000000004b13e09, 63'h7ffffffa2810051a, 63'h000007c32e4665fc, 63'h7ff465e765fbd928, 63'h1720d9c06a835ea7};
        rom[ 75] = {63'h7ffffffffffc30f3, 63'h00000000049dd00b, 63'h7ffffffa3aae2c6d, 63'h000007b1c2770d2a, 63'h7ff4755c4d6a3e9e, 63'h171547652b82fe17};
        rom[ 76] = {63'h7ffffffffffc4445, 63'h00000000048ac4fa, 63'h7ffffffa4cff615e, 63'h000007a08e0e5c39, 63'h7ff484ae94c7135f, 63'h1709c46d7aac774a};
        rom[ 77] = {63'h7ffffffffffc5722, 63'h0000000004781a80, 63'h7ffffffa5f052af8, 63'h0000078f9027c8e7, 63'h7ff493dea9fa5964, 63'h16fe50b6ef08517f};
        rom[ 78] = {63'h7ffffffffffc698f, 63'h000000000465ce59, 63'h7ffffffa70c10711, 63'h0000077ec7e3502f, 63'h7ff4a2ecf92789fe, 63'h16f2ec1f8ca41065};
        rom[ 79] = {63'h7ffffffffffc7b8d, 63'h000000000453de4e, 63'h7ffffffa82346a86, 63'h0000076e34655b0f, 63'h7ff4b1d9ecb688f1, 63'h16e79685c2d2298a};
        rom[ 80] = {63'h7ffffffffffc8d20, 63'h0000000004424839, 63'h7ffffffa9360c181, 63'h0000075dd4d6a3fd, 63'h7ff4c0a5ed5c61cf, 63'h16dc4fc86a72d1eb};
        rom[ 81] = {63'h7ffffffffffc9e4b, 63'h0000000004310a04, 63'h7ffffffaa4476fae, 63'h0000074da8641d21, 63'h7ff4cf516223d106, 63'h16d117c6c4456e92};
        rom[ 82] = {63'h7ffffffffffcaf11, 63'h00000000042021a5, 63'h7ffffffab4e9d07a, 63'h0000073dae3ed73c, 63'h7ff4dddcb0759a0f, 63'h16c5ee60774274b7};
        rom[ 83] = {63'h7ffffffffffcbf74, 63'h00000000040f8d22, 63'h7ffffffac5493749, 63'h0000072de59be938, 63'h7ff4ec483c20ac0e, 63'h16bad3758efd8731};
        rom[ 84] = {63'h7ffffffffffccf77, 63'h0000000003ff4a8c, 63'h7ffffffad566efaf, 63'h0000071e4db4586a, 63'h7ff4fa9467621653, 63'h16afc6e67a0fa056};
        rom[ 85] = {63'h7ffffffffffcdf1c, 63'h0000000003ef5804, 63'h7ffffffae5443da4, 63'h0000070ee5c50167, 63'h7ff508c192eccde3, 63'h16a4c894088918c4};
        rom[ 86] = {63'h7ffffffffffcee67, 63'h0000000003dfb3b5, 63'h7ffffffaf4e25db9, 63'h000006ffad0e818a, 63'h7ff516d01df14569, 63'h1699d85f6a6b5cd2};
        rom[ 87] = {63'h7ffffffffffcfd58, 63'h0000000003d05bda, 63'h7ffffffb04428549, 63'h000006f0a2d520fd, 63'h7ff524c06624d8ab, 63'h168ef62a2e2a239a};
        rom[ 88] = {63'h7ffffffffffd0bf4, 63'h0000000003c14eb5, 63'h7ffffffb1365e2a7, 63'h000006e1c660bd68, 63'h7ff53292c7c90cca, 63'h168421d63f33fbbd};
        rom[ 89] = {63'h7ffffffffffd1a3b, 63'h0000000003b28a99, 63'h7ffffffb224d9d55, 63'h000006d316fcb527, 63'h7ff540479db2a653, 63'h16795b45e4820340};
        rom[ 90] = {63'h7ffffffffffd2830, 63'h0000000003a40ddf, 63'h7ffffffb30fad629, 63'h000006c493f7d30c, 63'h7ff54ddf41509654, 63'h166ea25bbf2ea0e3};
        rom[ 91] = {63'h7ffffffffffd35d6, 63'h000000000395d6f0, 63'h7ffffffb3f6ea77f, 63'h000006b63ca43aab, 63'h7ff55b5a0ab2bf81, 63'h1663f6fac913167d};
        rom[ 92] = {63'h7ffffffffffd432e, 63'h000000000387e43b, 63'h7ffffffb4daa2561, 63'h000006a810575526, 63'h7ff568b850909469, 63'h16595906536bc4ed};
        rom[ 93] = {63'h7ffffffffffd503a, 63'h00000000037a343d, 63'h7ffffffb5bae5db3, 63'h0000069a0e69be79, 63'h7ff575fa684f8fd0, 63'h164ec8620582fb45};
        rom[ 94] = {63'h7ffffffffffd5cfc, 63'h00000000036cc57b, 63'h7ffffffb697c585b, 63'h0000068c36373347, 63'h7ff58320a6098817, 63'h164444f1db622bb8};
        rom[ 95] = {63'h7ffffffffffd6977, 63'h00000000035f9684, 63'h7ffffffb77151767, 63'h0000067e871e7f17, 63'h7ff5902b5c92deb5, 63'h1639ce9a248961e9};
        rom[ 96] = {63'h7ffffffffffd75ab, 63'h000000000352a5f0, 63'h7ffffffb84799736, 63'h0000067100816b07, 63'h7ff59d1add808c9b, 63'h162f653f82acd716};
        rom[ 97] = {63'h7ffffffffffd819b, 63'h000000000345f261, 63'h7ffffffb91aace99, 63'h00000663a1c4acf8, 63'h7ff5a9ef792e0c85, 63'h162508c6e8788189};
        rom[ 98] = {63'h7ffffffffffd8d49, 63'h0000000003397a83, 63'h7ffffffb9ea9aefd, 63'h000006566a4fd71e, 63'h7ff5b6a97ec323f1, 63'h161ab91598597d9c};
        rom[ 99] = {63'h7ffffffffffd98b5, 63'h00000000032d3d07, 63'h7ffffffbab772487, 63'h00000649598d47fe, 63'h7ff5c3493c398bbb, 63'h16107611234d2f73};
        rom[100] = {63'h7ffffffffffda3e3, 63'h00000000032138aa, 63'h7ffffffbb814163d, 63'h0000063c6eea1ad7, 63'h7ff5cfcefe627915, 63'h16063f9f67b5fd6f};
        rom[101] = {63'h7ffffffffffdaed2, 63'h0000000003156c30, 63'h7ffffffbc4816622, 63'h0000062fa9d6186a, 63'h7ff5dc3b10ec07b1, 63'h15fc15a690358425};
        rom[102] = {63'h7ffffffffffdb986, 63'h000000000309d663, 63'h7ffffffbd0bff157, 63'h0000062309c3a82a, 63'h7ff5e88dbe6685e6, 63'h15f1f80d128c2565};
        rom[103] = {63'h7ffffffffffdc3ff, 63'h0000000002fe7619, 63'h7ffffffbdcd0903d, 63'h000006168e27c1c3, 63'h7ff5f4c75049a38b, 63'h15e7e6b9ae7dd4b6};
        rom[104] = {63'h7ffffffffffdce3f, 63'h0000000002f34a2a, 63'h7ffffffbe8b41690, 63'h0000060a3679df06, 63'h7ff600e80ef98444, 63'h15dde1936cbc0458};
        rom[105] = {63'h7ffffffffffdd847, 63'h0000000002e8517a, 63'h7ffffffbf46b5385, 63'h000005fe0233ee28, 63'h7ff60cf041cbb600, 63'h15d3e8819dd4969b};
        rom[106] = {63'h7ffffffffffde218, 63'h0000000002dd8af1, 63'h7ffffffbfff711eb, 63'h000005f1f0d2445b, 63'h7ff618e02f0c0c47, 63'h15c9fb6bd925b809};
        rom[107] = {63'h7ffffffffffdebb5, 63'h0000000002d2f580, 63'h7ffffffc0b58183f, 63'h000005e601d390b9, 63'h7ff624b81c016119, 63'h15c01a39fbd6879f};
        rom[108] = {63'h7ffffffffffdf51e, 63'h0000000002c8901d, 63'h7ffffffc168f28cd, 63'h000005da34b8cf8a, 63'h7ff630784cf23bed, 63'h15b644d427d472e5};
        rom[109] = {63'h7ffffffffffdfe54, 63'h0000000002be59c5, 63'h7ffffffc219d01c9, 63'h000005ce89053dca, 63'h7ff63c2105295f8b, 63'h15ac7b22c2d52c63};
        rom[110] = {63'h7ffffffffffe0759, 63'h0000000002b4517c, 63'h7ffffffc2c825d68, 63'h000005c2fe3e4d10, 63'h7ff647b286fa3f4f, 63'h15a2bd0e755d239b};
        rom[111] = {63'h7ffffffffffe102e, 63'h0000000002aa764c, 63'h7ffffffc373ff1f9, 63'h000005b793eb97ae, 63'h7ff6532d13c55c6f, 63'h15990a8029ca6637};
        rom[112] = {63'h7ffffffffffe18d4, 63'h0000000002a0c743, 63'h7ffffffc41d671fc, 63'h000005ac4996d52b, 63'h7ff65e90ebfc8be4, 63'h158f63610b63d2c7};
        rom[113] = {63'h7ffffffffffe214c, 63'h0000000002974377, 63'h7ffffffc4c468c3c, 63'h000005a11ecbcef6, 63'h7ff669de4f272574, 63'h1585c79a856c85e7};
        rom[114] = {63'h7ffffffffffe2997, 63'h00000000028dea03, 63'h7ffffffc5690ebe4, 63'h000005961318556c, 63'h7ff675157be61c84, 63'h157c3716423b6b50};
        rom[115] = {63'h7ffffffffffe31b7, 63'h000000000284ba08, 63'h7ffffffc60b63896, 63'h0000058b260c3516, 63'h7ff68036aff80323, 63'h1572b1be2a56dcc0};
        rom[116] = {63'h7ffffffffffe39ac, 63'h00000000027bb2ab, 63'h7ffffffc6ab71680, 63'h0000058057392c30, 63'h7ff68b42283cf7dc, 63'h1569377c6394394e};
        rom[117] = {63'h7ffffffffffe4178, 63'h000000000272d318, 63'h7ffffffc74942671, 63'h00000575a632e06e, 63'h7ff6963820ba7edd, 63'h155fc83b503b6031};
        rom[118] = {63'h7ffffffffffe491a, 63'h00000000026a1a7d, 63'h7ffffffc7e4e05f0, 63'h0000056b128ed4fd, 63'h7ff6a118d49f46d7, 63'h155663e58e2dfa7c};
        rom[119] = {63'h7ffffffffffe5096, 63'h0000000002618811, 63'h7ffffffc87e54f4b, 63'h000005609be460c8, 63'h7ff6abe47e46da31, 63'h154d0a65f6127fd8};
        rom[120] = {63'h7ffffffffffe57ea, 63'h0000000002591b0d, 63'h7ffffffc915a99af, 63'h0000055641cca4eb, 63'h7ff6b69b573d3ce9, 63'h1543bba79a82e2c3};
        rom[121] = {63'h7ffffffffffe5f19, 63'h000000000250d2af, 63'h7ffffffc9aae793a, 63'h0000054c03e2836f, 63'h7ff6c13d984277a9, 63'h153a7795c73ed13d};
        rom[122] = {63'h7ffffffffffe6623, 63'h000000000248ae3a, 63'h7ffffffca3e17f09, 63'h00000541e1c29630, 63'h7ff6cbcb794e1081, 63'h15313e1c00617757};
        rom[123] = {63'h7ffffffffffe6d08, 63'h000000000240acf5, 63'h7ffffffcacf43951, 63'h00000537db0b2602, 63'h7ff6d645319271a5, 63'h15280f26019ab16d};
        rom[124] = {63'h7ffffffffffe73cb, 63'h000000000238ce2d, 63'h7ffffffcb5e7336a, 63'h0000052def5c2209, 63'h7ff6e0aaf7803eae, 63'h151eea9fbd6b9c62};
        rom[125] = {63'h7ffffffffffe7a6b, 63'h0000000002311130, 63'h7ffffffcbebaf5e5, 63'h000005241e571740, 63'h7ff6eafd00c998b9, 63'h1515d0755c667279};
        rom[126] = {63'h7ffffffffffe80e9, 63'h0000000002297553, 63'h7ffffffcc7700699, 63'h0000051a679f283b, 63'h7ff6f53b826551d1, 63'h150cc0933c71a3f2};
        rom[127] = {63'h7ffffffffffe8746, 63'h000000000221f9ed, 63'h7ffffffcd006e8b4, 63'h00000510cad90512, 63'h7ff6ff66b0920ffc, 63'h1503bae5f00e1ad2};
        rom[128] = {63'h7ffffffffffe8d84, 63'h00000000021a9e5a, 63'h7ffffffcd8801ccb, 63'h0000050747aae37c, 63'h7ff7097ebed96062, 63'h14fabf5a3da099c8};
        rom[129] = {63'h7ffffffffffe93a2, 63'h00000000021361f9, 63'h7ffffffce0dc20ea, 63'h000004fdddbc7721, 63'h7ff71383e012bac9, 63'h14f1cddd1ebe264f};
        rom[130] = {63'h7ffffffffffe99a1, 63'h00000000020c442e, 63'h7ffffffce91b70a1, 63'h000004f48cb6ea0c, 63'h7ff71d76466675eb, 63'h14e8e65bbf7b6ebf};
        rom[131] = {63'h7ffffffffffe9f82, 63'h0000000002054460, 63'h7ffffffcf13e8514, 63'h000004eb5444d554, 63'h7ff727562350acd9, 63'h14e008c37dbf1d27};
        rom[132] = {63'h7ffffffffffea546, 63'h0000000001fe61f7, 63'h7ffffffcf945d509, 63'h000004e2341239ea, 63'h7ff73123a7a415dc, 63'h14d73501e897084b};
        rom[133] = {63'h7ffffffffffeaaee, 63'h0000000001f79c63, 63'h7ffffffd0131d4f3, 63'h000004d92bcc7992, 63'h7ff73adf038ccb18, 63'h14ce6b04bf903457};
        rom[134] = {63'h7ffffffffffeb079, 63'h0000000001f0f313, 63'h7ffffffd0902f703, 63'h000004d03b225005, 63'h7ff7448866930554, 63'h14c5aab9f2119544};
        rom[135] = {63'h7ffffffffffeb5e9, 63'h0000000001ea657b, 63'h7ffffffd10b9ab36, 63'h000004c761c3cc3c, 63'h7ff74e1fff9dc921, 63'h14bcf40f9eb9852c};
        rom[136] = {63'h7ffffffffffebb3e, 63'h0000000001e3f314, 63'h7ffffffd18565f5a, 63'h000004be9f6249dd, 63'h7ff757a5fcf586c4, 63'h14b446f412bde123};
        rom[137] = {63'h7ffffffffffec079, 63'h0000000001dd9b56, 63'h7ffffffd1fd97f26, 63'h000004b5f3b06ad4, 63'h7ff7611a8c46ad24, 63'h14aba355c94ebf71};
        rom[138] = {63'h7ffffffffffec59b, 63'h0000000001d75dbf, 63'h7ffffffd2743743a, 63'h000004ad5e621108, 63'h7ff76a7ddaa43003, 63'h14a309236afbb25e};
        rom[139] = {63'h7ffffffffffecaa3, 63'h0000000001d139d0, 63'h7ffffffd2e94a634, 63'h000004a4df2c5841, 63'h7ff773d0148a01d5, 63'h149a784bcd1b8afe};
        rom[140] = {63'h7ffffffffffecf93, 63'h0000000001cb2f0b, 63'h7ffffffd35cd7ab7, 63'h0000049c75c59021, 63'h7ff77d1165df8175, 63'h1491f0bdf1368fbd};
        rom[141] = {63'h7ffffffffffed46b, 63'h0000000001c53cf5, 63'h7ffffffd3cee5577, 63'h0000049421e5364b, 63'h7ff78641f9f9dbf8, 63'h1489726904731aa8};
        rom[142] = {63'h7ffffffffffed92c, 63'h0000000001bf6318, 63'h7ffffffd43f79845, 63'h0000048be343f0a4, 63'h7ff78f61fb9e62f1, 63'h1480fd3c5f0493c4};
        rom[143] = {63'h7ffffffffffeddd6, 63'h0000000001b9a0fd, 63'h7ffffffd4ae9a315, 63'h00000483b99b87bb, 63'h7ff798719504d751, 63'h14789127839cbbe1};
        rom[144] = {63'h7ffffffffffee269, 63'h0000000001b3f634, 63'h7ffffffd51c4d411, 63'h0000047ba4a6e148, 63'h7ff7a170efd9a938, 63'h14702e1a1edf3cd6};
        rom[145] = {63'h7ffffffffffee6e7, 63'h0000000001ae624b, 63'h7ffffffd5889879c, 63'h00000473a421fad1, 63'h7ff7aa6035402ce7, 63'h1467d40406d77405};
        rom[146] = {63'h7ffffffffffeeb4f, 63'h0000000001a8e4d5, 63'h7ffffffd5f38185c, 63'h0000046bb7c9e468, 63'h7ff7b33f8dd4c515, 63'h145f82d53a706c8a};
        rom[147] = {63'h7ffffffffffeefa2, 63'h0000000001a37d67, 63'h7ffffffd65d0df48, 63'h00000463df5cbb8c, 63'h7ff7bc0f21af02e3, 63'h14573a7de0eefe87};
        rom[148] = {63'h7ffffffffffef3e0, 63'h00000000019e2b98, 63'h7ffffffd6c5433ae, 63'h0000045c1a99a61e, 63'h7ff7c4cf1863bba3, 63'h144efaee496e0946};
        rom[149] = {63'h7ffffffffffef80b, 63'h000000000198ef01, 63'h7ffffffd72c26b3d, 63'h000004546940cd79, 63'h7ff7cd7f990714b5, 63'h1446c416ea5cbe2d};
        rom[150] = {63'h7ffffffffffefc21, 63'h000000000193c73e, 63'h7ffffffd791bda0e, 63'h0000044ccb1359a0, 63'h7ff7d620ca2e85a2, 63'h143e95e860fef2a3};
        rom[151] = {63'h7fffffffffff0025, 63'h00000000018eb3ed, 63'h7ffffffd7f60d2ad, 63'h000004453fd36c8f, 63'h7ff7deb2d1f2d0b8, 63'h1436705370ef6f53};
        rom[152] = {63'h7fffffffffff0416, 63'h000000000189b4ae, 63'h7ffffffd8591a620, 63'h0000043dc7441d98, 63'h7ff7e735d5f1f256, 63'h142e534903a43359};
        rom[153] = {63'h7fffffffffff07f4, 63'h000000000184c922, 63'h7ffffffd8baea3f2, 63'h00000436612974e5, 63'h7ff7efa9fb510715, 63'h14263eba27f4a22b};
        rom[154] = {63'h7fffffffffff0bc0, 63'h00000000017ff0ed, 63'h7ffffffd91b81a38, 63'h0000042f0d48670e, 63'h7ff7f80f66be290b, 63'h141e329811a1932d};
        rom[155] = {63'h7fffffffffff0f7b, 63'h00000000017b2bb5, 63'h7ffffffd97ae559b, 63'h00000427cb66d0c7, 63'h7ff800663c72444e, 63'h14162ed418df3a2a};
        rom[156] = {63'h7fffffffffff1324, 63'h0000000001767922, 63'h7ffffffd9d91a15f, 63'h000004209b4b72a5, 63'h7ff808aea032e2f3, 63'h140e335fb9e0e00a};
        rom[157] = {63'h7fffffffffff16bd, 63'h000000000171d8de, 63'h7ffffffda362476b, 63'h000004197cbdecfc, 63'h7ff810e8b553f0a4, 63'h1406402c94666348};
        rom[158] = {63'h7fffffffffff1a44, 63'h00000000016d4a93, 63'h7ffffffda920904f, 63'h000004126f86bbcf, 63'h7ff819149eb9760e, 63'h13fe552c6b4b77ee};
        rom[159] = {63'h7fffffffffff1dbc, 63'h000000000168cdef, 63'h7ffffffdaeccc34d, 63'h0000040b736f32db, 63'h7ff821327ed94c46, 63'h13f6725124189ef2};
        rom[160] = {63'h7fffffffffff2124, 63'h00000000016462a1, 63'h7ffffffdb467265d, 63'h00000404884179b5, 63'h7ff8294277bcc855, 63'h13ee978cc695cd0b};
        rom[161] = {63'h7fffffffffff247c, 63'h0000000001600859, 63'h7ffffffdb9effe39, 63'h000003fdadc887f8, 63'h7ff83144ab025f17, 63'h13e6c4d17c5eb937};
        rom[162] = {63'h7fffffffffff27c5, 63'h00000000015bbeca, 63'h7ffffffdbf678e5e, 63'h000003f6e3d02192, 63'h7ff8393939df418d, 63'h13defa119078cb54};
        rom[163] = {63'h7fffffffffff2aff, 63'h00000000015785a7, 63'h7ffffffdc4ce1917, 63'h000003f02a24d319, 63'h7ff841204520f1d5, 63'h13d7373f6eeaa360};
        rom[164] = {63'h7fffffffffff2e2a, 63'h0000000001535ca6, 63'h7ffffffdca23df7f, 63'h000003e98093ee3b, 63'h7ff848f9ed2ed0eb, 63'h13cf7c4da455320b};
        rom[165] = {63'h7fffffffffff3147, 63'h00000000014f437d, 63'h7ffffffdcf69218b, 63'h000003e2e6eb863f, 63'h7ff850c6520ba550, 63'h13c7c92edd8e5b7f};
        rom[166] = {63'h7fffffffffff3456, 63'h00000000014b39e6, 63'h7ffffffdd49e1e0e, 63'h000003dc5cfa6c95, 63'h7ff8588593571ace, 63'h13c01dd5e73d1d5d};
        rom[167] = {63'h7fffffffffff3757, 63'h0000000001473f99, 63'h7ffffffdd9c312c1, 63'h000003d5e2902d7e, 63'h7ff86037d04f3b70, 63'h13b87a35ad77310a};
        rom[168] = {63'h7fffffffffff3a4b, 63'h0000000001435452, 63'h7ffffffdded83c47, 63'h000003cf777d0cc1, 63'h7ff867dd27d1e1d2, 63'h13b0de413b6023aa};
        rom[169] = {63'h7fffffffffff3d32, 63'h00000000013f77cf, 63'h7ffffffde3ddd630, 63'h000003c91b920272, 63'h7ff86f75b85e24f2, 63'h13a949ebbac9dd22};
        rom[170] = {63'h7fffffffffff400b, 63'h00000000013ba9cc, 63'h7ffffffde8d41b05, 63'h000003c2cea0b7cb, 63'h7ff87701a015bda2, 63'h13a1bd2873d68fb6};
        rom[171] = {63'h7fffffffffff42d8, 63'h000000000137ea0a, 63'h7ffffffdedbb4448, 63'h000003bc907b8413, 63'h7ff87e80fcbe65b7, 63'h139a37eacc9c09ff};
        rom[172] = {63'h7fffffffffff4599, 63'h0000000001343848, 63'h7ffffffdf2938a7d, 63'h000003b660f56999, 63'h7ff885f3ebc3311f, 63'h1392ba2648c864f4};
        rom[173] = {63'h7fffffffffff484d, 63'h000000000130944a, 63'h7ffffffdf75d252b, 63'h000003b03fe212bb, 63'h7ff88d5a8a35e0ed, 63'h138b43ce8948080a};
        rom[174] = {63'h7fffffffffff4af6, 63'h00000000012cfdd1, 63'h7ffffffdfc184ae4, 63'h000003aa2d15cefa, 63'h7ff894b4f4d03093, 63'h1383d4d74becfd73};
        rom[175] = {63'h7fffffffffff4d93, 63'h00000000012974a3, 63'h7ffffffe00c5314a, 63'h000003a428659029, 63'h7ff89c0347f51d4e, 63'h137c6d346b1790ac};
        rom[176] = {63'h7fffffffffff5024, 63'h000000000125f886, 63'h7ffffffe05640d12, 63'h0000039e31a6e797, 63'h7ff8a3459fb227f0, 63'h13750cd9dd6031a2};
        rom[177] = {63'h7fffffffffff52aa, 63'h000000000122893f, 63'h7ffffffe09f5120c, 63'h0000039848b0035b, 63'h7ff8aa7c17c09128, 63'h136db3bbb54296e5};
        rom[178] = {63'h7fffffffffff5526, 63'h00000000011f2697, 63'h7ffffffe0e787321, 63'h000003926d57ab9f, 63'h7ff8b1a6cb869057, 63'h136661ce20ca195d};
        rom[179] = {63'h7fffffffffff5796, 63'h00000000011bd057, 63'h7ffffffe12ee6260, 63'h0000038c9f754003, 63'h7ff8b8c5d6188517, 63'h135f1705693f4430};
        rom[180] = {63'h7fffffffffff59fc, 63'h0000000001188648, 63'h7ffffffe175710fc, 63'h00000386dee0b507, 63'h7ff8bfd9523a238d, 63'h1357d355f2d69397};
        rom[181] = {63'h7fffffffffff5c57, 63'h0000000001154837, 63'h7ffffffe1bb2af52, 63'h000003812b729183, 63'h7ff8c6e15a5f9ba2, 63'h135096b43c605d6b};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [(K + WSB)-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= {sb_in, idx_raw};
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [(K + WSB)-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB((K + WSB)), .ACC_SIGNED(1),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire        [K-1:0]    idx_p = esb[K-1:0];
    wire        [WSB-1:0]  sb_p  = esb[K +: WSB];
    wire        [WMAN-1:0] v_p   = {idx_p, ew};
    wire signed [WF-1:0]   f_p   = $signed({~v_p[WMAN-1], v_p[WMAN-2:0]});
    wire                   f_neg = f_p[WF-1];
    wire        [WF-1:0]   mag_f = f_neg ? (-f_p) : f_p;   // |f|, fits WF-1 bits (top bit structurally 0)

    wire [WF+ACCM-1:0] umag_p;   // unsigned |f| * C(f)
    wire [WSB:0]       fsb;      // {delayed f sign, external sideband} riding the pmul
    _zkf_pmul #(
        .WA(WF), .WB(ACCM), .A_SIGNED(0), .B_SIGNED(0),
        .WSB(WSB + 1), .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT_FINAL)
    ) u_final_pmul (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in({f_neg, sb_p}),
        .a(mag_f), .b(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(fsb), .p(umag_p)
    );
    assign sb_out = fsb[WSB-1:0];
    // Emit the magnitude and the sign SEPARATELY rather than a signed product: the caller folds the sign into
    // its e + log2(m') reconstruction as a single add/subtract, so the post-product cone carries one fewer wide
    // negate carry chain (a standalone two's-complement negate here would otherwise sit in series with that
    // adder and the magnitude abs, the critical path on wide formats). umag_p is the exact |f|*C(f): C(f) < 2
    // and |f| < 2**(WF-1) bound it below 2**(F2-1), so the F2+1-bit slice is lossless. The sign rode the pmul
    // sideband (fsb[WSB]) and so is aligned with out_valid.
    assign l_mag = umag_p[F2:0];
    assign l_neg = fsb[WSB];
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
