/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=48 (degree 5); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: two-stage ROM read + D*(2+STAGE_PRODUCT) (Horner).

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_exp2_m48 #(
    parameter D             = 5,
    parameter WSB           = 1,
    parameter WMULTIPLIER   = 0,
    parameter STAGE_PRODUCT = 0
) (
    input  wire           clk,
    input  wire           rst,
    input  wire           in_valid,
    input  wire [WSB-1:0] sb_in,
    input  wire [ 60-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire           out_valid,
    output wire [WSB-1:0] sb_out,
    output wire [ 48-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire           guard,
    output wire           round,
    output wire           sticky
);
    generate if (D != 5) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 48;
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 6;
    localparam integer CF   = 60;
    localparam integer RW   = 54;
    localparam integer CW   = 63;
    localparam integer ACCW = 63;
    localparam integer NSEG = 64;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [WIDX-1:0] idx = f[FF-1 -: WIDX];
    wire [RW-1:0]   w   = f[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[ 0] = {63'h000000000015f6df, 63'h00000000276534ac, 63'h00000038d611bfc7, 63'h00003d7f7bff0162, 63'h002c5c85fdf4743a, 63'h0fffffffffffffff};
        rom[ 1] = {63'h000000000016341a, 63'h0000000027d306c5, 63'h0000003974825ae7, 63'h00003e2aeb6f216f, 63'h002cd830162a5c18, 63'h102c9a3e778060ed};
        rom[ 2] = {63'h00000000001671ff, 63'h0000000028420b02, 63'h0000003a14aca319, 63'h00003ed838c663bb, 63'h002d5532ea4acff9, 63'h1059b0d31585743a};
        rom[ 3] = {63'h000000000016b091, 63'h0000000028b244b9, 63'h0000003ab6956799, 63'h00003f87693902ff, 63'h002dd3923b55e778, 63'h10874518759bc807};
        rom[ 4] = {63'h000000000016efd1, 63'h000000002923b749, 63'h0000003b5a41850e, 63'h000040388209bbc0, 63'h002e5351d4c2aab7, 63'h10b5586cf9890f61};
        rom[ 5] = {63'h0000000000172fc2, 63'h0000000029966619, 63'h0000003bffb5e5ab, 63'h000040eb8889f4c2, 63'h002ed4758c9c3e5b, 63'h10e3ec32d3d1a201};
        rom[ 6] = {63'h0000000000177065, 63'h000000002a0a549c, 63'h0000003ca6f78159, 63'h000041a08219e7e4, 63'h002f5701439f60d1, 63'h111301d0125b50a4};
        rom[ 7] = {63'h000000000017b1bc, 63'h000000002a7f864c, 63'h0000003d500b5dd6, 63'h000042577428cb7c, 63'h002fdaf8e55839cf, 63'h11429aaea92ddfb2};
        rom[ 8] = {63'h000000000017f3c9, 63'h000000002af5feaf, 63'h0000003dfaf68ee6, 63'h000043106434fc15, 63'h0030606068407ced, 63'h1172b83c7d517adb};
        rom[ 9] = {63'h000000000018368e, 63'h000000002b6dc153, 63'h0000003ea7be3670, 63'h000043cb57cc26b1, 63'h0030e73bcddde03a, 63'h11a35beb6fcb753b};
        rom[10] = {63'h0000000000187a0e, 63'h000000002be6d1d0, 63'h0000003f566784aa, 63'h00004488548b7374, 63'h00316f8f22e0e7c7, 63'h11d4873168b9aa77};
        rom[11] = {63'h000000000018be4a, 63'h000000002c6133ca, 63'h0000004006f7b843, 63'h00004547601fb0d4, 63'h0031f95e7f440701, 63'h12063b88628cd63a};
        rom[12] = {63'h0000000000190343, 63'h000000002cdceaed, 63'h00000040b9741e87, 63'h0000460880457f2e, 63'h003284ae066b18d8, 63'h12387a6e75623865};
        rom[13] = {63'h00000000001948fd, 63'h000000002d59faf1, 63'h000000416de2138b, 63'h000046cbbac97ceb, 63'h00331181e7432fa2, 63'h126b4565e27cdd24};
        rom[14] = {63'h0000000000198f7a, 63'h000000002dd86796, 63'h0000004224470253, 63'h000047911588730d, 63'h00339fde5c62bda4, 63'h129e9df51fdee12b};
        rom[15] = {63'h000000000019d6bb, 63'h000000002e5834a9, 63'h00000042dca86500, 63'h00004858966f8243, 63'h00342fc7ac2a1747, 63'h12d285a6e4030b3f};
        rom[16] = {63'h00000000001a1ec2, 63'h000000002ed96600, 63'h00000043970bc4f5, 63'h00004922437c5079, 63'h0034c14228e44fef, 63'h1306fe0a31b7152c};
        rom[17] = {63'h00000000001a6793, 63'h000000002f5bff7c, 63'h000000445376bb06, 63'h000049ee22bd36e2, 63'h0035545230e87264, 63'h133c08b26416ff4b};
        rom[18] = {63'h00000000001ab12e, 63'h000000002fe00508, 63'h0000004511eeefa0, 63'h00004abc3a517089, 63'h0035e8fc2ebb15e3, 63'h1371a7373aa9caa6};
        rom[19] = {63'h00000000001afb97, 63'h0000000030657a9d, 63'h00000045d27a1af9, 63'h00004b8c90694960, 63'h00367f44993050bf, 63'h13a7db34e59ff6e9};
        rom[20] = {63'h00000000001b46cf, 63'h0000000030ec643c, 63'h00000046951e0533, 63'h00004c5f2b464dd2, 63'h0037172ff38e09b2, 63'h13dea64c12342234};
        rom[21] = {63'h00000000001b92d8, 63'h000000003174c5f2, 63'h0000004759e08693, 63'h00004d34113b7add, 63'h0037b0c2cdaea8cf, 63'h14160a21f72e29f7};
        rom[22] = {63'h00000000001bdfb6, 63'h0000000031fea3d8, 63'h0000004820c787a8, 63'h00004e0b48ad6ead, 63'h00384c01c424292e, 63'h144e086061892d01};
        rom[23] = {63'h00000000001c2d6a, 63'h00000000328a0210, 63'h00000048e9d90177, 63'h00004ee4d81299c3, 63'h0038e8f1805b8c56, 63'h1486a2b5c13cd012};
        rom[24] = {63'h00000000001c7bf7, 63'h000000003316e4cc, 63'h00000049b51afdae, 63'h00004fc0c5f370a1, 63'h00398796b8c0b07f, 63'h14bfdad5362a271c};
        rom[25] = {63'h00000000001ccb5e, 63'h0000000033a55045, 63'h0000004a829396d0, 63'h0000509f18ea9e06, 63'h003a27f630e28ab9, 63'h14f9b2769d2ca6ac};
        rom[26] = {63'h00000000001d1ba3, 63'h00000000343548c2, 63'h0000004b5248f862, 63'h0000517fd7a535b2, 63'h003aca14b997c60f, 63'h15342b569d4f81dd};
        rom[27] = {63'h00000000001d6cc8, 63'h0000000034c6d297, 63'h0000004c24415f1d, 63'h0000526308e2e7b4, 63'h003b6df73123c8c3, 63'h156f4736b527da65};
        rom[28] = {63'h00000000001dbece, 63'h000000003559f222, 63'h0000004cf883191d, 63'h00005348b3763451, 63'h003c13a2835c20b8, 63'h15ab07dd48542957};
        rom[29] = {63'h00000000001e11ba, 63'h0000000035eeabce, 63'h0000004dcf148611, 63'h00005430de44a073, 63'h003cbb1ba9ce5837, 63'h15e76f15ad21486d};
        rom[30] = {63'h00000000001e658c, 63'h0000000036850412, 63'h0000004ea7fc176f, 63'h0000551b9046eaad, 63'h003d6467abe63425, 63'h16247eb03a5584b0};
        rom[31] = {63'h00000000001eba49, 63'h00000000371cff72, 63'h0000004f834050a0, 63'h00005608d08940d4, 63'h003e0f8b9f145cd0, 63'h166238825522248f};
        rom[32] = {63'h00000000001f0ff1, 63'h0000000037b6a27f, 63'h0000005060e7c738, 63'h000056f8a62b762b, 63'h003ebc8ca6f5728e, 63'h16a09e667f3bcc8f};
        rom[33] = {63'h00000000001f6688, 63'h000000003851f1d5, 63'h0000005140f92322, 63'h000057eb18613a2a, 63'h003f6b6ff5798f41, 63'h16dfb23c651a2ef0};
        rom[34] = {63'h00000000001fbe11, 63'h0000000038eef21f, 63'h00000052237b1edb, 63'h000058e02e724fd6, 63'h00401c3acb0c3601, 63'h171f75e8ec5f73db};
        rom[35] = {63'h000000000020168e, 63'h00000000398da813, 63'h00000053087487a0, 63'h000059d7efbac5be, 63'h0040cef276bcb219, 63'h175feb564267c8be};
        rom[36] = {63'h0000000000207001, 63'h000000003a2e1875, 63'h00000053efec3da4, 63'h00005ad263ab2e8c, 63'h0041839c5666e693, 63'h17a11473eb0186d6};
        rom[37] = {63'h000000000020ca6e, 63'h000000003ad04817, 63'h00000054d9e93444, 63'h00005bcf91c8da33, 63'h00423a3dd6dc8f7f, 63'h17e2f336cf4e620e};
        rom[38] = {63'h00000000002125d7, 63'h000000003b743bd8, 63'h00000055c672723e, 63'h00005ccf81ae0fc6, 63'h0042f2dc740ef644, 63'h182589994cce1289};
        rom[39] = {63'h000000000021823e, 63'h000000003c19f8a3, 63'h00000056b58f11e7, 63'h00005dd23b0a47e3, 63'h0043ad7db9391a2f, 63'h1868d99b4492ec7f};
        rom[40] = {63'h000000000021dfa8, 63'h000000003cc18374, 63'h00000057a7464161, 63'h00005ed7c5a267cd, 63'h00446a27410a4e87, 63'h18ace5422aa0db5a};
        rom[41] = {63'h0000000000223e15, 63'h000000003d6ae151, 63'h000000589b9f42d0, 63'h00005fe02950fd21, 63'h004528deb5d14f72, 63'h18f1ae991577362a};
        rom[42] = {63'h0000000000229d8a, 63'h000000003e161751, 63'h0000005992a16c95, 63'h000060eb6e067a39, 63'h0045e9a9d1a7ceee, 63'h193737b0cdc5e4f2};
        rom[43] = {63'h000000000022fe09, 63'h000000003ec32a98, 63'h0000005a8c542987, 63'h000061f99bc97332, 63'h0046ac8e5e9e7b37, 63'h197d829fde4e4f8a};
        rom[44] = {63'h0000000000235f95, 63'h000000003f722059, 63'h0000005b88bef927, 63'h0000630abab6dba0, 63'h0047719236e97fe1, 63'h19c49182a3f0901a};
        rom[45] = {63'h000000000023c231, 63'h000000004022fdd4, 63'h0000005c87e96fe0, 63'h0000641ed30244ea, 63'h004838bb450d830a, 63'h1a0c667b5de564b1};
        rom[46] = {63'h00000000002425df, 63'h0000000040d5c859, 63'h0000005d89db373c, 63'h00006535ecf61d58, 63'h0049020f840d1fec, 63'h1a5503b23e255c89};
        rom[47] = {63'h0000000000248aa4, 63'h00000000418a8547, 63'h0000005e8e9c0e23, 63'h0000665010f3efcd, 63'h0049cd94ff96e040, 63'h1a9e6b5579fdbf42};
        rom[48] = {63'h000000000024f082, 63'h0000000042413a0a, 63'h0000005f9633c912, 63'h0000676d4774a436, 63'h004a9b51d433b5c3, 63'h1ae89f995ad3ad5c};
        rom[49] = {63'h000000000025577b, 63'h0000000042f9ec21, 63'h00000060a0aa525e, 63'h0000688d9908c0ac, 63'h004b6b4c2f75f54e, 63'h1b33a2b84f15faf5};
        rom[50] = {63'h000000000025bf94, 63'h0000000043b4a115, 63'h00000061ae07aa68, 63'h000069b10e58ab47, 63'h004c3d8a5028d4e2, 63'h1b7f76f2fb5e46e8};
        rom[51] = {63'h00000000002628ce, 63'h0000000044715e83, 63'h00000062be53e7e2, 63'h00006ad7b024ecb0, 63'h004d121286806e1a, 63'h1bcc1e904bc1d222};
        rom[52] = {63'h000000000026932e, 63'h0000000045302a15, 63'h00000063d197380b, 63'h00006c0187467367, 63'h004de8eb344a4673, 63'h1c199bdd85529c20};
        rom[53] = {63'h000000000026feb7, 63'h0000000045f10986, 63'h00000064e7d9deea, 63'h00006d2e9caed7c4, 63'h004ec21acd1e5edf, 63'h1c67f12e57d14b48};
        rom[54] = {63'h0000000000276b6b, 63'h0000000046b402a2, 63'h0000006601243794, 63'h00006e5ef968a0be, 63'h004f9da7d690cc19, 63'h1cb720dcef906913};
        rom[55] = {63'h000000000027d94f, 63'h0000000047791b42, 63'h000000671d7eb468, 63'h00006f92a6978966, 63'h00507b98e863d93b, 63'h1d072d4a07897b8b};
        rom[56] = {63'h0000000000284865, 63'h0000000048405951, 63'h000000683cf1df50, 63'h000070c9ad78c72a, 63'h00515bf4acbab61b, 63'h1d5818dcfba48724};
        rom[57] = {63'h000000000028b8b0, 63'h000000004909c2cc, 63'h000000695f865a05, 63'h00007204176350dd, 63'h00523ec1e04cb2eb, 63'h1da9e603db32856e};
        rom[58] = {63'h0000000000292a35, 63'h0000000049d55dbf, 63'h0000006a8544de4e, 63'h00007341edc82683, 63'h0053240752990aa9, 63'h1dfc97337b9b5eb7};
        rom[59] = {63'h0000000000299cf5, 63'h000000004aa33047, 63'h0000006bae363e49, 63'h000074833a3299e4, 63'h00540bcbe61b3df5, 63'h1e502ee78b3ff625};
        rom[60] = {63'h00000000002a10f6, 63'h000000004b734092, 63'h0000006cda6364a5, 63'h000075c8064897eb, 63'h0054f616907fffda, 63'h1ea4afa2a490d983};
        rom[61] = {63'h00000000002a863a, 63'h000000004c4594df, 63'h0000006e09d554f2, 63'h000077105bcaf2d0, 63'h0055e2ee5adab614, 63'h1efa1bee615a2775};
        rom[62] = {63'h00000000002afcc5, 63'h000000004d1a3380, 63'h0000006f3c952bdd, 63'h0000785c4495ad16, 63'h0056d25a61db8e8f, 63'h1f50765b6e454065};
        rom[63] = {63'h00000000002b749b, 63'h000000004df122d7, 63'h0000007072ac1f7b, 63'h000079abcaa04550, 63'h0057c461d6062b94, 63'h1fa7c1819e90d82c};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [WSB-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= sb_in;
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [WSB-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(WSB), .ACC_SIGNED(0),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire _unused_horner = &{1'b0, ew, 1'b0};
    assign sb_out      = esb;
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
