from __future__ import annotations

import textwrap
from collections.abc import Mapping
from functools import cache
from importlib.resources import files
from importlib.resources.abc import Traversable
from types import MappingProxyType

_SEPARATOR = "// " + "-" * 117


@cache
def get_rtl() -> Mapping[str, str]:
    """Packaged RTL modules as a read-only mapping from POSIX path to Verilog source text."""
    out: dict[str, str] = {}

    def walk(node: Traversable, prefix: str) -> None:
        for child in node.iterdir():
            name = f"{prefix}{child.name}"
            if child.is_dir():
                walk(child, f"{name}/")
            elif child.name.endswith(".v"):
                out[name] = child.read_text(encoding="utf-8")

    walk(files("zkf") / "rtl", "")
    return MappingProxyType(dict(sorted(out.items())))


@cache
def get_rtl_bundle() -> str:
    """Every packaged RTL module in one Verilog source, public modules first."""
    from . import __version__

    rtl = get_rtl()
    public = ", ".join(path.removesuffix(".v") for path in rtl if not path.startswith("_"))
    blocks = [
        f"// GENERATED BY ZKF v{__version__}\n"
        + textwrap.fill(public, 120, initial_indent="// Public modules: ", subsequent_indent="//   ")
    ]
    for path in sorted(rtl, key=lambda path: (path.startswith("_"), path)):
        blocks.append(f"{_SEPARATOR}\n// BEGIN {path}\n\n{rtl[path].strip()}\n\n// END {path}")
    return "\n\n".join(blocks) + "\n"
