/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=32 (degree 3); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: two-stage ROM read + D*(2+STAGE_PRODUCT) (Horner).

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_exp2_m32 #(
    parameter D             = 3,
    parameter WSB           = 1,
    parameter WMULTIPLIER   = 0,
    parameter STAGE_PRODUCT = 0
) (
    input  wire           clk,
    input  wire           rst,
    input  wire           in_valid,
    input  wire [WSB-1:0] sb_in,
    input  wire [ 44-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire           out_valid,
    output wire [WSB-1:0] sb_out,
    output wire [ 32-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire           guard,
    output wire           round,
    output wire           sticky
);
    generate if (D != 3) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 32;
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 7;
    localparam integer CF   = 44;
    localparam integer RW   = 37;
    localparam integer CW   = 47;
    localparam integer ACCW = 47;
    localparam integer NSEG = 128;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [WIDX-1:0] idx = f[FF-1 -: WIDX];
    wire [RW-1:0]   w   = f[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[  0] = {47'h000000071fb1, 47'h00000f5fdbea, 47'h00162e42ff98, 47'h0ffffffffffb};
        rom[  1] = {47'h000000072998, 47'h00000f753af9, 47'h00164d1817bc, 47'h10163da9fb2e};
        rom[  2] = {47'h00000007338d, 47'h00000f8ab7be, 47'h00166c180bb5, 47'h102c9a3e777b};
        rom[  3] = {47'h000000073d8f, 47'h00000fa05260, 47'h00168b431716, 47'h104315e86e7b};
        rom[  4] = {47'h0000000747a0, 47'h00000fb60b0b, 47'h0016aa9975c7, 47'h1059b0d31580};
        rom[  5] = {47'h0000000751be, 47'h00000fcbe1e7, 47'h0016ca1b6400, 47'h10706b29ddf2};
        rom[  6] = {47'h000000075beb, 47'h00000fe1d71f, 47'h0016e9c91e4e, 47'h108745187597};
        rom[  7] = {47'h000000076626, 47'h00000ff7eadc, 47'h001709a2e194, 47'h109e3ecac6ee};
        rom[  8] = {47'h00000007706f, 47'h0000100e1d4a, 47'h001729a8eb06, 47'h10b5586cf984};
        rom[  9] = {47'h000000077ac6, 47'h000010246e93, 47'h001749db7831, 47'h10cc922b7243};
        rom[ 10] = {47'h00000007852c, 47'h0000103adee1, 47'h00176a3ac6f5, 47'h10e3ec32d3cc};
        rom[ 11] = {47'h000000078fa0, 47'h000010516e60, 47'h00178ac71588, 47'h10fb66affece};
        rom[ 12] = {47'h000000079a22, 47'h000010681d3c, 47'h0017ab80a278, 47'h111301d01256};
        rom[ 13] = {47'h00000007a4b3, 47'h0000107eeb9f, 47'h0017cc67aca9, 47'h112abdc06c2d};
        rom[ 14] = {47'h00000007af53, 47'h00001095d9b7, 47'h0017ed7c7356, 47'h11429aaea929};
        rom[ 15] = {47'h00000007ba02, 47'h000010ace7ad, 47'h00180ebf3614, 47'h115a98c8a589};
        rom[ 16] = {47'h00000007c4c0, 47'h000010c415b0, 47'h0018303034cc, 47'h1172b83c7d4c};
        rom[ 17] = {47'h00000007cf8c, 47'h000010db63ec, 47'h001851cfafc6, 47'h118af9388c89};
        rom[ 18] = {47'h00000007da68, 47'h000010f2d28d, 47'h0018739de79d, 47'h11a35beb6fc6};
        rom[ 19] = {47'h00000007e552, 47'h0000110a61c0, 47'h0018959b1d4b, 47'h11bbe0840457};
        rom[ 20] = {47'h00000007f04c, 47'h0000112211b3, 47'h0018b7c79220, 47'h11d4873168b4};
        rom[ 21] = {47'h00000007fb55, 47'h00001139e293, 47'h0018da2387cb, 47'h11ed5022fcd4};
        rom[ 22] = {47'h00000008066d, 47'h00001151d48f, 47'h0018fcaf4054, 47'h12063b886287};
        rom[ 23] = {47'h000000081195, 47'h00001169e7d3, 47'h00191f6afe1e, 47'h121f49917dd7};
        rom[ 24] = {47'h000000081ccc, 47'h000011821c8e, 47'h0019425703e9, 47'h12387a6e755d};
        rom[ 25] = {47'h000000082813, 47'h0000119a72f0, 47'h0019657394d4, 47'h1251ce4fb2a1};
        rom[ 26] = {47'h00000008336a, 47'h000011b2eb26, 47'h001988c0f457, 47'h126b4565e277};
        rom[ 27] = {47'h000000083ed0, 47'h000011cb855f, 47'h0019ac3f664c, 47'h1284dfe1f55e};
        rom[ 28] = {47'h000000084a46, 47'h000011e441cb, 47'h0019cfef2ee9, 47'h129e9df51fd9};
        rom[ 29] = {47'h0000000855cc, 47'h000011fd209a, 47'h0019f3d092c3, 47'h12b87fd0dad4};
        rom[ 30] = {47'h000000086162, 47'h0000121621fb, 47'h001a17e3d6cf, 47'h12d285a6e3fd};
        rom[ 31] = {47'h000000086d08, 47'h0000122f461e, 47'h001a3c294061, 47'h12ecafa93e29};
        rom[ 32] = {47'h0000000878bf, 47'h000012488d34, 47'h001a60a1152e, 47'h1306fe0a31b1};
        rom[ 33] = {47'h000000088486, 47'h00001261f76d, 47'h001a854b9b4c, 47'h132170fc4cd2};
        rom[ 34] = {47'h00000008905d, 47'h0000127b84fa, 47'h001aaa291932, 47'h133c08b26411};
        rom[ 35] = {47'h000000089c44, 47'h00001295360c, 47'h001acf39d5b9, 47'h1356c55f929a};
        rom[ 36] = {47'h00000008a83c, 47'h000012af0ad5, 47'h001af47e181d, 47'h1371a7373aa4};
        rom[ 37] = {47'h00000008b445, 47'h000012c90386, 47'h001b19f627fd, 47'h138cae6d05d2};
        rom[ 38] = {47'h00000008c05e, 47'h000012e32050, 47'h001b3fa24d5a, 47'h13a7db34e59a};
        rom[ 39] = {47'h00000008cc89, 47'h000012fd6168, 47'h001b6582d09b, 47'h13c32dc313a3};
        rom[ 40] = {47'h00000008d8c4, 47'h00001317c6fd, 47'h001b8b97fa8b, 47'h13dea64c122e};
        rom[ 41] = {47'h00000008e510, 47'h000013325144, 47'h001bb1e2145a, 47'h13fa4504ac7a};
        rom[ 42] = {47'h00000008f16d, 47'h0000134d0070, 47'h001bd861679e, 47'h14160a21f728};
        rom[ 43] = {47'h00000008fddb, 47'h00001367d4b3, 47'h001bff163e52, 47'h1431f5d950a2};
        rom[ 44] = {47'h000000090a5b, 47'h00001382ce42, 47'h001c2600e2da, 47'h144e08606183};
        rom[ 45] = {47'h0000000916ec, 47'h0000139ded4f, 47'h001c4d21a001, 47'h146a41ed1cfa};
        rom[ 46] = {47'h00000009238f, 47'h000013b93210, 47'h001c7478c0f8, 47'h1486a2b5c136};
        rom[ 47] = {47'h000000093043, 47'h000013d49cb8, 47'h001c9c06915b, 47'h14a32af0d7ce};
        rom[ 48] = {47'h000000093d09, 47'h000013f02d7d, 47'h001cc3cb5d2d, 47'h14bfdad53624};
        rom[ 49] = {47'h0000000949e0, 47'h0000140be493, 47'h001cebc770dc, 47'h14dcb299fdd7};
        rom[ 50] = {47'h0000000956ca, 47'h00001427c230, 47'h001d13fb1940, 47'h14f9b2769d26};
        rom[ 51] = {47'h0000000963c5, 47'h00001443c688, 47'h001d3c66a39c, 47'h1516daa2cf60};
        rom[ 52] = {47'h0000000970d2, 47'h0000145ff1d3, 47'h001d650a5d9d, 47'h15342b569d49};
        rom[ 53] = {47'h000000097df2, 47'h0000147c4446, 47'h001d8de6955e, 47'h1551a4ca5d8b};
        rom[ 54] = {47'h000000098b24, 47'h00001498be17, 47'h001db6fb9965, 47'h156f4736b521};
        rom[ 55] = {47'h000000099868, 47'h000014b55f7e, 47'h001de049b8a7, 47'h158d12d497c1};
        rom[ 56] = {47'h00000009a5be, 47'h000014d228b0, 47'h001e09d14284, 47'h15ab07dd484d};
        rom[ 57] = {47'h00000009b327, 47'h000014ef19e7, 47'h001e339286cc, 47'h15c9268a5940};
        rom[ 58] = {47'h00000009c0a3, 47'h0000150c3358, 47'h001e5d8dd5bf, 47'h15e76f15ad1b};
        rom[ 59] = {47'h00000009ce31, 47'h00001529753d, 47'h001e87c3800b, 47'h1605e1b976d5};
        rom[ 60] = {47'h00000009dbd3, 47'h00001546dfcd, 47'h001eb233d6ce, 47'h16247eb03a4f};
        rom[ 61] = {47'h00000009e987, 47'h000015647341, 47'h001edcdf2b97, 47'h16434634ccbc};
        rom[ 62] = {47'h00000009f74e, 47'h000015822fd2, 47'h001f07c5d067, 47'h16623882551b};
        rom[ 63] = {47'h0000000a0529, 47'h000015a015b8, 47'h001f32e817b1, 47'h168155d44ca3};
        rom[ 64] = {47'h0000000a1316, 47'h000015be252e, 47'h001f5e46545a, 47'h16a09e667f35};
        rom[ 65] = {47'h0000000a2118, 47'h000015dc5e6d, 47'h001f89e0d9ba, 47'h16c012750bd4};
        rom[ 66] = {47'h0000000a2f2c, 47'h000015fac1b0, 47'h001fb5b7fb9f, 47'h16dfb23c6513};
        rom[ 67] = {47'h0000000a3d54, 47'h000016194f30, 47'h001fe1cc0e47, 47'h16ff7df9518d};
        rom[ 68] = {47'h0000000a4b90, 47'h000016380728, 47'h00200e1d666a, 47'h171f75e8ec58};
        rom[ 69] = {47'h0000000a59e0, 47'h00001656e9d3, 47'h00203aac5934, 47'h173f9a48a57a};
        rom[ 70] = {47'h0000000a6843, 47'h00001675f76d, 47'h002067793c45, 47'h175feb564261};
        rom[ 71] = {47'h0000000a76bb, 47'h000016953032, 47'h0020948465b8, 47'h1780694fde56};
        rom[ 72] = {47'h0000000a8546, 47'h000016b4945d, 47'h0020c1ce2c1d, 47'h17a11473eafa};
        rom[ 73] = {47'h0000000a93e6, 47'h000016d4242b, 47'h0020ef56e67d, 47'h17c1ed0130ba};
        rom[ 74] = {47'h0000000aa29a, 47'h000016f3dfd8, 47'h00211d1eec5a, 47'h17e2f336cf47};
        rom[ 75] = {47'h0000000ab163, 47'h00001713c7a1, 47'h00214b2695b0, 47'h180427543e13};
        rom[ 76] = {47'h0000000ac040, 47'h00001733dbc4, 47'h0021796e3af6, 47'h182589994cc7};
        rom[ 77] = {47'h0000000acf31, 47'h000017541c7e, 47'h0021a7f6351b, 47'h18471a4623c0};
        rom[ 78] = {47'h0000000ade38, 47'h000017748a0e, 47'h0021d6bedd8d, 47'h1868d99b448b};
        rom[ 79] = {47'h0000000aed53, 47'h0000179524b2, 47'h002205c88e35, 47'h188ac7d98a5f};
        rom[ 80] = {47'h0000000afc84, 47'h000017b5eca7, 47'h00223513a179, 47'h18ace5422a99};
        rom[ 81] = {47'h0000000b0bc9, 47'h000017d6e22e, 47'h002264a0723b, 47'h18cf3216b53d};
        rom[ 82] = {47'h0000000b1b24, 47'h000017f80585, 47'h0022946f5bdf, 47'h18f1ae991570};
        rom[ 83] = {47'h0000000b2a94, 47'h0000181956ed, 47'h0022c480ba44, 47'h19145b0b91f8};
        rom[ 84] = {47'h0000000b3a1a, 47'h0000183ad6a5, 47'h0022f4d4e9cd, 47'h193737b0cdbe};
        rom[ 85] = {47'h0000000b49b5, 47'h0000185c84ee, 47'h0023256c4759, 47'h195a44cbc84a};
        rom[ 86] = {47'h0000000b5966, 47'h0000187e6209, 47'h00235647304b, 47'h197d829fde46};
        rom[ 87] = {47'h0000000b692d, 47'h000018a06e36, 47'h002387660287, 47'h19a0f170ca00};
        rom[ 88] = {47'h0000000b7909, 47'h000018c2a9b6, 47'h0023b8c91c73, 47'h19c49182a3e9};
        rom[ 89] = {47'h0000000b88fc, 47'h000018e514cd, 47'h0023ea70dcfa, 47'h19e86319e31b};
        rom[ 90] = {47'h0000000b9905, 47'h00001907afbb, 47'h00241c5da388, 47'h1a0c667b5ddd};
        rom[ 91] = {47'h0000000ba924, 47'h0000192a7ac4, 47'h00244e8fd010, 47'h1a309bec4a25};
        rom[ 92] = {47'h0000000bb959, 47'h0000194d762a, 47'h00248107c30a, 47'h1a5503b23e1d};
        rom[ 93] = {47'h0000000bc9a5, 47'h00001970a231, 47'h0024b3c5dd74, 47'h1a799e1330ab};
        rom[ 94] = {47'h0000000bda08, 47'h00001993ff1c, 47'h0024e6ca80d2, 47'h1a9e6b5579f6};
        rom[ 95] = {47'h0000000bea81, 47'h000019b78d2e, 47'h00251a160f30, 47'h1ac36bbfd3eb};
        rom[ 96] = {47'h0000000bfb12, 47'h000019db4cad, 47'h00254da8eb23, 47'h1ae89f995acb};
        rom[ 97] = {47'h0000000c0bb9, 47'h000019ff3dde, 47'h0025818377c9, 47'h1b0e07298dae};
        rom[ 98] = {47'h0000000c1c78, 47'h00001a236104, 47'h0025b5a618c7, 47'h1b33a2b84f0e};
        rom[ 99] = {47'h0000000c2d4e, 47'h00001a47b666, 47'h0025ea113251, 47'h1b59728de551};
        rom[100] = {47'h0000000c3e3b, 47'h00001a6c3e49, 47'h00261ec52924, 47'h1b7f76f2fb56};
        rom[101] = {47'h0000000c4f40, 47'h00001a90f8f4, 47'h002653c26288, 47'h1ba5b030a0fe};
        rom[102] = {47'h0000000c605c, 47'h00001ab5e6ae, 47'h002689094453, 47'h1bcc1e904bb9};
        rom[103] = {47'h0000000c7190, 47'h00001adb07bc, 47'h0026be9a34e8, 47'h1bf2c25bd715};
        rom[104] = {47'h0000000c82dc, 47'h00001b005c67, 47'h0026f4759b3a, 47'h1c199bdd854a};
        rom[105] = {47'h0000000c9440, 47'h00001b25e4f6, 47'h00272a9bdeca, 47'h1c40ab5fffc8};
        rom[106] = {47'h0000000ca5bd, 47'h00001b4ba1b2, 47'h0027610d67a8, 47'h1c67f12e57c9};
        rom[107] = {47'h0000000cb751, 47'h00001b7192e3, 47'h002797ca9e75, 47'h1c8f6d9406df};
        rom[108] = {47'h0000000cc8fe, 47'h00001b97b8d1, 47'h0027ced3ec64, 47'h1cb720dcef88};
        rom[109] = {47'h0000000cdac4, 47'h00001bbe13c7, 47'h00280629bb3a, 47'h1cdf0b555dbb};
        rom[110] = {47'h0000000ceca2, 47'h00001be4a40e, 47'h00283dcc7550, 47'h1d072d4a0781};
        rom[111] = {47'h0000000cfe9a, 47'h00001c0b69ef, 47'h002875bc8592, 47'h1d2f87080d81};
        rom[112] = {47'h0000000d10aa, 47'h00001c3265b6, 47'h0028adfa577f, 47'h1d5818dcfb9b};
        rom[113] = {47'h0000000d22d3, 47'h00001c5997ae, 47'h0028e686572e, 47'h1d80e316c97a};
        rom[114] = {47'h0000000d3516, 47'h00001c810021, 47'h00291f60f14b, 47'h1da9e603db29};
        rom[115] = {47'h0000000d4771, 47'h00001ca89f5c, 47'h0029588a931a, 47'h1dd321f301ab};
        rom[116] = {47'h0000000d59e7, 47'h00001cd075aa, 47'h00299203aa74, 47'h1dfc97337b92};
        rom[117] = {47'h0000000d6c76, 47'h00001cf88359, 47'h0029cbcca5d0, 47'h1e264614f598};
        rom[118] = {47'h0000000d7f1f, 47'h00001d20c8b5, 47'h002a05e5f439, 47'h1e502ee78b37};
        rom[119] = {47'h0000000d91e2, 47'h00001d49460b, 47'h002a40500557, 47'h1e7a51fbc743};
        rom[120] = {47'h0000000da4be, 47'h00001d71fbaa, 47'h002a7b0b496e, 47'h1ea4afa2a487};
        rom[121] = {47'h0000000db7b6, 47'h00001d9ae9e0, 47'h002ab618315d, 47'h1ecf482d8e5e};
        rom[122] = {47'h0000000dcac7, 47'h00001dc410fa, 47'h002af1772e9f, 47'h1efa1bee6151};
        rom[123] = {47'h0000000dddf3, 47'h00001ded7149, 47'h002b2d28b34e, 47'h1f252b376bb1};
        rom[124] = {47'h0000000df13a, 47'h00001e170b1c, 47'h002b692d3223, 47'h1f50765b6e3c};
        rom[125] = {47'h0000000e049b, 47'h00001e40dec3, 47'h002ba5851e75, 47'h1f7bfdad9cb4};
        rom[126] = {47'h0000000e1817, 47'h00001e6aec8e, 47'h002be230ec3c, 47'h1fa7c1819e87};
        rom[127] = {47'h0000000e2baf, 47'h00001e9534ce, 47'h002c1f311011, 47'h1fd3c22b8f68};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [WSB-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= sb_in;
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [WSB-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(WSB), .ACC_SIGNED(0),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire _unused_horner = &{1'b0, ew, 1'b0};
    assign sb_out      = esb;
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
