// GENERATED by zkf_trig.py -- DO NOT EDIT.
// Per-WMAN CORDIC constants (WMAN=36): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
// Binds _zkf_cordic_core (MODE as there); both modes run to the same depth N, so one LUT and one inverse gain
// serve either.

`default_nettype none

module _zkf_cordic_m36 #(
    parameter integer MODE      = 0,
    parameter integer UNROLL100 = 100,
    parameter integer PARALLEL  = (MODE != 1) && (UNROLL100 < 100),
    parameter integer EXPECT_WMAN       = 36,
    parameter integer EXPECT_N          = 20,
    parameter integer EXPECT_XF         = 60,
    parameter integer EXPECT_WX         = 62,
    parameter integer EXPECT_WT         = 54,
    parameter integer EXPECT_ZF         = 62,
    parameter integer EXPECT_WZ         = 65,
    parameter integer EXPECT_WCONST2PI  = 41,
    parameter integer EXPECT_CONST2PI_S = 38,
    parameter integer EXPECT_WINVTAU    = 41,
    parameter integer EXPECT_INVTAU_S   = 43,
    parameter integer EXPECT_WKINV_MAG  = 41,
    parameter integer EXPECT_KINV_S     = 41
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire                vectoring,
    input  wire signed [ 61:0] x0,
    input  wire signed [ 61:0] y0,
    input  wire signed [ 64:0] z0,
    output wire                busy,
    output wire                done,
    output wire                z_done,
    output wire signed [ 61:0] xn,
    output wire signed [ 61:0] yn,
    output wire signed [ 64:0] zn,
    output wire        [ 40:0] const2pi,   // round(2*pi * 2**CONST2PI_S), WMAN+5 bits (sin/cos to radians)
    output wire        [ 40:0] inv_tau,    // round(2**INVTAU_S / (2*pi)), WMAN+5 bits (atan2 turns scale)
    output wire        [ 40:0] kinv_mag    // round(2**KINV_S / gain), WMAN+5 bits (atan2 magnitude descale)
);
    localparam integer N    = 20;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 62;
    localparam integer WZ   = 65;
    localparam integer XF   = 60;   // x/y fractional scale
    localparam integer WT   = 54;   // quadrant-local coordinate width used to derive ZF
    localparam integer ZF   = 62;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer WCONST2PI  = 41;
    localparam integer WINVTAU    = 41;
    localparam integer WKINV_MAG  = 41;
    localparam integer CONST2PI_S = 38;   // scale of const2pi (== WMAN+2)
    localparam integer INVTAU_S   = 43;   // scale of inv_tau  (== WMAN+7)
    localparam integer KINV_S     = 41;   // scale of kinv_mag (== WMAN+5)
    localparam signed [WX-1:0] KINV = 62'sd700114967507787739;   // round(1/gain * 2**XF), the sin/cos seed

    // Geometry contract: the consuming RTL passes its locally-computed dimensions and constant scales here. If a
    // formula drifts away from zkf_trig.py, elaboration fails before any port truncation/extension can hide it.
    generate
        if ((EXPECT_WMAN      != 36) || (EXPECT_N  != N)  || (EXPECT_XF != XF) || (EXPECT_WX != WX) ||
            (EXPECT_WT        != WT) || (EXPECT_ZF != ZF) || (EXPECT_WZ != WZ) ||
            (EXPECT_WCONST2PI != WCONST2PI) || (EXPECT_CONST2PI_S != CONST2PI_S) ||
            (EXPECT_WINVTAU   != WINVTAU)   || (EXPECT_INVTAU_S   != INVTAU_S)   ||
            (EXPECT_WKINV_MAG != WKINV_MAG) || (EXPECT_KINV_S     != KINV_S)) begin : g_invalid_geometry_contract
            _zkf_invalid_cordic_geometry_contract u_invalid();
        end
    endgenerate

    assign const2pi = 41'd1727108826179;
    assign inv_tau  = 41'd1399941684381;
    assign kinv_mag = 41'd1335363326088;

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        65'd1399941684379,   // atan(2^-19)/2pi
        65'd2799883368747,   // atan(2^-18)/2pi
        65'd5599766737413,   // atan(2^-17)/2pi
        65'd11199533474175,   // atan(2^-16)/2pi
        65'd22399066943135,   // atan(2^-15)/2pi
        65'd44798133844548,   // atan(2^-14)/2pi
        65'd89596267355325,   // atan(2^-13)/2pi
        65'd179192532040472,   // atan(2^-12)/2pi
        65'd358385042719534,   // atan(2^-11)/2pi
        65'd716769914547871,   // atan(2^-10)/2pi
        65'd1433538461969102,   // atan(2^-9)/2pi
        65'd2867065987018958,   // atan(2^-8)/2pi
        65'd5734044481687724,   // atan(2^-7)/2pi
        65'd11467389120678282,   // atan(2^-6)/2pi
        65'd22929182573009054,   // atan(2^-5)/2pi
        65'd45813697873323707,   // atan(2^-4)/2pi
        65'd91273161881380487,   // atan(2^-3)/2pi
        65'd179807632645220259,   // atan(2^-2)/2pi
        65'd340304653033718298,   // atan(2^-1)/2pi
        65'd576460752303423488   // atan(2^-0)/2pi
    };

    // Rotation seeds (1/gain, 0), so (xn, yn) = (cos z0, sin z0).
    wire                 rotate = (MODE == 0) || ((MODE == 2) && !vectoring);
    wire signed [WX-1:0] seed_x = rotate ? KINV       : x0;
    wire signed [WX-1:0] seed_y = rotate ? {WX{1'b0}} : y0;
    _zkf_cordic_core #(
        .N(N), .UNROLL100(UNROLL100), .PARALLEL(PARALLEL), .WX(WX), .WZ(WZ), .MODE(MODE)
    ) u_cordic (
        .clk(clk), .rst(rst), .start(start), .vectoring(vectoring),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .z_done(z_done), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
