/// GENERATED by zkf_trig.py -- DO NOT EDIT.
/// Per-WMAN CORDIC constants (WMAN=16): arctan(2^-i)/2pi LUT in turns, inverse-gain seed, widths.
/// Binds _zkf_cordic_core (MODE as there); both modes run to the same depth N, so one LUT and one inverse gain
/// serve either.

`default_nettype none

module _zkf_cordic_m16 #(
    parameter integer MODE      = 0,
    parameter integer UNROLL100 = 100,
    parameter integer PARALLEL  = (MODE != 1) && (UNROLL100 < 100),
    parameter integer EXPECT_WMAN       = 16,
    parameter integer EXPECT_N          = 10,
    parameter integer EXPECT_XF         = 30,
    parameter integer EXPECT_WX         = 32,
    parameter integer EXPECT_WT         = 26,
    parameter integer EXPECT_ZF         = 34,
    parameter integer EXPECT_WZ         = 37,
    parameter integer EXPECT_WCONST2PI  = 21,
    parameter integer EXPECT_CONST2PI_S = 18,
    parameter integer EXPECT_WINVTAU    = 21,
    parameter integer EXPECT_INVTAU_S   = 23,
    parameter integer EXPECT_WKINV_MAG  = 21,
    parameter integer EXPECT_KINV_S     = 21
) (
    input  wire                clk,
    input  wire                rst,
    input  wire                start,
    input  wire                vectoring,
    input  wire signed [ 31:0] x0,
    input  wire signed [ 31:0] y0,
    input  wire signed [ 36:0] z0,
    output wire                busy,
    output wire                done,
    output wire                z_done,
    output wire signed [ 31:0] xn,
    output wire signed [ 31:0] yn,
    output wire signed [ 36:0] zn,
    output wire        [ 20:0] const2pi,   // round(2*pi * 2**CONST2PI_S), WMAN+5 bits (sin/cos to radians)
    output wire        [ 20:0] inv_tau,    // round(2**INVTAU_S / (2*pi)), WMAN+5 bits (atan2 turns scale)
    output wire        [ 20:0] kinv_mag    // round(2**KINV_S / gain), WMAN+5 bits (atan2 magnitude descale)
);
    localparam integer N    = 10;   // iterations (folded over the cycles selected by UNROLL100)
    localparam integer WX   = 32;
    localparam integer WZ   = 37;
    localparam integer XF   = 30;   // x/y fractional scale
    localparam integer WT   = 26;   // quadrant-local coordinate width used to derive ZF
    localparam integer ZF   = 34;   // angle (turns) fractional scale == WT + 2 + GUARD_ZF
    localparam integer WCONST2PI  = 21;
    localparam integer WINVTAU    = 21;
    localparam integer WKINV_MAG  = 21;
    localparam integer CONST2PI_S = 18;   // scale of const2pi (== WMAN+2)
    localparam integer INVTAU_S   = 23;   // scale of inv_tau  (== WMAN+7)
    localparam integer KINV_S     = 21;   // scale of kinv_mag (== WMAN+5)
    localparam signed [WX-1:0] KINV = 32'sd652033289;   // round(1/gain * 2**XF), the sin/cos seed

    // Geometry contract: the consuming RTL passes its locally-computed dimensions and constant scales here. If a
    // formula drifts away from zkf_trig.py, elaboration fails before any port truncation/extension can hide it.
    generate
        if ((EXPECT_WMAN      != 16) || (EXPECT_N  != N)  || (EXPECT_XF != XF) || (EXPECT_WX != WX) ||
            (EXPECT_WT        != WT) || (EXPECT_ZF != ZF) || (EXPECT_WZ != WZ) ||
            (EXPECT_WCONST2PI != WCONST2PI) || (EXPECT_CONST2PI_S != CONST2PI_S) ||
            (EXPECT_WINVTAU   != WINVTAU)   || (EXPECT_INVTAU_S   != INVTAU_S)   ||
            (EXPECT_WKINV_MAG != WKINV_MAG) || (EXPECT_KINV_S     != KINV_S)) begin : g_invalid_geometry_contract
            _zkf_invalid_cordic_geometry_contract u_invalid();
        end
    endgenerate

    assign const2pi = 21'd1647099;
    assign inv_tau  = 21'd1335088;
    assign kinv_mag = 21'd1273503;

    // arctan(2^-i)/(2*pi) in turns, scale 2**-ZF, packed L[0] in the low WZ bits.
    wire [N*WZ-1:0] LUT = {
        37'd5340347,   // atan(2^-9)/2pi
        37'd10680653,   // atan(2^-8)/2pi
        37'd21360980,   // atan(2^-7)/2pi
        37'd42719353,   // atan(2^-6)/2pi
        37'd85417861,   // atan(2^-5)/2pi
        37'd170669324,   // atan(2^-4)/2pi
        37'd340019024,   // atan(2^-3)/2pi
        37'd669835629,   // atan(2^-2)/2pi
        37'd1267733622,   // atan(2^-1)/2pi
        37'd2147483648   // atan(2^-0)/2pi
    };

    // Rotation seeds (1/gain, 0), so (xn, yn) = (cos z0, sin z0).
    wire                 rotate = (MODE == 0) || ((MODE == 2) && !vectoring);
    wire signed [WX-1:0] seed_x = rotate ? KINV       : x0;
    wire signed [WX-1:0] seed_y = rotate ? {WX{1'b0}} : y0;
    _zkf_cordic_core #(
        .N(N), .UNROLL100(UNROLL100), .PARALLEL(PARALLEL), .WX(WX), .WZ(WZ), .MODE(MODE)
    ) u_cordic (
        .clk(clk), .rst(rst), .start(start), .vectoring(vectoring),
        .x0(seed_x), .y0(seed_y), .z0(z0), .lut(LUT),
        .busy(busy), .done(done), .z_done(z_done), .xn(xn), .yn(yn), .zn(zn)
    );
endmodule

`default_nettype wire
