/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=53 (degree 5); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes C(f)=log2(1+f)/f by unsigned v (WFRAC+1 bits) and returns log2(m')=f*C(f) as
/// the unsigned magnitude l_mag = |f|*C(f) plus the sign l_neg (set when m>=sqrt(2)), at scale 2**-F2,
/// F2 = WFRAC+1+CF. The final f*C(f) multiply is fully unsigned (|f|*C(f)); the caller folds l_neg into its
/// reconstruction add/subtract. Register stages: two-stage ROM read + Horner + final multiply.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_log2_m53 #(
    parameter D                   = 5,
    parameter WSB                 = 1,
    parameter WMULTIPLIER         = 0,
    parameter STAGE_PRODUCT       = 0,
    parameter STAGE_PRODUCT_FINAL = STAGE_PRODUCT
) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire     [ 53-1:0] v,  // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire        [118:0] l_mag,  // |log2(m')| = |f|*C(f) magnitude at scale 2**-F2, F2 = WFRAC+1+CF
    output wire               l_neg   // sign of log2(m') (= sign of reduced f); 1 when m >= sqrt(2)
);
    generate if (D != 5) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 53;
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 9;
    localparam integer SEG_BASE = 106;
    localparam integer RW   = 44;
    localparam integer CW   = 68;
    localparam integer ACCW = 68;
    localparam integer NSEG = 363;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [K-1:0]    idx_raw = v[WMAN-1 -: K];
    wire [K-1:0]    idx_ofs = idx_raw - SEG_BASE[K-1:0];
    wire [WIDX-1:0] idx     = idx_ofs[WIDX-1:0];
    wire [RW-1:0]   w       = v[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[  0] = {68'hfffffffffffe96663, 68'h00000000026ec1fca, 68'hfffffffba6f3df72a, 68'h00000856609f92d7d, 68'hffedcc11fcbff155c, 68'h36a15298b852985c6};
        rom[  1] = {68'hfffffffffffe9b751, 68'h000000000267b2043, 68'hfffffffbb0a0ca565, 68'h0000084964059d1a9, 68'hffeddcb1bc8ead5df, 68'h368f26fcbf13545f7};
        rom[  2] = {68'hfffffffffffea06e6, 68'h000000000260bb55e, 68'hfffffffbba31a7e02, 68'h0000083c84483aca1, 68'hffeded37a01417feb, 68'h367d0bf392aeb6a77};
        rom[  3] = {68'hfffffffffffea5529, 68'h000000000259dd85f, 68'hfffffffbc3a6dc618, 68'h0000082fc113dabe3, 68'hffedfda3e0b594c0f, 68'h366b0163739c0d147};
        rom[  4] = {68'hfffffffffffeaa220, 68'h000000000253182ae, 68'hfffffffbcd00ca813, 68'h000008231a1616411, 68'hffee0df6b7329024c, 68'h36590732db64dbcd9};
        rom[  5] = {68'hfffffffffffeaedd3, 68'h00000000024c6add0, 68'hfffffffbd63fd3437, 68'h000008168efdac1b5, 68'hffee1e305ba6cf8e5, 68'h36471d487c000f018};
        rom[  6] = {68'hfffffffffffeb3846, 68'h000000000245d536c, 68'hfffffffbdf6456123, 68'h0000080a1f7a7bb8b, 68'hffee2e51058cb7634, 68'h3635438b3f2f77a8c};
        rom[  7] = {68'hfffffffffffeb8181, 68'h00000000023f56d47, 68'hfffffffbe86eb0c4a, 68'h000007fdcb3d8064e, 68'hffee3e58ebbf8789f, 68'h362379e245df89921};
        rom[  8] = {68'hfffffffffffebc989, 68'h000000000238ef545, 68'hfffffffbf15f3fa74, 68'h000007f191f8cc9f0, 68'hffee4e48447d8e792, 68'h3611c034e78951320};
        rom[  9] = {68'hfffffffffffec1063, 68'h0000000002329e566, 68'hfffffffbfa365d831, 68'h000007e5735f8584f, 68'hffee5e1f456a53060, 68'h3600166ab19697de3};
        rom[ 10] = {68'hfffffffffffec5616, 68'h00000000022c637cb, 68'hfffffffc02f463a54, 68'h000007d96f25de539, 68'hffee6dde2390b51eb, 68'h35ee7c6b66c82d48c};
        rom[ 11] = {68'hfffffffffffec9aa8, 68'h0000000002263e6ae, 68'hfffffffc0b99a9e60, 68'h000007cd850113fe8, 68'hffee7d851365059c4, 68'h35dcf21efe9e4d3e6};
        rom[ 12] = {68'hfffffffffffecde1d, 68'h0000000002202ec65, 68'hfffffffc142686aff, 68'h000007c1b4a768db8, 68'hffee8d1448c71557b, 68'h35cb776da4c318d47};
        rom[ 13] = {68'hfffffffffffed207b, 68'h00000000021a34364, 68'hfffffffc1c9b4f06b, 68'h000007b5fdd020644, 68'hffee9c8bf7043bad3, 68'h35ba0c3fb8771a5fa};
        rom[ 14] = {68'hfffffffffffed61c7, 68'h0000000002144e637, 68'hfffffffc24f8568df, 68'h000007aa60337b0b9, 68'hffeeabec50d954956, 68'h35a8b07dcbffcbb5c};
        rom[ 15] = {68'hfffffffffffeda207, 68'h00000000020e7cf85, 68'hfffffffc2d3def8fb, 68'h0000079edb8ab2275, 68'hffeebb358874b67e5, 68'h35976410a41816648};
        rom[ 16] = {68'hfffffffffffede13f, 68'h000000000208bfa0e, 68'hfffffffc356c6b031, 68'h000007936f8ff3ed4, 68'hffeeca67cf78200b2, 68'h358626e13762c5b28};
        rom[ 17] = {68'hfffffffffffee1f74, 68'h000000000203160ad, 68'hfffffffc3d8418926, 68'h000007881bfe5f83e, 68'hffeed98356fa9de1b, 68'h3574f8d8addee262d};
        rom[ 18] = {68'hfffffffffffee5cab, 68'h0000000001fd7fe54, 68'hfffffffc458546a16, 68'h0000077ce09201253, 68'hffeee8884f8a68ab8, 68'h3563d9e0605df05cd};
        rom[ 19] = {68'hfffffffffffee98e9, 68'h0000000001f7fce0d, 68'hfffffffc4d7042537, 68'h00000771bd07ce549, 68'hffeef776e92ebb6fd, 68'h3552c9e1d7fc067ee};
        rom[ 20] = {68'hfffffffffffeed432, 68'h0000000001f28caf8, 68'hfffffffc554557915, 68'h00000766b11da225d, 68'hffef064f5369a26a2, 68'h3541c8c6cd99b905f};
        rom[ 21] = {68'hfffffffffffef0e8b, 68'h0000000001ed2f050, 68'hfffffffc5d04d10f2, 68'h0000075bbc923996f, 68'hffef1511bd39c2827, 68'h3530d6792957cf19f};
        rom[ 22] = {68'hfffffffffffef47f8, 68'h0000000001e7e3963, 68'hfffffffc64aef851e, 68'h00000750df252ff9f, 68'hffef23be551c1987e, 68'h351ff2e30214bc302};
        rom[ 23] = {68'hfffffffffffef807e, 68'h0000000001e2aa196, 68'hfffffffc6c4415b50, 68'h000007461896fb705, 68'hffef3255490db7522, 68'h350f1dee9cebd6198};
        rom[ 24] = {68'hfffffffffffefb820, 68'h0000000001dd82463, 68'hfffffffc73c470702, 68'h0000073b68a8e976b, 68'hffef40d6c68d6fe8d, 68'h34fe57866cb640b22};
        rom[ 25] = {68'hfffffffffffefeee3, 68'h0000000001d86bd5b, 68'hfffffffc7b304e9c0, 68'h00000730cf1d1b80f, 68'hffef4f42fa9d86d38, 68'h34ed9f95118d8849e};
        rom[ 26] = {68'hffffffffffff024cc, 68'h0000000001d366822, 68'hfffffffc8287f537e, 68'h000007264bb683a5c, 68'hffef5d9a11c553b13, 68'h34dcf605584fe3fe3};
        rom[ 27] = {68'hffffffffffff059dd, 68'h0000000001ce72070, 68'hfffffffc89cba82ed, 68'h0000071bde38e15a1, 68'hffef6bdc3812e0365, 68'h34cc5ac23a26195bd};
        rom[ 28] = {68'hffffffffffff08e1b, 68'h0000000001c98e213, 68'hfffffffc90fbaa5c7, 68'h000007118668be3b5, 68'hffef7a09991c7fb1b, 68'h34bbcdb6dc0afabfd};
        rom[ 29] = {68'hffffffffffff0c189, 68'h0000000001c4ba8ea, 68'hfffffffc98183d91e, 68'h00000707440b6ae93, 68'hffef8822600260347, 68'h34ab4ece8e547a0c3};
        rom[ 30] = {68'hffffffffffff0f42c, 68'h0000000001bff70e8, 68'hfffffffc9f21a29ac, 68'h000006fd16e6fbed3, 68'hffef9626b770157b8, 68'h349addf4cc3e4962f};
        rom[ 31] = {68'hffffffffffff12607, 68'h0000000001bb43613, 68'hfffffffca6181941b, 68'h000006f2fec246b0d, 68'hffefa416c99e1db75, 68'h348a7b153b7603b7b};
        rom[ 32] = {68'hffffffffffff1571d, 68'h0000000001b69f483, 68'hfffffffcacfbe054f, 68'h000006e8fb64de822, 68'hffefb1f2c053604e3, 68'h347a261baba8d7232};
        rom[ 33] = {68'hffffffffffff18773, 68'h0000000001b20a862, 68'hfffffffcb3cd35ab2, 68'h000006df0c9711a52, 68'hffefbfbac4e6a6b44, 68'h3469def41612ab027};
        rom[ 34] = {68'hffffffffffff1b70b, 68'h0000000001ad84dea, 68'hfffffffcba8c56276, 68'h000006d53221e6736, 68'hffefcd6f00400f750, 68'h3459a58a9d0ebc044};
        rom[ 35] = {68'hffffffffffff1e5e8, 68'h0000000001a90e168, 68'hfffffffcc1397dbdd, 68'h000006cb6bcf18886, 68'hffefdb0f9ada7b886, 68'h344979cb8ba9a8634};
        rom[ 36] = {68'hffffffffffff2140f, 68'h0000000001a4a5f3a, 68'hfffffffcc7d4e777d, 68'h000006c1b96915faa, 68'hffefe89cbcc4f60dd, 68'h34395ba35534e6a6d};
        rom[ 37] = {68'hffffffffffff24183, 68'h0000000001a04c3cd, 68'hfffffffcce5ecd781, 68'h000006b81abafca1f, 68'hffeff6168da416864, 68'h34294afe94dba15ba};
        rom[ 38] = {68'hffffffffffff26e45, 68'h00000000019c00ba0, 68'hfffffffcd4d768fed, 68'h000006ae8f9097696, 68'hfff0037d34b35da6f, 68'h341947ca0d38f250f};
        rom[ 39] = {68'hffffffffffff29a5b, 68'h000000000197c3340, 68'hfffffffcdb3ef26da, 68'h000006a517b65badc, 68'hfff010d0d8c68cdc0, 68'h340951f2a7ef77fe6};
        rom[ 40] = {68'hffffffffffff2c5c6, 68'h00000000019393749, 68'hfffffffce195a14ba, 68'h0000069bb2f966a7f, 68'hfff01e11a04af894e, 68'h33f9696575423fcf6};
        rom[ 41] = {68'hffffffffffff2f08a, 68'h00000000018f7146a, 68'hfffffffce7dbac48f, 68'h0000069261277ae2a, 68'hfff02b3fb148d56fc, 68'h33e98e0fabaf0028c};
        rom[ 42] = {68'hffffffffffff31aa9, 68'h00000000018b5c75d, 68'hfffffffcee114942c, 68'h00000689220efdbbf, 68'hfff0385b3164805d5, 68'h33d9bfdea7899d135};
        rom[ 43] = {68'hffffffffffff34427, 68'h00000000018754ceb, 68'hfffffffcf436ad470, 68'h0000067ff57ef4f15, 68'hfff0456445dfc1d15, 68'h33c9febfea98f28fb};
        rom[ 44] = {68'hffffffffffff36d06, 68'h0000000001835a1ee, 68'hfffffffcfa4c0c97c, 68'h00000676db4704379, 68'hfff0525b139b0c17b, 68'h33ba4aa11bb4dfaa8};
        rom[ 45] = {68'hffffffffffff39549, 68'h00000000017f6c34b, 68'hfffffffd00519aaef, 68'h0000066dd3376adc7, 68'hfff05f3fbf16b4e2f, 68'h33aaa37006658d80b};
        rom[ 46] = {68'hffffffffffff3bcf3, 68'h00000000017b8adf7, 68'hfffffffd06478a41c, 68'h00000664dd210173b, 68'hfff06c126c742a29b, 68'h339b091a9a83ed785};
        rom[ 47] = {68'hffffffffffff3e406, 68'h000000000177b5ef2, 68'hfffffffd0c2e0d441, 68'h0000065bf8d5378de, 68'hfff078d33f7722674, 68'h338b7b8eebdb6a061};
        rom[ 48] = {68'hffffffffffff40a85, 68'h000000000173ed34c, 68'hfffffffd120554ebe, 68'h00000653262611797, 68'hfff085825b86c8550, 68'h337bfabb31ccc56ed};
        rom[ 49] = {68'hffffffffffff43073, 68'h00000000017030821, 68'hfffffffd17cd91b46, 68'h0000064a64e6260db, 68'hfff0921fe3aee22f7, 68'h336c868dc6f222064};
        rom[ 50] = {68'hffffffffffff455d1, 68'h00000000016c7fa98, 68'hfffffffd1d86f3614, 68'h00000641b4e89c7f9, 68'hfff09eabfaa0f49b2, 68'h335d1ef528c42f810};
        rom[ 51] = {68'hffffffffffff47aa3, 68'h000000000168da7e7, 68'hfffffffd2331a901e, 68'h0000063916012a3fc, 68'hfff0ab26c2b5613c6, 68'h334dc3dff74079038};
        rom[ 52] = {68'hffffffffffff49eeb, 68'h00000000016540d4e, 68'hfffffffd28cde0f45, 68'h00000630880410e29, 68'hfff0b7905dec81152, 68'h333e753cf490cfaa3};
        rom[ 53] = {68'hffffffffffff4c2ab, 68'h000000000161b281b, 68'hfffffffd2e5bc8e87, 68'h000006280ac61c103, 68'hfff0c3e8edefbabae, 68'h332f32fb04b3cd59c};
        rom[ 54] = {68'hffffffffffff4e5e5, 68'h00000000015e2f5a6, 68'hfffffffd33db8de2c, 68'h0000061f9e1c9f7ed, 68'hfff0d030941294774, 68'h331ffd092d266bb9a};
        rom[ 55] = {68'hffffffffffff5089c, 68'h00000000015ab7353, 68'hfffffffd394d5c3f7, 68'h0000061741dd74f4e, 68'hfff0dc677153c264b, 68'h3310d356948eab4b3};
        rom[ 56] = {68'hffffffffffff52ad2, 68'h00000000015749e93, 68'hfffffffd3eb15fb52, 68'h0000060ef5defa548, 68'hfff0e88da65e3098d, 68'h3301b5d2826746a32};
        rom[ 57] = {68'hffffffffffff54c89, 68'h000000000153e74df, 68'hfffffffd4407c357d, 68'h00000606b9f80faec, 68'hfff0f4a3538a096df, 68'h32f2a46c5eac6ddbf};
        rom[ 58] = {68'hffffffffffff56dc3, 68'h0000000001508f3bd, 68'hfffffffd4950b19b5, 68'h000005fe8e00155ff, 68'hfff100a898ddb7fbb, 68'h32e39f13b1898666f};
        rom[ 59] = {68'hffffffffffff58e83, 68'h00000000014d418be, 68'hfffffffd4e8c54566, 68'h000005f671ceea336, 68'hfff10c9d960ee6d00, 68'h32d4a5b82307eb75f};
        rom[ 60] = {68'hffffffffffff5aeca, 68'h000000000149fe17b, 68'hfffffffd53bad4c4d, 68'h000005ee653ce98fd, 68'hfff118826a837af84, 68'h32c5b8497abeab43c};
        rom[ 61] = {68'hffffffffffff5ce9a, 68'h000000000146c4b9b, 68'hfffffffd58dc5b8aa, 68'h000005e66822e9aaf, 68'hfff1245735528b6a2, 68'h32b6d6b79f833d94e};
        rom[ 62] = {68'hffffffffffff5edf6, 68'h000000000143954ca, 68'hfffffffd5df110b62, 68'h000005de7a5a39c56, 68'hfff1301c154554dc8, 68'h32a800f2971b2fd7d};
        rom[ 63] = {68'hffffffffffff60cde, 68'h0000000001406fac3, 68'hfffffffd62f91bc2b, 68'h000005d69bbca06d9, 68'hfff13bd128d82a1ed, 68'h329936ea85eec35be};
        rom[ 64] = {68'hffffffffffff62b57, 68'h00000000013d53b48, 68'hfffffffd67f4a39af, 68'h000005cecc2459ca4, 68'hfff147768e3b60fe0, 68'h328a788faebc7a250};
        rom[ 65] = {68'hffffffffffff64960, 68'h00000000013a41425, 68'hfffffffd6ce3ce9b8, 68'h000005c70b6c15ecc, 68'hfff1530c63543bc63, 68'h327bc5d2724d8ef22};
        rom[ 66] = {68'hffffffffffff666fc, 68'h0000000001373832f, 68'hfffffffd71c6c294f, 68'h000005bf596ef7296, 68'hfff15e92c5bdcf6ef, 68'h326d1ea34f2b5518e};
        rom[ 67] = {68'hffffffffffff6842c, 68'h00000000013438644, 68'hfffffffd769da4ce7, 68'h000005b7b60890779, 68'hfff16a09d2c9e6807, 68'h325e82f2e1557ce8c};
        rom[ 68] = {68'hffffffffffff6a0f4, 68'h00000000013141b4c, 68'hfffffffd7b689a07e, 68'h000005b02114e3d8b, 68'hfff17571a781e0bf4, 68'h324ff2b1e1f939564};
        rom[ 69] = {68'hffffffffffff6bd53, 68'h00000000012e54037, 68'hfffffffd8027c67c0, 68'h000005a89a7060c58, 68'hfff180ca60a78facb, 68'h32416dd1272943ba0};
        rom[ 70] = {68'hffffffffffff6d94c, 68'h00000000012b6f2fe, 68'hfffffffd84db4de2c, 68'h000005a121f7e2a27, 68'hfff18c141ab60fe8c, 68'h3232f441a396ba80e};
        rom[ 71] = {68'hffffffffffff6f4e1, 68'h000000000128931a2, 68'hfffffffd898353735, 68'h00000599b788af39f, 68'hfff1974ef1e29f826, 68'h322485f4664ad7b37};
        rom[ 72] = {68'hffffffffffff71013, 68'h000000000125bfa2d, 68'hfffffffd8e1ff9e63, 68'h000005925b00753d9, 68'hfff1a27b021d71442, 68'h321622da9a617c4b4};
        rom[ 73] = {68'hffffffffffff72ae3, 68'h000000000122f4ab1, 68'hfffffffd92b163777, 68'h0000058b0c3d4acd3, 68'hfff1ad9867127d080, 68'h3207cae586c48d572};
        rom[ 74] = {68'hffffffffffff74554, 68'h00000000012032147, 68'hfffffffd9737b1e88, 68'h00000583cb1dac045, 68'hfff1b8a73c2a4d210, 68'h31f97e068de81ffd1};
        rom[ 75] = {68'hffffffffffff75f67, 68'h00000000011d77c11, 68'hfffffffd9bb306824, 68'h0000057c9780798d7, 68'hfff1c3a79c8ac8e41, 68'h31eb3c2f2d8771749};
        rom[ 76] = {68'hffffffffffff7791d, 68'h00000000011ac5939, 68'hfffffffda0238216e, 68'h000005757144f73b3, 68'hfff1ce99a317fc5ed, 68'h31dd0550fe62a81fc};
        rom[ 77] = {68'hffffffffffff79278, 68'h0000000001181b6ef, 68'hfffffffda48945040, 68'h0000056e584acaa7b, 68'hfff1d97d6a74dd45f, 68'h31ced95db3fd5af60};
        rom[ 78] = {68'hffffffffffff7ab7a, 68'h0000000001157936c, 68'hfffffffda8e46f345, 68'h000005674c71f9d8c, 68'hfff1e4530d040d274, 68'h31c0b8471c5ddc7e1};
        rom[ 79] = {68'hffffffffffff7c423, 68'h000000000112decf0, 68'hfffffffdad352021a, 68'h000005604d9ae9eab, 68'hfff1ef1aa4e898eb7, 68'h31b2a1ff1fcd46a0d};
        rom[ 80] = {68'hffffffffffff7dc75, 68'h0000000001104c1c2, 68'hfffffffdb17b76d69, 68'h000005595ba65dbfe, 68'hfff1f9d44c06b5b15, 68'h31a49677c09844a9d};
        rom[ 81] = {68'hffffffffffff7f472, 68'h00000000010dc102f, 68'hfffffffdb5b791f04, 68'h00000552767574b5d, 68'hfff204801c047b0e4, 68'h319695a31ad098d4f};
        rom[ 82] = {68'hffffffffffff80c1b, 68'h00000000010b3d68c, 68'hfffffffdb9e98fa05, 68'h0000054b9de9a95ff, 68'hfff20f1e2e4a9abe9, 68'h31889f73640f5ad36};
        rom[ 83] = {68'hffffffffffff82372, 68'h000000000108c1336, 68'hfffffffdbe118dae6, 68'h00000544d1e4d046f, 68'hfff219ae9c0515cf7, 68'h317ab3daeb37ecbcb};
        rom[ 84] = {68'hffffffffffff83a76, 68'h0000000001064c48f, 68'hfffffffdc22fa979c, 68'h0000053e124916ad9, 68'hfff224317e23ef4dc, 68'h316cd2cc183ba3ebf};
        rom[ 85] = {68'hffffffffffff8512b, 68'h000000000103de8fe, 68'hfffffffdc643fffb5, 68'h000005375ef9015a9, 68'hfff22ea6ed5bdc831, 68'h315efc396bde23515};
        rom[ 86] = {68'hffffffffffff86791, 68'h00000000010177ef5, 68'hfffffffdca4eadc6d, 68'h00000530b7d76b670, 68'hfff2390f0226f2cb5, 68'h315130157f7a64ccd};
        rom[ 87] = {68'hffffffffffff87da9, 68'h0000000000ff184e8, 68'hfffffffdce4fcf0cc, 68'h0000052a1cc785121, 68'hfff24369d4c5530c6, 68'h31436e5304c86f2e5};
        rom[ 88] = {68'hffffffffffff89375, 68'h0000000000fcbf953, 68'hfffffffdd2477f9bb, 68'h000005238dacd2990, 68'hfff24db77d3dd2d98, 68'h3135b6e4c5a3b6828};
        rom[ 89] = {68'hffffffffffff8a8f5, 68'h0000000000fa6dab8, 68'hfffffffdd635dae1f, 68'h0000051d0a6b2b143, 68'hfff257f8135ea34bb, 68'h312809bda3d2245d2};
        rom[ 90] = {68'hffffffffffff8be2c, 68'h0000000000f82279f, 68'hfffffffdda1afbef2, 68'h0000051692e6b7588, 68'hfff2622baebdf5988, 68'h311a66d098cbc5d9d};
        rom[ 91] = {68'hffffffffffff8d319, 68'h0000000000f5dde96, 68'hfffffffdddf6fd758, 68'h000005102703f0dd1, 68'hfff26c5266ba9d702, 68'h310cce10b5831d169};
        rom[ 92] = {68'hffffffffffff8e7bf, 68'h0000000000f39fe31, 68'hfffffffde1c9f9cb8, 68'h00000509c6a7a0a5e, 68'hfff2766c527cb12c0, 68'h30ff3f71222e13f43};
        rom[ 93] = {68'hffffffffffff8fc1e, 68'h0000000000f168508, 68'hfffffffde5940aed2, 68'h0000050371b6de323, 68'hfff2807988f627d5d, 68'h30f1bae51e0f8df08};
        rom[ 94] = {68'hffffffffffff91038, 68'h0000000000ef371ba, 68'hfffffffde9554a7d8, 68'h000004fd28170e6fa, 68'hfff28a7a20e37510c, 68'h30e4405fff4196f81};
        rom[ 95] = {68'hffffffffffff9240d, 68'h0000000000ed0c2ec, 68'hfffffffded0dd1c80, 68'h000004f6e9ade2b11, 68'hfff2946e30cc22ec3, 68'h30d6cfd532802d150};
        rom[ 96] = {68'hffffffffffff9379f, 68'h0000000000eae7748, 68'hfffffffdf0bdb9c1d, 68'h000004f0b66157aa0, 68'hfff29e55cf0369a91, 68'h30c969383af4a2e9d};
        rom[ 97] = {68'hffffffffffff94aee, 68'h0000000000e8c8d7b, 68'hfffffffdf4651b0b2, 68'h000004ea8e17b46da, 68'hfff2a83111a8c5798, 68'h30bc0c7cb20198ed1};
        rom[ 98] = {68'hffffffffffff95dfc, 68'h0000000000e6b043b, 68'hfffffffdf8040df08, 68'h000004e470b789722, 68'hfff2b2000ea88a42d, 68'h30aeb996470f8b65e};
        rom[ 99] = {68'hffffffffffff970ca, 68'h0000000000e49da41, 68'hfffffffdfb9aaa6c5, 68'h000004de5e27af97a, 68'hfff2bbc2dbbc7569b, 68'h30a17078bf59f32ec};
        rom[100] = {68'hffffffffffff98358, 68'h0000000000e290e4a, 68'hfffffffdff290827c, 68'h000004d8564f47332, 68'hfff2c5798e6c3db0a, 68'h30943117f5bcf74d1};
        rom[101] = {68'hffffffffffff995a8, 68'h0000000000e089f1a, 68'hfffffffe02af3e7c1, 68'h000004d25915b71d3, 68'hfff2cf243c0e212f7, 68'h3086fb67da83ad72a};
        rom[102] = {68'hffffffffffff9a7ba, 68'h0000000000de88b79, 68'hfffffffe062d64742, 68'h000004cc6662abc45, 68'hfff2d8c2f9c7716c7, 68'h3079cf5c7336e7878};
        rom[103] = {68'hffffffffffff9b990, 68'h0000000000dc8d234, 68'hfffffffe09a390cd3, 68'h000004c67e1e16429, 68'hfff2e255dc8d1d9d2, 68'h306cace9da6c8c5f9};
        rom[104] = {68'hffffffffffff9cb2a, 68'h0000000000da9721b, 68'hfffffffe0d11d9f86, 68'h000004c0a0302b77b, 68'hfff2ebdcf9243b170, 68'h305f94043f9779c8a};
        rom[105] = {68'hffffffffffff9dc8a, 68'h0000000000d8a6a05, 68'hfffffffe1078561bb, 68'h000004bacc8163258, 68'hfff2f55864228bf6a, 68'h3052849fe6d7ee240};
        rom[106] = {68'hffffffffffff9edaf, 68'h0000000000d6bb8cd, 68'hfffffffe13d71b133, 68'h000004b502fa7710e, 68'hfff2fec831ef04044, 68'h30457eb128cc77c4c};
        rom[107] = {68'hffffffffffff9fe9c, 68'h0000000000d4d5d51, 68'hfffffffe172e3e722, 68'h000004af438462254, 68'hfff3082c76c24bdcd, 68'h3038822c72636854e};
        rom[108] = {68'hffffffffffffa0f51, 68'h0000000000d2f5675, 68'hfffffffe1a7dd5841, 68'h000004a98e085f9bf, 68'hfff3118546a742660, 68'h302b8f0644acca87e};
        rom[109] = {68'hffffffffffffa1fce, 68'h0000000000d11a320, 68'hfffffffe1dc5f54dc, 68'h000004a3e26fea26b, 68'hfff31ad2b57b7c93a, 68'h301ea53334acd86a4};
        rom[110] = {68'hffffffffffffa3015, 68'h0000000000cf4423d, 68'hfffffffe2106b28e9, 68'h0000049e40a4bb1ce, 68'hfff32414d6efc3859, 68'h3011c4a7eb2ef0a12};
        rom[111] = {68'hffffffffffffa4027, 68'h0000000000cd732bd, 68'hfffffffe244021c13, 68'h00000498a890c9ad0, 68'hfff32d4bbe8891040, 68'h3004ed59249908f75};
        rom[112] = {68'hffffffffffffa5003, 68'h0000000000cba7394, 68'hfffffffe2772571cd, 68'h000004931a1e4a100, 68'hfff336777f9e8a600, 68'h2ff81f3bb0bf9c97c};
        rom[113] = {68'hffffffffffffa5fac, 68'h0000000000c9e03ba, 68'hfffffffe2a9d66963, 68'h0000048d9537acc07, 68'hfff33f982d5ef9bfa, 68'h2feb5a4472ba145e1};
        rom[114] = {68'hffffffffffffa6f21, 68'h0000000000c81e22a, 68'hfffffffe2dc163e08, 68'h0000048819c79db48, 68'hfff348addacc45da5, 68'h2fde9e6860b7a7aab};
        rom[115] = {68'hffffffffffffa7e64, 68'h0000000000c660de5, 68'hfffffffe30de626e5, 68'h00000482a7b9039ae, 68'hfff351b89abe682cb, 68'h2fd1eb9c83d4b42ec};
        rom[116] = {68'hffffffffffffa8d75, 68'h0000000000c4a85ed, 68'hfffffffe33f47572c, 68'h0000047d3ef6ff1a6, 68'hfff35ab87fe361a8b, 68'h2fc541d5f7f08b293};
        rom[117] = {68'hffffffffffffa9c55, 68'h0000000000c2f494b, 68'hfffffffe3703afe21, 68'h00000477df6cea14e, 68'hfff363ad9cbfade85, 68'h2fb8a109eb83b2952};
        rom[118] = {68'hffffffffffffaab05, 68'h0000000000c145708, 68'hfffffffe3a0c24731, 68'h00000472890656ec9, 68'hfff36c9803aeb4e86, 68'h2fac092d9f7698ce7};
        rom[119] = {68'hffffffffffffab985, 68'h0000000000bf9ae34, 68'hfffffffe3d0de59f9, 68'h0000046d3baf0fcc1, 68'hfff37577c6e33b510, 68'h2f9f7a3666f8b9374};
        rom[120] = {68'hffffffffffffac7d7, 68'h0000000000bdf4de1, 68'hfffffffe400905a57, 68'h00000467f75315f1a, 68'hfff37e4cf867d1511, 68'h2f92f419a758306f7};
        rom[121] = {68'hffffffffffffad5fa, 68'h0000000000bc53524, 68'hfffffffe42fd9687a, 68'h00000462bbdea0fc7, 68'hfff38717aa1f40129, 68'h2f8676ccd7d9beb31};
        rom[122] = {68'hffffffffffffae3ef, 68'h0000000000bab6316, 68'hfffffffe45ebaa0ee, 68'h0000045d893e1e3cf, 68'hfff38fd7edc4f5cbf, 68'h2f7a0245819136fb8};
        rom[123] = {68'hffffffffffffaf1b8, 68'h0000000000b91d6d4, 68'hfffffffe48d351ca8, 68'h000004585f5e30077, 68'hfff3988dd4ed70753, 68'h2f6d96793f3a59838};
        rom[124] = {68'hffffffffffffaff54, 68'h0000000000b788f7d, 68'hfffffffe4bb49f118, 68'h000004533e2bad098, 68'hfff3a1397106a7248, 68'h2f61335dbd1218536};
        rom[125] = {68'hffffffffffffb0cc5, 68'h0000000000b5f8c35, 68'hfffffffe4e8fa3030, 68'h0000044e25939fa1e, 68'hfff3a9dad35872183, 68'h2f54d8e8b8b044800};
        rom[126] = {68'hffffffffffffb1a0b, 68'h0000000000b46cc21, 68'hfffffffe51646e878, 68'h000004491583453a5, 68'hfff3b2720d04f1726, 68'h2f48871000e1a2ccb};
        rom[127] = {68'hffffffffffffb2727, 68'h0000000000b2e4e6b, 68'hfffffffe543312515, 68'h000004440de80da49, 68'hfff3baff2f08f2abe, 68'h2f3c3dc975826663b};
        rom[128] = {68'hffffffffffffb3419, 68'h0000000000b161240, 68'hfffffffe56fb9edd6, 68'h0000043f0eaf9a795, 68'hfff3c3824a3c54c26, 68'h2f2ffd0b0759105ea};
        rom[129] = {68'hffffffffffffb40e2, 68'h0000000000afe16ce, 68'hfffffffe59be24746, 68'h0000043a17c7be794, 68'hfff3cbfb6f526b277, 68'h2f23c4cab7f1b2dd4};
        rom[130] = {68'hffffffffffffb4d82, 68'h0000000000ae65b48, 68'hfffffffe5c7ab32b0, 68'h00000435291e7cf10, 68'hfff3d46aaeda5f739, 68'h2f1794fe9979966d5};
        rom[131] = {68'hffffffffffffb59fb, 68'h0000000000acedee5, 68'hfffffffe5f315ae31, 68'h0000043042a2091ed, 68'hfff3dcd0193f91e3d, 68'h2f0b6d9cce9b40899};
        rom[132] = {68'hffffffffffffb664c, 68'h0000000000ab7a0db, 68'hfffffffe61e22b4c0, 68'h0000042b6440c59ab, 68'hfff3e52bbec9f8a47, 68'h2eff4e9b8a5ad9fd3};
        rom[133] = {68'hffffffffffffb7276, 68'h0000000000aa0a067, 68'hfffffffe648d33e3e, 68'h000004268de943c09, 68'hfff3ed7daf9e7deeb, 68'h2ef337f10ff2f3fad};
        rom[134] = {68'hffffffffffffb7e7a, 68'h0000000000a89dcc6, 68'hfffffffe673283f7c, 68'h00000421bf8a431ce, 68'hfff3f5c5fbbf5cfc7, 68'h2ee72993b2b1aabbc};
        rom[135] = {68'hffffffffffffb8a59, 68'h0000000000a735539, 68'hfffffffe69d22aa48, 68'h0000041cf912b0daf, 68'hfff3fe04b30c7dd75, 68'h2edb2379d5d62480d};
        rom[136] = {68'hffffffffffffb9612, 68'h0000000000a5d0904, 68'hfffffffe6c6c36d7c, 68'h000004183a71a7358, 68'hfff40639e543d006e, 68'h2ecf2599ec6e6bd0a};
        rom[137] = {68'hffffffffffffba1a7, 68'h0000000000a46f76d, 68'hfffffffe6f00b7501, 68'h0000041383966ce9a, 68'hfff40e65a201a421f, 68'h2ec32fea7935a3d63};
        rom[138] = {68'hffffffffffffbad17, 68'h0000000000a311fbc, 68'hfffffffe718fba9e3, 68'h0000040ed47074aaf, 68'hfff41687f8c10446d, 68'h2eb742620e7295c30};
        rom[139] = {68'hffffffffffffbb864, 68'h0000000000a1b813e, 68'hfffffffe74194f251, 68'h0000040a2cef5c9a8, 68'hfff41ea0f8dc0b7f8, 68'h2eab5cf74dd696202};
        rom[140] = {68'hffffffffffffbc38e, 68'h0000000000a061b3f, 68'hfffffffe769d831b1, 68'h000004058d02edbf5, 68'hfff426b0b18c3c146, 68'h2e9f7fa0e85cc0f94};
        rom[141] = {68'hffffffffffffbce95, 68'h00000000009f0ed11, 68'hfffffffe791c648a5, 68'h00000400f49b1b80d, 68'hfff42eb731ead4d25, 68'h2e93aa559e298bd4d};
        rom[142] = {68'hffffffffffffbd97a, 68'h00000000009dbf606, 68'hfffffffe7b9601513, 68'h000003fc63a803232, 68'hfff436b488f12547a, 68'h2e87dd0c3e6aac6ca};
        rom[143] = {68'hffffffffffffbe43d, 68'h00000000009c73575, 68'hfffffffe7e0a67235, 68'h000003f7da19eb455, 68'hfff43ea8c578e0fb2, 68'h2e7c17bba7375320a};
        rom[144] = {68'hffffffffffffbeedf, 68'h00000000009b2aab3, 68'hfffffffe8079a389f, 68'h000003f357e143615, 68'hfff44693f63c71a1e, 68'h2e705a5ac570b81f7};
        rom[145] = {68'hffffffffffffbf961, 68'h000000000099e551d, 68'hfffffffe82e3c3e46, 68'h000003eedceea34e0, 68'hfff44e7629d74856d, 68'h2e64a4e094a2fa45b};
        rom[146] = {68'hffffffffffffc03c2, 68'h000000000098a340d, 68'hfffffffe8548d568e, 68'h000003ea6932cac27, 68'hfff4564f6ec62dd74, 68'h2e58f7441ee64eb6b};
        rom[147] = {68'hffffffffffffc0e03, 68'h000000000097646e4, 68'hfffffffe87a8e5253, 68'h000003e5fc9ea0db7, 68'hfff45e1fd36791c8a, 68'h2e4d517c7cc080363};
        rom[148] = {68'hffffffffffffc1825, 68'h00000000009628d01, 68'hfffffffe8a03fffec, 68'h000003e1972333a27, 68'hfff465e765fbd90ad, 68'h2e41b380d506bd4de};
        rom[149] = {68'hffffffffffffc2228, 68'h000000000094f05c8, 68'hfffffffe8c5a32b3b, 68'h000003dd38b1b7966, 68'hfff46da634a5ab19a, 68'h2e361d485cbfb44c4};
        rom[150] = {68'hffffffffffffc2c0d, 68'h000000000093bb09e, 68'hfffffffe8eab89db4, 68'h000003d8e13b8735c, 68'hfff4755c4d6a3e81e, 68'h2e2a8eca5705fc2ef};
        rom[151] = {68'hffffffffffffc35d3, 68'h00000000009288ceb, 68'hfffffffe90f811e61, 68'h000003d490b2228ae, 68'hfff47d09be31a46c6, 68'h2e1f07fe14eac98c7};
        rom[152] = {68'hffffffffffffc3f7c, 68'h00000000009159a18, 68'hfffffffe933fd71f2, 68'h000003d047072eb97, 68'hfff484ae94c71342f, 68'h2e1388daf558ee95b};
        rom[153] = {68'hffffffffffffc4908, 68'h0000000000902d791, 68'hfffffffe9582e5abe, 68'h000003cc042c758d8, 68'hfff48c4aded93071c, 68'h2e08115864f8254a7};
        rom[154] = {68'hffffffffffffc5277, 68'h00000000008f044c4, 68'hfffffffe97c1498d0, 68'h000003c7c813e50c7, 68'hfff493dea9fa5948c, 68'h2dfca16dde10a2ff2};
        rom[155] = {68'hffffffffffffc5bc9, 68'h00000000008dde11f, 68'hfffffffe99fb0e9f0, 68'h000003c392af8f070, 68'hfff49b6a03a0eb006, 68'h2df13912e86ef454f};
        rom[156] = {68'hffffffffffffc64ff, 68'h00000000008cbac16, 68'hfffffffe9c30409a4, 68'h000003bf63f1a8ad4, 68'hfff4a2ecf92789e3a, 68'h2de5d83f194820c9e};
        rom[157] = {68'hffffffffffffc6e19, 68'h00000000008b9a51b, 68'hfffffffe9e60eb140, 68'h000003bb3bcc8a239, 68'hfff4aa6797cd67a3b, 68'h2dda7eea131e15065};
        rom[158] = {68'hffffffffffffc7718, 68'h00000000008a7cba4, 68'hfffffffea08d197e9, 68'h000003b71a32ae19a, 68'hfff4b1d9ecb688d73, 68'h2dcf2d0b85a45314e};
        rom[159] = {68'hffffffffffffc7ffd, 68'h00000000008961f29, 68'hfffffffea2b4d729e, 68'h000003b2ff16b1625, 68'hfff4b94404ec09a88, 68'h2dc3e29b2da4e7b01};
        rom[160] = {68'hffffffffffffc88c6, 68'h00000000008849f22, 68'hfffffffea4d82f440, 68'h000003aeea6b528d4, 68'hfff4c0a5ed5c61b59, 68'h2db89f90d4e5a3d71};
        rom[161] = {68'hffffffffffffc9175, 68'h00000000008734b0b, 68'hfffffffea6f72cd97, 68'h000003aadc2371820, 68'hfff4c7ffb2dba7242, 68'h2dad63e4520d99dc6};
        rom[162] = {68'hffffffffffffc9a0b, 68'h00000000008622261, 68'hfffffffea911dad5d, 68'h000003a6d4320f1c1, 68'hfff4cf516223d0ed9, 68'h2da22f8d888add240};
        rom[163] = {68'hffffffffffffca287, 68'h000000000085124a2, 68'hfffffffeab2844041, 68'h000003a2d28a4cc8d, 68'hfff4d69b07d4f8647, 68'h2d970284687883ca4};
        rom[164] = {68'hffffffffffffcaaea, 68'h0000000000840514e, 68'hfffffffead3a730f2, 68'h0000039ed71f6c262, 68'hfff4dddcb07599f67, 68'h2d8bdcc0ee84e96e1};
        rom[165] = {68'hffffffffffffcb334, 68'h000000000082fa7e9, 68'hfffffffeaf4872823, 68'h0000039ae1e4cea31, 68'hfff4e5166872d52e3, 68'h2d80be3b23d8325d3};
        rom[166] = {68'hffffffffffffcbb65, 68'h000000000081f27f5, 68'hfffffffeb1524cc92, 68'h00000396f2cdf5213, 68'hfff4ec483c20abf6b, 68'h2d75a6eb1dfb0e627};
        rom[167] = {68'hffffffffffffcc37e, 68'h000000000080ed0f8, 68'hfffffffeb3580c311, 68'h0000039309ce7f979, 68'hfff4f37237ba4122b, 68'h2d6a96c8febdba790};
        rom[168] = {68'hffffffffffffccb80, 68'h00000000007fea279, 68'hfffffffeb559bae8b, 68'h0000038f26da2cb6d, 68'hfff4fa946762163c1, 68'h2d5f8dccf41f40abc};
        rom[169] = {68'hffffffffffffcd36a, 68'h00000000007ee9c01, 68'hfffffffeb7576300b, 68'h0000038b49e4d98e4, 68'hfff501aed722489b7, 68'h2d548bef3834f566e};
        rom[170] = {68'hffffffffffffcdb3c, 68'h00000000007debd1a, 68'hfffffffeb9510e6c0, 68'h0000038772e28132d, 68'hfff508c192eccdccc, 68'h2d49912811123187f};
        rom[171] = {68'hffffffffffffce2f8, 68'h00000000007cf0551, 68'hfffffffebb46c7007, 68'h00000383a1c73c667, 68'hfff50fcca69baf413, 68'h2d3e9d6fd0b04878e};
        rom[172] = {68'hffffffffffffcea9d, 68'h00000000007bf7432, 68'hfffffffebd3896770, 68'h0000037fd68741413, 68'hfff516d01df145528, 68'h2d33b0bed4d6b9a58};
        rom[173] = {68'hffffffffffffcf22c, 68'h00000000007b0094c, 68'hfffffffebf26866c3, 68'h0000037c1116e2db2, 68'hfff51dcc04987198d, 68'h2d28cb0d87039c9d2};
        rom[174] = {68'hffffffffffffcf9a5, 68'h00000000007a0c430, 68'hfffffffec110a0607, 68'h00000378516a90f7d, 68'hfff524c06624d895e, 68'h2d1dec545c544734d};
        rom[175] = {68'hffffffffffffd0108, 68'h0000000000791a471, 68'hfffffffec2f6edb87, 68'h000003749776d7b24, 68'hfff52bad4e131ab7c, 68'h2d13148bd56e2d004};
        rom[176] = {68'hffffffffffffd0855, 68'h0000000000782a9a0, 68'hfffffffec4d977bd9, 68'h00000370e3305f2ab, 68'hfff53292c7c90cb58, 68'h2d0843ac7e67f77a3};
        rom[177] = {68'hffffffffffffd0f8e, 68'h0000000000773d353, 68'hfffffffec6b8479e5, 68'h0000036d348beb34d, 68'hfff53970de95ef47a, 68'h2cfd79aeeeb2d6374};
        rom[178] = {68'hffffffffffffd16b1, 68'h00000000007652121, 68'hfffffffec893666e6, 68'h000003698b7e5b079, 68'hfff540479db2a63e9, 68'h2cf2b68bc90406801};
        rom[179] = {68'hffffffffffffd1dc0, 68'h000000000075692a0, 68'hfffffffeca6add274, 68'h00000365e7fca8edc, 68'hfff547171041eef9a, 68'h2ce7fa3bbb3e91b1a};
        rom[180] = {68'hffffffffffffd24bb, 68'h0000000000748276a, 68'hfffffffecc3eb4a88, 68'h0000036249fbe9f7a, 68'hfff54ddf415096403, 68'h2cdd44b77e5d41c64};
        rom[181] = {68'hffffffffffffd2ba2, 68'h0000000000739df19, 68'hfffffffece0ef5b83, 68'h0000035eb1714dadc, 68'hfff554a03bd5ad7f2, 68'h2cd295f7d65ccb68f};
        rom[182] = {68'hffffffffffffd3274, 68'h000000000072bb948, 68'hfffffffecfdba902f, 68'h0000035b1e521dc48, 68'hfff55b5a0ab2bf6d1, 68'h2cc7edf592262cf99};
        rom[183] = {68'hffffffffffffd3933, 68'h000000000071db595, 68'hfffffffed1a4d71ca, 68'h000003579093bdd13, 68'hfff5620cb8b404169, 68'h2cbd4ca98b7941e9e};
        rom[184] = {68'hffffffffffffd3fdf, 68'h000000000070fd39e, 68'hfffffffed36a88806, 68'h00000354082baaff4, 68'hfff568b8509094558, 68'h2cb2b20ca6d789dad};
        rom[185] = {68'hffffffffffffd4678, 68'h00000000007021302, 68'hfffffffed52cc5911, 68'h00000350850f7bc75, 68'hfff56f5cdcea9cb3a, 68'h2ca81e17d36f22e7c};
        rom[186] = {68'hffffffffffffd4cfe, 68'h00000000006f47363, 68'hfffffffed6eb9699b, 68'h0000034d0734dfa6a, 68'hfff575fa684f8fbce, 68'h2c9d90c40b05f68b7};
        rom[187] = {68'hffffffffffffd5372, 68'h00000000006e6f461, 68'hfffffffed8a703cd7, 68'h000003498e919ed79, 68'hfff57c90fd3857c07, 68'h2c930a0a51e5188ea};
        rom[188] = {68'hffffffffffffd59d3, 68'h00000000006d995a1, 68'hfffffffeda5f15485, 68'h000003461b1b9a0b7, 68'hfff58320a6098804f, 68'h2c8889e3b6c457715};
        rom[189] = {68'hffffffffffffd6022, 68'h00000000006cc56c6, 68'hfffffffedc13d30f1, 68'h00000342acc8ca245, 68'hfff589a96d138d6fd, 68'h2c7e104952b5fdc12};
        rom[190] = {68'hffffffffffffd665f, 68'h00000000006bf3776, 68'hfffffffeddc5450fe, 68'h0000033f438f3ff0d, 68'hfff5902b5c92dea2b, 68'h2c739d344912c3d2b};
        rom[191] = {68'hffffffffffffd6c8b, 68'h00000000006b23758, 68'hfffffffedf7373225, 68'h0000033bdf6523e81, 68'hfff596a67eb02b904, 68'h2c69309dc765f1536};
        rom[192] = {68'hffffffffffffd72a5, 68'h00000000006a55614, 68'hfffffffee11e6507f, 68'h000003388040b5e6d, 68'hfff59d1add808c89e, 68'h2c5eca7f0559ae2c4};
        rom[193] = {68'hffffffffffffd78ae, 68'h00000000006989352, 68'hfffffffee2c6226c3, 68'h0000033526184ced1, 68'hfff5a3888305b0c8e, 68'h2c546ad144a382306};
        rom[194] = {68'hffffffffffffd7ea6, 68'h000000000068beebe, 68'hfffffffee46ab2e52, 68'h00000331d0e256dd4, 68'hfff5a9ef792e0c73a, 68'h2c4a118dd0f103128};
        rom[195] = {68'hffffffffffffd848d, 68'h000000000067f6801, 68'hfffffffee60c1df34, 68'h0000032e8095583b7, 68'hfff5b04fc9d50621c, 68'h2c3fbeadffd4b01eb};
        rom[196] = {68'hffffffffffffd8a64, 68'h0000000000672fec9, 68'hfffffffee7aa6b024, 68'h0000032b3527ebedf, 68'hfff5b6a97ec323dff, 68'h2c35722b30b2fb381};
        rom[197] = {68'hffffffffffffd902a, 68'h0000000000666b2c2, 68'hfffffffee945a168c, 68'h00000327ee90c2fe6, 68'hfff5bcfca1ae37b4f, 68'h2c2b2bfeccaf7e9af};
        rom[198] = {68'hffffffffffffd95e0, 68'h000000000065a839c, 68'hfffffffeeaddc8690, 68'h00000324acc6a45bd, 68'hfff5c3493c398baab, 68'h2c20ec22469a5ee5c};
        rom[199] = {68'hffffffffffffd9b87, 68'h000000000064e7104, 68'hfffffffeec72e730f, 68'h000003216fc06c9d7, 68'hfff5c98f57f60d5b5, 68'h2c16b28f1addd8ecf};
        rom[200] = {68'hffffffffffffda11e, 68'h00000000006427aad, 68'hfffffffeee0504da7, 68'h0000031e37750dc62, 68'hfff5cfcefe6279052, 68'h2c0c7f3ecf6bfadf4};
        rom[201] = {68'hffffffffffffda6a5, 68'h0000000000636a047, 68'hfffffffeef94286bc, 68'h0000031b03db8f08f, 68'hfff5d60838eb84265, 68'h2c02522af3ac8841b};
        rom[202] = {68'hffffffffffffdac1d, 68'h000000000062ae185, 68'hfffffffef12058d78, 68'h00000317d4eb0c8de, 68'hfff5dc3b10ec07a1c, 68'h2bf82b4d206b084b7};
        rom[203] = {68'hffffffffffffdb185, 68'h000000000061f3e19, 68'hfffffffef2a99cfd0, 68'h00000314aa9ab7380, 68'hfff5e2678fad296f1, 68'h2bee0a9ef7c4fe2ca};
        rom[204] = {68'hffffffffffffdb6df, 68'h0000000000613b5ba, 68'hfffffffef42ffba89, 68'h0000031184e1d46be, 68'hfff5e88dbe6685d71, 68'h2be3f01a25184aca9};
        rom[205] = {68'hffffffffffffdbc2a, 68'h0000000000608481b, 68'hfffffffef5b37b93d, 68'h0000030e63b7bdd6c, 68'hfff5eeada63e583da, 68'h2bd9dbb85cf1b77fa};
        rom[206] = {68'hffffffffffffdc167, 68'h00000000005fcf4f3, 68'hfffffffef7342365c, 68'h0000030b4713e136b, 68'hfff5f4c75049a37b8, 68'h2bcfcd735cfba96c2};
        rom[207] = {68'hffffffffffffdc695, 68'h00000000005f1bbf9, 68'hfffffffef8b1f9b2f, 68'h000003082eedc0233, 68'hfff5fadac58c59c7f, 68'h2bc5c544ebecfce9b};
        rom[208] = {68'hffffffffffffdcbb4, 68'h00000000005e69ce6, 68'hfffffffefa2d04fe0, 68'h000003051b3cefd68, 68'hfff600e80ef98434f, 68'h2bbbc326d97808b0a};
        rom[209] = {68'hffffffffffffdd0c6, 68'h00000000005db9772, 68'hfffffffefba54bb7b, 68'h000003020bf918f7d, 68'hfff606ef357369bf0, 68'h2bb1c712fe39c843d};
        rom[210] = {68'hffffffffffffdd5ca, 68'h00000000005d0ab57, 68'hfffffffefd1ad43f0, 68'h000002ff0119f765c, 68'hfff60cf041cbb5f12, 68'h2ba7d1033ba92d35d};
        rom[211] = {68'hffffffffffffddac1, 68'h00000000005c5d850, 68'hfffffffefe8da4e19, 68'h000002fbfa975a01f, 68'hfff612eb3cc39f1f9, 68'h2b9de0f17c0696ddc};
        rom[212] = {68'hffffffffffffddfa9, 68'h00000000005bb1e18, 68'hfffffffefffdc3dbd, 68'h000002f8f869227d2, 68'hfff618e02f0c0c396, 68'h2b93f6d7b24b7011f};
        rom[213] = {68'hffffffffffffde485, 68'h00000000005b07c6d, 68'hffffffff016b37592, 68'h000002f5fa874523a, 68'hfff61ecf2145ba331, 68'h2b8a12afda19f2806};
        rom[214] = {68'hffffffffffffde953, 68'h00000000005a5f30a, 68'hffffffff02d605742, 68'h000002f300e9c8aac, 68'hfff624b81c01610b4, 68'h2b803473f7ad0f3f4};
        rom[215] = {68'hffffffffffffdee14, 68'h000000000059b81ae, 68'hffffffff043e3436d, 68'h000002f00b88c5fec, 68'hfff62a9b27bfd86a6, 68'h2b765c1e17c87c2f2};
        rom[216] = {68'hffffffffffffdf2c9, 68'h00000000005912819, 68'hffffffff05a3c99af, 68'h000002ed1a5c68114, 68'hfff630784cf23bdf2, 68'h2b6c89a84fa8e5cb4};
        rom[217] = {68'hffffffffffffdf770, 68'h0000000000586e609, 68'hffffffff0706cb89f, 68'h000002ea2d5ceba8c, 68'hfff6364f93fa0eb83, 68'h2b62bd0cbcf44504a};
        rom[218] = {68'hffffffffffffdfc0b, 68'h000000000057cbb3f, 68'hffffffff08673fdd4, 68'h000002e744829f2ff, 68'hfff63c2105295f7d9, 68'h2b58f64585aa58c71};
        rom[219] = {68'hffffffffffffe009a, 68'h0000000000572a77d, 68'hffffffff09c52c5e9, 68'h000002e45fc5e2865, 68'hfff641eca8c2eb093, 68'h2b4f354cd81542c66};
        rom[220] = {68'hffffffffffffe051d, 68'h0000000000568aa84, 68'hffffffff0b2096c82, 68'h000002e17f1f26d12, 68'hfff647b286fa3f41c, 68'h2b457a1ceaba4735f};
        rom[221] = {68'hffffffffffffe0993, 68'h000000000055ec417, 68'hffffffff0c7984c48, 68'h000002dea286ee4cc, 68'hfff64d72a7f3dd771, 68'h2b3bc4affc4aaf0af};
        rom[222] = {68'hffffffffffffe0dfd, 68'h0000000000554f3fa, 68'hffffffff0dcffbef5, 68'h000002dbc9f5cc1ed, 68'hfff6532d13c55c62a, 68'h2b3215005394cc6de};
        rom[223] = {68'hffffffffffffe125c, 68'h000000000054b39f1, 68'hffffffff0f2401d4f, 68'h000002d8f5646428f, 68'hfff658e1d27589ccb, 68'h2b286b083f7520fe2};
        rom[224] = {68'hffffffffffffe16af, 68'h000000000054195c1, 68'hffffffff10759bf30, 68'h000002d624cb6adbb, 68'hfff65e90ebfc8bd73, 68'h2b1ec6c216c7a58d8};
        rom[225] = {68'hffffffffffffe1af6, 68'h00000000005380730, 68'hffffffff11c4cfb89, 68'h000002d35823a50a8, 68'hfff6643a684401ef5, 68'h2b152828385932fa6};
        rom[226] = {68'hffffffffffffe1f32, 68'h000000000052e8e04, 68'hffffffff1311a285f, 68'h000002d08f65e7c00, 68'hfff669de4f272567b, 68'h2b0b8f350ad90bcf2};
        rom[227] = {68'hffffffffffffe2363, 68'h00000000005252a03, 68'hffffffff145c19ad5, 68'h000002cdca8b18129, 68'hfff66f7ca872e9bad, 68'h2b01fbe2fcca86502};
        rom[228] = {68'hffffffffffffe2789, 68'h000000000051bdaf7, 68'hffffffff15a43a72c, 68'h000002cb098c2af9a, 68'hfff675157be61c786, 68'h2af86e2c8476d6a13};
        rom[229] = {68'hffffffffffffe2ba3, 68'h0000000000512a0a7, 68'hffffffff16ea0a0c3, 68'h000002c84c622523f, 68'hfff67aa8d13184dd2, 68'h2aeee60c1fdef8adf};
        rom[230] = {68'hffffffffffffe2fb3, 68'h00000000005097adc, 68'hffffffff182d8da1f, 68'h000002c593061acd4, 68'hfff68036aff803171, 68'h2ae5637c54adb97fd};
        rom[231] = {68'hffffffffffffe33b8, 68'h00000000005006961, 68'hffffffff196eca4e9, 68'h000002c2dd712f95b, 68'hfff685bf1fceaf373, 68'h2adbe677b029dfaf0};
        rom[232] = {68'hffffffffffffe37b3, 68'h00000000004f76bff, 68'hffffffff1aadc51f1, 68'h000002c02b9c9658d, 68'hfff68b42283cf7d0b, 68'h2ad26ef8c728729c0};
        rom[233] = {68'hffffffffffffe3ba3, 68'h00000000004ee8282, 68'hffffffff1bea83136, 68'h000002bd7d8191058, 68'hfff690bfd0bcc047f, 68'h2ac8fcfa35ff201fb};
        rom[234] = {68'hffffffffffffe3f89, 68'h00000000004e5acb5, 68'hffffffff1d25091e1, 68'h000002bad31970764, 68'hfff6963820ba7ed14, 68'h2abf9076a076c062e};
        rom[235] = {68'hffffffffffffe4364, 68'h00000000004dcea65, 68'hffffffff1e5d5c24d, 68'h000002b82c5d9449d, 68'hfff69bab1f955a20b, 68'h2ab62968b1bdf78c5};
        rom[236] = {68'hffffffffffffe4736, 68'h00000000004d43b5e, 68'hffffffff1f9381005, 68'h000002b589476abcb, 68'hfff6a118d49f46cc0, 68'h2aacc7cb1c5bf4f83};
        rom[237] = {68'hffffffffffffe4afd, 68'h00000000004cb9f6f, 68'hffffffff20c77c7cc, 68'h000002b2e9d07082a, 68'hfff6a681471d245f6, 68'h2aa36b989a234faa7};
        rom[238] = {68'hffffffffffffe4ebb, 68'h00000000004c31665, 68'hffffffff21f95359a, 68'h000002b04df230a0b, 68'hfff6abe47e46da265, 68'h2a9a14cbec24ffaff};
        rom[239] = {68'hffffffffffffe526f, 68'h00000000004baa00f, 68'hffffffff23290a4a2, 68'h000002adb5a644481, 68'hfff6b142814773a8c, 68'h2a90c35fdaa374228};
        rom[240] = {68'hffffffffffffe5619, 68'h00000000004b23c3c, 68'hffffffff2456a5f53, 68'h000002ab20e652b12, 68'hfff6b69b573d3cde4, 68'h2a87774f3505c5855};
        rom[241] = {68'hffffffffffffe59ba, 68'h00000000004a9eabc, 68'hffffffff25822af59, 68'h000002a88fac10f6a, 68'hfff6bbef0739de177, 68'h2a7e3094d1cb042f3};
        rom[242] = {68'hffffffffffffe5d51, 68'h00000000004a1ab60, 68'hffffffff26ab9dda2, 68'h000002a601f141f1e, 68'hfff6c13d9842779f1, 68'h2a74ef2b8e7da27a2};
        rom[243] = {68'hffffffffffffe60df, 68'h00000000004997df9, 68'hffffffff27d30325e, 68'h000002a377afb616d, 68'hfff6c687114fbd132, 68'h2a6bb30e4fa6fa704};
        rom[244] = {68'hffffffffffffe6464, 68'h00000000004916257, 68'hffffffff28f85f504, 68'h000002a0f0e14b512, 68'hfff6cbcb794e1076f, 68'h2a627c3800c2eead9};
        rom[245] = {68'hffffffffffffe67e0, 68'h0000000000489584e, 68'hffffffff2a1bb6c50, 68'h0000029e6d7fece11, 68'hfff6d10ad71d9cffb, 68'h2a594aa39433a631a};
        rom[246] = {68'hffffffffffffe6b52, 68'h00000000004815fb0, 68'hffffffff2b3d0de48, 68'h0000029bed8593392, 68'hfff6d6453192719ad, 68'h2a501e4c033562da3};
        rom[247] = {68'hffffffffffffe6ebc, 68'h00000000004797850, 68'hffffffff2c5c6903d, 68'h0000029970ec43dc0, 68'hfff6db7a8f749b30d, 68'h2a46f72c4dd27242c};
        rom[248] = {68'hffffffffffffe721e, 68'h0000000000471a201, 68'hffffffff2d79cc6d1, 68'h00000296f7ae113b4, 68'hfff6e0aaf7803ea3d, 68'h2a3dd53f7ad738c42};
        rom[249] = {68'hffffffffffffe7576, 68'h0000000000469dc99, 68'hffffffff2e953c5f2, 68'h0000029481c51a956, 68'hfff6e5d67065b28ba, 68'h2a34b88097c656523};
        rom[250] = {68'hffffffffffffe78c6, 68'h000000000046227eb, 68'hffffffff2faebd0e0, 68'h000002920f2b8bd5d, 68'hfff6eafd00c998af7, 68'h2a2ba0eab8cce4f34};
        rom[251] = {68'hffffffffffffe7c0e, 68'h000000000045a83cd, 68'hffffffff30c652a32, 68'h0000028f9fdb9d73c, 68'hfff6f01eaf44f73e5, 68'h2a228e78f8b6d0919};
        rom[252] = {68'hffffffffffffe7f4d, 68'h0000000000452f014, 68'hffffffff31dc013d2, 68'h0000028d33cf94526, 68'hfff6f53b826551c73, 68'h2a19812678e347e45};
        rom[253] = {68'hffffffffffffe8284, 68'h000000000044b6c97, 68'hffffffff32efccf02, 68'h0000028acb01c1a14, 68'hfff6fa5380acc1f0e, 68'h2a1078ee613946311};
        rom[254] = {68'hffffffffffffe85b2, 68'h0000000000443f92d, 68'hffffffff3401b9c5f, 68'h00000288656c82bca, 68'hfff6ff66b0920ff35, 68'h2a0775cbe01c35a50};
        rom[255] = {68'hffffffffffffe88d9, 68'h000000000043c95ac, 68'hffffffff3511cbbe0, 68'h00000286030a410eb, 68'hfff704751880cad1d, 68'h29fe77ba2a60aa08d};
        rom[256] = {68'hffffffffffffe8bf8, 68'h000000000043541ec, 68'hffffffff362006cdc, 68'h00000283a3d571f0f, 68'hfff7097ebed96058c, 68'h29f57eb47b41338fb};
        rom[257] = {68'hffffffffffffe8f0e, 68'h000000000042dfdc6, 68'hffffffff372c6ee08, 68'h0000028147c8968db, 68'hfff70e83a9f134dcf, 68'h29ec8ab6145349856};
        rom[258] = {68'hffffffffffffe921d, 68'h0000000000426c911, 68'hffffffff383707d78, 68'h0000027eeede3bc26, 68'hfff71383e012bac05, 68'h29e39bba3d7c4c9dc};
        rom[259] = {68'hffffffffffffe9525, 68'h000000000041fa3a7, 68'hffffffff393fd58a8, 68'h0000027c9910fa01c, 68'hfff7187f677d89b9a, 68'h29dab1bc44e6a0aad};
        rom[260] = {68'hffffffffffffe9824, 68'h00000000004188d62, 68'hffffffff3a46dbc74, 68'h0000027a465b7536f, 68'hfff71d76466675e27, 68'h29d1ccb77ef6dd7d7};
        rom[261] = {68'hffffffffffffe9b1c, 68'h0000000000411861a, 68'hffffffff3b4c1e521, 68'h00000277f6b85ca80, 68'hfff7226882f7a68a6, 68'h29c8eca7464116b67};
        rom[262] = {68'hffffffffffffe9e0d, 68'h000000000040a8dab, 68'hffffffff3c4fa0e5e, 68'h00000275aa226ad9f, 68'hfff727562350acd0b, 68'h29c01186fb7e3a4e5};
        rom[263] = {68'hffffffffffffea0f6, 68'h0000000000403a3ef, 68'hffffffff3d5167341, 68'h00000273609465740, 68'hfff72c3f2d869a05b, 68'h29b73b520581859a6};
        rom[264] = {68'hffffffffffffea3d8, 68'h00000000003fcc8c2, 68'hffffffff3e5174e4c, 68'h000002711a091d23f, 68'hfff73123a7a415d34, 68'h29ae6a03d12e10968};
        rom[265] = {68'hffffffffffffea6b3, 68'h00000000003f5fbfe, 68'hffffffff3f4fcd972, 68'h0000026ed67b6d823, 68'hfff7360397a9742e0, 68'h29a59d97d16c6f3c1};
        rom[266] = {68'hffffffffffffea987, 68'h00000000003ef3d81, 68'hffffffff404c74e11, 68'h0000026c95e63cf6f, 68'hfff73adf038ccb0fe, 68'h299cd6097f2068ae8};
        rom[267] = {68'hffffffffffffeac53, 68'h00000000003e88d25, 68'hffffffff41476e4fa, 68'h0000026a58447c9ea, 68'hfff73fb5f13a07fbc, 68'h29941354591ec406e};
        rom[268] = {68'hffffffffffffeaf19, 68'h00000000003e1eac9, 68'hffffffff4240bd670, 68'h000002681d91282fb, 68'hfff744886693054be, 68'h298b5573e4232a887};
        rom[269] = {68'hffffffffffffeb1d8, 68'h00000000003db5649, 68'hffffffff433865a2a, 68'h00000265e5c745dfe, 68'hfff74956696f9f4af, 68'h29829c63aac61f092};
        rom[270] = {68'hffffffffffffeb490, 68'h00000000003d4cf84, 68'hffffffff442e6a755, 68'h00000263b0e1e64a5, 68'hfff74e1fff9dc918f, 68'h2979e81f3d730a58b};
        rom[271] = {68'hffffffffffffeb741, 68'h00000000003ce5656, 68'hffffffff4522cf494, 68'h000002617edc24557, 68'hfff752e52ee1a15bc, 68'h297138a2325e5c727};
        rom[272] = {68'hffffffffffffeb9ec, 68'h00000000003c7ea9e, 68'hffffffff461597804, 68'h0000025f4fb1251a0, 68'hfff757a5fcf586bcb, 68'h29688de8257bc2465};
        rom[273] = {68'hffffffffffffebc90, 68'h00000000003c18c3b, 68'hffffffff4706c673b, 68'h0000025d235c17c94, 68'hfff75c626f8a2c330, 68'h295fe7ecb8746fe5d};
        rom[274] = {68'hffffffffffffebf2d, 68'h00000000003bb3b0d, 68'hffffffff47f65f74c, 68'h0000025af9d835945, 68'hfff7611a8c46ad1cc, 68'h295746ab929d7ee28};
        rom[275] = {68'hffffffffffffec1c4, 68'h00000000003b4f6f2, 68'hffffffff48e465cc6, 68'h00000258d320c1939, 68'hfff765ce58c8a1257, 68'h294eaa2060ee60abf};
        rom[276] = {68'hffffffffffffec455, 68'h00000000003aebfca, 68'hffffffff49d0dcbb7, 68'h00000256af3108adf, 68'hfff76a7ddaa42ffbd, 68'h29461246d5f764bca};
        rom[277] = {68'hffffffffffffec6e0, 68'h00000000003a89576, 68'hffffffff4abbc77ad, 68'h000002548e0461813, 68'hfff76f29176424d78, 68'h293d7f1aa9d85263c};
        rom[278] = {68'hffffffffffffec964, 68'h00000000003a277d6, 68'hffffffff4ba5293b9, 68'h000002526f962c49a, 68'hfff773d0148a01ce2, 68'h2934f0979a3715fc9};
        rom[279] = {68'hffffffffffffecbe2, 68'h000000000039c66cc, 68'hffffffff4c8d0526c, 68'h0000025053e1d2cb1, 68'hfff77872d78e12f96, 68'h292c66b96a3681639};
        rom[280] = {68'hffffffffffffece5a, 68'h00000000003966237, 68'hffffffff4d735e5de, 68'h0000024e3ae2c838e, 68'hfff77d1165df816db, 68'h2923e17be26d1f799};
        rom[281] = {68'hffffffffffffed0cc, 68'h000000000039069fb, 68'hffffffff4e5837fab, 68'h0000024c2494891f7, 68'hfff781abc4e466037, 68'h291b60dad0dc1a872};
        rom[282] = {68'hffffffffffffed338, 68'h000000000038a7df8, 68'hffffffff4f3b950f6, 68'h0000024a10f29b4cf, 68'hfff78641f9f9dbf13, 68'h2912e4d208e635511};
        rom[283] = {68'hffffffffffffed59e, 68'h00000000003849e12, 68'hffffffff501d78a6c, 68'h00000247fff88dbb2, 68'hfff78ad40a7413393, 68'h290a6d5d6346d6b1a};
        rom[284] = {68'hffffffffffffed7fe, 68'h000000000037eca2a, 68'hffffffff50fde5c42, 68'h00000245f1a1f878e, 68'hfff78f61fb9e62ea1, 68'h2901fa78be092787b};
        rom[285] = {68'hffffffffffffeda59, 68'h00000000003790224, 68'hffffffff51dcdf639, 68'h00000243e5ea7c93f, 68'hfff793ebd2bb5b329, 68'h28f98c1ffc7f42d14};
        rom[286] = {68'hffffffffffffedcae, 68'h000000000037345e2, 68'hffffffff52ba6879c, 68'h00000241dccdc4038, 68'hfff798719504d74a3, 68'h28f1224f073977c31};
        rom[287] = {68'hffffffffffffedefd, 68'h000000000036d9549, 68'hffffffff539683f48, 68'h0000023fd64781924, 68'hfff79cf347ac0f2dd, 68'h28e8bd01cbfd9db38};
        rom[288] = {68'hffffffffffffee147, 68'h0000000000367f03c, 68'hffffffff547134ba3, 68'h0000023dd25370c93, 68'hfff7a170efd9a9317, 68'h28e05c343dbe79ac6};
        rom[289] = {68'hffffffffffffee38b, 68'h000000000036256a0, 68'hffffffff554a7daa9, 68'h0000023bd0ed55daa, 68'hfff7a5ea92adcb681, 68'h28d7ffe2549335798};
        rom[290] = {68'hffffffffffffee5ca, 68'h000000000035cc858, 68'hffffffff5622619e3, 68'h00000239d210fd8cf, 68'hfff7aa6035402ce0b, 68'h28cfa8080daee8096};
        rom[291] = {68'hffffffffffffee803, 68'h0000000000357454a, 68'hffffffff56f8e366d, 68'h00000237d5ba3d265, 68'hfff7aed1dca026ba5, 68'h28c754a16b582ef74};
        rom[292] = {68'hffffffffffffeea37, 68'h0000000000351cd5a, 68'hffffffff57ce05cf8, 68'h00000235dbe4f2581, 68'hfff7b33f8dd4c50f0, 68'h28bf05aa74e0d9137};
        rom[293] = {68'hffffffffffffeec66, 68'h000000000034c606e, 68'hffffffff58a1cb9ca, 68'h00000233e48d032ab, 68'hfff7b7a94ddcd7b5d, 68'h28b6bb1f369da1c31};
        rom[294] = {68'hffffffffffffeee8f, 68'h0000000000346fe6c, 68'hffffffff5974378be, 68'h00000231efae5de97, 68'hfff7bc0f21af02dcc, 68'h28ae74fbc1ddfd0d7};
        rom[295] = {68'hffffffffffffef0b3, 68'h0000000000341a73a, 68'hffffffff5a454c545, 68'h0000022ffd44f90f0, 68'hfff7c0710e39cf7b6, 68'h28a6333c2ce3f42f3};
        rom[296] = {68'hffffffffffffef2d3, 68'h000000000033c5abd, 68'hffffffff5b150ca6a, 68'h0000022e0d4cd331b, 68'hfff7c4cf1863bb9d2, 68'h289df5dc92dc128ca};
        rom[297] = {68'hffffffffffffef4ed, 68'h000000000033718dc, 68'hffffffff5be37b2d2, 68'h0000022c1fc1f2f02, 68'hfff7c929450b4a85d, 68'h2895bcd913d562db1};
        rom[298] = {68'hffffffffffffef702, 68'h0000000000331e17f, 68'hffffffff5cb09a8bb, 68'h0000022a34a066de3, 68'hfff7cd7f990714af0, 68'h288d882dd4b97c5ab};
        rom[299] = {68'hffffffffffffef912, 68'h000000000032cb48b, 68'hffffffff5d7c6d5ff, 68'h000002284be445721, 68'hfff7d1d21925d79f3, 68'h288557d6ff449ffba};
        rom[300] = {68'hffffffffffffefb1e, 68'h000000000032791e9, 68'hffffffff5e46f6414, 68'h000002266589acf17, 68'hfff7d620ca2e859bf, 68'h287d2bd0c1fde546a};
        rom[301] = {68'hffffffffffffefd24, 68'h0000000000322797f, 68'hffffffff5f1037c0e, 68'h00000224818cc35f0, 68'hfff7da6bb0e055366, 68'h28750417502f76e5b};
        rom[302] = {68'hffffffffffffeff26, 68'h000000000031d6b37, 68'hffffffff5fd8346a2, 68'h000002229fe9b6683, 68'hfff7deb2d1f2d0b2b, 68'h286ce0a6e1dedea63};
        rom[303] = {68'hfffffffffffff0123, 68'h000000000031866f7, 68'hffffffff609eeec23, 68'h00000220c09cbb52f, 68'hfff7e2f63215e54b7, 68'h2864c17bb3c560d10};
        rom[304] = {68'hfffffffffffff031b, 68'h00000000003136ca8, 68'hffffffff616469483, 68'h0000021ee3a20eebe, 68'hfff7e735d5f1f250d, 68'h285ca692074866b32};
        rom[305] = {68'hfffffffffffff050f, 68'h000000000030e7c33, 68'hffffffff6228a6759, 68'h0000021d08f5f5749, 68'hfff7eb71c227d8241, 68'h28548fe62271f8343};
        rom[306] = {68'hfffffffffffff06fe, 68'h00000000003099581, 68'hffffffff62eba8bdd, 68'h0000021b3094ba91d, 68'hfff7efa9fb51070fb, 68'h284c7d744fe944568};
        rom[307] = {68'hfffffffffffff08e9, 68'h0000000000304b87a, 68'hffffffff63ad728ec, 68'h000002195a7ab13a5, 68'hfff7f3de85ff8dfc9, 68'h28446f38deeb387db};
        rom[308] = {68'hfffffffffffff0acf, 68'h00000000002ffe508, 68'hffffffff646e06507, 68'h0000021786a433a5c, 68'hfff7f80f66be29051, 68'h283c6530234326598};
        rom[309] = {68'hfffffffffffff0cb1, 68'h00000000002fb1b15, 68'hffffffff652d66656, 68'h00000215b50da33b8, 68'hfff7fc3ca2104fe4f, 68'h28345f56754378523};
        rom[310] = {68'hfffffffffffff0e8e, 68'h00000000002f65a8a, 68'hffffffff65eb952a6, 68'h00000213e5b36881c, 68'hfff800663c724448b, 68'h282c5da831be74545};
        rom[311] = {68'hfffffffffffff1067, 68'h00000000002f1a351, 68'hffffffff66a894f6c, 68'h000002121891f30d3, 68'hfff8048c3a591ffa6, 68'h28246021b9ff0cdaa};
        rom[312] = {68'hfffffffffffff123c, 68'h00000000002ecf556, 68'hffffffff6764681c8, 68'h000002104da5b9705, 68'hfff808aea032e2edf, 68'h281c66bf73c1c0148};
        rom[313] = {68'hfffffffffffff140c, 68'h00000000002e85081, 68'hffffffff681f10e81, 68'h0000020e84eb392b2, 68'hfff80ccd7266812c7, 68'h2814717dc92d85085};
        rom[314] = {68'hfffffffffffff15d8, 68'h00000000002e3b4be, 68'hffffffff68d891a09, 68'h0000020cbe5ef69b2, 68'hfff810e8b553f09f3, 68'h280c805928ccc690c};
        rom[315] = {68'hfffffffffffff17a0, 68'h00000000002df21f9, 68'hffffffff6990ec87e, 68'h0000020af9fd7ceb4, 68'hfff815006d5436baa, 68'h2804934e05866c151};
        rom[316] = {68'hfffffffffffff1964, 68'h00000000002da981b, 68'hffffffff6a4823da9, 68'h0000020937c35e042, 68'hfff819149eb976093, 68'h27fcaa58d696efdc5};
        rom[317] = {68'hfffffffffffff1b24, 68'h00000000002d61711, 68'hffffffff6afe39d03, 68'h0000020777ad327c9, 68'hfff81d254dcefb979, 68'h27f4c576178982dc3};
        rom[318] = {68'hfffffffffffff1ce0, 68'h00000000002d19ec6, 68'hffffffff6bb3309b0, 68'h00000205b9b79989d, 68'hfff821327ed94c410, 68'h27ece4a248313de3d};
        rom[319] = {68'hfffffffffffff1e97, 68'h00000000002cd2f25, 68'hffffffff6c670a683, 68'h00000203fddf38f0b, 68'hfff8253c361631dd3, 68'h27e507d9eca26003e};
        rom[320] = {68'hfffffffffffff204b, 68'h00000000002c8c81c, 68'hffffffff6d19c9602, 68'h000002024420bcf61, 68'hfff8294277bcc8505, 68'h27dd2f198d2b9a15e};
        rom[321] = {68'hfffffffffffff21fb, 68'h00000000002c46996, 68'hffffffff6dcb6fa5f, 68'h000002008c78d8501, 68'hfff82d4547fd8a7bb, 68'h27d55a5db64f6742d};
        rom[322] = {68'hfffffffffffff23a7, 68'h00000000002c01380, 68'hffffffff6e7bff582, 68'h000001fed6e444175, 68'hfff83144ab025f121, 68'h27cd89a2f8bd726da};
        rom[323] = {68'hfffffffffffff254f, 68'h00000000002bbc5c5, 68'hffffffff6f2b7a900, 68'h000001fd235fbfb80, 68'hfff83540a4eea54d7, 68'h27c5bce5e94c08618};
        rom[324] = {68'hfffffffffffff26f4, 68'h00000000002b78054, 68'hffffffff6fd9e3626, 68'h000001fb71e810e3c, 68'hfff8393939df41880, 68'h27bdf42320f196a84};
        rom[325] = {68'hfffffffffffff2895, 68'h00000000002b34319, 68'hffffffff70873bdf2, 68'h000001f9c27a03830, 68'hfff83d2e6deaa9b84, 68'h27b62f573cbe36eae};
        rom[326] = {68'hfffffffffffff2a32, 68'h00000000002af0e02, 68'hffffffff713386117, 68'h000001f8151269a6c, 68'hfff841204520f1d0a, 68'h27ae6e7eddd546c02};
        rom[327] = {68'hfffffffffffff2bcb, 68'h00000000002aae0fb, 68'hffffffff71dec3ffd, 68'h000001f669ae1b7ac, 68'hfff8450ec38bd802b, 68'h27a6b196a9670bcc3};
        rom[328] = {68'hfffffffffffff2d61, 68'h00000000002a6bbf3, 68'hffffffff7288f7ac5, 68'h000001f4c049f7376, 68'hfff848f9ed2ed0e65, 68'h279ef89b48aa6415e};
        rom[329] = {68'hfffffffffffff2ef3, 68'h00000000002a29ed8, 68'hffffffff733223142, 68'h000001f318e2e113e, 68'hfff84ce1c60713854, 68'h2797438968d682752};
        rom[330] = {68'hfffffffffffff3081, 68'h000000000029e8996, 68'hffffffff73da48303, 68'h000001f17375c338c, 68'hfff850c6520ba54b5, 68'h278f925dbb1cb6fef};
        rom[331] = {68'hfffffffffffff320c, 68'h000000000029a7c1d, 68'hffffffff748168f4d, 68'h000001efcfff8db25, 68'hfff854a7952d65db8, 68'h2787e514f4a24354a};
        rom[332] = {68'hfffffffffffff3394, 68'h0000000000296765b, 68'hffffffff752787520, 68'h000001ee2e7d36635, 68'hfff8588593571aca0, 68'h27803babce7a3ab9e};
        rom[333] = {68'hfffffffffffff3518, 68'h0000000000292783f, 68'hffffffff75cca5333, 68'h000001ec8eebb8f7c, 68'hfff85c60506d7b3bc, 68'h2778961f059f6dd81};
        rom[334] = {68'hfffffffffffff3698, 68'h000000000028e81b6, 68'hffffffff7670c47fa, 68'h000001eaf14816d79, 68'hfff86037d04f3b6c2, 68'h2770f46b5aee62143};
        rom[335] = {68'hfffffffffffff3816, 68'h000000000028a92b1, 68'hffffffff7713e71a5, 68'h000001e9558f571a0, 68'hfff8640c16d518179, 68'h2769568d931f545c6};
        rom[336] = {68'hfffffffffffff398f, 68'h0000000000286ab1e, 68'hffffffff77b60ee1c, 68'h000001e7bbbe8678b, 68'hfff867dd27d1e1cdb, 68'h2761bc8276c04754a};
        rom[337] = {68'hfffffffffffff3b06, 68'h0000000000282caec, 68'hffffffff78573db09, 68'h000001e623d2b742e, 68'hfff86bab071288290, 68'h275a2646d22f1cc7b};
        rom[338] = {68'hfffffffffffff3c79, 68'h000000000027ef20c, 68'hffffffff78f7755ce, 68'h000001e48dc90150e, 68'hfff86f75b85e24ed9, 68'h275293d77593ba433};
        rom[339] = {68'hfffffffffffff3de9, 68'h000000000027b206b, 68'hffffffff7996b7b90, 68'h000001e2f99e81f7b, 68'hfff8733d3f76070f1, 68'h274b053134da38c6e};
        rom[340] = {68'hfffffffffffff3f56, 68'h000000000027755fb, 68'hffffffff7a3506930, 68'h000001e167505bfcd, 68'hfff87701a015bd9d8, 68'h27437a50e7ad1f6be};
        rom[341] = {68'hfffffffffffff40c0, 68'h000000000027392ab, 68'hffffffff7ad263b4d, 68'h000001dfd6dbb789d, 68'hfff87ac2ddf3229a1, 68'h273bf333696fa8ee4};
        rom[342] = {68'hfffffffffffff4226, 68'h000000000026fd66c, 68'hffffffff7b6ed0e4a, 68'h000001de483dc2208, 68'hfff87e80fcbe65b34, 68'h27346fd5993813fdb};
        rom[343] = {68'hfffffffffffff438a, 68'h000000000026c212d, 68'hffffffff7c0a4fe48, 68'h000001dcbb73ae8ed, 68'hfff8823c002216e95, 68'h272cf03459c9fe3f2};
        rom[344] = {68'hfffffffffffff44ea, 68'h000000000026872de, 68'hffffffff7ca4e2729, 68'h000001db307ab4e32, 68'hfff885f3ebc3311ad, 68'h2725744c9190c9e72};
        rom[345] = {68'hfffffffffffff4647, 68'h0000000000264cb72, 68'hffffffff7d3e8a493, 68'h000001d9a75012609, 68'hfff889a8c3412479c, 68'h271dfc1b2a9a0dd43};
        rom[346] = {68'hfffffffffffff47a1, 68'h00000000002612ad7, 68'hffffffff7dd7491ed, 68'h000001d81ff109735, 68'hfff88d5a8a35e0e96, 68'h2716879d129010134};
        rom[347] = {68'hfffffffffffff48f9, 68'h000000000025d9100, 68'hffffffff7e6f20a61, 68'h000001d69a5ae1a55, 68'hfff891094435e044e, 68'h270f16cf3ab44ab64};
        rom[348] = {68'hfffffffffffff4a4d, 68'h0000000000259fddd, 68'hffffffff7f06128dd, 68'h000001d5168ae792d, 68'hfff894b4f4d0308fa, 68'h2707a9ae97d9fae61};
        rom[349] = {68'hfffffffffffff4b9e, 68'h0000000000256715e, 68'hffffffff7f9c20816, 68'h000001d3947e6cdf2, 68'hfff8985d9f8e7e0e3, 68'h270040382260ba18f};
        rom[350] = {68'hfffffffffffff4ced, 68'h0000000000252eb77, 68'hffffffff80314c282, 68'h000001d21432c829a, 68'hfff89c0347f51d49f, 68'h26f8da68d62f21577};
        rom[351] = {68'hfffffffffffff4e38, 68'h000000000024f6c18, 68'hffffffff80c59725e, 68'h000001d095a555029, 68'hfff89fa5f18314fd8, 68'h26f1783db2ad76796};
        rom[352] = {68'hfffffffffffff4f81, 68'h000000000024bf332, 68'hffffffff8159031b0, 68'h000001cf18d373e05, 68'hfff8a3459fb227ec1, 68'h26ea19b3bac063445};
        rom[353] = {68'hfffffffffffff50c7, 68'h000000000024880b8, 68'hffffffff81eb91a40, 68'h000001cd9dba8a14b, 68'hfff8a6e255f6dea2c, 68'h26e2bec7f4c3b656e};
        rom[354] = {68'hfffffffffffff520a, 68'h0000000000245149b, 68'hffffffff827d445a0, 68'h000001cc245801c1d, 68'hfff8aa7c17c091245, 68'h26db67776a852dca3};
        rom[355] = {68'hfffffffffffff534a, 68'h0000000000241aece, 68'hffffffff830e1cd2a, 68'h000001caaca949d03, 68'hfff8ae12e87970802, 68'h26d413bf293f4b74b};
        rom[356] = {68'hfffffffffffff5488, 68'h000000000023e4f42, 68'hffffffff839e1ca01, 68'h000001c936abd5e3b, 68'hfff8b1a6cb8690536, 68'h26ccc39c419432b92};
        rom[357] = {68'hfffffffffffff55c3, 68'h000000000023af5ea, 68'hffffffff842d4550e, 68'h000001c7c25d1e518, 68'hfff8b537c447f0361, 68'h26c5770bc7888fcce};
        rom[358] = {68'hfffffffffffff56fb, 68'h0000000000237a2b8, 68'hffffffff84bb98707, 68'h000001c64fbaa015a, 68'hfff8b8c5d61885135, 68'h26be2e0ad27e88602};
        rom[359] = {68'hfffffffffffff5830, 68'h000000000023455a0, 68'hffffffff85491786b, 68'h000001c4dec1dcc8f, 68'hfff8bc51044e426ca, 68'h26b6e8967d30b594b};
        rom[360] = {68'hfffffffffffff5963, 68'h00000000002310e93, 68'hffffffff85d5c4181, 68'h000001c36f705a972, 68'hfff8bfd9523a2389d, 68'h26afa6abe5ad272df};
        rom[361] = {68'hfffffffffffff5a94, 68'h000000000022dcd85, 68'hffffffff86619fa60, 68'h000001c201c3a4349, 68'hfff8c35ec32834945, 68'h26a868482d506fe65};
        rom[362] = {68'hfffffffffffff5bc1, 68'h000000000022a9268, 68'hffffffff86ecabae6, 68'h000001c095b948d47, 68'hfff8c6e15a5f9b9ee, 68'h26a12d6878c0bad6b};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [(K + WSB)-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= {sb_in, idx_raw};
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [(K + WSB)-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB((K + WSB)), .ACC_SIGNED(1),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire        [K-1:0]    idx_p = esb[K-1:0];
    wire        [WSB-1:0]  sb_p  = esb[K +: WSB];
    wire        [WMAN-1:0] v_p   = {idx_p, ew};
    wire signed [WF-1:0]   f_p   = $signed({~v_p[WMAN-1], v_p[WMAN-2:0]});
    wire                   f_neg = f_p[WF-1];
    wire        [WF-1:0]   mag_f = f_neg ? (-f_p) : f_p;   // |f|, fits WF-1 bits (top bit structurally 0)

    wire [WF+ACCM-1:0] umag_p;   // unsigned |f| * C(f)
    wire [WSB:0]       fsb;      // {delayed f sign, external sideband} riding the pmul
    _zkf_pmul #(
        .WA(WF), .WB(ACCM), .A_SIGNED(0), .B_SIGNED(0),
        .WSB(WSB + 1), .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT_FINAL)
    ) u_final_pmul (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in({f_neg, sb_p}),
        .a(mag_f), .b(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(fsb), .p(umag_p)
    );
    assign sb_out = fsb[WSB-1:0];
    // Emit the magnitude and the sign SEPARATELY rather than a signed product: the caller folds the sign into
    // its e + log2(m') reconstruction as a single add/subtract, so the post-product cone carries one fewer wide
    // negate carry chain (a standalone two's-complement negate here would otherwise sit in series with that
    // adder and the magnitude abs, the critical path on wide formats). umag_p is the exact |f|*C(f): C(f) < 2
    // and |f| < 2**(WF-1) bound it below 2**(F2-1), so the F2+1-bit slice is lossless. The sign rode the pmul
    // sideband (fsb[WSB]) and so is aligned with out_valid.
    assign l_mag = umag_p[F2:0];
    assign l_neg = fsb[WSB];
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
