/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_log2 at WMAN=36 (degree 3); zero-bubble, see _zkf_horner.
/// Symmetric reduction: indexes C(f)=log2(1+f)/f by unsigned v (WFRAC+1 bits) and returns log2(m')=f*C(f) as
/// the unsigned magnitude l_mag = |f|*C(f) plus the sign l_neg (set when m>=sqrt(2)), at scale 2**-F2,
/// F2 = WFRAC+1+CF. The final f*C(f) multiply is fully unsigned (|f|*C(f)); the caller folds l_neg into its
/// reconstruction add/subtract. Register stages: two-stage ROM read + Horner + final multiply.

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_log2_m36 #(
    parameter D                   = 3,
    parameter WSB                 = 1,
    parameter WMULTIPLIER         = 0,
    parameter STAGE_PRODUCT       = 0,
    parameter STAGE_PRODUCT_FINAL = STAGE_PRODUCT
) (
    input  wire               clk,
    input  wire               rst,
    input  wire               in_valid,
    input  wire     [WSB-1:0] sb_in,
    input  wire     [ 36-1:0] v,  // index coordinate v = f + 2**WFRAC (WFRAC+1 = WMAN bits)
    output wire               out_valid,
    output wire     [WSB-1:0] sb_out,
    output wire        [84:0] l_mag,  // |log2(m')| = |f|*C(f) magnitude at scale 2**-F2, F2 = WFRAC+1+CF
    output wire               l_neg   // sign of log2(m') (= sign of reduced f); 1 when m >= sqrt(2)
);
    generate if (D != 3) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 36;
    localparam integer WFRAC = WMAN - 1;
    localparam integer CF    = WMAN + 12;
    localparam integer F2    = WFRAC + 1 + CF;   // f is at scale 2**-(WFRAC+1): one bit wider than WFRAC+CF
    localparam integer WF    = WMAN;             // signed reduced-argument width = WFRAC + 1
    localparam integer ACCM  = CF + 2;           // C(f) < 2 -> acc < 2**(CF+1); trim the Horner guard bits so
                                                // the final multiply's acc operand fits a smaller DSP grid
    localparam integer K    = 10;
    localparam integer SEG_BASE = 212;
    localparam integer RW   = 26;
    localparam integer CW   = 51;
    localparam integer ACCW = 51;
    localparam integer NSEG = 725;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [K-1:0]    idx_raw = v[WMAN-1 -: K];
    wire [K-1:0]    idx_ofs = idx_raw - SEG_BASE[K-1:0];
    wire [WIDX-1:0] idx     = idx_ofs[WIDX-1:0];
    wire [RW-1:0]   w       = v[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[  0] = {51'h7fffffffba962, 51'h0000010acbfbb, 51'h7ffb73047f34d, 51'h1b50a94c5c292};
        rom[  1] = {51'h7fffffffbae38, 51'h00000109fbbe1, 51'h7ffb751946f83, 51'h1b4c1d5b61efc};
        rom[  2] = {51'h7fffffffbb308, 51'h000001092c68b, 51'h7ffb772c6f287, 51'h1b47937e5f898};
        rom[  3] = {51'h7fffffffbb7d0, 51'h000001085dfa3, 51'h7ffb793df994e, 51'h1b430bb3b64b2};
        rom[  4] = {51'h7fffffffbbc91, 51'h0000010790715, 51'h7ffb7b4de809c, 51'h1b3e85f9c9573};
        rom[  5] = {51'h7fffffffbc14c, 51'h00000106c3ccb, 51'h7ffb7d5c3c512, 51'h1b3a024efd9b6};
        rom[  6] = {51'h7fffffffbc600, 51'h00000105f80b0, 51'h7ffb7f68f8321, 51'h1b3580b1b9cde};
        rom[  7] = {51'h7fffffffbcaad, 51'h000001052d2b1, 51'h7ffb81741d717, 51'h1b310120666b0};
        rom[  8] = {51'h7fffffffbcf53, 51'h00000104632b9, 51'h7ffb837dadd14, 51'h1b2c83996db25};
        rom[  9] = {51'h7fffffffbd3f2, 51'h000001039a0b3, 51'h7ffb8585ab113, 51'h1b28081b3ba45};
        rom[ 10] = {51'h7fffffffbd88b, 51'h00000102d1c8c, 51'h7ffb878c16ee5, 51'h1b238ea43dffe};
        rom[ 11] = {51'h7fffffffbdd1e, 51'h000001020a630, 51'h7ffb8990f3232, 51'h1b1f1732e43fa};
        rom[ 12] = {51'h7fffffffbe1a9, 51'h0000010143d8a, 51'h7ffb8b944167b, 51'h1b1aa1c59f979};
        rom[ 13] = {51'h7fffffffbe62e, 51'h000001007e287, 51'h7ffb8d960371c, 51'h1b162e5ae2f28};
        rom[ 14] = {51'h7fffffffbeaad, 51'h000000ffb9514, 51'h7ffb8f963af46, 51'h1b11bcf122efa};
        rom[ 15] = {51'h7fffffffbef25, 51'h000000fef551d, 51'h7ffb9194e9a05, 51'h1b0d4d86d5e01};
        rom[ 16] = {51'h7fffffffbf397, 51'h000000fe3228f, 51'h7ffb93921123d, 51'h1b08e01a73c48};
        rom[ 17] = {51'h7fffffffbf803, 51'h000000fd6fd56, 51'h7ffb958db32ae, 51'h1b0474aa764ac};
        rom[ 18] = {51'h7fffffffbfc68, 51'h000000fcae560, 51'h7ffb9787d15ef, 51'h1b000b3558cb3};
        rom[ 19] = {51'h7fffffffc00c7, 51'h000000fbeda9a, 51'h7ffb99806d674, 51'h1afba3b99846a};
        rom[ 20] = {51'h7fffffffc0520, 51'h000000fb2dcf1, 51'h7ffb9b7788e88, 51'h1af73e35b363f};
        rom[ 21] = {51'h7fffffffc0973, 51'h000000fa6ec52, 51'h7ffb9d6d25854, 51'h1af2daa82a6d8};
        rom[ 22] = {51'h7fffffffc0dbf, 51'h000000f9b08ab, 51'h7ffb9f6144dd9, 51'h1aee790f7f4f0};
        rom[ 23] = {51'h7fffffffc1206, 51'h000000f8f31ea, 51'h7ffba153e88f5, 51'h1aea196a35933};
        rom[ 24] = {51'h7fffffffc1646, 51'h000000f8367fb, 51'h7ffba34512360, 51'h1ae5bbb6d2617};
        rom[ 25] = {51'h7fffffffc1a80, 51'h000000f77aace, 51'h7ffba534c36b0, 51'h1ae15ff3dc7b8};
        rom[ 26] = {51'h7fffffffc1eb5, 51'h000000f6bfa51, 51'h7ffba722fdc54, 51'h1add061fdc3b7};
        rom[ 27] = {51'h7fffffffc22e3, 51'h000000f605670, 51'h7ffba90fc2d99, 51'h1ad8ae395b910};
        rom[ 28] = {51'h7fffffffc270c, 51'h000000f54bf1b, 51'h7ffbaafb143a8, 51'h1ad4583ee5ffc};
        rom[ 29] = {51'h7fffffffc2b2f, 51'h000000f493440, 51'h7ffbace4f3785, 51'h1ad0042f089cb};
        rom[ 30] = {51'h7fffffffc2f4c, 51'h000000f3db5cd, 51'h7ffbaecd62215, 51'h1acbb208520bf};
        rom[ 31] = {51'h7fffffffc3363, 51'h000000f3243b1, 51'h7ffbb0b461c14, 51'h1ac761c9527ec};
        rom[ 32] = {51'h7fffffffc3774, 51'h000000f26dddb, 51'h7ffbb299f3e21, 51'h1ac313709bb14};
        rom[ 33] = {51'h7fffffffc3b80, 51'h000000f1b843a, 51'h7ffbb47e1a0b6, 51'h1abec6fcc0e85};
        rom[ 34] = {51'h7fffffffc3f86, 51'h000000f1036bb, 51'h7ffbb660d5c2b, 51'h1aba7c6c56ef5};
        rom[ 35] = {51'h7fffffffc4387, 51'h000000f04f550, 51'h7ffbb842288b5, 51'h1ab633bdf4162};
        rom[ 36] = {51'h7fffffffc4782, 51'h000000ef9bfe6, 51'h7ffbba2213e69, 51'h1ab1ecf0302ee};
        rom[ 37] = {51'h7fffffffc4b78, 51'h000000eee966d, 51'h7ffbbc009953a, 51'h1aada801a48bf};
        rom[ 38] = {51'h7fffffffc4f67, 51'h000000ee378d5, 51'h7ffbbdddba4fa, 51'h1aa964f0ebfde};
        rom[ 39] = {51'h7fffffffc5352, 51'h000000ed8670d, 51'h7ffbbfb978558, 51'h1aa523bca2d15};
        rom[ 40] = {51'h7fffffffc5737, 51'h000000ecd6104, 51'h7ffbc193d4de5, 51'h1aa0e46366ccc};
        rom[ 41] = {51'h7fffffffc5b17, 51'h000000ec266ab, 51'h7ffbc36cd160f, 51'h1a9ca6e3d72ec};
        rom[ 42] = {51'h7fffffffc5ef1, 51'h000000eb777f1, 51'h7ffbc5446f525, 51'h1a986b3c94abd};
        rom[ 43] = {51'h7fffffffc62c6, 51'h000000eac94c6, 51'h7ffbc71ab0255, 51'h1a94316c416c3};
        rom[ 44] = {51'h7fffffffc6696, 51'h000000ea1bd1a, 51'h7ffbc8ef954ad, 51'h1a8ff971810a4};
        rom[ 45] = {51'h7fffffffc6a61, 51'h000000e96f0de, 51'h7ffbcac32031d, 51'h1a8bc34af8901};
        rom[ 46] = {51'h7fffffffc6e26, 51'h000000e8c3001, 51'h7ffbcc9552473, 51'h1a878ef74e75d};
        rom[ 47] = {51'h7fffffffc71e6, 51'h000000e817a74, 51'h7ffbce662cf5f, 51'h1a835c752a9f7};
        rom[ 48] = {51'h7fffffffc75a1, 51'h000000e76d028, 51'h7ffbd035b1a71, 51'h1a7f2bc3365b0};
        rom[ 49] = {51'h7fffffffc7957, 51'h000000e6c310d, 51'h7ffbd203e1c1c, 51'h1a7afce01c5eb};
        rom[ 50] = {51'h7fffffffc7d08, 51'h000000e619d14, 51'h7ffbd3d0beab1, 51'h1a76cfca88c6a};
        rom[ 51] = {51'h7fffffffc80b4, 51'h000000e57142d, 51'h7ffbd59c49c66, 51'h1a72a48129137};
        rom[ 52] = {51'h7fffffffc845b, 51'h000000e4c9649, 51'h7ffbd76684750, 51'h1a6e7b02ac27d};
        rom[ 53] = {51'h7fffffffc87fd, 51'h000000e42235b, 51'h7ffbd92f70167, 51'h1a6a534dc2471};
        rom[ 54] = {51'h7fffffffc8b99, 51'h000000e37bb51, 51'h7ffbdaf70e085, 51'h1a662d611d12f};
        rom[ 55] = {51'h7fffffffc8f31, 51'h000000e2d5e1f, 51'h7ffbdcbd5fa67, 51'h1a62093b6f89f};
        rom[ 56] = {51'h7fffffffc92c5, 51'h000000e230bb4, 51'h7ffbde82664ab, 51'h1a5de6db6e056};
        rom[ 57] = {51'h7fffffffc9653, 51'h000000e18c403, 51'h7ffbe046234d3, 51'h1a59c63fce37a};
        rom[ 58] = {51'h7fffffffc99dc, 51'h000000e0e86fc, 51'h7ffbe20898042, 51'h1a55a767472a2};
        rom[ 59] = {51'h7fffffffc9d61, 51'h000000e045492, 51'h7ffbe3c9c5c40, 51'h1a518a50913bd};
        rom[ 60] = {51'h7fffffffca0e1, 51'h000000dfa2cb7, 51'h7ffbe589addf8, 51'h1a4d6efa661f1};
        rom[ 61] = {51'h7fffffffca45c, 51'h000000df00f5a, 51'h7ffbe74851a78, 51'h1a49556380d80};
        rom[ 62] = {51'h7fffffffca7d3, 51'h000000de5fc70, 51'h7ffbe905b26b0, 51'h1a453d8a9dbae};
        rom[ 63] = {51'h7fffffffcab45, 51'h000000ddbf3e9, 51'h7ffbeac1d1776, 51'h1a41276e7a6a1};
        rom[ 64] = {51'h7fffffffcaeb2, 51'h000000dd1f5b8, 51'h7ffbec7cb0184, 51'h1a3d130dd5d45};
        rom[ 65] = {51'h7fffffffcb21b, 51'h000000dc801cf, 51'h7ffbee364f977, 51'h1a39006770333};
        rom[ 66] = {51'h7fffffffcb57f, 51'h000000dbe181f, 51'h7ffbefeeb13d1, 51'h1a34ef7a0b094};
        rom[ 67] = {51'h7fffffffcb8de, 51'h000000db4389c, 51'h7ffbf1a5d64f7, 51'h1a30e04469202};
        rom[ 68] = {51'h7fffffffcbc39, 51'h000000daa6338, 51'h7ffbf35bc0136, 51'h1a2cd2c54e874};
        rom[ 69] = {51'h7fffffffcbf90, 51'h000000da097e5, 51'h7ffbf5106fcbc, 51'h1a28c6fb8091b};
        rom[ 70] = {51'h7fffffffcc2e2, 51'h000000d96d695, 51'h7ffbf6c3e6b9f, 51'h1a24bce5c5d4c};
        rom[ 71] = {51'h7fffffffcc630, 51'h000000d8d1f3c, 51'h7ffbf876261d9, 51'h1a20b482e6262};
        rom[ 72] = {51'h7fffffffcc979, 51'h000000d8371cc, 51'h7ffbfa272f348, 51'h1a1cadd1aa9a6};
        rom[ 73] = {51'h7fffffffcccbe, 51'h000000d79ce38, 51'h7ffbfbd7033b3, 51'h1a18a8d0dd833};
        rom[ 74] = {51'h7fffffffccfff, 51'h000000d703472, 51'h7ffbfd85a36c4, 51'h1a14a57f4a6db};
        rom[ 75] = {51'h7fffffffcd33b, 51'h000000d66a46f, 51'h7ffbff331100c, 51'h1a10a3dbbe210};
        rom[ 76] = {51'h7fffffffcd673, 51'h000000d5d1e20, 51'h7ffc00df4d301, 51'h1a0ca3e5069c6};
        rom[ 77] = {51'h7fffffffcd9a7, 51'h000000d53a17a, 51'h7ffc028a59300, 51'h1a08a599f315a};
        rom[ 78] = {51'h7fffffffcdcd6, 51'h000000d4a2e6e, 51'h7ffc04343634d, 51'h1a04a8f953f7a};
        rom[ 79] = {51'h7fffffffce001, 51'h000000d40c4f2, 51'h7ffc05dce5712, 51'h1a00ae01fae0c};
        rom[ 80] = {51'h7fffffffce329, 51'h000000d3764f7, 51'h7ffc07846815e, 51'h19fcb4b2baa10};
        rom[ 81] = {51'h7fffffffce64c, 51'h000000d2e0e72, 51'h7ffc092abf52b, 51'h19f8bd0a6738e};
        rom[ 82] = {51'h7fffffffce96b, 51'h000000d24c156, 51'h7ffc0acfec555, 51'h19f4c707d5d76};
        rom[ 83] = {51'h7fffffffcec85, 51'h000000d1b7d96, 51'h7ffc0c73f04a4, 51'h19f0d2a9dcd8c};
        rom[ 84] = {51'h7fffffffcef9c, 51'h000000d124327, 51'h7ffc0e16cc5c3, 51'h19ecdfef53c4b};
        rom[ 85] = {51'h7fffffffcf2af, 51'h000000d0911fd, 51'h7ffc0fb881b49, 51'h19e8eed7134d2};
        rom[ 86] = {51'h7fffffffcf5bd, 51'h000000cffea0a, 51'h7ffc1159117b0, 51'h19e4ff5ff54c6};
        rom[ 87] = {51'h7fffffffcf8c8, 51'h000000cf6cb43, 51'h7ffc12f87cd5d, 51'h19e11188d4c3d};
        rom[ 88] = {51'h7fffffffcfbcf, 51'h000000cedb59c, 51'h7ffc1496c4e9d, 51'h19dd25508dda5};
        rom[ 89] = {51'h7fffffffcfed2, 51'h000000ce4a90a, 51'h7ffc1633eada2, 51'h19d93ab5fddad};
        rom[ 90] = {51'h7fffffffd01d0, 51'h000000cdba580, 51'h7ffc17cfefc8b, 51'h19d551b80332b};
        rom[ 91] = {51'h7fffffffd04cb, 51'h000000cd2aaf2, 51'h7ffc196ad4d5b, 51'h19d16a557d706};
        rom[ 92] = {51'h7fffffffd07c3, 51'h000000cc9b955, 51'h7ffc1b049b200, 51'h19cd848d4d41e};
        rom[ 93] = {51'h7fffffffd0ab6, 51'h000000cc0d09e, 51'h7ffc1c9d43c51, 51'h19c9a05e54736};
        rom[ 94] = {51'h7fffffffd0da5, 51'h000000cb7f0c0, 51'h7ffc1e34cfe0b, 51'h19c5bdc775eda};
        rom[ 95] = {51'h7fffffffd1091, 51'h000000caf19b1, 51'h7ffc1fcb408d9, 51'h19c1dcc795b4b};
        rom[ 96] = {51'h7fffffffd1379, 51'h000000ca64b64, 51'h7ffc216096e4a, 51'h19bdfd5d98e65};
        rom[ 97] = {51'h7fffffffd165d, 51'h000000c9d85cf, 51'h7ffc22f4d3fd8, 51'h19ba1f8865b8b};
        rom[ 98] = {51'h7fffffffd193d, 51'h000000c94c8e7, 51'h7ffc2487f8ee9, 51'h19b64346e3790};
        rom[ 99] = {51'h7fffffffd1c1a, 51'h000000c8c149f, 51'h7ffc261a06cca, 51'h19b26897fa89d};
        rom[100] = {51'h7fffffffd1ef3, 51'h000000c8368ee, 51'h7ffc27aafeab1, 51'h19ae8f7a94620};
        rom[101] = {51'h7fffffffd21c8, 51'h000000c7ac5c7, 51'h7ffc293ae19c0, 51'h19aab7ed9b8b2};
        rom[102] = {51'h7fffffffd249a, 51'h000000c722b21, 51'h7ffc2ac9b0b03, 51'h19a6e1effba02};
        rom[103] = {51'h7fffffffd2768, 51'h000000c6998f0, 51'h7ffc2c576cf6d, 51'h19a30d80a14c0};
        rom[104] = {51'h7fffffffd2a33, 51'h000000c610f29, 51'h7ffc2de4177df, 51'h199f3a9e7a485};
        rom[105] = {51'h7fffffffd2cfa, 51'h000000c588dc2, 51'h7ffc2f6fb1522, 51'h199b6948755c0};
        rom[106] = {51'h7fffffffd2fbd, 51'h000000c5014b0, 51'h7ffc30fa3b7eb, 51'h1997997d8259d};
        rom[107] = {51'h7fffffffd327d, 51'h000000c47a3e7, 51'h7ffc3283b70d9, 51'h1993cb3c921f5};
        rom[108] = {51'h7fffffffd3539, 51'h000000c3f3b5f, 51'h7ffc340c25076, 51'h198ffe8496932};
        rom[109] = {51'h7fffffffd37f2, 51'h000000c36db0b, 51'h7ffc359386736, 51'h198c335482a40};
        rom[110] = {51'h7fffffffd3aa8, 51'h000000c2e82e3, 51'h7ffc3719dc57a, 51'h198869ab4a474};
        rom[111] = {51'h7fffffffd3d5a, 51'h000000c2632da, 51'h7ffc389f27b8d, 51'h1984a187e2779};
        rom[112] = {51'h7fffffffd4008, 51'h000000c1deae8, 51'h7ffc3a23699a4, 51'h1980dae941339};
        rom[113] = {51'h7fffffffd42b3, 51'h000000c15ab01, 51'h7ffc3ba6a2fe1, 51'h197d15ce5d7cc};
        rom[114] = {51'h7fffffffd455b, 51'h000000c0d731c, 51'h7ffc3d28d4e53, 51'h197952362f562};
        rom[115] = {51'h7fffffffd4800, 51'h000000c05432e, 51'h7ffc3eaa004f1, 51'h1975901fafc2c};
        rom[116] = {51'h7fffffffd4aa1, 51'h000000bfd1b2e, 51'h7ffc402a263a1, 51'h1971cf89d8c4b};
        rom[117] = {51'h7fffffffd4d3f, 51'h000000bf4fb11, 51'h7ffc41a947a33, 51'h196e1073a55bb};
        rom[118] = {51'h7fffffffd4fd9, 51'h000000bece2ce, 51'h7ffc432765865, 51'h196a52dc1183e};
        rom[119] = {51'h7fffffffd5270, 51'h000000be4d25a, 51'h7ffc44a480ddf, 51'h196696c21a34a};
        rom[120] = {51'h7fffffffd5504, 51'h000000bdcc9ac, 51'h7ffc46209aa37, 51'h1962dc24bd5f4};
        rom[121] = {51'h7fffffffd5795, 51'h000000bd4c8ba, 51'h7ffc479bb3cee, 51'h195f2302f9edb};
        rom[122] = {51'h7fffffffd5a23, 51'h000000bcccf7a, 51'h7ffc4915cd573, 51'h195b6b5bcfc19};
        rom[123] = {51'h7fffffffd5cad, 51'h000000bc4dde3, 51'h7ffc4a8ee8320, 51'h1957b52e3fb28};
        rom[124] = {51'h7fffffffd5f34, 51'h000000bbcf3eb, 51'h7ffc4c070553e, 51'h195400794b8d8};
        rom[125] = {51'h7fffffffd61b8, 51'h000000bb51188, 51'h7ffc4d7e25b00, 51'h19504d3bf6135};
        rom[126] = {51'h7fffffffd6439, 51'h000000bad36b1, 51'h7ffc4ef44a389, 51'h194c9b7542f75};
        rom[127] = {51'h7fffffffd66b7, 51'h000000ba5635d, 51'h7ffc506973de6, 51'h1948eb2436de8};
        rom[128] = {51'h7fffffffd6932, 51'h000000b9d9783, 51'h7ffc51dda3915, 51'h19453c47d75e3};
        rom[129] = {51'h7fffffffd6ba9, 51'h000000b95d318, 51'h7ffc5350da3fe, 51'h19418edf2afac};
        rom[130] = {51'h7fffffffd6e1e, 51'h000000b8e1614, 51'h7ffc54c318d78, 51'h193de2e93926b};
        rom[131] = {51'h7fffffffd708f, 51'h000000b86606e, 51'h7ffc563460447, 51'h193a38650a415};
        rom[132] = {51'h7fffffffd72fe, 51'h000000b7eb21c, 51'h7ffc57a4b171e, 51'h19368f51a7959};
        rom[133] = {51'h7fffffffd7569, 51'h000000b770b15, 51'h7ffc59140d49c, 51'h1932e7ae1b591};
        rom[134] = {51'h7fffffffd77d1, 51'h000000b6f6b51, 51'h7ffc5a8274b4e, 51'h192f417970aab};
        rom[135] = {51'h7fffffffd7a37, 51'h000000b67d2c6, 51'h7ffc5befe89b1, 51'h192b9cb2b391b};
        rom[136] = {51'h7fffffffd7c99, 51'h000000b60416b, 51'h7ffc5d5c69e2e, 51'h1927f958f0fc9};
        rom[137] = {51'h7fffffffd7ef9, 51'h000000b58b738, 51'h7ffc5ec7f971d, 51'h1924576b36bfb};
        rom[138] = {51'h7fffffffd8156, 51'h000000b513424, 51'h7ffc6032982c4, 51'h1920b6e893949};
        rom[139] = {51'h7fffffffd83af, 51'h000000b49b826, 51'h7ffc619c46f59, 51'h191d17d017187};
        rom[140] = {51'h7fffffffd8606, 51'h000000b424335, 51'h7ffc630506afe, 51'h19197a20d1cb5};
        rom[141] = {51'h7fffffffd885a, 51'h000000b3ad549, 51'h7ffc646cd83c5, 51'h1915ddd9d50ee};
        rom[142] = {51'h7fffffffd8aac, 51'h000000b336e58, 51'h7ffc65d3bc7af, 51'h191242fa33256};
        rom[143] = {51'h7fffffffd8cfa, 51'h000000b2c0e5b, 51'h7ffc6739b44ac, 51'h190ea980ff309};
        rom[144] = {51'h7fffffffd8f45, 51'h000000b24b54a, 51'h7ffc689ec089a, 51'h190b116d4d30b};
        rom[145] = {51'h7fffffffd918e, 51'h000000b1d631a, 51'h7ffc6a02e2147, 51'h19077abe32034};
        rom[146] = {51'h7fffffffd93d4, 51'h000000b1617c5, 51'h7ffc6b6619c6e, 51'h1903e572c3623};
        rom[147] = {51'h7fffffffd9617, 51'h000000b0ed342, 51'h7ffc6cc8687bd, 51'h1900518a17e2b};
        rom[148] = {51'h7fffffffd9858, 51'h000000b079588, 51'h7ffc6e29cf0cd, 51'h18fcbf0346f40};
        rom[149] = {51'h7fffffffd9a95, 51'h000000b005e8f, 51'h7ffc6f8a4e52a, 51'h18f92ddd68dec};
        rom[150] = {51'h7fffffffd9cd0, 51'h000000af92e4f, 51'h7ffc70e9e724f, 51'h18f59e1796c3a};
        rom[151] = {51'h7fffffffd9f08, 51'h000000af204c0, 51'h7ffc72489a5a4, 51'h18f20fb0ea9a8};
        rom[152] = {51'h7fffffffda13e, 51'h000000aeae1d9, 51'h7ffc73a668c83, 51'h18ee82a87f314};
        rom[153] = {51'h7fffffffda371, 51'h000000ae3c594, 51'h7ffc750353436, 51'h18eaf6fd702af};
        rom[154] = {51'h7fffffffda5a1, 51'h000000adcafe7, 51'h7ffc765f5a9f6, 51'h18e76caed9fea};
        rom[155] = {51'h7fffffffda7cf, 51'h000000ad5a0ca, 51'h7ffc77ba7faed, 51'h18e3e3bbd9f68};
        rom[156] = {51'h7fffffffda9fa, 51'h000000ace9837, 51'h7ffc7914c3433, 51'h18e05c238e2ee};
        rom[157] = {51'h7fffffffdac22, 51'h000000ac79624, 51'h7ffc7a6e262d2, 51'h18dcd5e515951};
        rom[158] = {51'h7fffffffdae48, 51'h000000ac09a8a, 51'h7ffc7bc6a93c5, 51'h18d950ff8fe69};
        rom[159] = {51'h7fffffffdb06b, 51'h000000ab9a562, 51'h7ffc7d1e4d3f5, 51'h18d5cd721db00};
        rom[160] = {51'h7fffffffdb28b, 51'h000000ab2b6a3, 51'h7ffc7e751303d, 51'h18d24b3be04c1};
        rom[161] = {51'h7fffffffdb4a9, 51'h000000aabce46, 51'h7ffc7fcafb568, 51'h18ceca5bf9e2c};
        rom[162] = {51'h7fffffffdb6c5, 51'h000000aa4ec43, 51'h7ffc812007034, 51'h18cb4ad18d684};
        rom[163] = {51'h7fffffffdb8de, 51'h000000a9e1092, 51'h7ffc827436d4b, 51'h18c7cc9bbe9bf};
        rom[164] = {51'h7fffffffdbaf4, 51'h000000a973b2d, 51'h7ffc83c78b94c, 51'h18c44fb9b207a};
        rom[165] = {51'h7fffffffdbd08, 51'h000000a906c0b, 51'h7ffc851a060c5, 51'h18c0d42a8cfe7};
        rom[166] = {51'h7fffffffdbf1a, 51'h000000a89a324, 51'h7ffc866ba7035, 51'h18bd59ed759be};
        rom[167] = {51'h7fffffffdc129, 51'h000000a82e073, 51'h7ffc87bc6f40e, 51'h18b9e10192c32};
        rom[168] = {51'h7fffffffdc336, 51'h000000a7c23ef, 51'h7ffc890c5f8b0, 51'h18b669660c1dc};
        rom[169] = {51'h7fffffffdc540, 51'h000000a756d90, 51'h7ffc8a5b78a70, 51'h18b2f31a0a1b1};
        rom[170] = {51'h7fffffffdc748, 51'h000000a6ebd50, 51'h7ffc8ba9bb590, 51'h18af7e1cb5ef0};
        rom[171] = {51'h7fffffffdc94d, 51'h000000a681327, 51'h7ffc8cf728647, 51'h18ac0a6d39917};
        rom[172] = {51'h7fffffffdcb50, 51'h000000a616f0e, 51'h7ffc8e43c08bc, 51'h18a8980abfbd2};
        rom[173] = {51'h7fffffffdcd50, 51'h000000a5ad0fe, 51'h7ffc8f8f84908, 51'h18a526f473eec};
        rom[174] = {51'h7fffffffdcf4f, 51'h000000a5438f0, 51'h7ffc90da75335, 51'h18a1b72982642};
        rom[175] = {51'h7fffffffdd14a, 51'h000000a4da6dc, 51'h7ffc922493340, 51'h189e48a9181b6};
        rom[176] = {51'h7fffffffdd344, 51'h000000a471abc, 51'h7ffc936ddf517, 51'h189adb7262d1d};
        rom[177] = {51'h7fffffffdd53b, 51'h000000a409488, 51'h7ffc94b65a499, 51'h18976f8491033};
        rom[178] = {51'h7fffffffdd730, 51'h000000a3a143a, 51'h7ffc95fe04d9a, 51'h189404ded1e90};
        rom[179] = {51'h7fffffffdd923, 51'h000000a3399ca, 51'h7ffc9744dfbdc, 51'h18909b8055794};
        rom[180] = {51'h7fffffffddb13, 51'h000000a2d2533, 51'h7ffc988aebb17, 51'h188d33684c65d};
        rom[181] = {51'h7fffffffddd01, 51'h000000a26b66c, 51'h7ffc99d0296f2, 51'h1889cc95e81b9};
        rom[182] = {51'h7fffffffddeed, 51'h000000a204d6e, 51'h7ffc9b1499b09, 51'h188667085ac18};
        rom[183] = {51'h7fffffffde0d6, 51'h000000a19ea35, 51'h7ffc9c583d2e9, 51'h188302bed737c};
        rom[184] = {51'h7fffffffde2bd, 51'h000000a138cb7, 51'h7ffc9d9b14a11, 51'h187f9fb891170};
        rom[185] = {51'h7fffffffde4a2, 51'h000000a0d34f0, 51'h7ffc9edd20bf4, 51'h187c3df4bcaf5};
        rom[186] = {51'h7fffffffde685, 51'h000000a06e2d7, 51'h7ffca01e623f7, 51'h1878dd728f07b};
        rom[187] = {51'h7fffffffde866, 51'h000000a009667, 51'h7ffca15ed9d70, 51'h18757e313ddce};
        rom[188] = {51'h7fffffffdea44, 51'h0000009fa4f99, 51'h7ffca29e883ac, 51'h1872202fffa0c};
        rom[189] = {51'h7fffffffdec20, 51'h0000009f40e66, 51'h7ffca3dd6e1e6, 51'h186ec36e0b795};
        rom[190] = {51'h7fffffffdedfb, 51'h0000009edd2c8, 51'h7ffca51b8c34e, 51'h186b67ea99400};
        rom[191] = {51'h7fffffffdefd3, 51'h0000009e79cb8, 51'h7ffca658e3309, 51'h18680da4e1811};
        rom[192] = {51'h7fffffffdf1a8, 51'h0000009e16c30, 51'h7ffca79573c2b, 51'h1864b49c1d7a4};
        rom[193] = {51'h7fffffffdf37c, 51'h0000009db412a, 51'h7ffca8d13e9bf, 51'h18615ccf871a8};
        rom[194] = {51'h7fffffffdf54e, 51'h0000009d51b9e, 51'h7ffcaa0c446c0, 51'h185e063e5900c};
        rom[195] = {51'h7fffffffdf71d, 51'h0000009cefb87, 51'h7ffcab4685e1f, 51'h185ab0e7ce7b8};
        rom[196] = {51'h7fffffffdf8ea, 51'h0000009c8e0df, 51'h7ffcac8003abf, 51'h18575ccb2387b};
        rom[197] = {51'h7fffffffdfab6, 51'h0000009c2cb9f, 51'h7ffcadb8be776, 51'h185409e794d04};
        rom[198] = {51'h7fffffffdfc7f, 51'h0000009bcbbc1, 51'h7ffcaef0b6f0e, 51'h1850b83c5facf};
        rom[199] = {51'h7fffffffdfe46, 51'h0000009b6b13e, 51'h7ffcb027edc46, 51'h184d67c8c221d};
        rom[200] = {51'h7fffffffe000b, 51'h0000009b0ac11, 51'h7ffcb15e639cd, 51'h184a188bfade7};
        rom[201] = {51'h7fffffffe01ce, 51'h0000009aaac34, 51'h7ffcb2941924a, 51'h1846ca85493d1};
        rom[202] = {51'h7fffffffe0390, 51'h0000009a4b19f, 51'h7ffcb3c90f055, 51'h18437db3ed41d};
        rom[203] = {51'h7fffffffe054f, 51'h00000099ebc4e, 51'h7ffcb4fd45e7a, 51'h18403217279a0};
        rom[204] = {51'h7fffffffe070c, 51'h000000998cc3a, 51'h7ffcb630be73a, 51'h183ce7ae399b6};
        rom[205] = {51'h7fffffffe08c7, 51'h000000992e15e, 51'h7ffcb76379509, 51'h18399e7865436};
        rom[206] = {51'h7fffffffe0a80, 51'h00000098cfbb3, 51'h7ffcb89577250, 51'h18365674ed364};
        rom[207] = {51'h7fffffffe0c37, 51'h0000009871b33, 51'h7ffcb9c6b896c, 51'h18330fa314be6};
        rom[208] = {51'h7fffffffe0dec, 51'h0000009813fd8, 51'h7ffcbaf73e4ac, 51'h182fca021fcbb};
        rom[209] = {51'h7fffffffe0f9f, 51'h00000097b699d, 51'h7ffcbc2708e57, 51'h182c859152f2b};
        rom[210] = {51'h7fffffffe1151, 51'h000000975987c, 51'h7ffcbd56190a5, 51'h1829424ff36bf};
        rom[211] = {51'h7fffffffe1300, 51'h00000096fcc6e, 51'h7ffcbe846f5c4, 51'h1826003d47130};
        rom[212] = {51'h7fffffffe14ae, 51'h00000096a056f, 51'h7ffcbfb20c7d7, 51'h1822bf5894663};
        rom[213] = {51'h7fffffffe1659, 51'h0000009644378, 51'h7ffcc0def10f3, 51'h181f7fa122856};
        rom[214] = {51'h7fffffffe1803, 51'h00000095e8684, 51'h7ffcc20b1db24, 51'h181c41163931a};
        rom[215] = {51'h7fffffffe19ab, 51'h000000958ce8d, 51'h7ffcc33693069, 51'h181903b720cc5};
        rom[216] = {51'h7fffffffe1b51, 51'h0000009531b8d, 51'h7ffcc46151ab7, 51'h1815c78322566};
        rom[217] = {51'h7fffffffe1cf5, 51'h00000094d6d7f, 51'h7ffcc58b5a3f8, 51'h18128c79876fb};
        rom[218] = {51'h7fffffffe1e97, 51'h000000947c45d, 51'h7ffcc6b4ad608, 51'h180f52999a566};
        rom[219] = {51'h7fffffffe2037, 51'h0000009422022, 51'h7ffcc7dd4babb, 51'h180c19e2a5e62};
        rom[220] = {51'h7fffffffe21d6, 51'h00000093c80c8, 51'h7ffcc90535bd9, 51'h1808e253f5977};
        rom[221] = {51'h7fffffffe2372, 51'h000000936e64a, 51'h7ffcca2c6c31e, 51'h1805abecd57ed};
        rom[222] = {51'h7fffffffe250d, 51'h00000093150a1, 51'h7ffccb52efa3c, 51'h180276ac924c7};
        rom[223] = {51'h7fffffffe26a6, 51'h00000092bbfca, 51'h7ffccc78c0ada, 51'h17ff4292794b2};
        rom[224] = {51'h7fffffffe283e, 51'h00000092633bd, 51'h7ffccd9ddfe94, 51'h17fc0f9dd85fc};
        rom[225] = {51'h7fffffffe29d3, 51'h000000920ac77, 51'h7ffccec24defb, 51'h17f8ddcdfe08b};
        rom[226] = {51'h7fffffffe2b67, 51'h00000091b29f1, 51'h7ffccfe60b595, 51'h17f5ad22395d0};
        rom[227] = {51'h7fffffffe2cf9, 51'h000000915ac27, 51'h7ffcd10918bdf, 51'h17f27d99da0bd};
        rom[228] = {51'h7fffffffe2e89, 51'h0000009103312, 51'h7ffcd22b76b4a, 51'h17ef4f34305bc};
        rom[229] = {51'h7fffffffe3018, 51'h00000090abeaf, 51'h7ffcd34d25d3c, 51'h17ec21f08d2a2};
        rom[230] = {51'h7fffffffe31a5, 51'h0000009054ef6, 51'h7ffcd46e26b12, 51'h17e8f5ce41ea5};
        rom[231] = {51'h7fffffffe3330, 51'h0000008ffe3e4, 51'h7ffcd58e79e1e, 51'h17e5cacca0a52};
        rom[232] = {51'h7fffffffe34b9, 51'h0000008fa7d73, 51'h7ffcd6ae1ffa6, 51'h17e2a0eafbf84};
        rom[233] = {51'h7fffffffe3640, 51'h0000008f51b9e, 51'h7ffcd7cd198e8, 51'h17df7828a7156};
        rom[234] = {51'h7fffffffe37c6, 51'h0000008efbe60, 51'h7ffcd8eb67317, 51'h17dc5084f5c1d};
        rom[235] = {51'h7fffffffe394b, 51'h0000008ea65b4, 51'h7ffcda090975b, 51'h17d929ff3c55a};
        rom[236] = {51'h7fffffffe3acd, 51'h0000008e51194, 51'h7ffcdb2600ed3, 51'h17d60496cfbb4};
        rom[237] = {51'h7fffffffe3c4e, 51'h0000008dfc1fc, 51'h7ffcdc424e293, 51'h17d2e04b056e8};
        rom[238] = {51'h7fffffffe3dcd, 51'h0000008da76e7, 51'h7ffcdd5df1ba5, 51'h17cfbd1b337c5};
        rom[239] = {51'h7fffffffe3f4b, 51'h0000008d5304f, 51'h7ffcde78ec309, 51'h17cc9b06b081e};
        rom[240] = {51'h7fffffffe40c7, 51'h0000008cfee30, 51'h7ffcdf933e1b7, 51'h17c97a0cd3ac1};
        rom[241] = {51'h7fffffffe4241, 51'h0000008cab084, 51'h7ffce0ace809a, 51'h17c65a2cf4b6e};
        rom[242] = {51'h7fffffffe43ba, 51'h0000008c57748, 51'h7ffce1c5ea895, 51'h17c33b666becd};
        rom[243] = {51'h7fffffffe4531, 51'h0000008c04275, 51'h7ffce2de46280, 51'h17c01db892263};
        rom[244] = {51'h7fffffffe46a6, 51'h0000008bb1208, 51'h7ffce3f5fb72b, 51'h17bd0122c0c89};
        rom[245] = {51'h7fffffffe481a, 51'h0000008b5e5fb, 51'h7ffce50d0af5c, 51'h17b9e5a451c62};
        rom[246] = {51'h7fffffffe498c, 51'h0000008b0be49, 51'h7ffce623753cd, 51'h17b6cb3c9f9d2};
        rom[247] = {51'h7fffffffe4afd, 51'h0000008ab9aee, 51'h7ffce7393ad31, 51'h17b3b1eb05574};
        rom[248] = {51'h7fffffffe4c6c, 51'h0000008a67be5, 51'h7ffce84e5c432, 51'h17b099aede890};
        rom[249] = {51'h7fffffffe4dd9, 51'h0000008a16129, 51'h7ffce962da16d, 51'h17ad828787512};
        rom[250] = {51'h7fffffffe4f45, 51'h00000089c4ab6, 51'h7ffcea76b4d78, 51'h17aa6c745c581};
        rom[251] = {51'h7fffffffe50b0, 51'h0000008973886, 51'h7ffceb89ed0e1, 51'h17a75774bacf5};
        rom[252] = {51'h7fffffffe5219, 51'h0000008922a96, 51'h7ffcec9c8342a, 51'h17a443880070c};
        rom[253] = {51'h7fffffffe5380, 51'h00000088d20e0, 51'h7ffcedae77fcd, 51'h17a130ad8b7e5};
        rom[254] = {51'h7fffffffe54e6, 51'h0000008881b60, 51'h7ffceebfcbc3a, 51'h179e1ee4bac13};
        rom[255] = {51'h7fffffffe564a, 51'h0000008831a12, 51'h7ffcefd07f1d9, 51'h179b0e2ced893};
        rom[256] = {51'h7fffffffe57ad, 51'h00000087e1cf1, 51'h7ffcf0e092907, 51'h1797fe8583ac8};
        rom[257] = {51'h7fffffffe590e, 51'h00000087923f7, 51'h7ffcf1f006a1b, 51'h1794efeddd86d};
        rom[258] = {51'h7fffffffe5a6e, 51'h0000008742f22, 51'h7ffcf2fedbd60, 51'h1791e2655bf8d};
        rom[259] = {51'h7fffffffe5bcc, 51'h00000086f3e6c, 51'h7ffcf40d12b18, 51'h178ed5eb6067c};
        rom[260] = {51'h7fffffffe5d29, 51'h00000086a51d0, 51'h7ffcf51aabb7f, 51'h178bca7f4cbcc};
        rom[261] = {51'h7fffffffe5e84, 51'h000000865694b, 51'h7ffcf627a76c6, 51'h1788c02083644};
        rom[262] = {51'h7fffffffe5fde, 51'h00000086084d8, 51'h7ffcf73406514, 51'h1785b6ce674d9};
        rom[263] = {51'h7fffffffe6136, 51'h00000085ba473, 51'h7ffcf83fc8e89, 51'h1782ae885bea3};
        rom[264] = {51'h7fffffffe628d, 51'h000000856c817, 51'h7ffcf94aefb3d, 51'h177fa74dc52d6};
        rom[265] = {51'h7fffffffe63e3, 51'h000000851efbf, 51'h7ffcfa557b33d, 51'h177ca11e078b7};
        rom[266] = {51'h7fffffffe6537, 51'h00000084d1b68, 51'h7ffcfb5f6be8f, 51'h17799bf887f97};
        rom[267] = {51'h7fffffffe668a, 51'h0000008484b0e, 51'h7ffcfc68c252f, 51'h177697dcabec6};
        rom[268] = {51'h7fffffffe67db, 51'h0000008437eab, 51'h7ffcfd717ef12, 51'h177394c9d958d};
        rom[269] = {51'h7fffffffe692b, 51'h00000083eb63c, 51'h7ffcfe79a2424, 51'h177092bf76b25};
        rom[270] = {51'h7fffffffe6a79, 51'h000000839f1bd, 51'h7ffcff812cc47, 51'h176d91bceaeb0};
        rom[271] = {51'h7fffffffe6bc6, 51'h0000008353129, 51'h7ffd00881ef56, 51'h176a91c19d72e};
        rom[272] = {51'h7fffffffe6d12, 51'h000000830747c, 51'h7ffd018e79524, 51'h176792ccf6373};
        rom[273] = {51'h7fffffffe6e5c, 51'h00000082bbbb2, 51'h7ffd02943c57a, 51'h176494de5da24};
        rom[274] = {51'h7fffffffe6fa5, 51'h00000082706c6, 51'h7ffd03996881b, 51'h176197f53c9ac};
        rom[275] = {51'h7fffffffe70ec, 51'h00000082255b5, 51'h7ffd049dfe4bf, 51'h175e9c10fc833};
        rom[276] = {51'h7fffffffe7233, 51'h00000081da87b, 51'h7ffd05a1fe318, 51'h175ba13107394};
        rom[277] = {51'h7fffffffe7377, 51'h000000818ff13, 51'h7ffd06a568acf, 51'h1758a754c715a};
        rom[278] = {51'h7fffffffe74bb, 51'h000000814597a, 51'h7ffd07a83e384, 51'h1755ae7ba6eb4};
        rom[279] = {51'h7fffffffe75fd, 51'h00000080fb7ab, 51'h7ffd08aa7f4d1, 51'h1752b6a51206d};
        rom[280] = {51'h7fffffffe773e, 51'h00000080b19a2, 51'h7ffd09ac2c645, 51'h174fbfd0742e5};
        rom[281] = {51'h7fffffffe787d, 51'h0000008067f5b, 51'h7ffd0aad45f6a, 51'h174cc9fd39a0a};
        rom[282] = {51'h7fffffffe79bb, 51'h000000801e8d3, 51'h7ffd0badcc7bf, 51'h1749d52acf14c};
        rom[283] = {51'h7fffffffe7af8, 51'h0000007fd5605, 51'h7ffd0cadc06be, 51'h1746e158a1b99};
        rom[284] = {51'h7fffffffe7c34, 51'h0000007f8c6ee, 51'h7ffd0dad223d8, 51'h1743ee861f355};
        rom[285] = {51'h7fffffffe7d6e, 51'h0000007f43b89, 51'h7ffd0eabf2675, 51'h1740fcb2b5a4e};
        rom[286] = {51'h7fffffffe7ea7, 51'h0000007efb3d2, 51'h7ffd0faa315f7, 51'h173e0bddd39ba};
        rom[287] = {51'h7fffffffe7fde, 51'h0000007eb2fc7, 51'h7ffd10a7df9b6, 51'h173b1c06e822a};
        rom[288] = {51'h7fffffffe8115, 51'h0000007e6af62, 51'h7ffd11a4fd905, 51'h17382d2d62b85};
        rom[289] = {51'h7fffffffe824a, 51'h0000007e232a0, 51'h7ffd12a18bb2d, 51'h17353f50b3501};
        rom[290] = {51'h7fffffffe837d, 51'h0000007ddb97d, 51'h7ffd139d8a770, 51'h173252704a517};
        rom[291] = {51'h7fffffffe84b0, 51'h0000007d943f6, 51'h7ffd1498fa50a, 51'h172f668b98982};
        rom[292] = {51'h7fffffffe85e1, 51'h0000007d4d206, 51'h7ffd1593dbb2c, 51'h172c7ba20f732};
        rom[293] = {51'h7fffffffe8711, 51'h0000007d063ab, 51'h7ffd168e2f102, 51'h172991b320a45};
        rom[294] = {51'h7fffffffe8840, 51'h0000007cbf8df, 51'h7ffd1787f4db1, 51'h1726a8be3e603};
        rom[295] = {51'h7fffffffe896e, 51'h0000007c7919f, 51'h7ffd18812d855, 51'h1723c0c2db4d3};
        rom[296] = {51'h7fffffffe8a9a, 51'h0000007c32de9, 51'h7ffd1979d9802, 51'h1720d9c06a835};
        rom[297] = {51'h7fffffffe8bc5, 51'h0000007becdb7, 51'h7ffd1a71f93c7, 51'h171df3b65f8ba};
        rom[298] = {51'h7fffffffe8cef, 51'h0000007ba7106, 51'h7ffd1b698d2a9, 51'h171b0ea42e5fd};
        rom[299] = {51'h7fffffffe8e18, 51'h0000007b617d4, 51'h7ffd1c6095ba8, 51'h17182a894b69c};
        rom[300] = {51'h7fffffffe8f3f, 51'h0000007b1c21b, 51'h7ffd1d57135bb, 51'h171547652b82f};
        rom[301] = {51'h7fffffffe9065, 51'h0000007ad6fd8, 51'h7ffd1e4d067d3, 51'h1712653743f45};
        rom[302] = {51'h7fffffffe918a, 51'h0000007a92109, 51'h7ffd1f426f8d9, 51'h170f83ff0a756};
        rom[303] = {51'h7fffffffe92ae, 51'h0000007a4d5a8, 51'h7ffd20374efae, 51'h170ca3bbf52c2};
        rom[304] = {51'h7fffffffe93d1, 51'h0000007a08db4, 51'h7ffd212ba532e, 51'h1709c46d7aac7};
        rom[305] = {51'h7fffffffe94f3, 51'h00000079c4927, 51'h7ffd221f72a2d, 51'h1706e61311f7a};
        rom[306] = {51'h7fffffffe9613, 51'h00000079807ff, 51'h7ffd2312b7b77, 51'h170408ac327c1};
        rom[307] = {51'h7fffffffe9732, 51'h000000793ca38, 51'h7ffd240574dd1, 51'h17012c3854149};
        rom[308] = {51'h7fffffffe9850, 51'h00000078f8fcf, 51'h7ffd24f7aa7fb, 51'h16fe50b6ef085};
        rom[309] = {51'h7fffffffe996d, 51'h00000078b58bf, 51'h7ffd25e9590ac, 51'h16fb76277c09e};
        rom[310] = {51'h7fffffffe9a89, 51'h0000007872507, 51'h7ffd26da80e95, 51'h16f89c8974377};
        rom[311] = {51'h7fffffffe9ba3, 51'h000000782f4a1, 51'h7ffd27cb22860, 51'h16f5c3dc5119c};
        rom[312] = {51'h7fffffffe9cbd, 51'h00000077ec78b, 51'h7ffd28bb3e4b0, 51'h16f2ec1f8ca40};
        rom[313] = {51'h7fffffffe9dd5, 51'h00000077a9dc2, 51'h7ffd29aad4a20, 51'h16f01552a1339};
        rom[314] = {51'h7fffffffe9eec, 51'h0000007767742, 51'h7ffd2a99e5f47, 51'h16ed3f75098f0};
        rom[315] = {51'h7fffffffea002, 51'h0000007725407, 51'h7ffd2b8872ab3, 51'h16ea6a8640e65};
        rom[316] = {51'h7fffffffea117, 51'h00000076e340f, 51'h7ffd2c767b2eb, 51'h16e79685c2d22};
        rom[317] = {51'h7fffffffea22b, 51'h00000076a1755, 51'h7ffd2d63ffe72, 51'h16e4c3730b534};
        rom[318] = {51'h7fffffffea33e, 51'h000000765fdd8, 51'h7ffd2e51013c1, 51'h16e1f14d96d27};
        rom[319] = {51'h7fffffffea450, 51'h000000761e792, 51'h7ffd2f3d7f94d, 51'h16df2014e21fe};
        rom[320] = {51'h7fffffffea560, 51'h00000075dd482, 51'h7ffd30297b583, 51'h16dc4fc86a72d};
        rom[321] = {51'h7fffffffea670, 51'h000000759c4a3, 51'h7ffd3114f4ec9, 51'h16d98067ad691};
        rom[322] = {51'h7fffffffea77e, 51'h000000755b7f3, 51'h7ffd31ffecb7f, 51'h16d6b1f22906c};
        rom[323] = {51'h7fffffffea88c, 51'h000000751ae6d, 51'h7ffd32ea63201, 51'h16d3e4675bb5d};
        rom[324] = {51'h7fffffffea998, 51'h00000074da810, 51'h7ffd33d4588a0, 51'h16d117c6c4456};
        rom[325] = {51'h7fffffffeaaa3, 51'h000000749a4d8, 51'h7ffd34bdcd5aa, 51'h16ce4c0fe1e9f};
        rom[326] = {51'h7fffffffeabad, 51'h000000745a4c2, 51'h7ffd35a6c1f64, 51'h16cb8142343c4};
        rom[327] = {51'h7fffffffeacb6, 51'h000000741a7c9, 51'h7ffd368f36c10, 51'h16c8b75d3b397};
        rom[328] = {51'h7fffffffeadbe, 51'h00000073dadec, 51'h7ffd37772c1e7, 51'h16c5ee6077427};
        rom[329] = {51'h7fffffffeaec5, 51'h000000739b728, 51'h7ffd385ea271c, 51'h16c3264b691b8};
        rom[330] = {51'h7fffffffeafcb, 51'h000000735c378, 51'h7ffd39459a1dc, 51'h16c05f1d91ec1};
        rom[331] = {51'h7fffffffeb0d0, 51'h000000731d2da, 51'h7ffd3a2c1384e, 51'h16bd98d6733e0};
        rom[332] = {51'h7fffffffeb1d4, 51'h00000072de54b, 51'h7ffd3b120f093, 51'h16bad3758efd8};
        rom[333] = {51'h7fffffffeb2d7, 51'h000000729fac7, 51'h7ffd3bf78d0c5, 51'h16b80efa6778a};
        rom[334] = {51'h7fffffffeb3d9, 51'h000000726134d, 51'h7ffd3cdc8def9, 51'h16b54b647f5ed};
        rom[335] = {51'h7fffffffeb4da, 51'h0000007222ed7, 51'h7ffd3dc11213d, 51'h16b288b359c0c};
        rom[336] = {51'h7fffffffeb5da, 51'h00000071e4d65, 51'h7ffd3ea519d98, 51'h16afc6e67a0fa};
        rom[337] = {51'h7fffffffeb6d8, 51'h00000071a6ef1, 51'h7ffd3f88a5a0e, 51'h16ad05fd641d0};
        rom[338] = {51'h7fffffffeb7d6, 51'h000000716937a, 51'h7ffd406bb5c99, 51'h16aa45f79c1a7};
        rom[339] = {51'h7fffffffeb8d3, 51'h000000712bafd, 51'h7ffd414e4ab30, 51'h16a786d4a6991};
        rom[340] = {51'h7fffffffeb9cf, 51'h00000070ee576, 51'h7ffd423064bc3, 51'h16a4c89408891};
        rom[341] = {51'h7fffffffebaca, 51'h00000070b12e3, 51'h7ffd43120443c, 51'h16a20b3547399};
        rom[342] = {51'h7fffffffebbc4, 51'h0000007074340, 51'h7ffd43f329a7e, 51'h169f4eb7e8582};
        rom[343] = {51'h7fffffffebcbc, 51'h000000703768b, 51'h7ffd44d3d5469, 51'h169c931b71f04};
        rom[344] = {51'h7fffffffebdb4, 51'h0000006ffacc1, 51'h7ffd45b4077d5, 51'h1699d85f6a6b5};
        rom[345] = {51'h7fffffffebeab, 51'h0000006fbe5df, 51'h7ffd4693c0a93, 51'h16971e83588ff};
        rom[346] = {51'h7fffffffebfa1, 51'h0000006f821e1, 51'h7ffd477301271, 51'h16946586c381c};
        rom[347] = {51'h7fffffffec096, 51'h0000006f460c5, 51'h7ffd4851c9536, 51'h1691ad6932c10};
        rom[348] = {51'h7fffffffec18b, 51'h0000006f0a289, 51'h7ffd4930198a3, 51'h168ef62a2e2a2};
        rom[349] = {51'h7fffffffec27e, 51'h0000006ece729, 51'h7ffd4a0df2273, 51'h168c3fc93df58};
        rom[350] = {51'h7fffffffec370, 51'h0000006e92ea2, 51'h7ffd4aeb5385c, 51'h16898a45eab71};
        rom[351] = {51'h7fffffffec461, 51'h0000006e578f2, 51'h7ffd4bc83e00e, 51'h1686d59fbd5de};
        rom[352] = {51'h7fffffffec552, 51'h0000006e1c616, 51'h7ffd4ca4b1f33, 51'h168421d63f33f};
        rom[353] = {51'h7fffffffec641, 51'h0000006de160a, 51'h7ffd4d80afb71, 51'h16816ee8f9dda};
        rom[354] = {51'h7fffffffec72f, 51'h0000006da68cd, 51'h7ffd4e5c37a67, 51'h167ebcd777596};
        rom[355] = {51'h7fffffffec81d, 51'h0000006d6be5c, 51'h7ffd4f374a1ad, 51'h167c0ba141ffa};
        rom[356] = {51'h7fffffffec90a, 51'h0000006d316b3, 51'h7ffd5011e76d9, 51'h16795b45e4820};
        rom[357] = {51'h7fffffffec9f5, 51'h0000006cf71d0, 51'h7ffd50ec0ff79, 51'h1676abc4e9eb6};
        rom[358] = {51'h7fffffffecae0, 51'h0000006cbcfb0, 51'h7ffd51c5c4116, 51'h1673fd1ddd9f4};
        rom[359] = {51'h7fffffffecbca, 51'h0000006c83051, 51'h7ffd529f04134, 51'h16714f504b59b};
        rom[360] = {51'h7fffffffeccb3, 51'h0000006c493af, 51'h7ffd5377d0551, 51'h166ea25bbf2ea};
        rom[361] = {51'h7fffffffecd9b, 51'h0000006c0f9c9, 51'h7ffd5450292e5, 51'h166bf63fc589d};
        rom[362] = {51'h7fffffffece82, 51'h0000006bd629a, 51'h7ffd55280ef65, 51'h16694afbeb2e6};
        rom[363] = {51'h7fffffffecf69, 51'h0000006b9ce22, 51'h7ffd55ff8203e, 51'h1666a08fbd368};
        rom[364] = {51'h7fffffffed04e, 51'h0000006b63c5d, 51'h7ffd56d682ad9, 51'h1663f6fac9131};
        rom[365] = {51'h7fffffffed133, 51'h0000006b2ad48, 51'h7ffd57ad1149a, 51'h16614e3c9c8b5};
        rom[366] = {51'h7fffffffed217, 51'h0000006af20e0, 51'h7ffd58832e2de, 51'h165ea654c5bca};
        rom[367] = {51'h7fffffffed2f9, 51'h0000006ab9724, 51'h7ffd5958d9aff, 51'h165bff42d319f};
        rom[368] = {51'h7fffffffed3db, 51'h0000006a81011, 51'h7ffd5a2e14250, 51'h16595906536bc};
        rom[369] = {51'h7fffffffed4bd, 51'h0000006a48ba3, 51'h7ffd5b02dde20, 51'h1656b39ed5cf9};
        rom[370] = {51'h7fffffffed59d, 51'h0000006a109d9, 51'h7ffd5bd7373b8, 51'h16540f0be9b79};
        rom[371] = {51'h7fffffffed67c, 51'h00000069d8ab0, 51'h7ffd5cab2085d, 51'h16516b4d1eea7};
        rom[372] = {51'h7fffffffed75b, 51'h00000069a0e24, 51'h7ffd5d7e9a14c, 51'h164ec8620582f};
        rom[373] = {51'h7fffffffed838, 51'h0000006969435, 51'h7ffd5e51a43c1, 51'h164c264a2defa};
        rom[374] = {51'h7fffffffed915, 51'h0000006931cde, 51'h7ffd5f243f4ef, 51'h1649850528f28};
        rom[375] = {51'h7fffffffed9f1, 51'h00000068fa81f, 51'h7ffd5ff66ba07, 51'h1646e49287a0b};
        rom[376] = {51'h7fffffffedacd, 51'h00000068c35f3, 51'h7ffd60c829834, 51'h164444f1db622};
        rom[377] = {51'h7fffffffedba7, 51'h000000688c659, 51'h7ffd61997949a, 51'h1641a622b5f15};
        rom[378] = {51'h7fffffffedc80, 51'h000000685594e, 51'h7ffd626a5b45c, 51'h163f0824a95b0};
        rom[379] = {51'h7fffffffedd59, 51'h000000681eecf, 51'h7ffd633acfc94, 51'h163c6af747fd9};
        rom[380] = {51'h7fffffffede31, 51'h00000067e86db, 51'h7ffd640ad7259, 51'h1639ce9a24896};
        rom[381] = {51'h7fffffffedf08, 51'h00000067b216f, 51'h7ffd64da71abd, 51'h1637330cd1ffb};
        rom[382] = {51'h7fffffffedfde, 51'h000000677be87, 51'h7ffd65a99face, 51'h1634984ee3b2f};
        rom[383] = {51'h7fffffffee0b4, 51'h0000006745e23, 51'h7ffd667861793, 51'h1631fe5fed463};
        rom[384] = {51'h7fffffffee189, 51'h000000671003f, 51'h7ffd6746b760f, 51'h162f653f82acd};
        rom[385] = {51'h7fffffffee25c, 51'h00000066da4d9, 51'h7ffd6814a1b42, 51'h162ccced382a4};
        rom[386] = {51'h7fffffffee330, 51'h00000066a4bef, 51'h7ffd68e220c24, 51'h162a3568a251c};
        rom[387] = {51'h7fffffffee402, 51'h000000666f57e, 51'h7ffd69af34daa, 51'h16279eb15605e};
        rom[388] = {51'h7fffffffee4d3, 51'h000000663a183, 51'h7ffd6a7bde4c5, 51'h162508c6e8788};
        rom[389] = {51'h7fffffffee5a4, 51'h0000006604ffd, 51'h7ffd6b481d660, 51'h162273a8ef2a4};
        rom[390] = {51'h7fffffffee674, 51'h00000065d00ea, 51'h7ffd6c13f2761, 51'h161fdf56ffea5};
        rom[391] = {51'h7fffffffee743, 51'h000000659b446, 51'h7ffd6cdf5dcaa, 51'h161d4bd0b0d64};
        rom[392] = {51'h7fffffffee811, 51'h0000006566a0f, 51'h7ffd6daa5fb19, 51'h161ab91598597};
        rom[393] = {51'h7fffffffee8df, 51'h0000006532244, 51'h7ffd6e74f8787, 51'h161827254d2d2};
        rom[394] = {51'h7fffffffee9ac, 51'h00000064fdce2, 51'h7ffd6f3f286c6, 51'h161595ff6657c};
        rom[395] = {51'h7fffffffeea78, 51'h00000064c99e6, 51'h7ffd7008efda6, 51'h161305a37b2cf};
        rom[396] = {51'h7fffffffeeb43, 51'h000000649594e, 51'h7ffd70d24f0f3, 51'h16107611234d3};
        rom[397] = {51'h7fffffffeec0e, 51'h0000006461b18, 51'h7ffd719b46572, 51'h160de747f6a57};
        rom[398] = {51'h7fffffffeecd8, 51'h000000642df42, 51'h7ffd7263d5fe5, 51'h160b59478d6ee};
        rom[399] = {51'h7fffffffeeda1, 51'h00000063fa5c9, 51'h7ffd732bfe509, 51'h1608cc0f802ed};
        rom[400] = {51'h7fffffffeee69, 51'h00000063c6eac, 51'h7ffd73f3bf996, 51'h16063f9f67b5f};
        rom[401] = {51'h7fffffffeef31, 51'h00000063939e7, 51'h7ffd74bb1a242, 51'h1603b3f6dd20b};
        rom[402] = {51'h7fffffffeeff7, 51'h0000006360779, 51'h7ffd75820e3ba, 51'h1601291579d64};
        rom[403] = {51'h7fffffffef0be, 51'h000000632d760, 51'h7ffd76489c2ac, 51'h15fe9efad788f};
        rom[404] = {51'h7fffffffef183, 51'h00000062fa999, 51'h7ffd770ec43bc, 51'h15fc15a690358};
        rom[405] = {51'h7fffffffef248, 51'h00000062c7e21, 51'h7ffd77d486b8f, 51'h15f98d183e230};
        rom[406] = {51'h7fffffffef30b, 51'h00000062954f8, 51'h7ffd7899e3ec1, 51'h15f7054f7be28};
        rom[407] = {51'h7fffffffef3cf, 51'h0000006262e1b, 51'h7ffd795edc1ec, 51'h15f47e4be44ec};
        rom[408] = {51'h7fffffffef491, 51'h0000006230987, 51'h7ffd7a236f9a6, 51'h15f1f80d128c2};
        rom[409] = {51'h7fffffffef553, 51'h00000061fe73a, 51'h7ffd7ae79ea80, 51'h15ef7292a2080};
        rom[410] = {51'h7fffffffef614, 51'h00000061cc733, 51'h7ffd7bab69905, 51'h15eceddc2e78d};
        rom[411] = {51'h7fffffffef6d4, 51'h000000619a96f, 51'h7ffd7c6ed09c0, 51'h15ea69e953dda};
        rom[412] = {51'h7fffffffef794, 51'h0000006168dec, 51'h7ffd7d31d4133, 51'h15e7e6b9ae7dd};
        rom[413] = {51'h7fffffffef853, 51'h00000061374a8, 51'h7ffd7df4743de, 51'h15e5644cdae8f};
        rom[414] = {51'h7fffffffef911, 51'h0000006105da0, 51'h7ffd7eb6b163d, 51'h15e2e2a275f68};
        rom[415] = {51'h7fffffffef9cf, 51'h00000060d48d3, 51'h7ffd7f788bcc8, 51'h15e061ba1cc56};
        rom[416] = {51'h7fffffffefa8b, 51'h00000060a363f, 51'h7ffd803a03bf2, 51'h15dde1936cbc0};
        rom[417] = {51'h7fffffffefb47, 51'h00000060725e1, 51'h7ffd80fb19829, 51'h15db622e0387c};
        rom[418] = {51'h7fffffffefc03, 51'h00000060417b8, 51'h7ffd81bbcd5d9, 51'h15d8e3897f1ce};
        rom[419] = {51'h7fffffffefcbe, 51'h0000006010bc1, 51'h7ffd827c1f969, 51'h15d665a57db62};
        rom[420] = {51'h7fffffffefd78, 51'h0000005fe01fa, 51'h7ffd833c1073a, 51'h15d3e8819dd49};
        rom[421] = {51'h7fffffffefe31, 51'h0000005fafa61, 51'h7ffd83fba03ad, 51'h15d16c1d7e3f5};
        rom[422] = {51'h7fffffffefeea, 51'h0000005f7f4f5, 51'h7ffd84bacf31a, 51'h15cef078be034};
        rom[423] = {51'h7fffffffeffa2, 51'h0000005f4f1b3, 51'h7ffd85799d9d9, 51'h15cc7592fc72d};
        rom[424] = {51'h7ffffffff0059, 51'h0000005f1f099, 51'h7ffd86380bc3c, 51'h15c9fb6bd925b};
        rom[425] = {51'h7ffffffff0110, 51'h0000005eef1a5, 51'h7ffd86f619e91, 51'h15c78202f3f89};
        rom[426] = {51'h7ffffffff01c6, 51'h0000005ebf4d6, 51'h7ffd87b3c8522, 51'h15c50957ed0cf};
        rom[427] = {51'h7ffffffff027c, 51'h0000005e8fa28, 51'h7ffd887117437, 51'h15c2916a64c8d};
        rom[428] = {51'h7ffffffff0330, 51'h0000005e6019b, 51'h7ffd892e07011, 51'h15c01a39fbd68};
        rom[429] = {51'h7ffffffff03e4, 51'h0000005e30b2c, 51'h7ffd89ea97cef, 51'h15bda3c653244};
        rom[430] = {51'h7ffffffff0498, 51'h0000005e016da, 51'h7ffd8aa6c9f0b, 51'h15bb2e0f0be44};
        rom[431] = {51'h7ffffffff054b, 51'h0000005dd24a1, 51'h7ffd8b629da9c, 51'h15b8b913c78bf};
        rom[432] = {51'h7ffffffff05fd, 51'h0000005da3481, 51'h7ffd8c1e133d4, 51'h15b644d427d47};
        rom[433] = {51'h7ffffffff06ae, 51'h0000005d74678, 51'h7ffd8cd92aee3, 51'h15b3d14fceb99};
        rom[434] = {51'h7ffffffff075f, 51'h0000005d45a83, 51'h7ffd8d93e4ff3, 51'h15b15e865e7a2};
        rom[435] = {51'h7ffffffff080f, 51'h0000005d170a0, 51'h7ffd8e4e41b2c, 51'h15aeec7779977};
        rom[436] = {51'h7ffffffff08bf, 51'h0000005ce88ce, 51'h7ffd8f08414b0, 51'h15ac7b22c2d52};
        rom[437] = {51'h7ffffffff096e, 51'h0000005cba30b, 51'h7ffd8fc1e40a0, 51'h15aa0a87dd390};
        rom[438] = {51'h7ffffffff0a1c, 51'h0000005c8bf55, 51'h7ffd907b2a317, 51'h15a79aa66c0aa};
        rom[439] = {51'h7ffffffff0aca, 51'h0000005c5ddaa, 51'h7ffd91341402c, 51'h15a52b7e12d32};
        rom[440] = {51'h7ffffffff0b77, 51'h0000005c2fe08, 51'h7ffd91eca1bf4, 51'h15a2bd0e755d2};
        rom[441] = {51'h7ffffffff0c24, 51'h0000005c0206e, 51'h7ffd92a4d3a7f, 51'h15a04f5737b45};
        rom[442] = {51'h7ffffffff0ccf, 51'h0000005bd44d8, 51'h7ffd935ca9fda, 51'h159de257fe255};
        rom[443] = {51'h7ffffffff0d7b, 51'h0000005ba6b46, 51'h7ffd94142500e, 51'h159b76106d3d7};
        rom[444] = {51'h7ffffffff0e25, 51'h0000005b793b6, 51'h7ffd94cb44f20, 51'h15990a8029ca6};
        rom[445] = {51'h7ffffffff0ecf, 51'h0000005b4be26, 51'h7ffd95820a112, 51'h15969fa6d8da2};
        rom[446] = {51'h7ffffffff0f79, 51'h0000005b1ea94, 51'h7ffd9638749e1, 51'h159435841fba9};
        rom[447] = {51'h7ffffffff1021, 51'h0000005af18fe, 51'h7ffd96ee84d88, 51'h1591cc17a3f96};
        rom[448] = {51'h7ffffffff10ca, 51'h0000005ac4962, 51'h7ffd97a43affd, 51'h158f63610b63d};
        rom[449] = {51'h7ffffffff1171, 51'h0000005a97bbf, 51'h7ffd985997533, 51'h158cfb5ffc065};
        rom[450] = {51'h7ffffffff1218, 51'h0000005a6b013, 51'h7ffd990e9a11a, 51'h158a94141c2c9};
        rom[451] = {51'h7ffffffff12bf, 51'h0000005a3e65c, 51'h7ffd99c34379e, 51'h15882d7d1260f};
        rom[452] = {51'h7ffffffff1364, 51'h0000005a11e98, 51'h7ffd9a7793ca7, 51'h1585c79a856c8};
        rom[453] = {51'h7ffffffff140a, 51'h00000059e58c6, 51'h7ffd9b2b8b419, 51'h1583626c1c56c};
        rom[454] = {51'h7ffffffff14ae, 51'h00000059b94e3, 51'h7ffd9bdf2a1d6, 51'h1580fdf17e654};
        rom[455] = {51'h7ffffffff1552, 51'h000000598d2ee, 51'h7ffd9c92709bb, 51'h157e9a2a531bb};
        rom[456] = {51'h7ffffffff15f6, 51'h00000059612e5, 51'h7ffd9d455efa3, 51'h157c3716423b6};
        rom[457] = {51'h7ffffffff1699, 51'h00000059354c7, 51'h7ffd9df7f5763, 51'h1579d4b4f3c34};
        rom[458] = {51'h7ffffffff173b, 51'h0000005909892, 51'h7ffd9eaa344d0, 51'h157773060fef7};
        rom[459] = {51'h7ffffffff17dd, 51'h00000058dde43, 51'h7ffd9f5c1bbb9, 51'h157512093f394};
        rom[460] = {51'h7ffffffff187e, 51'h00000058b25da, 51'h7ffda00dabfea, 51'h1572b1be2a56d};
        rom[461] = {51'h7ffffffff191f, 51'h0000005886f54, 51'h7ffda0bee552c, 51'h157052247a3b0};
        rom[462] = {51'h7ffffffff19bf, 51'h000000585bab0, 51'h7ffda16fc7f45, 51'h156df33bd814f};
        rom[463] = {51'h7ffffffff1a5e, 51'h00000058307ed, 51'h7ffda220541f6, 51'h156b9503ed503};
        rom[464] = {51'h7ffffffff1afd, 51'h0000005805708, 51'h7ffda2d08a0fe, 51'h1569377c63943};
        rom[465] = {51'h7ffffffff1b9c, 51'h00000057da7ff, 51'h7ffda3806a018, 51'h1566daa4e4c46};
        rom[466] = {51'h7ffffffff1c39, 51'h00000057afad2, 51'h7ffda42ff42fd, 51'h15647e7d1aff9};
        rom[467] = {51'h7ffffffff1cd7, 51'h0000005784f7e, 51'h7ffda4df28d60, 51'h15622304b0a01};
        rom[468] = {51'h7ffffffff1d73, 51'h000000575a602, 51'h7ffda58e082f4, 51'h155fc83b503b6};
        rom[469] = {51'h7ffffffff1e0f, 51'h000000572fe5c, 51'h7ffda63c92765, 51'h155d6e20a4a1f};
        rom[470] = {51'h7ffffffff1eab, 51'h000000570588b, 51'h7ffda6eac7e5f, 51'h155b14b458def};
        rom[471] = {51'h7ffffffff1f46, 51'h00000056db48c, 51'h7ffda798a8b89, 51'h1558bbf618384};
        rom[472] = {51'h7ffffffff1fe1, 51'h00000056b125f, 51'h7ffda84635287, 51'h155663e58e2df};
        rom[473] = {51'h7ffffffff207b, 51'h0000005687201, 51'h7ffda8f36d6f9, 51'h15540c82667a5};
        rom[474] = {51'h7ffffffff2114, 51'h000000565d371, 51'h7ffda9a051c7e, 51'h1551b5cc4d11a};
        rom[475] = {51'h7ffffffff21ad, 51'h00000056336ae, 51'h7ffdaa4ce26b0, 51'h154f5fc2ee21d};
        rom[476] = {51'h7ffffffff2245, 51'h0000005609bb5, 51'h7ffdaaf91f925, 51'h154d0a65f6128};
        rom[477] = {51'h7ffffffff22dd, 51'h00000055e0285, 51'h7ffdaba509772, 51'h154ab5b511847};
        rom[478] = {51'h7ffffffff2375, 51'h00000055b6b1d, 51'h7ffdac50a0527, 51'h154861afed51b};
        rom[479] = {51'h7ffffffff240b, 51'h000000558d57b, 51'h7ffdacfbe45d3, 51'h15460e56368d5};
        rom[480] = {51'h7ffffffff24a2, 51'h000000556419e, 51'h7ffdada6d5cfe, 51'h1543bba79a82e};
        rom[481] = {51'h7ffffffff2537, 51'h000000553af83, 51'h7ffdae5174e32, 51'h154169a3c6b6c};
        rom[482] = {51'h7ffffffff25cd, 51'h0000005511f2a, 51'h7ffdaefbc1cf1, 51'h153f184a68e58};
        rom[483] = {51'h7ffffffff2661, 51'h00000054e9090, 51'h7ffdafa5bccbd, 51'h153cc79b2f03f};
        rom[484] = {51'h7ffffffff26f6, 51'h00000054c03b4, 51'h7ffdb04f66113, 51'h153a7795c73ed};
        rom[485] = {51'h7ffffffff2789, 51'h0000005497895, 51'h7ffdb0f8bdd6f, 51'h15382839dffaa};
        rom[486] = {51'h7ffffffff281d, 51'h000000546ef31, 51'h7ffdb1a1c4548, 51'h1535d98727d38};
        rom[487] = {51'h7ffffffff28af, 51'h0000005446787, 51'h7ffdb24a79c13, 51'h15338b7d4d9ce};
        rom[488] = {51'h7ffffffff2941, 51'h000000541e195, 51'h7ffdb2f2de541, 51'h15313e1c00617};
        rom[489] = {51'h7ffffffff29d3, 51'h00000053f5d59, 51'h7ffdb39af2442, 51'h152ef162ef62f};
        rom[490] = {51'h7ffffffff2a64, 51'h00000053cdad3, 51'h7ffdb442b5c80, 51'h152ca551ca19d};
        rom[491] = {51'h7ffffffff2af5, 51'h00000053a59ff, 51'h7ffdb4ea29163, 51'h152a59e840353};
        rom[492] = {51'h7ffffffff2b85, 51'h000000537dade, 51'h7ffdb5914c653, 51'h15280f26019ab};
        rom[493] = {51'h7ffffffff2c15, 51'h0000005355d6d, 51'h7ffdb6381feb0, 51'h1525c50abe661};
        rom[494] = {51'h7ffffffff2ca4, 51'h000000532e1ac, 51'h7ffdb6dea3ddb, 51'h15237b9626e93};
        rom[495] = {51'h7ffffffff2d33, 51'h0000005306798, 51'h7ffdb784d8731, 51'h152132c7ebabe};
        rom[496] = {51'h7ffffffff2dc1, 51'h00000052def30, 51'h7ffdb82abde0a, 51'h151eea9fbd6b9};
        rom[497] = {51'h7ffffffff2e4f, 51'h00000052b7872, 51'h7ffdb8d0545be, 51'h151ca31d4d1b4};
        rom[498] = {51'h7ffffffff2edc, 51'h000000529035e, 51'h7ffdb9759c1a0, 51'h151a5c404be32};
        rom[499] = {51'h7ffffffff2f69, 51'h0000005268ff2, 51'h7ffdba1a95501, 51'h151816086b20c};
        rom[500] = {51'h7ffffffff2ff5, 51'h0000005241e2b, 51'h7ffdbabf4032f, 51'h1515d0755c667};
        rom[501] = {51'h7ffffffff3081, 51'h000000521ae0a, 51'h7ffdbb639cf76, 51'h15138b86d17b6};
        rom[502] = {51'h7ffffffff310c, 51'h00000051f3f8c, 51'h7ffdbc07abd1d, 51'h1511473c7c5b6};
        rom[503] = {51'h7ffffffff3197, 51'h00000051cd2b0, 51'h7ffdbcab6cf69, 51'h150f03960f36a};
        rom[504] = {51'h7ffffffff3221, 51'h00000051a6774, 51'h7ffdbd4ee099e, 51'h150cc0933c71a};
        rom[505] = {51'h7ffffffff32ab, 51'h000000517fdd7, 51'h7ffdbdf206efa, 51'h150a7e33b6a4d};
        rom[506] = {51'h7ffffffff3334, 51'h00000051595d9, 51'h7ffdbe94e02bc, 51'h15083c77309ca};
        rom[507] = {51'h7ffffffff33bd, 51'h0000005132f76, 51'h7ffdbf376c81b, 51'h1505fb5d5d593};
        rom[508] = {51'h7ffffffff3446, 51'h000000510caae, 51'h7ffdbfd9ac251, 51'h1503bae5f00e1};
        rom[509] = {51'h7ffffffff34ce, 51'h00000050e6780, 51'h7ffdc07b9f490, 51'h15017b109c227};
        rom[510] = {51'h7ffffffff3556, 51'h00000050c05ea, 51'h7ffdc11d4620c, 51'h14ff3bdd15305};
        rom[511] = {51'h7ffffffff35dd, 51'h000000509a5eb, 51'h7ffdc1bea0df1, 51'h14fcfd4b0f050};
        rom[512] = {51'h7ffffffff3663, 51'h0000005074781, 51'h7ffdc25fafb6e, 51'h14fabf5a3da09};
        rom[513] = {51'h7ffffffff36e9, 51'h000000504eaab, 51'h7ffdc30072daa, 51'h14f8820a5535b};
        rom[514] = {51'h7ffffffff376f, 51'h0000005028f67, 51'h7ffdc3a0ea7cd, 51'h14f6455b0a29a};
        rom[515] = {51'h7ffffffff37f5, 51'h00000050035b5, 51'h7ffdc44116cfa, 51'h14f4094c1113e};
        rom[516] = {51'h7ffffffff3879, 51'h0000004fddd93, 51'h7ffdc4e0f8053, 51'h14f1cddd1ebe2};
        rom[517] = {51'h7ffffffff38fe, 51'h0000004fb86ff, 51'h7ffdc5808e4f6, 51'h14ef930de8242};
        rom[518] = {51'h7ffffffff3982, 51'h0000004f931f9, 51'h7ffdc61fd9dfe, 51'h14ed58de22735};
        rom[519] = {51'h7ffffffff3a05, 51'h0000004f6de7e, 51'h7ffdc6bedae86, 51'h14eb1f4d830ae};
        rom[520] = {51'h7ffffffff3a88, 51'h0000004f48c8e, 51'h7ffdc75d919a2, 51'h14e8e65bbf7b7};
        rom[521] = {51'h7ffffffff3b0b, 51'h0000004f23c27, 51'h7ffdc7fbfe267, 51'h14e6ae088d86f};
        rom[522] = {51'h7ffffffff3b8d, 51'h0000004efed48, 51'h7ffdc89a20be7, 51'h14e47653a3208};
        rom[523] = {51'h7ffffffff3c0f, 51'h0000004ed9ff0, 51'h7ffdc937f992f, 51'h14e23f3cb66c4};
        rom[524] = {51'h7ffffffff3c90, 51'h0000004eb541c, 51'h7ffdc9d588d4b, 51'h14e008c37dbf2};
        rom[525] = {51'h7ffffffff3d11, 51'h0000004e909cd, 51'h7ffdca72ceb45, 51'h14ddd2e7af9e9};
        rom[526] = {51'h7ffffffff3d92, 51'h0000004e6c101, 51'h7ffdcb0fcb622, 51'h14db9da902c0c};
        rom[527] = {51'h7ffffffff3e12, 51'h0000004e479b6, 51'h7ffdcbac7f0e9, 51'h14d969072e0c1};
        rom[528] = {51'h7ffffffff3e91, 51'h0000004e233ea, 51'h7ffdcc48e9e98, 51'h14d73501e8970};
        rom[529] = {51'h7ffffffff3f10, 51'h0000004dfef9e, 51'h7ffdcce50c231, 51'h14d50198e9a84};
        rom[530] = {51'h7ffffffff3f8f, 51'h0000004ddaccf, 51'h7ffdcd80e5eae, 51'h14d2cecbe8b63};
        rom[531] = {51'h7ffffffff400d, 51'h0000004db6b7d, 51'h7ffdce1c77709, 51'h14d09c9a9d66f};
        rom[532] = {51'h7ffffffff408b, 51'h0000004d92ba5, 51'h7ffdceb7c0e3b, 51'h14ce6b04bf903};
        rom[533] = {51'h7ffffffff4109, 51'h0000004d6ed47, 51'h7ffdcf52c2737, 51'h14cc3a0a0736f};
        rom[534] = {51'h7ffffffff4186, 51'h0000004d4b062, 51'h7ffdcfed7c4f0, 51'h14ca09aa2c8f6};
        rom[535] = {51'h7ffffffff4203, 51'h0000004d274f4, 51'h7ffdd087eea55, 51'h14c7d9e4e7fce};
        rom[536] = {51'h7ffffffff427f, 51'h0000004d03afc, 51'h7ffdd12219a54, 51'h14c5aab9f2119};
        rom[537] = {51'h7ffffffff42fb, 51'h0000004ce0278, 51'h7ffdd1bbfd7d7, 51'h14c37c29038e7};
        rom[538] = {51'h7ffffffff4376, 51'h0000004cbcb68, 51'h7ffdd2559a5c6, 51'h14c14e31d5631};
        rom[539] = {51'h7ffffffff43f1, 51'h0000004c995ca, 51'h7ffdd2eef0708, 51'h14bf20d420ad5};
        rom[540] = {51'h7ffffffff446c, 51'h0000004c7619e, 51'h7ffdd387ffe7f, 51'h14bcf40f9eb98};
        rom[541] = {51'h7ffffffff44e6, 51'h0000004c52ee1, 51'h7ffdd420c8f0c, 51'h14bac7e409020};
        rom[542] = {51'h7ffffffff4560, 51'h0000004c2fd92, 51'h7ffdd4b94bb8e, 51'h14b89c51192f3};
        rom[543] = {51'h7ffffffff45d9, 51'h0000004c0cdb1, 51'h7ffdd551886e1, 51'h14b6715689173};
        rom[544] = {51'h7ffffffff4652, 51'h0000004be9f3d, 51'h7ffdd5e97f3de, 51'h14b446f412bde};
        rom[545] = {51'h7ffffffff46cb, 51'h0000004bc7233, 51'h7ffdd6813055c, 51'h14b21d297054a};
        rom[546] = {51'h7ffffffff4743, 51'h0000004ba4693, 51'h7ffdd7189be30, 51'h14aff3f65c3a3};
        rom[547] = {51'h7ffffffff47bb, 51'h0000004b81c5b, 51'h7ffdd7afc212d, 51'h14adcb5a90fa9};
        rom[548] = {51'h7ffffffff4832, 51'h0000004b5f38b, 51'h7ffdd846a3122, 51'h14aba355c94ec};
        rom[549] = {51'h7ffffffff48a9, 51'h0000004b3cc21, 51'h7ffdd8dd3f0dd, 51'h14a97be7c01cb};
        rom[550] = {51'h7ffffffff4920, 51'h0000004b1a61c, 51'h7ffdd9739632a, 51'h14a7551030773};
        rom[551] = {51'h7ffffffff4996, 51'h0000004af817c, 51'h7ffdda09a8ad1, 51'h14a52eced59d9};
        rom[552] = {51'h7ffffffff4a0c, 51'h0000004ad5e3d, 51'h7ffdda9f76a98, 51'h14a309236afbb};
        rom[553] = {51'h7ffffffff4a81, 51'h0000004ab3c61, 51'h7ffddb3500545, 51'h14a0e40dac29c};
        rom[554] = {51'h7ffffffff4af6, 51'h0000004a91be4, 51'h7ffddbca45d98, 51'h149ebf8d54ec2};
        rom[555] = {51'h7ffffffff4b6b, 51'h0000004a6fcc7, 51'h7ffddc5f47652, 51'h149c9ba221335};
        rom[556] = {51'h7ffffffff4bdf, 51'h0000004a4df08, 51'h7ffddcf40522f, 51'h149a784bcd1b8};
        rom[557] = {51'h7ffffffff4c53, 51'h0000004a2c2a6, 51'h7ffddd887f3ec, 51'h1498558a14ecf};
        rom[558] = {51'h7ffffffff4cc7, 51'h0000004a0a7a0, 51'h7ffdde1cb5e40, 51'h1496335cb51b4};
        rom[559] = {51'h7ffffffff4d3a, 51'h00000049e8df4, 51'h7ffddeb0a93e1, 51'h149411c36a45a};
        rom[560] = {51'h7ffffffff4dad, 51'h00000049c75a2, 51'h7ffddf4459785, 51'h1491f0bdf1369};
        rom[561] = {51'h7ffffffff4e1f, 51'h00000049a5ea8, 51'h7ffddfd7c6bdd, 51'h148fd04c06e3c};
        rom[562] = {51'h7ffffffff4e91, 51'h0000004984905, 51'h7ffde06af1399, 51'h148db06d686e1};
        rom[563] = {51'h7ffffffff4f03, 51'h00000049634b9, 51'h7ffde0fdd9165, 51'h148b9121d3210};
        rom[564] = {51'h7ffffffff4f74, 51'h00000049421c2, 51'h7ffde1907e7ef, 51'h1489726904731};
        rom[565] = {51'h7ffffffff4fe5, 51'h000000492101e, 51'h7ffde222e19dd, 51'h14875442ba056};
        rom[566] = {51'h7ffffffff5056, 51'h00000048fffce, 51'h7ffde2b5029d7, 51'h148536aeb1a36};
        rom[567] = {51'h7ffffffff50c6, 51'h00000048df0cf, 51'h7ffde346e1a82, 51'h148319aca9431};
        rom[568] = {51'h7ffffffff5136, 51'h00000048be321, 51'h7ffde3d87ee81, 51'h1480fd3c5f049};
        rom[569] = {51'h7ffffffff51a5, 51'h000000489d6c2, 51'h7ffde469da872, 51'h147ee15d91320};
        rom[570] = {51'h7ffffffff5214, 51'h000000487cbb2, 51'h7ffde4faf4af4, 51'h147cc60ffe3fa};
        rom[571] = {51'h7ffffffff5283, 51'h000000485c1f0, 51'h7ffde58bcd8a4, 51'h147aab5364cb5};
        rom[572] = {51'h7ffffffff52f2, 51'h000000483b979, 51'h7ffde61c6541a, 51'h14789127839cc};
        rom[573] = {51'h7ffffffff5360, 51'h000000481b24e, 51'h7ffde6acbbfef, 51'h1476778c19a50};
        rom[574] = {51'h7ffffffff53cd, 51'h00000047fac6d, 51'h7ffde73cd1eb7, 51'h14745e80e5fed};
        rom[575] = {51'h7ffffffff543b, 51'h00000047da7d5, 51'h7ffde7cca7306, 51'h14724605a7ede};
        rom[576] = {51'h7ffffffff54a8, 51'h00000047ba485, 51'h7ffde85c3bf6d, 51'h14702e1a1edf4};
        rom[577] = {51'h7ffffffff5514, 51'h000000479a27c, 51'h7ffde8eb9067c, 51'h146e16be0a68e};
        rom[578] = {51'h7ffffffff5581, 51'h000000477a1b9, 51'h7ffde97aa4abe, 51'h146bfff12a499};
        rom[579] = {51'h7ffffffff55ed, 51'h000000475a23b, 51'h7ffdea0978ebf, 51'h1469e9b33e691};
        rom[580] = {51'h7ffffffff5658, 51'h000000473a400, 51'h7ffdea980d507, 51'h1467d40406d77};
        rom[581] = {51'h7ffffffff56c3, 51'h000000471a709, 51'h7ffdeb266201e, 51'h1465bee343cd7};
        rom[582] = {51'h7ffffffff572e, 51'h00000046fab53, 51'h7ffdebb477287, 51'h1463aa50b5ac1};
        rom[583] = {51'h7ffffffff5799, 51'h00000046db0de, 51'h7ffdec424cec6, 51'h1461964c1cfca};
        rom[584] = {51'h7ffffffff5803, 51'h00000046bb7a9, 51'h7ffdeccfe375a, 51'h145f82d53a707};
        rom[585] = {51'h7ffffffff586d, 51'h000000469bfb2, 51'h7ffded5d3aec2, 51'h145d6febcee0c};
        rom[586] = {51'h7ffffffff58d7, 51'h000000467c8f9, 51'h7ffdedea5377a, 51'h145b5d8f9b4ed};
        rom[587] = {51'h7ffffffff5940, 51'h000000465d37d, 51'h7ffdee772d3fd, 51'h14594bc060e36};
        rom[588] = {51'h7ffffffff59a9, 51'h000000463df3c, 51'h7ffdef03c86c3, 51'h14573a7de0ef0};
        rom[589] = {51'h7ffffffff5a11, 51'h000000461ec36, 51'h7ffdef9025241, 51'h145529c7dce97};
        rom[590] = {51'h7ffffffff5a79, 51'h00000045ffa69, 51'h7ffdf01c438ee, 51'h1453199e1671f};
        rom[591] = {51'h7ffffffff5ae1, 51'h00000045e09d6, 51'h7ffdf0a823d3a, 51'h14510a004f4f0};
        rom[592] = {51'h7ffffffff5b49, 51'h00000045c1a79, 51'h7ffdf133c6195, 51'h144efaee496e0};
        rom[593] = {51'h7ffffffff5bb0, 51'h00000045a2c54, 51'h7ffdf1bf2a86f, 51'h144cec67c6e38};
        rom[594] = {51'h7ffffffff5c17, 51'h0000004583f64, 51'h7ffdf24a51434, 51'h144ade6c89eab};
        rom[595] = {51'h7ffffffff5c7d, 51'h00000045653a8, 51'h7ffdf2d53a74d, 51'h1448d0fc54e59};
        rom[596] = {51'h7ffffffff5ce4, 51'h0000004546921, 51'h7ffdf35fe6423, 51'h1446c416ea5cc};
        rom[597] = {51'h7ffffffff5d4a, 51'h0000004527fcc, 51'h7ffdf3ea54d1c, 51'h1444b7bc0cff3};
        rom[598] = {51'h7ffffffff5daf, 51'h00000045097a9, 51'h7ffdf4748649e, 51'h1442abeb7fa25};
        rom[599] = {51'h7ffffffff5e14, 51'h00000044eb0b6, 51'h7ffdf4fe7ad0a, 51'h1440a0a50541b};
        rom[600] = {51'h7ffffffff5e79, 51'h00000044ccaf4, 51'h7ffdf588328c0, 51'h143e95e860fef};
        rom[601] = {51'h7ffffffff5ede, 51'h00000044ae660, 51'h7ffdf611ada21, 51'h143c8bb55621d};
        rom[602] = {51'h7ffffffff5f42, 51'h00000044902fa, 51'h7ffdf69aec388, 51'h143a820ba817c};
        rom[603] = {51'h7ffffffff5fa6, 51'h00000044720c1, 51'h7ffdf723ee750, 51'h143878eb1a740};
        rom[604] = {51'h7ffffffff600a, 51'h0000004453fb4, 51'h7ffdf7acb47d1, 51'h1436705370ef7};
        rom[605] = {51'h7ffffffff606d, 51'h0000004435fd2, 51'h7ffdf8353e765, 51'h143468446f687};
        rom[606] = {51'h7ffffffff60d0, 51'h000000441811b, 51'h7ffdf8bd8c85e, 51'h143260bdd9e2b};
        rom[607] = {51'h7ffffffff6133, 51'h00000043fa38c, 51'h7ffdf9459ed10, 51'h143059bf74874};
        rom[608] = {51'h7ffffffff6196, 51'h00000043dc725, 51'h7ffdf9cd757ce, 51'h142e534903a43};
        rom[609] = {51'h7ffffffff61f8, 51'h00000043bebe6, 51'h7ffdfa5510ae6, 51'h142c4d5a4bacc};
        rom[610] = {51'h7ffffffff625a, 51'h00000043a11cd, 51'h7ffdfadc708a5, 51'h142a47f311390};
        rom[611] = {51'h7ffffffff62bb, 51'h00000043838da, 51'h7ffdfb6395359, 51'h142843131905c};
        rom[612] = {51'h7ffffffff631c, 51'h000000436610b, 51'h7ffdfbea7ed4a, 51'h14263eba27f4a};
        rom[613] = {51'h7ffffffff637d, 51'h0000004348a60, 51'h7ffdfc712d8c1, 51'h14243ae8030bb};
        rom[614] = {51'h7ffffffff63de, 51'h000000432b4d7, 51'h7ffdfcf7a1804, 51'h1422379c6f75a};
        rom[615] = {51'h7ffffffff643e, 51'h000000430e070, 51'h7ffdfd7ddad58, 51'h142034d732813};
        rom[616] = {51'h7ffffffff649e, 51'h00000042f0d2a, 51'h7ffdfe03d9aff, 51'h141e329811a19};
        rom[617] = {51'h7ffffffff64fe, 51'h00000042d3b04, 51'h7ffdfe899e339, 51'h141c30ded26e0};
        rom[618] = {51'h7ffffffff655d, 51'h00000042b69fd, 51'h7ffdff0f28847, 51'h141a2fab3aa1c};
        rom[619] = {51'h7ffffffff65bc, 51'h0000004299a15, 51'h7ffdff9478c65, 51'h14182efd101bd};
        rom[620] = {51'h7ffffffff661b, 51'h000000427cb49, 51'h7ffe00198f1cf, 51'h14162ed418df3};
        rom[621] = {51'h7ffffffff6679, 51'h000000425fd9a, 51'h7ffe009e6babe, 51'h14142f301b127};
        rom[622] = {51'h7ffffffff66d8, 51'h0000004243106, 51'h7ffe01230e96a, 51'h14123010dcff8};
        rom[623] = {51'h7ffffffff6736, 51'h000000422658d, 51'h7ffe01a77800a, 51'h1410317625141};
        rom[624] = {51'h7ffffffff6793, 51'h0000004209b2e, 51'h7ffe022ba80d1, 51'h140e335fb9e0e};
        rom[625] = {51'h7ffffffff67f1, 51'h00000041ed1e8, 51'h7ffe02af9edf3, 51'h140c35cd621a1};
        rom[626] = {51'h7ffffffff684e, 51'h00000041d09b9, 51'h7ffe03335c9a0, 51'h140a38bee496c};
        rom[627] = {51'h7ffffffff68aa, 51'h00000041b42a2, 51'h7ffe03b6e1607, 51'h14083c3408513};
        rom[628] = {51'h7ffffffff6907, 51'h0000004197ca1, 51'h7ffe043a2d556, 51'h1406402c94666};
        rom[629] = {51'h7ffffffff6963, 51'h000000417b7b5, 51'h7ffe04bd409b7, 51'h140444a850163};
        rom[630] = {51'h7ffffffff69bf, 51'h000000415f3de, 51'h7ffe05401b557, 51'h140249a702c33};
        rom[631] = {51'h7ffffffff6a1a, 51'h000000414311b, 51'h7ffe05c2bda5b, 51'h14004f2873f27};
        rom[632] = {51'h7ffffffff6a76, 51'h0000004126f6a, 51'h7ffe064527aec, 51'h13fe552c6b4b7};
        rom[633] = {51'h7ffffffff6ad1, 51'h000000410aecc, 51'h7ffe06c75992d, 51'h13fc5bb2b0983};
        rom[634] = {51'h7ffffffff6b2c, 51'h00000040eef3e, 51'h7ffe074953742, 51'h13fa62bb0bc4c};
        rom[635] = {51'h7ffffffff6b86, 51'h00000040d30c1, 51'h7ffe07cb1574c, 51'h13f86a4544df7};
        rom[636] = {51'h7ffffffff6be0, 51'h00000040b7353, 51'h7ffe084c9fb6b, 51'h13f672512418a};
        rom[637] = {51'h7ffffffff6c3a, 51'h000000409b6f4, 51'h7ffe08cdf25bd, 51'h13f47ade71c28};
        rom[638] = {51'h7ffffffff6c94, 51'h000000407fba2, 51'h7ffe094f0d85e, 51'h13f283ecf6513};
        rom[639] = {51'h7ffffffff6ced, 51'h000000406415e, 51'h7ffe09cff156a, 51'h13f08d7c7a5a7};
        rom[640] = {51'h7ffffffff6d46, 51'h0000004048826, 51'h7ffe0a509def9, 51'h13ee978cc695d};
        rom[641] = {51'h7ffffffff6d9f, 51'h000000402cff9, 51'h7ffe0ad113722, 51'h13eca21da3dc1};
        rom[642] = {51'h7ffffffff6df8, 51'h00000040118d6, 51'h7ffe0b5151ffc, 51'h13eaad2edb27b};
        rom[643] = {51'h7ffffffff6e50, 51'h0000003ff62bd, 51'h7ffe0bd159b9a, 51'h13e8b8c035944};
        rom[644] = {51'h7ffffffff6ea8, 51'h0000003fdadad, 51'h7ffe0c512ac0f, 51'h13e6c4d17c5eb};
        rom[645] = {51'h7ffffffff6f00, 51'h0000003fbf9a5, 51'h7ffe0cd0c536c, 51'h13e4d16278e4f};
        rom[646] = {51'h7ffffffff6f57, 51'h0000003fa46a4, 51'h7ffe0d50293c0, 51'h13e2de72f4a60};
        rom[647] = {51'h7ffffffff6fae, 51'h0000003f894aa, 51'h7ffe0dcf56f19, 51'h13e0ec02b941c};
        rom[648] = {51'h7ffffffff7005, 51'h0000003f6e3b5, 51'h7ffe0e4e4e782, 51'h13defa119078d};
        rom[649] = {51'h7ffffffff705c, 51'h0000003f533c5, 51'h7ffe0ecd0ff07, 51'h13dd089f442c9};
        rom[650] = {51'h7ffffffff70b2, 51'h0000003f384d9, 51'h7ffe0f4b9b7b0, 51'h13db17ab9e5f2};
        rom[651] = {51'h7ffffffff7109, 51'h0000003f1d6f0, 51'h7ffe0fc9f1384, 51'h13d927366932d};
        rom[652] = {51'h7ffffffff715e, 51'h0000003f02a0a, 51'h7ffe104811489, 51'h13d7373f6eeaa};
        rom[653] = {51'h7ffffffff71b4, 51'h0000003ee7e25, 51'h7ffe10c5fbcc3, 51'h13d547c679e9c};
        rom[654] = {51'h7ffffffff7209, 51'h0000003ecd342, 51'h7ffe1143b0e35, 51'h13d358cb54b38};
        rom[655] = {51'h7ffffffff725f, 51'h0000003eb295e, 51'h7ffe11c130adf, 51'h13d16a4dc9eb8};
        rom[656] = {51'h7ffffffff72b3, 51'h0000003e98079, 51'h7ffe123e7b4c1, 51'h13cf7c4da4553};
        rom[657] = {51'h7ffffffff7308, 51'h0000003e7d894, 51'h7ffe12bb90dd8, 51'h13cd8ecaaed40};
        rom[658] = {51'h7ffffffff735c, 51'h0000003e631ab, 51'h7ffe133871822, 51'h13cba1c4b46b4};
        rom[659] = {51'h7ffffffff73b0, 51'h0000003e48bc0, 51'h7ffe13b51d598, 51'h13c9b53b803dd};
        rom[660] = {51'h7ffffffff7404, 51'h0000003e2e6d1, 51'h7ffe143194834, 51'h13c7c92edd8e6};
        rom[661] = {51'h7ffffffff7458, 51'h0000003e142de, 51'h7ffe14add71ed, 51'h13c5dd9e97bef};
        rom[662] = {51'h7ffffffff74ab, 51'h0000003df9fe5, 51'h7ffe1529e54bb, 51'h13c3f28a7a512};
        rom[663] = {51'h7ffffffff74fe, 51'h0000003ddfde6, 51'h7ffe15a5bf290, 51'h13c207f250e5d};
        rom[664] = {51'h7ffffffff7551, 51'h0000003dc5ce1, 51'h7ffe162164d62, 51'h13c01dd5e73d2};
        rom[665] = {51'h7ffffffff75a3, 51'h0000003dabcd3, 51'h7ffe169cd6720, 51'h13be343509365};
        rom[666] = {51'h7ffffffff75f6, 51'h0000003d91dbe, 51'h7ffe1718141bb, 51'h13bc4b0f82cfb};
        rom[667] = {51'h7ffffffff7648, 51'h0000003d77f9f, 51'h7ffe17931df22, 51'h13ba62652026a};
        rom[668] = {51'h7ffffffff769a, 51'h0000003d5e277, 51'h7ffe180df4142, 51'h13b87a35ad773};
        rom[669] = {51'h7ffffffff76eb, 51'h0000003d44644, 51'h7ffe188896a06, 51'h13b69280f71c5};
        rom[670] = {51'h7ffffffff773d, 51'h0000003d2ab05, 51'h7ffe190305b59, 51'h13b4ab46c98fa};
        rom[671] = {51'h7ffffffff778e, 51'h0000003d110bb, 51'h7ffe197d41724, 51'h13b2c486f1696};
        rom[672] = {51'h7ffffffff77de, 51'h0000003cf7764, 51'h7ffe19f749f4d, 51'h13b0de413b602};
        rom[673] = {51'h7ffffffff782f, 51'h0000003cddeff, 51'h7ffe1a711f5ba, 51'h13aef87574491};
        rom[674] = {51'h7ffffffff787f, 51'h0000003cc478c, 51'h7ffe1aeac1c4f, 51'h13ad132369179};
        rom[675] = {51'h7ffffffff78cf, 51'h0000003cab10b, 51'h7ffe1b64314f0, 51'h13ab2e4ae6dd4};
        rom[676] = {51'h7ffffffff791f, 51'h0000003c91b79, 51'h7ffe1bdd6e17e, 51'h13a949ebbac9e};
        rom[677] = {51'h7ffffffff796f, 51'h0000003c786d7, 51'h7ffe1c56783d8, 51'h13a76605b22b4};
        rom[678] = {51'h7ffffffff79be, 51'h0000003c5f324, 51'h7ffe1ccf4fddd, 51'h13a582989a6d2};
        rom[679] = {51'h7ffffffff7a0e, 51'h0000003c4605f, 51'h7ffe1d47f516b, 51'h13a39fa441191};
        rom[680] = {51'h7ffffffff7a5c, 51'h0000003c2ce88, 51'h7ffe1dc06805c, 51'h13a1bd2873d69};
        rom[681] = {51'h7ffffffff7aab, 51'h0000003c13d9d, 51'h7ffe1e38a8c8b, 51'h139fdb25006a9};
        rom[682] = {51'h7ffffffff7afa, 51'h0000003bfad9f, 51'h7ffe1eb0b77d1, 51'h139df999b4b7d};
        rom[683] = {51'h7ffffffff7b48, 51'h0000003be1e8c, 51'h7ffe1f2894406, 51'h139c18865ebe7};
        rom[684] = {51'h7ffffffff7b96, 51'h0000003bc9063, 51'h7ffe1fa03f2fe, 51'h139a37eacc9c0};
        rom[685] = {51'h7ffffffff7be4, 51'h0000003bb0325, 51'h7ffe2017b8690, 51'h139857c6cc8b8};
        rom[686] = {51'h7ffffffff7c31, 51'h0000003b976cf, 51'h7ffe208f0008d, 51'h1396781a2ce50};
        rom[687] = {51'h7ffffffff7c7e, 51'h0000003b7eb62, 51'h7ffe2106162c8, 51'h139498e4bc1dd};
        rom[688] = {51'h7ffffffff7ccb, 51'h0000003b660dd, 51'h7ffe217cfaf12, 51'h1392ba2648c86};
        rom[689] = {51'h7ffffffff7d18, 51'h0000003b4d740, 51'h7ffe21f3ae738, 51'h1390dbdea1940};
        rom[690] = {51'h7ffffffff7d65, 51'h0000003b34e88, 51'h7ffe226a30d09, 51'h138efe0d954d0};
        rom[691] = {51'h7ffffffff7db1, 51'h0000003b1c6b7, 51'h7ffe22e082252, 51'h138d20b2f2dc7};
        rom[692] = {51'h7ffffffff7dfd, 51'h0000003b03fca, 51'h7ffe2356a28dc, 51'h138b43ce89480};
        rom[693] = {51'h7ffffffff7e49, 51'h0000003aeb9c2, 51'h7ffe23cc92272, 51'h1389676027b24};
        rom[694] = {51'h7ffffffff7e95, 51'h0000003ad349e, 51'h7ffe2442510dc, 51'h13878b679d5a2};
        rom[695] = {51'h7ffffffff7ee0, 51'h0000003abb05d, 51'h7ffe24b7df5e1, 51'h1385afe4b99b1};
        rom[696] = {51'h7ffffffff7f2c, 51'h0000003aa2cfe, 51'h7ffe252d3d345, 51'h1383d4d74bed0};
        rom[697] = {51'h7ffffffff7f77, 51'h0000003a8aa81, 51'h7ffe25a26aace, 51'h1381fa3f23e3f};
        rom[698] = {51'h7ffffffff7fc1, 51'h0000003a728e5, 51'h7ffe261767e3f, 51'h1380201c11306};
        rom[699] = {51'h7ffffffff800c, 51'h0000003a5a82a, 51'h7ffe268c34f57, 51'h137e466de39eb};
        rom[700] = {51'h7ffffffff8056, 51'h0000003a4284e, 51'h7ffe2700d1fd9, 51'h137c6d346b179};
        rom[701] = {51'h7ffffffff80a1, 51'h0000003a2a952, 51'h7ffe27753f182, 51'h137a946f779f7};
        rom[702] = {51'h7ffffffff80eb, 51'h0000003a12b34, 51'h7ffe27e97c611, 51'h1378bc1ed956c};
        rom[703] = {51'h7ffffffff8134, 51'h00000039fadf3, 51'h7ffe285d89f41, 51'h1376e4426079b};
        rom[704] = {51'h7ffffffff817e, 51'h00000039e3190, 51'h7ffe28d167ecd, 51'h13750cd9dd603};
        rom[705] = {51'h7ffffffff81c7, 51'h00000039cb609, 51'h7ffe29451666f, 51'h137335e5207de};
        rom[706] = {51'h7ffffffff8210, 51'h00000039b3b5e, 51'h7ffe29b8957e0, 51'h13715f63fa61e};
        rom[707] = {51'h7ffffffff8259, 51'h000000399c18f, 51'h7ffe2a2be54d6, 51'h136f89563bb6c};
        rom[708] = {51'h7ffffffff82a2, 51'h0000003984899, 51'h7ffe2a9f05f07, 51'h136db3bbb5429};
        rom[709] = {51'h7ffffffff82ea, 51'h000000396d07e, 51'h7ffe2b11f7827, 51'h136bde9437e6b};
        rom[710] = {51'h7ffffffff8332, 51'h000000395593c, 51'h7ffe2b84ba1ea, 51'h136a09df949fa};
        rom[711] = {51'h7ffffffff837a, 51'h000000393e2d3, 51'h7ffe2bf74de02, 51'h1368359d9c853};
        rom[712] = {51'h7ffffffff83c2, 51'h0000003926d41, 51'h7ffe2c69b2e1f, 51'h136661ce20ca1};
        rom[713] = {51'h7ffffffff840a, 51'h000000390f887, 51'h7ffe2cdbe93f0, 51'h13648e70f2bc3};
        rom[714] = {51'h7ffffffff8451, 51'h00000038f84a4, 51'h7ffe2d4df1124, 51'h1362bb85e3c44};
        rom[715] = {51'h7ffffffff8498, 51'h00000038e1197, 51'h7ffe2dbfca768, 51'h1360e90cc565d};
        rom[716] = {51'h7ffffffff84df, 51'h00000038c9f5f, 51'h7ffe2e3175867, 51'h135f1705693f4};
        rom[717] = {51'h7ffffffff8526, 51'h00000038b2dfc, 51'h7ffe2ea2f25cb, 51'h135d456fa1099};
        rom[718] = {51'h7ffffffff856c, 51'h000000389bd6e, 51'h7ffe2f144113d, 51'h135b744b3e986};
        rom[719] = {51'h7ffffffff85b3, 51'h0000003884db3, 51'h7ffe2f8561c67, 51'h1359a39813d9d};
        rom[720] = {51'h7ffffffff85f9, 51'h000000386decb, 51'h7ffe2ff6548ed, 51'h1357d355f2d69};
        rom[721] = {51'h7ffffffff863f, 51'h00000038570b5, 51'h7ffe306719876, 51'h13560384adb1a};
        rom[722] = {51'h7ffffffff8684, 51'h0000003840372, 51'h7ffe30d7b0ca5, 51'h1354342416a83};
        rom[723] = {51'h7ffffffff86ca, 51'h00000038296ff, 51'h7ffe31481a71e, 51'h135265340011f};
        rom[724] = {51'h7ffffffff870f, 51'h0000003812b5d, 51'h7ffe31b856983, 51'h135096b43c606};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [(K + WSB)-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= {sb_in, idx_raw};
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [(K + WSB)-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB((K + WSB)), .ACC_SIGNED(1),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire        [K-1:0]    idx_p = esb[K-1:0];
    wire        [WSB-1:0]  sb_p  = esb[K +: WSB];
    wire        [WMAN-1:0] v_p   = {idx_p, ew};
    wire signed [WF-1:0]   f_p   = $signed({~v_p[WMAN-1], v_p[WMAN-2:0]});
    wire                   f_neg = f_p[WF-1];
    wire        [WF-1:0]   mag_f = f_neg ? (-f_p) : f_p;   // |f|, fits WF-1 bits (top bit structurally 0)

    wire [WF+ACCM-1:0] umag_p;   // unsigned |f| * C(f)
    wire [WSB:0]       fsb;      // {delayed f sign, external sideband} riding the pmul
    _zkf_pmul #(
        .WA(WF), .WB(ACCM), .A_SIGNED(0), .B_SIGNED(0),
        .WSB(WSB + 1), .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT_FINAL)
    ) u_final_pmul (
        .clk(clk), .rst(rst), .in_valid(ev), .sb_in({f_neg, sb_p}),
        .a(mag_f), .b(acc[ACCM-1:0]),
        .out_valid(out_valid), .sb_out(fsb), .p(umag_p)
    );
    assign sb_out = fsb[WSB-1:0];
    // Emit the magnitude and the sign SEPARATELY rather than a signed product: the caller folds the sign into
    // its e + log2(m') reconstruction as a single add/subtract, so the post-product cone carries one fewer wide
    // negate carry chain (a standalone two's-complement negate here would otherwise sit in series with that
    // adder and the magnitude abs, the critical path on wide formats). umag_p is the exact |f|*C(f): C(f) < 2
    // and |f| < 2**(WF-1) bound it below 2**(F2-1), so the F2+1-bit slice is lossless. The sign rode the pmul
    // sideband (fsb[WSB]) and so is aligned with out_valid.
    assign l_mag = umag_p[F2:0];
    assign l_neg = fsb[WSB];
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
