/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=24 (degree 2); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: two-stage ROM read + D*(2+STAGE_PRODUCT) (Horner).

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_exp2_m24 #(
    parameter D             = 2,
    parameter WSB           = 1,
    parameter WMULTIPLIER   = 0,
    parameter STAGE_PRODUCT = 0
) (
    input  wire           clk,
    input  wire           rst,
    input  wire           in_valid,
    input  wire [WSB-1:0] sb_in,
    input  wire [ 36-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire           out_valid,
    output wire [WSB-1:0] sb_out,
    output wire [ 24-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire           guard,
    output wire           round,
    output wire           sticky
);
    generate if (D != 2) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 24;
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 8;
    localparam integer CF   = 36;
    localparam integer RW   = 28;
    localparam integer CW   = 39;
    localparam integer ACCW = 39;
    localparam integer NSEG = 256;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [WIDX-1:0] idx = f[FF-1 -: WIDX];
    wire [RW-1:0]   w   = f[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[  0] = {39'h000003d94d, 39'h000b1720ff, 39'h1000000007};
        rom[  1] = {39'h000003dbf9, 39'h000b1ed399, 39'h100b1afa62};
        rom[  2] = {39'h000003dea7, 39'h000b268b8b, 39'h10163daa02};
        rom[  3] = {39'h000003e156, 39'h000b2e48d8, 39'h1021681442};
        rom[  4] = {39'h000003e408, 39'h000b360b84, 39'h102c9a3e7f};
        rom[  5] = {39'h000003e6bb, 39'h000b3dd393, 39'h1037d42e19};
        rom[  6] = {39'h000003e970, 39'h000b45a109, 39'h104315e876};
        rom[  7] = {39'h000003ec27, 39'h000b4d73e9, 39'h104e5f72fe};
        rom[  8] = {39'h000003eee0, 39'h000b554c38, 39'h1059b0d31d};
        rom[  9] = {39'h000003f19b, 39'h000b5d29f8, 39'h10650a0e43};
        rom[ 10] = {39'h000003f458, 39'h000b650d2e, 39'h10706b29e5};
        rom[ 11] = {39'h000003f717, 39'h000b6cf5de, 39'h107bd42b7a};
        rom[ 12] = {39'h000003f9d7, 39'h000b74e40b, 39'h108745187d};
        rom[ 13] = {39'h000003fc9a, 39'h000b7cd7b9, 39'h1092bdf66d};
        rom[ 14] = {39'h000003ff5e, 39'h000b84d0ec, 39'h109e3ecace};
        rom[ 15] = {39'h0000040224, 39'h000b8ccfa7, 39'h10a9c79b27};
        rom[ 16] = {39'h00000404ed, 39'h000b94d3f0, 39'h10b5586d01};
        rom[ 17] = {39'h00000407b7, 39'h000b9cddc8, 39'h10c0f145ec};
        rom[ 18] = {39'h0000040a83, 39'h000ba4ed35, 39'h10cc922b7a};
        rom[ 19] = {39'h0000040d51, 39'h000bad023b, 39'h10d83b2341};
        rom[ 20] = {39'h0000041021, 39'h000bb51cdc, 39'h10e3ec32db};
        rom[ 21] = {39'h00000412f3, 39'h000bbd3d1d, 39'h10efa55fe7};
        rom[ 22] = {39'h00000415c7, 39'h000bc56303, 39'h10fb66b006};
        rom[ 23] = {39'h000004189c, 39'h000bcd8e90, 39'h11073028df};
        rom[ 24] = {39'h0000041b74, 39'h000bd5bfc8, 39'h111301d01a};
        rom[ 25] = {39'h0000041e4e, 39'h000bddf6b1, 39'h111edbab66};
        rom[ 26] = {39'h000004212a, 39'h000be6334d, 39'h112abdc074};
        rom[ 27] = {39'h0000042408, 39'h000bee75a0, 39'h1136a814fa};
        rom[ 28] = {39'h00000426e7, 39'h000bf6bdaf, 39'h11429aaeb1};
        rom[ 29] = {39'h00000429c9, 39'h000bff0b7e, 39'h114e959357};
        rom[ 30] = {39'h0000042cad, 39'h000c075f10, 39'h115a98c8ad};
        rom[ 31] = {39'h0000042f93, 39'h000c0fb869, 39'h1166a45479};
        rom[ 32] = {39'h000004327a, 39'h000c18178e, 39'h1172b83c85};
        rom[ 33] = {39'h0000043564, 39'h000c207c83, 39'h117ed4869e};
        rom[ 34] = {39'h0000043850, 39'h000c28e74b, 39'h118af93894};
        rom[ 35] = {39'h0000043b3e, 39'h000c3157eb, 39'h119726583f};
        rom[ 36] = {39'h0000043e2e, 39'h000c39ce66, 39'h11a35beb78};
        rom[ 37] = {39'h0000044120, 39'h000c424ac1, 39'h11af99f81b};
        rom[ 38] = {39'h0000044414, 39'h000c4acd00, 39'h11bbe0840c};
        rom[ 39] = {39'h000004470a, 39'h000c535527, 39'h11c82f9530};
        rom[ 40] = {39'h0000044a02, 39'h000c5be33a, 39'h11d4873171};
        rom[ 41] = {39'h0000044cfc, 39'h000c64773d, 39'h11e0e75ebc};
        rom[ 42] = {39'h0000044ff8, 39'h000c6d1134, 39'h11ed502305};
        rom[ 43] = {39'h00000452f6, 39'h000c75b124, 39'h11f9c18441};
        rom[ 44] = {39'h00000455f6, 39'h000c7e5710, 39'h12063b886b};
        rom[ 45] = {39'h00000458f9, 39'h000c8702fc, 39'h1212be3581};
        rom[ 46] = {39'h0000045bfd, 39'h000c8fb4ee, 39'h121f499186};
        rom[ 47] = {39'h0000045f04, 39'h000c986ce8, 39'h122bdda281};
        rom[ 48] = {39'h000004620d, 39'h000ca12af0, 39'h12387a6e7d};
        rom[ 49] = {39'h0000046517, 39'h000ca9ef09, 39'h12451ffb8a};
        rom[ 50] = {39'h0000046824, 39'h000cb2b937, 39'h1251ce4fbb};
        rom[ 51] = {39'h0000046b33, 39'h000cbb8980, 39'h125e857127};
        rom[ 52] = {39'h0000046e45, 39'h000cc45fe6, 39'h126b4565eb};
        rom[ 53] = {39'h0000047158, 39'h000ccd3c6f, 39'h12780e3426};
        rom[ 54] = {39'h000004746d, 39'h000cd61f1f, 39'h1284dfe1fe};
        rom[ 55] = {39'h0000047785, 39'h000cdf07f9, 39'h1291ba759a};
        rom[ 56] = {39'h0000047a9e, 39'h000ce7f702, 39'h129e9df528};
        rom[ 57] = {39'h0000047dba, 39'h000cf0ec3f, 39'h12ab8a66d9};
        rom[ 58] = {39'h00000480d8, 39'h000cf9e7b3, 39'h12b87fd0e3};
        rom[ 59] = {39'h00000483f9, 39'h000d02e964, 39'h12c57e397f};
        rom[ 60] = {39'h000004871b, 39'h000d0bf154, 39'h12d285a6ec};
        rom[ 61] = {39'h0000048a3f, 39'h000d14ff8a, 39'h12df961f6c};
        rom[ 62] = {39'h0000048d66, 39'h000d1e1408, 39'h12ecafa947};
        rom[ 63] = {39'h000004908f, 39'h000d272ed4, 39'h12f9d24ac6};
        rom[ 64] = {39'h00000493ba, 39'h000d304ff2, 39'h1306fe0a3a};
        rom[ 65] = {39'h00000496e7, 39'h000d397766, 39'h131432edf7};
        rom[ 66] = {39'h0000049a17, 39'h000d42a534, 39'h132170fc55};
        rom[ 67] = {39'h0000049d49, 39'h000d4bd962, 39'h132eb83bb1};
        rom[ 68] = {39'h000004a07c, 39'h000d5513f2, 39'h133c08b26d};
        rom[ 69] = {39'h000004a3b3, 39'h000d5e54eb, 39'h13496266ed};
        rom[ 70] = {39'h000004a6eb, 39'h000d679c50, 39'h1356c55f9b};
        rom[ 71] = {39'h000004aa26, 39'h000d70ea25, 39'h136431a2e7};
        rom[ 72] = {39'h000004ad62, 39'h000d7a3e70, 39'h1371a73743};
        rom[ 73] = {39'h000004b0a1, 39'h000d839935, 39'h137f262327};
        rom[ 74] = {39'h000004b3e3, 39'h000d8cfa77, 39'h138cae6d0f};
        rom[ 75] = {39'h000004b726, 39'h000d96623d, 39'h139a401b7a};
        rom[ 76] = {39'h000004ba6c, 39'h000d9fd089, 39'h13a7db34ee};
        rom[ 77] = {39'h000004bdb4, 39'h000da94561, 39'h13b57fbff5};
        rom[ 78] = {39'h000004c0ff, 39'h000db2c0ca, 39'h13c32dc31c};
        rom[ 79] = {39'h000004c44c, 39'h000dbc42c7, 39'h13d0e544f7};
        rom[ 80] = {39'h000004c79b, 39'h000dc5cb5e, 39'h13dea64c1b};
        rom[ 81] = {39'h000004caec, 39'h000dcf5a93, 39'h13ec70df25};
        rom[ 82] = {39'h000004ce3f, 39'h000dd8f06a, 39'h13fa4504b5};
        rom[ 83] = {39'h000004d195, 39'h000de28ce8, 39'h140822c371};
        rom[ 84] = {39'h000004d4ee, 39'h000dec3013, 39'h14160a2200};
        rom[ 85] = {39'h000004d848, 39'h000df5d9ed, 39'h1423fb2712};
        rom[ 86] = {39'h000004dba5, 39'h000dff8a7d, 39'h1431f5d95a};
        rom[ 87] = {39'h000004df04, 39'h000e0941c7, 39'h143ffa3f8e};
        rom[ 88] = {39'h000004e266, 39'h000e12ffcf, 39'h144e08606b};
        rom[ 89] = {39'h000004e5ca, 39'h000e1cc49a, 39'h145c2042b1};
        rom[ 90] = {39'h000004e930, 39'h000e26902c, 39'h146a41ed26};
        rom[ 91] = {39'h000004ec98, 39'h000e30628b, 39'h14786d6694};
        rom[ 92] = {39'h000004f003, 39'h000e3a3bbc, 39'h1486a2b5ca};
        rom[ 93] = {39'h000004f371, 39'h000e441bc2, 39'h1494e1e19c};
        rom[ 94] = {39'h000004f6e0, 39'h000e4e02a3, 39'h14a32af0e1};
        rom[ 95] = {39'h000004fa52, 39'h000e57f064, 39'h14b17dea77};
        rom[ 96] = {39'h000004fdc7, 39'h000e61e508, 39'h14bfdad53f};
        rom[ 97] = {39'h000005013e, 39'h000e6be096, 39'h14ce41b821};
        rom[ 98] = {39'h00000504b7, 39'h000e75e311, 39'h14dcb29a07};
        rom[ 99] = {39'h0000050833, 39'h000e7fec7f, 39'h14eb2d81e2};
        rom[100] = {39'h0000050bb1, 39'h000e89fce4, 39'h14f9b276a6};
        rom[101] = {39'h0000050f32, 39'h000e941446, 39'h1508417f4f};
        rom[102] = {39'h00000512b4, 39'h000e9e32a9, 39'h1516daa2d9};
        rom[103] = {39'h000005163a, 39'h000ea85811, 39'h15257de849};
        rom[104] = {39'h00000519c2, 39'h000eb28485, 39'h15342b56a7};
        rom[105] = {39'h0000051d4c, 39'h000ebcb808, 39'h1542e2f500};
        rom[106] = {39'h00000520d9, 39'h000ec6f2a0, 39'h1551a4ca67};
        rom[107] = {39'h0000052468, 39'h000ed13451, 39'h156070ddf3};
        rom[108] = {39'h00000527fa, 39'h000edb7d21, 39'h156f4736bf};
        rom[109] = {39'h0000052b8e, 39'h000ee5cd14, 39'h157e27dbec};
        rom[110] = {39'h0000052f25, 39'h000ef0242f, 39'h158d12d4a1};
        rom[111] = {39'h00000532be, 39'h000efa8278, 39'h159c082809};
        rom[112] = {39'h0000053659, 39'h000f04e7f3, 39'h15ab07dd52};
        rom[113] = {39'h00000539f8, 39'h000f0f54a6, 39'h15ba11fbb2};
        rom[114] = {39'h0000053d98, 39'h000f19c895, 39'h15c9268a63};
        rom[115] = {39'h000005413b, 39'h000f2443c5, 39'h15d84590a3};
        rom[116] = {39'h00000544e1, 39'h000f2ec63b, 39'h15e76f15b7};
        rom[117] = {39'h0000054889, 39'h000f394ffd, 39'h15f6a320e7};
        rom[118] = {39'h0000054c34, 39'h000f43e10f, 39'h1605e1b981};
        rom[119] = {39'h0000054fe1, 39'h000f4e7977, 39'h16152ae6d8};
        rom[120] = {39'h0000055391, 39'h000f59193a, 39'h16247eb044};
        rom[121] = {39'h0000055744, 39'h000f63c05c, 39'h1633dd1d23};
        rom[122] = {39'h0000055af9, 39'h000f6e6ee3, 39'h16434634d7};
        rom[123] = {39'h0000055eb0, 39'h000f7924d4, 39'h1652b9fec6};
        rom[124] = {39'h000005626a, 39'h000f83e235, 39'h166238825f};
        rom[125] = {39'h0000056627, 39'h000f8ea709, 39'h1671c1c712};
        rom[126] = {39'h00000569e7, 39'h000f997357, 39'h168155d457};
        rom[127] = {39'h0000056da8, 39'h000fa44724, 39'h1690f4b1a9};
        rom[128] = {39'h000005716d, 39'h000faf2275, 39'h16a09e6689};
        rom[129] = {39'h0000057534, 39'h000fba054e, 39'h16b052fa7f};
        rom[130] = {39'h00000578fe, 39'h000fc4efb6, 39'h16c0127516};
        rom[131] = {39'h0000057cca, 39'h000fcfe1b2, 39'h16cfdcdddf};
        rom[132] = {39'h0000058099, 39'h000fdadb46, 39'h16dfb23c6f};
        rom[133] = {39'h000005846b, 39'h000fe5dc79, 39'h16ef929863};
        rom[134] = {39'h000005883f, 39'h000ff0e54f, 39'h16ff7df95c};
        rom[135] = {39'h0000058c16, 39'h000ffbf5cd, 39'h170f7466fe};
        rom[136] = {39'h0000058ff0, 39'h0010070dfa, 39'h171f75e8f7};
        rom[137] = {39'h00000593cc, 39'h0010122dda, 39'h172f8286f5};
        rom[138] = {39'h00000597ab, 39'h00101d5572, 39'h173f9a48b0};
        rom[139] = {39'h0000059b8d, 39'h00102884c9, 39'h174fbd35e2};
        rom[140] = {39'h0000059f72, 39'h001033bbe3, 39'h175feb564d};
        rom[141] = {39'h000005a359, 39'h00103efac5, 39'h177024b1b6};
        rom[142] = {39'h000005a742, 39'h00104a4176, 39'h1780694fe9};
        rom[143] = {39'h000005ab2f, 39'h0010558ffb, 39'h1790b938b7};
        rom[144] = {39'h000005af1e, 39'h001060e659, 39'h17a11473f6};
        rom[145] = {39'h000005b310, 39'h00106c4495, 39'h17b17b0981};
        rom[146] = {39'h000005b705, 39'h001077aab5, 39'h17c1ed013b};
        rom[147] = {39'h000005bafc, 39'h00108318be, 39'h17d26a630a};
        rom[148] = {39'h000005bef7, 39'h00108e8eb7, 39'h17e2f336da};
        rom[149] = {39'h000005c2f4, 39'h00109a0ca3, 39'h17f387849c};
        rom[150] = {39'h000005c6f3, 39'h0010a5928a, 39'h1804275449};
        rom[151] = {39'h000005caf6, 39'h0010b12071, 39'h1814d2addc};
        rom[152] = {39'h000005cefb, 39'h0010bcb65c, 39'h1825899958};
        rom[153] = {39'h000005d303, 39'h0010c85452, 39'h18364c1ec4};
        rom[154] = {39'h000005d70e, 39'h0010d3fa58, 39'h18471a462f};
        rom[155] = {39'h000005db1c, 39'h0010dfa874, 39'h1857f417aa};
        rom[156] = {39'h000005df2c, 39'h0010eb5eab, 39'h1868d99b4f};
        rom[157] = {39'h000005e340, 39'h0010f71d03, 39'h1879cad93d};
        rom[158] = {39'h000005e756, 39'h001102e382, 39'h188ac7d995};
        rom[159] = {39'h000005eb6f, 39'h00110eb22e, 39'h189bd0a483};
        rom[160] = {39'h000005ef8b, 39'h00111a890b, 39'h18ace54236};
        rom[161] = {39'h000005f3a9, 39'h0011266820, 39'h18be05bae1};
        rom[162] = {39'h000005f7cb, 39'h0011324f72, 39'h18cf3216c0};
        rom[163] = {39'h000005fbef, 39'h00113e3f08, 39'h18e06a5e13};
        rom[164] = {39'h0000060017, 39'h00114a36e6, 39'h18f1ae9921};
        rom[165] = {39'h0000060441, 39'h0011563713, 39'h1902fed033};
        rom[166] = {39'h000006086e, 39'h0011623f94, 39'h19145b0b9d};
        rom[167] = {39'h0000060c9e, 39'h00116e506f, 39'h1925c353b5};
        rom[168] = {39'h00000610d1, 39'h00117a69ab, 39'h193737b0d9};
        rom[169] = {39'h0000061507, 39'h0011868b4c, 39'h1948b82b6b};
        rom[170] = {39'h000006193f, 39'h001192b558, 39'h195a44cbd4};
        rom[171] = {39'h0000061d7b, 39'h00119ee7d6, 39'h196bdd9a82};
        rom[172] = {39'h00000621b9, 39'h0011ab22cc, 39'h197d829fea};
        rom[173] = {39'h00000625fb, 39'h0011b7663e, 39'h198f33e485};
        rom[174] = {39'h0000062a3f, 39'h0011c3b234, 39'h19a0f170d5};
        rom[175] = {39'h0000062e87, 39'h0011d006b2, 39'h19b2bb4d5f};
        rom[176] = {39'h00000632d1, 39'h0011dc63c0, 39'h19c49182af};
        rom[177] = {39'h000006371f, 39'h0011e8c962, 39'h19d6741957};
        rom[178] = {39'h0000063b6f, 39'h0011f5379f, 39'h19e86319ef};
        rom[179] = {39'h0000063fc2, 39'h001201ae7c, 39'h19fa5e8d13};
        rom[180] = {39'h0000064419, 39'h00120e2e01, 39'h1a0c667b69};
        rom[181] = {39'h0000064872, 39'h00121ab632, 39'h1a1e7aed9a};
        rom[182] = {39'h0000064ccf, 39'h0012274716, 39'h1a309bec56};
        rom[183] = {39'h000006512e, 39'h001233e0b3, 39'h1a42c98052};
        rom[184] = {39'h0000065590, 39'h001240830e, 39'h1a5503b24a};
        rom[185] = {39'h00000659f6, 39'h00124d2e2f, 39'h1a674a8b00};
        rom[186] = {39'h0000065e5f, 39'h001259e21a, 39'h1a799e133c};
        rom[187] = {39'h00000662ca, 39'h0012669ed7, 39'h1a8bfe53cd};
        rom[188] = {39'h0000066739, 39'h001273646b, 39'h1a9e6b5586};
        rom[189] = {39'h0000066bab, 39'h00128032dc, 39'h1ab0e52141};
        rom[190] = {39'h000006701f, 39'h00128d0a31, 39'h1ac36bbfe0};
        rom[191] = {39'h0000067497, 39'h001299ea6f, 39'h1ad5ff3a48};
        rom[192] = {39'h0000067912, 39'h0012a6d39e, 39'h1ae89f9967};
        rom[193] = {39'h0000067d91, 39'h0012b3c5c2, 39'h1afb4ce62f};
        rom[194] = {39'h0000068212, 39'h0012c0c0e3, 39'h1b0e07299a};
        rom[195] = {39'h0000068696, 39'h0012cdc506, 39'h1b20ce6ca7};
        rom[196] = {39'h0000068b1e, 39'h0012dad232, 39'h1b33a2b85b};
        rom[197] = {39'h0000068fa8, 39'h0012e7e86d, 39'h1b468415c3};
        rom[198] = {39'h0000069436, 39'h0012f507be, 39'h1b59728df2};
        rom[199] = {39'h00000698c7, 39'h001302302a, 39'h1b6c6e29fe};
        rom[200] = {39'h0000069d5b, 39'h00130f61b8, 39'h1b7f76f308};
        rom[201] = {39'h000006a1f3, 39'h00131c9c6e, 39'h1b928cf234};
        rom[202] = {39'h000006a68d, 39'h001329e054, 39'h1ba5b030ad};
        rom[203] = {39'h000006ab2b, 39'h0013372d6e, 39'h1bb8e0b7a7};
        rom[204] = {39'h000006afcc, 39'h00134483c3, 39'h1bcc1e9058};
        rom[205] = {39'h000006b470, 39'h001351e35b, 39'h1bdf69c400};
        rom[206] = {39'h000006b917, 39'h00135f4c3a, 39'h1bf2c25be4};
        rom[207] = {39'h000006bdc2, 39'h00136cbe69, 39'h1c0628614e};
        rom[208] = {39'h000006c270, 39'h00137a39ec, 39'h1c199bdd92};
        rom[209] = {39'h000006c721, 39'h001387becb, 39'h1c2d1cda07};
        rom[210] = {39'h000006cbd5, 39'h0013954d0d, 39'h1c40ab600c};
        rom[211] = {39'h000006d08d, 39'h0013a2e4b7, 39'h1c54477908};
        rom[212] = {39'h000006d548, 39'h0013b085d0, 39'h1c67f12e64};
        rom[213] = {39'h000006da06, 39'h0013be305f, 39'h1c7ba88995};
        rom[214] = {39'h000006dec7, 39'h0013cbe46a, 39'h1c8f6d9414};
        rom[215] = {39'h000006e38c, 39'h0013d9a1f8, 39'h1ca340575e};
        rom[216] = {39'h000006e854, 39'h0013e76910, 39'h1cb720dcfc};
        rom[217] = {39'h000006ed1f, 39'h0013f539b8, 39'h1ccb0f2e7a};
        rom[218] = {39'h000006f1ee, 39'h00140313f6, 39'h1cdf0b556b};
        rom[219] = {39'h000006f6c0, 39'h001410f7d2, 39'h1cf3155b69};
        rom[220] = {39'h000006fb96, 39'h00141ee552, 39'h1d072d4a14};
        rom[221] = {39'h000007006e, 39'h00142cdc7d, 39'h1d1b532b16};
        rom[222] = {39'h000007054a, 39'h00143add59, 39'h1d2f87081b};
        rom[223] = {39'h0000070a2a, 39'h001448e7ed, 39'h1d43c8ead8};
        rom[224] = {39'h0000070f0d, 39'h001456fc40, 39'h1d5818dd09};
        rom[225] = {39'h00000713f3, 39'h0014651a59, 39'h1d6c76e870};
        rom[226] = {39'h00000718dd, 39'h001473423f, 39'h1d80e316d7};
        rom[227] = {39'h0000071dca, 39'h00148173f8, 39'h1d955d720d};
        rom[228] = {39'h00000722ba, 39'h00148faf8b, 39'h1da9e603e8};
        rom[229] = {39'h00000727ae, 39'h00149df4ff, 39'h1dbe7cd648};
        rom[230] = {39'h0000072ca5, 39'h0014ac445a, 39'h1dd321f30f};
        rom[231] = {39'h00000731a0, 39'h0014ba9da5, 39'h1de7d56429};
        rom[232] = {39'h000007369e, 39'h0014c900e5, 39'h1dfc973389};
        rom[233] = {39'h0000073ba0, 39'h0014d76e21, 39'h1e11676b27};
        rom[234] = {39'h00000740a5, 39'h0014e5e561, 39'h1e26461503};
        rom[235] = {39'h00000745ae, 39'h0014f466ab, 39'h1e3b333b24};
        rom[236] = {39'h0000074aba, 39'h001502f207, 39'h1e502ee799};
        rom[237] = {39'h0000074fca, 39'h001511877b, 39'h1e65392475};
        rom[238] = {39'h00000754dd, 39'h001520270e, 39'h1e7a51fbd5};
        rom[239] = {39'h00000759f4, 39'h00152ed0c8, 39'h1e8f7977db};
        rom[240] = {39'h0000075f0e, 39'h00153d84af, 39'h1ea4afa2b2};
        rom[241] = {39'h000007642c, 39'h00154c42cb, 39'h1eb9f4868a};
        rom[242] = {39'h000007694d, 39'h00155b0b22, 39'h1ecf482d9c};
        rom[243] = {39'h0000076e72, 39'h001569ddbb, 39'h1ee4aaa226};
        rom[244] = {39'h000007739a, 39'h001578ba9f, 39'h1efa1bee6f};
        rom[245] = {39'h00000778c7, 39'h001587a1d3, 39'h1f0f9c1cc4};
        rom[246] = {39'h0000077df6, 39'h0015969360, 39'h1f252b377a};
        rom[247] = {39'h0000078329, 39'h0015a58f4c, 39'h1f3ac948eb};
        rom[248] = {39'h0000078860, 39'h0015b4959e, 39'h1f50765b7c};
        rom[249] = {39'h0000078d9b, 39'h0015c3a65e, 39'h1f66327996};
        rom[250] = {39'h00000792d9, 39'h0015d2c193, 39'h1f7bfdadab};
        rom[251] = {39'h000007981a, 39'h0015e1e744, 39'h1f91d80232};
        rom[252] = {39'h0000079d60, 39'h0015f11778, 39'h1fa7c181ad};
        rom[253] = {39'h000007a2a9, 39'h0016005237, 39'h1fbdba36a1};
        rom[254] = {39'h000007a7f6, 39'h00160f9789, 39'h1fd3c22b9e};
        rom[255] = {39'h000007ad46, 39'h00161ee773, 39'h1fe9d96b38};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [WSB-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= sb_in;
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [WSB-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(WSB), .ACC_SIGNED(0),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire _unused_horner = &{1'b0, ew, 1'b0};
    assign sb_out      = esb;
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
