/// GENERATED by zkf_transcendental.py -- DO NOT EDIT.
/// Table+polynomial core for zkf_exp2 at WMAN=27 (degree 3); zero-bubble, see _zkf_horner.
/// Evaluates the significand 2**f in [1,2) from the reduced fractional argument f (FF = WMAN + 12 bits).
/// Register stages: two-stage ROM read + D*(2+STAGE_PRODUCT) (Horner).

// verilog_lint: waive-start line-length  (the ROM rows are wide one-liners)

`default_nettype none

`ifndef ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE
`define ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifndef ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST
`define ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

module _zkf_exp2_m27 #(
    parameter D             = 3,
    parameter WSB           = 1,
    parameter WMULTIPLIER   = 0,
    parameter STAGE_PRODUCT = 0
) (
    input  wire           clk,
    input  wire           rst,
    input  wire           in_valid,
    input  wire [WSB-1:0] sb_in,
    input  wire [ 39-1:0] f,            // FF = WMAN + 12 reduced-argument fraction bits, in [0,1)
    output wire           out_valid,
    output wire [WSB-1:0] sb_out,
    output wire [ 27-1:0] significand,  // 2**f in [1,2): hidden bit + WFRAC fraction
    output wire           guard,
    output wire           round,
    output wire           sticky
);
    generate if (D != 3) begin : g_degree_mismatch  _zkf_invalid_degree_mismatch u_invalid(); end endgenerate
    localparam integer WMAN = 27;
    localparam integer FF   = WMAN + 12;
    localparam integer K    = 6;
    localparam integer CF   = 39;
    localparam integer RW   = 33;
    localparam integer CW   = 42;
    localparam integer ACCW = 42;
    localparam integer NSEG = 64;
    localparam integer WIDX = (NSEG <= 1) ? 1 : $clog2(NSEG);

    wire [WIDX-1:0] idx = f[FF-1 -: WIDX];
    wire [RW-1:0]   w   = f[RW-1:0];
    `ZKF_ATTRIBUTE_ROM_PRE reg [(D+1)*CW-1:0] rom [0:NSEG-1] `ZKF_ATTRIBUTE_ROM_POST;
    initial begin
        rom[ 0] = {42'h0000001c929, 42'h00001ebfa54, 42'h00162e4303f, 42'h07ffffffffe};
        rom[ 1] = {42'h0000001ce23, 42'h00001f155cc, 42'h00166c18101, 42'h08164d1f3ba};
        rom[ 2] = {42'h0000001d32b, 42'h00001f6c032, 42'h0016aa997a3, 42'h082cd8698aa};
        rom[ 3] = {42'h0000001d842, 42'h00001fc39b1, 42'h0016e9c922c, 42'h0843a28c3aa};
        rom[ 4] = {42'h0000001dd66, 42'h0000201c273, 42'h001729a8ef9, 42'h085aac367ca};
        rom[ 5] = {42'h0000001e299, 42'h00002075aa3, 42'h00176a3acb8, 42'h0871f61969c};
        rom[ 6] = {42'h0000001e7da, 42'h000020d026b, 42'h0017ab80a71, 42'h088980e8090};
        rom[ 7] = {42'h0000001ed2a, 42'h0000212b9f7, 42'h0017ed7c780, 42'h08a14d57547};
        rom[ 8] = {42'h0000001f289, 42'h00002188172, 42'h00183030398, 42'h08b95c1e3e8};
        rom[ 9] = {42'h0000001f7f7, 42'h000021e590a, 42'h0018739dec6, 42'h08d1adf5b7c};
        rom[10] = {42'h0000001fd74, 42'h000022440ec, 42'h0018b7c796f, 42'h08ea4398b43};
        rom[11] = {42'h00000020300, 42'h000022a3943, 42'h0018fcaf453, 42'h09031dc4312};
        rom[12] = {42'h0000002089c, 42'h00002304240, 42'h0019425708d, 42'h091c3d373a8};
        rom[13] = {42'h00000020e47, 42'h00002365c0f, 42'h001988c0f95, 42'h0935a2b2f11};
        rom[14] = {42'h00000021402, 42'h000023c86e0, 42'h0019cfef33f, 42'h094f4efa8fc};
        rom[15] = {42'h000000219cd, 42'h0000242c2e2, 42'h001a17e3dbe, 42'h096942d371d};
        rom[16] = {42'h00000021fa8, 42'h00002491046, 42'h001a60a11a5, 42'h09837f0518b};
        rom[17] = {42'h00000022594, 42'h000024f6f3a, 42'h001aaa291e6, 42'h099e045931e};
        rom[18] = {42'h00000022b90, 42'h0000255dff2, 42'h001af47e1d6, 42'h09b8d39b9d2};
        rom[19] = {42'h0000002319c, 42'h000025c629d, 42'h001b3fa252b, 42'h09d3ed9a72a};
        rom[20] = {42'h000000237ba, 42'h0000262f76f, 42'h001b8b97fff, 42'h09ef532608f};
        rom[21] = {42'h00000023de9, 42'h00002699e99, 42'h001bd8616d1, 42'h0a0b0510fb6};
        rom[22] = {42'h00000024429, 42'h00002705850, 42'h001c2600e86, 42'h0a270430309};
        rom[23] = {42'h00000024a7a, 42'h000027724c5, 42'h001c7478c68, 42'h0a43515ae07};
        rom[24] = {42'h000000250dd, 42'h000027e042f, 42'h001cc3cb62d, 42'h0a5fed6a9ae};
        rom[25] = {42'h00000025751, 42'h0000284f6c1, 42'h001d13fb1ef, 42'h0a7cd93b4e6};
        rom[26] = {42'h00000025dd8, 42'h000028bfcb1, 42'h001d650a636, 42'h0a9a15ab4e7};
        rom[27] = {42'h00000026471, 42'h00002931635, 42'h001db6fb9f3, 42'h0ab7a39b5a6};
        rom[28] = {42'h00000026b1c, 42'h000029a4384, 42'h001e09d1486, 42'h0ad583eea3f};
        rom[29] = {42'h000000271da, 42'h00002a184d5, 42'h001e5d8ddbb, 42'h0af3b78ad66};
        rom[30] = {42'h000000278ab, 42'h00002a8da5f, 42'h001eb233dcd, 42'h0b123f581cf};
        rom[31] = {42'h00000027f8e, 42'h00002b0445b, 42'h001f07c5d67, 42'h0b311c412a6};
        rom[32] = {42'h00000028685, 42'h00002b7c302, 42'h001f5e465a8, 42'h0b504f333f6};
        rom[33] = {42'h00000028d90, 42'h00002bf568e, 42'h001fb5b801d, 42'h0b6fd91e325};
        rom[34] = {42'h000000294ae, 42'h00002c6ff38, 42'h00200e1d6cb, 42'h0b8fbaf475f};
        rom[35] = {42'h00000029bdf, 42'h00002cebd3c, 42'h00206779429, 42'h0baff5ab210};
        rom[36] = {42'h0000002a325, 42'h00002d690d5, 42'h0020c1ce328, 42'h0bd08a39f54};
        rom[37] = {42'h0000002aa7f, 42'h00002de7a40, 42'h00211d1ef2d, 42'h0bf1799b677};
        rom[38] = {42'h0000002b1ee, 42'h00002e679b9, 42'h0021796e418, 42'h0c12c4cca63};
        rom[39] = {42'h0000002b971, 42'h00002ee8f7d, 42'h0021d6bee43, 42'h0c346ccda21};
        rom[40] = {42'h0000002c109, 42'h00002f6bbcb, 42'h00223513a82, 42'h0c5672a1151};
        rom[41] = {42'h0000002c8b7, 42'h00002fefee2, 42'h0022946f62a, 42'h0c78d74c8a8};
        rom[42] = {42'h0000002d079, 42'h00003075901, 42'h0022f4d4f0a, 42'h0c9b9bd866a};
        rom[43] = {42'h0000002d852, 42'h000030fca68, 42'h00235647373, 42'h0cbec14feef};
        rom[44] = {42'h0000002e040, 42'h00003185359, 42'h0023b8c9237, 42'h0ce248c151c};
        rom[45] = {42'h0000002e845, 42'h0000320f414, 42'h00241c5daa9, 42'h0d06333daeb};
        rom[46] = {42'h0000002f05f, 42'h0000329acdd, 42'h00248107ca3, 42'h0d2a81d91ed};
        rom[47] = {42'h0000002f891, 42'h00003327df6, 42'h0024e6ca880, 42'h0d4f35aabcc};
        rom[48] = {42'h000000300d9, 42'h000033b67a2, 42'h00254da8f27, 42'h0d744fccad2};
        rom[49] = {42'h00000030938, 42'h00003446a28, 42'h0025b5a6202, 42'h0d99d15c274};
        rom[50] = {42'h000000311af, 42'h000034d85cb, 42'h00261ec5309, 42'h0dbfbb797d7};
        rom[51] = {42'h00000031a3d, 42'h0000356bad2, 42'h002689094bd, 42'h0de60f4825a};
        rom[52] = {42'h000000322e3, 42'h00003600984, 42'h0026f475a2d, 42'h0e0ccdeec26};
        rom[53] = {42'h00000032ba1, 42'h00003697227, 42'h0027610d6f5, 42'h0e33f8972ba};
        rom[54] = {42'h00000033478, 42'h0000372f505, 42'h0027ced3f43, 42'h0e5b906e778};
        rom[55] = {42'h00000033d67, 42'h000037c9267, 42'h00283dcc7d3, 42'h0e8396a5038};
        rom[56] = {42'h0000003466f, 42'h00003864a96, 42'h0028adfa5f7, 42'h0eac0c6e7d9};
        rom[57] = {42'h00000034f90, 42'h00003901dde, 42'h00291f60f95, 42'h0ed4f301ed5};
        rom[58] = {42'h000000358cb, 42'h000039a0c89, 42'h00299203b29, 42'h0efe4b99bd8};
        rom[59] = {42'h0000003621f, 42'h00003a416e4, 42'h002a05e5fc7, 42'h0f281773c55};
        rom[60] = {42'h00000036b8e, 42'h00003ae3d3d, 42'h002a7b0b51c, 42'h0f5257d1520};
        rom[61] = {42'h00000037517, 42'h00003b87fe1, 42'h002af177370, 42'h0f7d0df7306};
        rom[62] = {42'h00000037eba, 42'h00003c2df1f, 42'h002b692d3aa, 42'h0fa83b2db6d};
        rom[63] = {42'h00000038878, 42'h00003cd5b47, 42'h002be230f4d, 42'h0fd3e0c0cf0};
    end
    reg [(D+1)*CW-1:0] r_co1, r_co2;
    reg [RW-1:0] r_w1, r_w2;
    reg r_rv1, r_rv2;
    reg [WSB-1:0] r_rsb1, r_rsb2;
    always @(posedge clk) begin
        if (rst) begin r_rv1 <= 1'b0; r_rv2 <= 1'b0; end
        else begin r_rv1 <= in_valid; r_rv2 <= r_rv1; end
        r_co1  <= rom[idx];
        r_w1   <= w;
        r_rsb1 <= sb_in;
        r_co2  <= r_co1;
        r_w2   <= r_w1;
        r_rsb2 <= r_rsb1;
    end
    wire signed [ACCW-1:0] acc;
    wire                   ev;
    wire         [WSB-1:0] esb;
    wire          [RW-1:0] ew;
    _zkf_horner #(
        .D(D), .WCOEF(CW), .WRARG(RW), .WACC(ACCW), .WSB(WSB), .ACC_SIGNED(0),
        .WMULTIPLIER(WMULTIPLIER), .STAGE_PRODUCT(STAGE_PRODUCT)
    ) u_h (
        .clk(clk), .rst(rst), .in_valid(r_rv2), .sb_in(r_rsb2), .coeffs(r_co2), .w(r_w2),
        .out_valid(ev), .sb_out(esb), .w_out(ew), .acc(acc)
    );
    wire _unused_horner = &{1'b0, ew, 1'b0};
    assign sb_out      = esb;
    assign significand = acc[CF -: WMAN];
    assign guard       = acc[CF-WMAN];
    assign round       = acc[CF-WMAN-1];
    assign sticky      = |acc[CF-WMAN-2:0];
    assign out_valid   = ev;
endmodule

`ifdef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_PRE
`undef ZKF_ATTRIBUTE_ROM_PRE_DEFAULTED
`endif
`ifdef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`undef ZKF_ATTRIBUTE_ROM_POST
`undef ZKF_ATTRIBUTE_ROM_POST_DEFAULTED
`endif

// verilog_lint: waive-stop line-length
`default_nettype wire
