name: CI
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
env:
  COCOTB_IGNORE_PYTHON_REQUIRES: "1"

jobs:
  tests:
    name: tests
    runs-on: [self-hosted, ci-runner]
    container: &mega_toolchain_container
      image: containers.zubax.com/zubax-fpga-toolchain-mega:latest
      options: --user root --cap-add NET_ADMIN --shm-size 8g --volume /run/udev:/run/udev:ro
    steps:
      - &checkout_step
        uses: actions/checkout@v7
      - &python_cache_step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: pip-${{ runner.os }}-
      - run: nox -s tests black

  deep:
    name: deep
    if: contains(github.event.head_commit.message, '#ci-deep')
    runs-on: [self-hosted, ci-runner]
    container: *mega_toolchain_container
    steps:
      - *checkout_step
      - *python_cache_step
      - run: nox -s deep

  accuracy:
    name: accuracy
    runs-on: [self-hosted, ci-runner]
    container: *mega_toolchain_container
    steps:
      - *checkout_step
      - *python_cache_step
      - run: nox -s accuracy

  formal:
    name: formal
    runs-on: ubuntu-latest
    container: &fpga_toolchain_container
      image: ghcr.io/zubax/zubax-fpga-toolchain:latest
      options: --user root
    steps:
      - *checkout_step
      - *python_cache_step
      - run: nox -s formal
      - if: always()
        uses: actions/upload-artifact@v7
        with: { name: formal-report, path: build/float/formal/report.html, if-no-files-found: ignore }

  synth:
    name: synth
    runs-on: ubuntu-latest
    container: *fpga_toolchain_container
    steps:
      - *checkout_step
      - *python_cache_step
      - run: nox -s synth
      - if: always()
        uses: actions/upload-artifact@v7
        with: { name: synth-artifacts, path: build, if-no-files-found: ignore }
